### ISSUE TITLE
Placing down blocks also spawns particles [Fabric]

### ISSUE THREAD

**Issue by ArtixAllMighty** [haubna/PhysicsMod#1]
When placing down blocks, particles are also being spawned. 

I believe this to not be intentional. 

If it is, then i'd like to ask for a config option to activate / deactive on placing blocks 

Side note : particles for placing blocks appear after fiddling with the options menu. When first starting minecraft and playing a world, no particles will spawn when placing a block, until you edit the options.

vid :
https://streamable.com/bjqcwd

**Comment by haubna** [comment]
I can't seem to reproduce this bug. Does it happen in singleplayer as well? Does it happen on other server? My guess is that this modified server sends 2 packets to you where it places a block, insta removes it and places it again.

**Comment by ArtixAllMighty** [comment]
Good question. let me try this outside of my claimed land

**Comment by ArtixAllMighty** [comment]
It seems to be an off hand issue

video : 
https://streamable.com/fd519p

**Comment by haubna** [comment]
Fixed in the newest release

**Comment by ArtixAllMighty** [comment]
sweet ! Does this include piston changes ? or do i make a new issue for that ? 

video : 
https://streamable.com/r5arpi

**Comment by haubna** [comment]
New issue, but this might be impossible to fix since I don't know the reason why a block gets set to air (in this case from a piston).
