### ISSUE TITLE
Physics Mod crash with Iris installed

### ISSUE THREAD

**Issue by RowanSkie** [haubna/PhysicsMod#1]
I've been doing some stuff with my mod list, and notice that Iris crashes the game when Physics Mod is also online. Got any idea why?

**Comment by haubna** [comment]
Send me a crash log please :)

Mark Joshua Zuniga ***@***.***> schrieb am Mo. 5. Juli 2021
um 10:36:

**Comment by RowanSkie** [comment]
I've created full details over Iris's side of things, since apparently that they've fixed it on their end once.

https://github.com/IrisShaders/Iris/issues/488

**Comment by haubna** [comment]
Ok if there is any problem on my side, please let me know.

Am Mo., 5. Juli 2021 um 10:49 Uhr schrieb Mark Joshua Zuniga <
***@***.***>:

**Comment by IMS212** [comment]
This has just been fixed, feel free to close. 2 more questions slightly related: 1: are there plans to open source this mod, and 2: is this mod going to update to 1.17.1? (It crashes when actual physics takes place)

**Comment by haubna** [comment]
1: no.
2: I will look into it!

Edit: looks like they changed a packet that I was using. Need to recompile for 1.17.1. Should be done by tomorrow.

**Comment by haubna** [comment]
> This has just been fixed, feel free to close. 2 more questions slightly related: 1: are there plans to open source this mod, and 2: is this mod going to update to 1.17.1? (It crashes when actual physics takes place)

Oh and is there something I can do to make Iris compatible out of the box? I haven't looked at it yet.

**Comment by haubna** [comment]
Updated to 1.17.1 now.
