### ISSUE TITLE
particles are displayed when a block is moved

### ISSUE THREAD

**Issue by Keys-Unlimited** [haubna/PhysicsMod#10]
https://user-images.githubusercontent.com/78640228/107114079-40172900-6889-11eb-9d25-086df48ed49a.mp4

I have attached a video to show that when a block is moved by a piston or slime block, the mod assumes it is broken, I think this is a mistake. I do not have experience in coding mods but I think this is a mistake in considering the event as breaking. Hopefully this issue is fixed. Thank you.

**Comment by haubna** [comment]
Fixed in latest version

**Comment by Keys-Unlimited** [comment]
> Fixed in latest version

thank you. love the mod

**Comment by rojaoo** [comment]
Lol, i'm stuck in old versions because my PC can't handle newer version
