### ISSUE TITLE
physics_config.json & physics_server_config.json into configs folder in main path (out of config folder) v1.3.4 for MC 1.16.5

### ISSUE THREAD

**Issue by Hrodgaer** [haubna/PhysicsMod#100]
In v1.3.4 for MC 1.16.5, the physics_config.json & physics_server_config.json are saved into folder named "configs" in main path (.minecraft), causing configurations can't be saved on a server such as Aternos.
In v2.3.6 for MC 1.17 is solved.
Please, release a new version por MC 1.16.5 that solve this issue so that we can play on a server in MC 1.16.5, since v1.17.X isn't yet optimized and really works very badly.
Thanks!

**Comment by haubna** [comment]
No. Physics Mod for 1.17 is way more optimized and better.

Hrodgaer ***@***.***> schrieb am Mi. 1. Sep. 2021 um 22:11:

**Comment by Hrodgaer** [comment]
In this case I will have to play on the server without this wonderful mod, waiting for MC 1.17.x to be optimized and with Forge and Optifine working together. Thank you very much for the reply!
