### ISSUE TITLE
Unable to use gl_VertexID in shaders [BUG]

### ISSUE THREAD

**Issue by bawat** [haubna/PhysicsMod#1008]
**Describe the bug**
This VoxelsReimagined shader code
    if (gl_VertexID % 4 == 0) {

Gets transformed into
    if (physics_finalPositionID % 4 == 0) {

Because of this PhysicsMod code
vertex = StringUtils.replace(vertex, "gl_Vertex", "physics_finalPosition");

Because PhysicsMod meant to change gl_Vertex to physics_finalPosition. But gl_VertexID also exists and gets caught in the crossfire.

**Comment by bawat** [comment]
Haubna says this is fixed in 1.21

**Comment by haubna** [comment]
Yup fixed with 1.21.

**Comment by dwdvIl** [comment]
But what about 1.20.1?
Do you have any patches for 1.20.1 and Iris 1.6? (v167d)

Edit: Nevermind, I managed to make my own patch for it
If anyone's curious, you need to patch two files:

- net/diebuddies/physics/ocean/ShaderInjectionOcean.class
- net/diebuddies/physics/ocean/ShaderInjectionLiquids.class

Below the code that replaces `gl_Vertex` with `physics_finalPosition`:
`vertex = StringUtils.replace(vertex, "physics_finalPositionID", "gl_VertexID");`
