### ISSUE TITLE
Expired URL

### ISSUE THREAD

**Issue by gioissussYT** [haubna/PhysicsMod#1010]
When i tried to download 1.21.3 v173 and 1.21.1 v172b on the ko-fi page it says Expired URL.

Please check if the URL's are not paid.

![image_2024-12-01_205452234](https://github.com/user-attachments/assets/6fc4a43b-d79d-4453-a8ba-6e3bbe168f2d)

Minecraft Version: 1.21.3 also 1.21.1
Physics Mod Version: V173 and v172

**Comment by haubna** [comment]
Thanks for letting me know! They weren't paid but I somehow messed up copying a proper link. Fixed now.
