### ISSUE TITLE
Texture Glitch

### ISSUE THREAD

**Issue by StealthMeister1** [haubna/PhysicsMod#102]
Sometimes when a mob enters its ragdoll state, the textures of my skin, mobs that aren't dead, and any items that I hold will get glitched and show the textures of the mob (you'll see what I mean). Or in the case of tools I hold, they either show nothing or various other items.

It has fixed itself so far every time, but the time it takes to fix itself varies. Sometimes it's immediate, sometimes a few seconds, other times 30 seconds to a few minutes. Still annoying. Also, quitting to the menu and reloading does not fix it. I haven't tried F3+T yet as I just remembered it was a thing and I already shut the game down.

All in all, you'll see what I mean when you look at the photos.

EDIT: Just tested F3+T and it does NOT fix the issue.

![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_18_42 PM - Copy](https://user-images.githubusercontent.com/12484573/131936251-a9347c18-2164-4108-940c-9ae35ee18618.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_18_42 PM](https://user-images.githubusercontent.com/12484573/131936260-62a4018b-7df1-4237-8632-e83a35e83931.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_18_49 PM](https://user-images.githubusercontent.com/12484573/131936265-d6626a28-8d67-4bc9-adbc-f5add8213758.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_18_55 PM](https://user-images.githubusercontent.com/12484573/131936270-ac1a5fb7-6f22-4f54-b46a-47adc1fe24b0.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_19_01 PM](https://user-images.githubusercontent.com/12484573/131936275-1f46312a-7c5e-4af2-bbfd-7cfb3d5c7bd7.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_19_16 PM](https://user-images.githubusercontent.com/12484573/131936279-91d833c6-822e-4c4c-80c5-619fad278993.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_19_28 PM](https://user-images.githubusercontent.com/12484573/131936284-3fcf7177-8759-473b-aa73-bba7647e200a.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_19_37 PM](https://user-images.githubusercontent.com/12484573/131936285-bce06bb4-f014-484a-923c-96acf05eb1ac.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_19_44 PM](https://user-images.githubusercontent.com/12484573/131936290-767d0c4c-bafe-490d-a168-ff3dc59c1e95.png)
![Minecraft_ 1 17 1 - Singleplayer 9_2_2021 8_19_54 PM](https://user-images.githubusercontent.com/12484573/131936296-3ea7cf74-1af3-4a5a-b8e9-fc1813622a49.png)

**Comment by WitherSkell** [comment]
i think its because of shaders.

**Comment by StealthMeister1** [comment]
> i think its because of shaders.

I'll test it for awhile without shaders.

**Comment by StealthMeister1** [comment]
It is indeed because of shaders. I have two accounts, one using it and one not. One with shaders got the glitch and the one not using it did not.

Still, would it be possible for this mod to be configured to work with shaders more properly?

**Comment by haubna** [comment]
Are you using Optifine + Vanillaccurate?

**Comment by StealthMeister1** [comment]
> Are you using Optifine + Vanillaccurate?

No. I'm just using Optifine, Shaders, and the Physics mod.

**Comment by haubna** [comment]
Try the Iris Shader Mod and let me know if this problem still exists. Optifine was just a quick hack to make it work but for Sodium nobody should use Optifine.

**Comment by StealthMeister1** [comment]
> Try the Iris Shader Mod and let me know if this problem still exists. Optifine was just a quick hack to make it work but for Sodium nobody should use Optifine.

It won't let me. It conflicts with optifabric and crashes before it can start.

**Comment by haubna** [comment]
Yeah because you should only use optifabric when optifine is installed. Remove optifabric as well.

**Comment by StealthMeister1** [comment]
> Yeah because you should only use optifabric when optifine is installed. Remove optifabric as well.

Oh I didn't even see you tell me to remove optifine. Well how am I supposed to use shaders without optifine?

**Comment by haubna** [comment]
Iris Shader mod. This Mod also integrates Sodium which will give you waaaaay better performance.

**Comment by StealthMeister1** [comment]
> Iris Shader mod.

This? https://www.curseforge.com/minecraft/mc-mods/irisshaders/download/3404785

I tried it and it doesn't even look like shaders. No dynamic lighting, shadows, or anything.

**Comment by haubna** [comment]
You need to install the shaders... please read the instructions.

**Comment by StealthMeister1** [comment]
> You need to install the shaders... please read the instructions.

Ohhhh, so I use whatever shaders with Iris?

**Comment by haubna** [comment]
Yeah.

**Comment by StealthMeister1** [comment]
> Yeah.

I'll get back to you in about 10 minutes. Gonna let me spawner build up mobs and slaughter them all at once. That's when the glitch happens the most.

**Comment by StealthMeister1** [comment]
It did not occur.

**Comment by haubna** [comment]
Ok good. I will not fix this issue since Optifine is only available over a third developer and not the original creator of Optifine. The go to shader mod for fabric is Iris.
