### ISSUE TITLE
Suggestion: Physics Sound Effects

### ISSUE THREAD

**Issue by Khodyn** [haubna/PhysicsMod#103]
Sound effects for physics objects and ragdolls would add a lot of immersion.

**Comment by haubna** [comment]
I like that idea :)

**Comment by ChapperNi** [comment]
+1 to this idea, i had the exact same idea in mind.

**Comment by QAQlinmiao** [comment]
Same idea

**Comment by PiotrekUnityDeveloper** [comment]
great idea!

**Comment by kingarthur0975** [comment]
OMG yes!!

**Comment by haubna** [comment]
Added sound effects in 2.6.0.
