### ISSUE TITLE
Game Crashes when Entering a World with Fabric Physics Mod 2.5.7

### ISSUE THREAD

**Issue by TubaApollo** [haubna/PhysicsMod#106]
Hey, with the latest version of the physics mod, my game crashes as soon as I enter a world. I did not have this problem with the previous versions. Here is the log from the crash https://paste.ee/p/mfkv5.

**Comment by haubna** [comment]
Something is majorly messed up in your mods folder. First what are those mod names?
  [✔️] iris-mc1.17-1.1.2-starline+build.538
  [✔️] sodium-extra-mc1.17.1-0.3.4
  [✔️] sodium-fabric-mc1.17.1-0.3.2+IRIS2-build.151

Don't seem like the original mod files. Second: Iris includes Sodium so why do you use both? Either use Iris or Sodium and sodium should be just one file. I only support the original mod files.

**Comment by haubna** [comment]
I've looked it up and starline seems to be a fork of Iris. This is not supported. Tested original Iris and Sodium Mod and it works fine.

**Comment by TubaApollo** [comment]
Okay good to know, i was only confused as it worked with the previous version

**Comment by haubna** [comment]
Yeah I am constantly adding stuff and I guess some performance improvement broke it with the fork you are using.

**Comment by TubaApollo** [comment]
I have the same Problem with only Iris, Sodium, FabricApi and the PhysicsMod. No Idea what that could cause. https://paste.ee/p/SmdFT

**Comment by haubna** [comment]
Oh wow. Found the bug. It worked in the development environment and when trying to run it on the normal minecraft client it crashed as well. Fixed it. Just redownload version 2.5.7 from https://minecraftphysicsmod.com

**Comment by TubaApollo** [comment]
Great, thank you very much!
