### ISSUE TITLE
ReplayMod Compatibility

### ISSUE THREAD

**Issue by evolvoodoo** [haubna/PhysicsMod#107]
I see that you added compatibility with the replay mod. However, when I re-render a scene with the physics mod active I get physics for the items but not the ragdoll physics as is set. Is there something I need to tick on for these to render in the final scene? Or is this in fact an issue? I am not entirely sure, hopefully, you can sus it out. Thank you for any help.

**Comment by haubna** [comment]
I haven't played with rendering in Replay Mod since it didn't work with shaders enabled. I will have a look at it.

**Comment by evolvoodoo** [comment]
The replay mod certainly works with shaders currently. I run complimentary shaders and the renders turn out fantastic. If you could get the ragdoll physics working in the renders  it would honestly open a whole new world of machinema. Thanks for your time and work on this mod. It is simply fantastic.

**Comment by haubna** [comment]
Rendering works now (but the blocks most be destroyed within the rendering sequence).
