### ISSUE TITLE
Tridents dont fall correctly

### ISSUE THREAD

**Issue by dbrighthd** [haubna/PhysicsMod#109]
Some items like Tridents and Spyglasses dont lay flat on the ground correctly. I assume its because they look different when held than they do on the ground

![2021-09-09_13 47 03](https://user-images.githubusercontent.com/68525639/132760334-b4a7c16e-5ec2-4c0d-871d-988190ea963f.png)

**Comment by haubna** [comment]
Fixed in 2.5.12
