### ISSUE TITLE
[Enhancement] Proportional Destruction Particles

### ISSUE THREAD

**Issue by Brittank88** [haubna/PhysicsMod#11]
Akin to [this mod for 1.12](https://www.curseforge.com/minecraft/mc-mods/proportional-destruction-particles), it would be nice if non-full-blocks that are broken have proportional particles. Currently, breaking stairs will generate a full block's worth of fragments. It breaks the realism a bit.

**Comment by haubna** [comment]
Yeah I am working on it but it is way more complex than his version. I guess he simply uses the visual hitbox. I need to parse the original model file to get the cubes to later turn them into fractured ones in realtime :)
But definitely on my todo list!

**Comment by Brittank88** [comment]
That sounds so cool. Would this also mean that particles have improved textures? Cables, CC Turtles and some modded chests have texture issues for example.

**Comment by haubna** [comment]
Ok newest version (1.2.0) is uploaded. It supports a lot of new blocks (included modded ones). The texture used is still the break particle texture. I might change this in a future version :)
