### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by TheSteveRemix** [haubna/PhysicsMod#110]
unique blood colours for mobs (creeper=green, enderman=bright purple etc)

**Comment by Alexzrequester** [comment]
that's neat!
good idea-
it would be cool

**Comment by QAQlinmiao** [comment]
wow this cool awa

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
