### ISSUE TITLE
Vine Physics

### ISSUE THREAD

**Issue by caoqt1** [haubna/PhysicsMod#114]
I dont own the pro version of vine physics but i thought of something and that is how are the hitboxes for vines going to work on servers as i am pretty sure you can get banned or it will disable the mod if it alters the hitbox position or something like that but i had an idea

basically disable vine physics on servers/multiplayer making them only for singleplayer?

**Comment by LizIsTired** [comment]
AFAIK, it doesn't change the hitbox at all, the normal vanilla hitbox applies for everything but a separate version is simulated and rendered for use with Physics Mod, servers have no idea that anything is going on because there isn't anything going on

**Comment by haubna** [comment]
It only changes the visuals like a shader :)
