### ISSUE TITLE
[Request] Fishing Pole Physics

### ISSUE THREAD

**Issue by KingSkel** [haubna/PhysicsMod#115]
The string of a fishing pole irl normally lays on top of the water and flows around with the current, as well as a small bit of string below the bobby where the hook is tied to. Minecraft string on the fishing pole floats in the air not even touching the water and there's no hook. The only physics Vanilla MC has for it, would be the bobby bouncing on the water.

Could you give the Fishing Pole more physics?

**Comment by haubna** [comment]
Sure! :)

**Comment by haubna** [comment]
Added in Pro V13
