### ISSUE TITLE
[Bug] Minecraft will consistently randomly crash, even on a external server.

### ISSUE THREAD

**Issue by StatusConnected** [haubna/PhysicsMod#118]
When the game crashes it says "java.lang.NullPointerException: Cannot invoke "physx.geomutils.PxConvexMesh.getAddress()" because "mesh" is null"

**Comment by haubna** [comment]
Which version are you using?

StatusConnected ***@***.***> schrieb am Di. 14. Sep. 2021 um
15:39:

**Comment by StatusConnected** [comment]
I am using version 2.5.5.

**Comment by haubna** [comment]
Update to version 2.5.9.

StatusConnected ***@***.***> schrieb am Di. 14. Sep. 2021 um
15:42:

**Comment by StatusConnected** [comment]
Just updated.

**Comment by haubna** [comment]
Perfect, issues was fixed with version 2.5.6.
