### ISSUE TITLE
[Bug] Infinite Loading Screen on version 2.5.9

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#121]
Title above tells you everything :)

**Comment by haubna** [comment]
I can't seem to reproduce this bug. Are you using Minecraft 1.17.1 for sure? This error would only occur when using Minecraft 1.17.

**Comment by NaiNonTH** [comment]
> I can't seem to reproduce this bug. Are you using Minecraft 1.17.1 for sure? This error would only occur when using Minecraft 1.17.

I am sure. I used 1.17.1

**Comment by haubna** [comment]
Send me a log please when this occurs. You can hold down F3 + C for about 10 seconds to crash the client while loading.

**Comment by NaiNonTH** [comment]
> Send me a log please when this occurs. You can hold down F3 + C for about 10 seconds to crash the client while loading.

https://www.mediafire.com/file/vd9yukkon0gadjr/2021-09-15-5.log/file

I can't put them in pastebin because it's too long

**Comment by haubna** [comment]
Some other mod tries to Mixin into cape rendering with the function "fixCapeTransparency". Not sure which though. My best guess is that the capes mod is conflicting with my mod. I can probably resolve this with the next release.

**Comment by NaiNonTH** [comment]
> Some other mod tries to Mixin into cape rendering with the function "fixCapeTransparency". Not sure which though. My best guess is that the capes mod is conflicting with my mod. I can probably resolve this with the next release.

Yeah, you're right, Thank you :)
