### ISSUE TITLE
[Feature Request] Toggle update notification on/off

### ISSUE THREAD

**Issue by elhertz** [haubna/PhysicsMod#123]
Title self explanatory.

**Comment by haubna** [comment]
Why though? People always reported bugs from old versions because they never updated. Just download the latest version.

**Comment by elhertz** [comment]
I made a modpack to play with my brothers and I want to be in control of the updates. That's my own personal reason but I'm sure there're people who rather disable them and update at their own pace.

**Comment by haubna** [comment]
I will make an option in the config file in future releases! :)

**Comment by elhertz** [comment]
Thank you!

**Comment by haubna** [comment]
Now available in version 2.5.10
