### ISSUE TITLE
[Bug] Cloth physics breaks player model when shaders activated

### ISSUE THREAD

**Issue by Likarios** [haubna/PhysicsMod#124]
#  Using:
- optifabric-1.11.20
- OptiFine_1.17.1_HD_U_G9
- fabric-api-0.40.1+1.17
- fabric-language-kotlin-1.6.4+kotlin.1.5.30
- physics-mod-pro-v7

# Issue:

As soon as shaders are activated, the two layers of the player and his item sometimes break appart and the cape isn't rendered anymore.

It seems to affect every shader I tested.
Deactivating either cloth physics or shaders resolves the issue, but both cannot coexist.

## Without shaders
<a href="https://ibb.co/zXS6rBC"><img src="https://i.ibb.co/48j17XC/2021-09-16-01-25-42.png" alt="2021-09-16-01-25-42" border="0"></a>

## With shaders
<a href="https://ibb.co/JtqkSGF"><img src="https://i.ibb.co/zxFftBH/2021-09-16-01-26-26.png" alt="2021-09-16-01-26-26" border="0"></a>

**Comment by haubna** [comment]
I've tried multiple things now, can't seem to fix it. Optifine is such a mess. The only solution I can give you is to use the Iris Shader mod. Physics Mod got developed with Iris Shader support.

**Comment by Likarios** [comment]
Thanks for your fast reply and your time involved, I appreciate.
Too bad, several things are still lacking in Iris Shaders.

**Comment by haubna** [comment]
Yeah I know. Still trying to get it somehow to work because I need it for the Forge release anyways.

**Comment by haubna** [comment]
By the way I might have some interesting stuff for you to replace Optifine. Here are all alternatives for the Optifine features in Fabric: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by Likarios** [comment]
Thanks, I never came accross such detailled references, will give those a try!
Good luck in making your mod forge portable with shaders.

**Comment by haubna** [comment]
I've got good news for you! Cloth rendering works now with Optifine, will upload a new version today/tomorrow :)

**Comment by Likarios** [comment]
Wow, you are pretty efficient! May I ask how you managed to make it works?

Glad to hear that anyway! You are the cherry on the cake which is my modpack.

**Comment by haubna** [comment]
I completely moved the rendering to another point. Seems like Optifine has no problem there.

**Comment by Likarios** [comment]
May I point you new rendering problems?

## Cape physics with BSL shaders:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/3StKgYj/cape-bsl.png" alt="cape-bsl" border="0"></a>

## Cape physics with all SEUS PTGI shaders:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/chk29dG/cape-ptgi-hrr.png" alt="cape-ptgi-hrr" border="0"></a>

**Comment by haubna** [comment]
Not going to support every shader. I don't have the timer for it.
