### ISSUE TITLE
[Bug] Deleting a selected cape in files and then starting the game makes it crash

### ISSUE THREAD

**Issue by Likarios** [haubna/PhysicsMod#125]
# Using:
- fabric-api-0.40.1+1.17
- fabric-language-kotlin-1.6.4+kotlin.1.5.30
- physics-mod-pro-v7

# Issue:
Selecting a certain cape in the physics option, then quiting the game, then deleting the files of the cape in question in the capes folder will make Minecraft crash when trying to render the cape with an -1 error code ```Cannot read field "positions" because "simulation.mesh" is null```.

**Comment by haubna** [comment]
Fixed in Pro V8
