### ISSUE TITLE
[BUG] Blocks like torch/sea_lantern do not emit light

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [haubna/PhysicsMod#126]
When switching to blocky block destruction any light source like torch or sea lantern **is not emitting any light when destroyed**
I don't know if this is intentional but i saw that as a bug.

Also i have a suggestion to make blocky destroyed redstone lamp emit a light when touching a redstone powered block (like redstone block)

**Comment by haubna** [comment]
But it is destroyed, so it shouldn't emit light.
