### ISSUE TITLE
[REQUEST] Liquid Physics and Deformation

### ISSUE THREAD

**Issue by Touqai** [haubna/PhysicsMod#127]
Now it may be very difficult but if there was a way for minecraft to have realistic liquid physics like RDR2 for example it would be amazing same with lava and having the option of making it so your feet place depths in the ground as deforming it. I would love that but I do understand you'd probably need a decent pc but if you could make that possible and make it so the game settings have an option to turn that on that would be fantastic

**Comment by caoqt1** [comment]
Interesting idea but imagine the hell it would be just to render that in real time

**Comment by cuccboi** [comment]
It would be very cool, but haubna thought of how horrible it would be to add these features already. :(

**Comment by Touqai** [comment]
Well, Yes It may be hard to render it in time, But Keep in mind remember how you've got red dead redemption they have this feature added so it just means you'll need a decent pc for it to work

**Comment by caoqt1** [comment]
the rdr2 liquid thing looks more like ripples and shaders  than physics

**Comment by haubna** [comment]
Added liquid physics in the pro version
