### ISSUE TITLE
[BUG] Some shaders make every render blurry

### ISSUE THREAD

**Issue by Likarios** [haubna/PhysicsMod#128]
Those visual artifacts are seen when using BSL, SEUS PTGI, and some others even with motion blur OFF.

## Duplicated vines:
<img src="https://i.ibb.co/YZjmgB3/duplicate-vines.png" alt="duplicate-vines" border="0">

## Vines are rendered strangely
<img src="https://i.ibb.co/6tHDDmH/glitch-vines.png" alt="glitch-vines" border="0">

## Block physics are blurry
<img src="https://i.ibb.co/27NLD8v/glitch-blocks.png" alt="glitch-blocks" border="0">

**Comment by haubna** [comment]
This is a shader bug. They use temporal antialiasing which causes this.
