### ISSUE TITLE
[BUG] Cape stretchs when moving relatively fast

### ISSUE THREAD

**Issue by Likarios** [haubna/PhysicsMod#129]
You may be aware of this issue. It happens in every configuration.

<img src="https://i.ibb.co/hYhrSLT/cape-size.png" alt="cape-size" border="0">

**Comment by haubna** [comment]
Yes, improvements will come with performance improvement update!

Likarios ***@***.***> schrieb am Sa. 18. Sep. 2021 um 19:04:

**Comment by haubna** [comment]
Should be better in the new version (especially since version V12).
