### ISSUE TITLE
 [Fabric 1.17] - Blocks under Y:0 are ignored by block particules

### ISSUE THREAD

**Issue by StellaBiscuit** [haubna/PhysicsMod#13]
With the new world height limit added in 1.17 and soon being implemented in 1.18, you can place/break block under Y:0 and above Y:256
Sadly, all the block particules ignore blocks under Y:0 (didn't tested above Y:256) and just go trough it

**Comment by haubna** [comment]
Thanks for the report! Fixed in the newest version (2.1.2).
