### ISSUE TITLE
Fabric version crashes randomly during gameplay with message: Error: java.lang.ArrayIndexOutOfBoundsException: Index 1600 out of bounds for length 1600

### ISSUE THREAD

**Issue by kingarthur0975** [haubna/PhysicsMod#131]
I'm running version 2.5.10 for 1.17.1, and this crash only happens when I have this mod installed. Any ideas as to why?

**Comment by haubna** [comment]
Crash log please.

**Comment by kingarthur0975** [comment]
Here's the crash log: [](https://pastebin.com/nnhEiR8Y)

**Comment by kingarthur0975** [comment]
https://pastebin.com/nnhEiR8Y
the crash log ^

**Comment by haubna** [comment]
I think I got the culprit, should be fixed in version 2.5.12 (not released yet).

**Comment by haubna** [comment]
Released version 2.5.12, should be fixed :)
