### ISSUE TITLE
[REQUEST] Ragdoll physics while still alive

### ISSUE THREAD

**Issue by Fahobomoclowbia** [haubna/PhysicsMod#132]
I think it would be cool if you could ragdoll mobs before they die. 
Think in other games like Skyrim or Dishonored or something. 

Maybe if you hit a mob with a heavy attack you could send it flying ragdolled, then it would get up and return to normal. I think something like this would add a lot of depth and impact to combat. Im already really impressed with the ragdoll physics from the mod. This is just the next step really.

**Comment by haubna** [comment]
It is a client side mod. This would require syncing stuff and would need to come from the server. Maybe in the future but I got other plans for now :P

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
