### ISSUE TITLE
[REQUEST] Toggle player ragdoll

### ISSUE THREAD

**Issue by KotaTNT** [haubna/PhysicsMod#134]
[REQUEST] It would be really cool if you can make your self go ragdoll without dying so you can jump of a cliff then go ragdoll and see your body just flopping down the cliff lol.

**Comment by Liamsawn** [comment]
Seems like a cool idea.

**Comment by Liamsawn** [comment]
But it's a client-side mod and it needs syncing and I'm pretty sure that's hard to do.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
