### ISSUE TITLE
Minecraft won't load with versions past 2.5.9 [BUG]

### ISSUE THREAD

**Issue by elijah-schulman** [haubna/PhysicsMod#135]
Not sure why but in version 2.5.9 my main menu loads without a resource pack and then falls into a loop showing the Mojang loading screen then back to the menu and it continues like that. Any newer version I try to use Minecraft doesn't even open. No crash logs appear though. (I'm guessing it's a compatibility issue with another mod)

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.9+

**Comment by haubna** [comment]
Try it without the mods and let me know. Would be nice to know whether a mod causes it and if so which one so I can fix it :)

**Comment by Bullseye55** [comment]
Just got this error updating from 2.5.8 to 2.5.15, and have a log report. Only mod changed was Physics. It makes sense considering the performance optimizations introduced in 2.5.9, too.

https://pastebin.com/C5BTFVMM

**Comment by haubna** [comment]
Root of this error is from another mod. Probably a weird JOML dependency on
his side.

Bullseye55 ***@***.***> schrieb am Fr. 1. Okt. 2021 um 14:45:

**Comment by Bullseye55** [comment]
Will have to keep testing with my spare time to find it, then. Hmm.

**Comment by haubna** [comment]
software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:474)

Bullseye55 ***@***.***> schrieb am Fr. 1. Okt. 2021 um 14:53:

**Comment by Bullseye55** [comment]
Geckolib's repository, no doubt, a very common dependency. 

https://github.com/bernie-g/geckolib

**Comment by haubna** [comment]
Tried geckolib with Fabric today. Everything works fine now.
