### ISSUE TITLE
Cloth physics for Elytra [REQUEST]

### ISSUE THREAD

**Issue by SirPytan** [haubna/PhysicsMod#138]
It would be awesome if you could maybe add a version of your cloth physics for the Elytra and maybe even make it a bit configurable, it could be maybe similar to the batman wings/cape when he flies from Batman: Arkham Knight?

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
