### ISSUE TITLE
using Figura and Physics mod 2.1.2 at the same time causes crash

### ISSUE THREAD

**Issue by SkyTheNerd** [haubna/PhysicsMod#14]
[crash-2021-07-14_06.07.00-client.txt](https://github.com/haubna/PhysicsMod/files/6815293/crash-2021-07-14_06.07.00-client.txt)

**Comment by haubna** [comment]
Will be fixed in the next release. Thanks for the report! :)

**Comment by haubna** [comment]
Fixed. Also mod creators can now add ragdoll support with the new API if they want to :)

**Comment by SkyTheNerd** [comment]
Epic, Keep up the good work.
