### ISSUE TITLE
Realistic slime block [REQUEST]

### ISSUE THREAD

**Issue by edcnekcescsecf** [haubna/PhysicsMod#140]
Realistic slime block
Please add a realistic slime block like here in this viedeo https://m.youtube.com/watch?v=mEIqOiEwJJ4
Gretings Uranium

**Comment by Skittlq** [comment]
If he does do this, I wish him good luck. That could be almost impossible because Portemay used a rendering software, I think blender?

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
