### ISSUE TITLE
Switching to a Resource Pack breaks textures of blocks effected by vine physics.

### ISSUE THREAD

**Issue by xSaVageAU** [haubna/PhysicsMod#143]
**Describe the bug**
Switching from default textures to a resourcepack makes vine physics blocks invisible. switching back to default textures makes the blocks reappear, but with a broken texture.

This only effects the ones that are close-ish to you (maybe 10-15 blocks). If you run a short distance and come back it returns to normal. Freshly placed/grown sugarcane after the bug occurs is uneffected

**To Reproduce**
Stand near Blocks/Foliage effected by vine physics and switch between resourcepacks. it doesn't matter what resourcepack you use, aslong as minecraft does its reload thing after you apply anything in that menu will cause it to happen

**Screenshots**

Before Switching to a resourcepacks.
![2021-09-27_14 07 36](https://user-images.githubusercontent.com/80192613/134849359-0b5bc425-5d11-4c9d-afb2-34113dd7c325.png)

After switching to a resource pack.
![2021-09-27_14 07 49](https://user-images.githubusercontent.com/80192613/134849470-e3c90dda-2e3d-4d76-afc1-0f641a37dd54.png)

After switching back to default. (freshly planted sugarcane on right for comparison)
![2021-09-27_14 11 46](https://user-images.githubusercontent.com/80192613/134849527-cfec733b-51ef-4d35-b0c4-a14f59dc6364.png)

Different texture when starting bug with resourcepack already enabled.
![2021-09-27_14 18 53](https://user-images.githubusercontent.com/80192613/134849608-e1862108-c6ed-47b9-995e-3ff797db5791.png)

Minecraft Version: 1.17.1
Physics Mod Version: V12 Pro

**Comment by haubna** [comment]
Fixed in the next release, thanks for the report! :)

**Comment by haubna** [comment]
Fixed in Pro V13

**Comment by xSaVageAU** [comment]
Awesome :) That was very quick, I'm impressed!
