### ISSUE TITLE
Black Particles Appear When Mining Block and Inside of Fractured Pieces [BUG]

### ISSUE THREAD

**Issue by minfonica** [haubna/PhysicsMod#144]
Black square particles appear when I mine blocks and are standing in a pile of fractured pieces. MC Break Particles are off in the physics settings. 

Mine any block while standing inside a pile of fractured blocks. 

![2021-09-27_02 05 08](https://user-images.githubusercontent.com/91454749/134860387-ff025a79-55a4-4c37-938c-98742cf28d9c.png)

Minecraft Version: <1.17.1>
Physics Mod Version: <2.5.13>

**Comment by xSaVageAU** [comment]
If i'm correct MC Break Particles option only applies to the particles when the block breaks, and not the particles from hitting it(these are effected by the particles option in video settings). As to why they are black though I cannot help you with that issue (i'm just a consumer). My best bet for now would be to turn particles down or off in video options

**Comment by haubna** [comment]
Are you sure that the black particles are caused by the physics mod? Are they colored when not using the physics mod? Are you using any other mods?

**Comment by minfonica** [comment]
Thank you all for the quick replies. After some further testing it turns out Biomes O'Plenty of all mods is responsible for this.
