### ISSUE TITLE
Fishing rod line physics might be a bit too long

### ISSUE THREAD

**Issue by xSaVageAU** [haubna/PhysicsMod#145]
**A description of the requested feature**
I'm loving the V13 update, especially the banner physics!
I love the new fishing rod aswell, but I feel that the line is maybe a bit too long.
I don't throw the rod out far so the extra fishing line sort of clumps together.

![2021-09-28_01 22 14](https://user-images.githubusercontent.com/80192613/134943619-5de72b25-53f1-439d-b2b0-a1932ce8b0ae.png)
![2021-09-28_01 22 05](https://user-images.githubusercontent.com/80192613/134943628-e6b41ecd-7dfd-4b5d-a31a-a3238fece9e5.png)

**Comment by haubna** [comment]
I will add an option with fishing line length :P

xSaVageAU ***@***.***> schrieb am Mo. 27. Sep. 2021 um 18:00:

**Comment by haubna** [comment]
Was added a couple weeks ago :)
