### ISSUE TITLE
No block physics on bamboo using Fractured physics

### ISSUE THREAD

**Issue by xSaVageAU** [haubna/PhysicsMod#146]
**Describe the bug**
With Fractured block physics enabled bamboo doesn't have physics when broken. Only the top of the bamboo (the flowering bit) has block physics but they are just square textures.
The Blocky block physics looks great on all the bamboo and works as you would expect.

For now i've just set bamboo to use blocky physics and fractured physics for everything else. (Maybe that could be the default as it looks really good!)

**To Reproduce**
Break Bamboo with fractured block physics.

**Screenshots**
Top of bamboo with Fractured physics
![2021-09-28_02 40 37](https://user-images.githubusercontent.com/80192613/134956365-ed256645-198f-4f5c-ac36-b52f62a81251.png)

Bamboo with Blocky physics
![2021-09-28_02 45 14](https://user-images.githubusercontent.com/80192613/134956719-3ed0a2fc-b218-4259-bac0-bc84d41d6920.png)

Minecraft Version: 1.17.1
Physics Mod Version: Pro V13

**Comment by haubna** [comment]
Does this occur without a texture pack too? Some texture packs mess up the models. But yeah at some point I will release a custom config with individual settings that fit the certain blocks.

**Comment by xSaVageAU** [comment]
yeah it happens without it too

**Comment by haubna** [comment]
Fixed in version 2.5.15

**Comment by xSaVageAU** [comment]
Very nice :)
