### ISSUE TITLE
Compatibility with ReplayMod for 1.16.5 [BUG]

### ISSUE THREAD

**Issue by rojaoo** [haubna/PhysicsMod#148]
**Describe the bug**
When I render a video with PhysicsMod and ReplayMod, the block physics just freeze. I can't play on 1,17.1 because of OpenGL, the most recent version I can use is1.16.5.

**To Reproduce**
Record a replay with the ReplayMod and PhysicsMod, and render it.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/67767832/134984072-144127da-94c4-47e2-8597-8c7279c4712e.png)

Minecraft Version: 1.16.5
Physics Mod Version: 1.3.4

**Comment by haubna** [comment]
Legacy versions of Minecraft are not supported.

**Comment by rojaoo** [comment]
So, you wont update 1.16 mod anymore?

**Comment by haubna** [comment]
Correct.

**Comment by rojaoo** [comment]
Ok, thank you anyway
