### ISSUE TITLE
 my cape is abnormal

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#15]
In **version 2.2.0**, my cape is abnormal
![2021-07-15_11 07 07](https://user-images.githubusercontent.com/83525912/125724297-637cf2c4-1f9f-467b-ab6c-4533d96ca87a.png)

**Comment by haubna** [comment]
Please let me know if this problem persists in version 2.2.1!

**Comment by QAQlinmiao** [comment]
Return to normal in version 2.2.1
