### ISSUE TITLE
BUG REPORT: Immersive Portals compatibility

### ISSUE THREAD

**Issue by Nyx019** [haubna/PhysicsMod#15]
Hello! I really love this mod, but when playing in combination with Immersive Portals, I realized that when I go through a nether portal, no blocks that I break in the nether will have the particles from this Physics Mod. To test if this was due to the mod maybe not registering me changing the dimension, I first went back into the overworld to test if the nether blocks would show the animation there. They did. Then I tried placing a vanilla portal and going through - then the animations also worked in the nether. Thus, I can say with certainty that this mod is not really compatible with Immersive Portals

**Comment by haubna** [comment]
No intention to fix this issue anytime soon. First I want to finish this mod and then we talk compatibility with other mods, but thanks for the report :)
