### ISSUE TITLE
Can we pick up the ragdoll with our hands？

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#150]
You can use a tool, such as a wooden stick or directly pick up the body of the doll with your hands, which is very interesting.

**Comment by caoqt1** [comment]
This seems like a good idea as this does not sound like something you have to do on the server

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
