### ISSUE TITLE
PhysX Mac M1 (arm64) natives

### ISSUE THREAD

**Issue by Protoxy22** [haubna/PhysicsMod#151]
[libPhysXJniBindings_arm64.dylib.zip](https://github.com/haubna/PhysicsMod/files/7270466/libPhysXJniBindings_arm64.dylib.zip)

Hello, I share you natives I built with my mac m1 (arm64) for a project
Latest version 0.4.14

**Comment by haubna** [comment]
I can't ship it because I can't guarantee a virus free native lib from a user. I am sorry.

**Comment by Protoxy22** [comment]
I understand

**Comment by leobeekay** [comment]
Hello, how can I use this lib in existing 2.7.2 mod?
