### ISSUE TITLE
Feature description [REQUEST]

### ISSUE THREAD

**Issue by DiamondStudiosCode** [haubna/PhysicsMod#152]
**Requested feature**
PLEASE ADD IT TO *1.12 2*!! It's the largest mod version so far. Basically, it has the most mods and that's why I want it to be on *1.12 2*

**Comment by caoqt1** [comment]
Sorry bro but your out of luck, haubna already stated that he will not be updating the physics mod for older versions of minecraft :/

**Comment by QAQlinmiao** [comment]
https://minecraftphysicsmod.com/pro
Once I reach the patreon goal of 2000$ I will port the Physics Mod to the most requested Minecraft versions (if possible).
Therefore, he has to complete the goal of $2,000 before he can port to other versions.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
