### ISSUE TITLE
1.16.5 is a "LTS" modding version and you should at least support it with bug fixes. [REQUEST]

### ISSUE THREAD

**Issue by txnitxnichopper** [haubna/PhysicsMod#153]
Updating any modpack with more than a couple of mods is a huge issue. Because of this there are only a handful of major release versions that cement themselves with big modpacks, basically only three in eight years, 1.7.10, 1.12.2, and 1.16.5. Every other version in between has limited support for major mods. 

Doing some quick math on Curseforge shows that all the 1.16.5 modpacks have 10x the playerbase of all the 1.17 packs. There are more then ten 1.12.2 modpacks that each have more players than all the 1.17 packs combined. 1.16.5 is a de facto "Long Term Support" version and will continue to be supported by everyone else in the community for at least a few more years.

Your attitude towards even doing simple bug fixes for "legacy versions" that are _less than a year old_ makes me not even want to include this mod in my modpacks. If I run into a game breaking bug, you won't fix it? And the source isn't even available for others to fix it themselves.

Besides, Caves and Cliffs Part II _isn't even out yet_. Every single new feature added in that version has been easily backported by the community.

**Comment by haubna** [comment]
I will once the patreon goal is reached. I will pay someone for porting to
older versions then.

Vice ***@***.***> schrieb am Sa. 2. Okt. 2021 um 08:58:
