### ISSUE TITLE
Death Types [REQUEST]

### ISSUE THREAD

**Issue by rwilliaise** [haubna/PhysicsMod#155]
**Description**
There should be an option for mobs (and specific mobs) to either fracture, ragdoll, and etc if they die to a specific damage source. In other words, you could have zombies fracture when they die from explosive damage, or skeletons fall apart when killed with ranged.

**Comment by caoqt1** [comment]
You can already do this

**Comment by rwilliaise** [comment]
How?

**Comment by tiagopro206** [comment]
You can't. You can only make them have different physics from eachother.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
