### ISSUE TITLE
Bendy limbs and weight control [REQUEST]

### ISSUE THREAD

**Issue by tiagopro206** [haubna/PhysicsMod#156]
**New ragdoll type: Flexible limbs and  Setting: Weight property**

Make it possible to choose a new type of ragdoll physics that makes it possible for mobs to bend their limbs as they fall, together with that, a new setting that allows the player to change the mobs' weights so physics would behave differently on them.

For example: Making an Iron Golem simply collapse on the floor while a player or zombie gets pushed a bit and takes a little more to fall.

**Comment by MikeOxLongLOL** [comment]
That would require to edit the models so i am guessing no

**Comment by SkyTheNerd** [comment]
Weight would actually be pretty cool, there are already gravity properties.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
