### ISSUE TITLE
TNT Knock-On effect.

### ISSUE THREAD

**Issue by dferr18** [haubna/PhysicsMod#157]
Hi, I would like to request that, in the event a TNT Block explodes, the same physics effect will be enabled.

For example;
in the current state,
I place a TNT block under ground and set it off, and the explosion hollows out a bit of the immediate surrounding enviroment.
However, with the request i am making, the TNT would have the same physics domino affect as the player does by destroying blocks manually.

**Comment by caoqt1** [comment]
So you want tnt to not fling blocks?

**Comment by dferr18** [comment]
Oh no what I mean is, when you smash a block all the blocks on top of it crumble, almost all blocks above, however tnt just makes a regular hole
And doesn’t have that ceiling domino effect.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
