### ISSUE TITLE
When the player dies, all the dolls will not move

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#158]
They appear to be in a stopped state, and they won’t move no matter how you do it

This problem appeared after the player was killed by a monster

![2021-10-05_03 48 22](https://user-images.githubusercontent.com/83525912/135915208-82120e57-ebd9-45dd-9e0f-cecda114159d.png)

Minecraft Version: <1.17.1>
Physics Mod Version: <2.5.15>

**Comment by haubna** [comment]
Please open a new issue with the proper description like in the issue template. I can't help you without a proper description.
