### ISSUE TITLE
The rag doll seems to be stationary and unable to move [BUG]

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#159]
They appear to be in a stopped state, and they won’t move no matter how you do it

This problem appeared after the player was killed by a monster (I was killed by a spider)

![2021-10-05_03 44 45](https://user-images.githubusercontent.com/83525912/135916161-2d124b45-26eb-4ce6-9dfd-a0d2b3e2ca1e.png)
![2021-10-05_03 48 22](https://user-images.githubusercontent.com/83525912/135916164-7a25cf88-6982-48aa-806d-57d053a08c53.png)

MODS：
![_)BFPCL$S1_9B9~E~O3SM{9](https://user-images.githubusercontent.com/83525912/136660576-37e552f3-4a5b-49cf-b6d7-744938f9520e.png)

Minecraft Version: <1.17.1>
Physics Mod Version: <2.5.15>

**Comment by haubna** [comment]
Do you use any other mods? Which Modloader are you using? Fabric or Forge + version number?

**Comment by QAQlinmiao** [comment]
fabric，no other mods

**Comment by QAQlinmiao** [comment]
I encountered this problem in this version, and there has never been such a problem before 2.5.15

**Comment by haubna** [comment]
I just tried it and I can't seem to reproduce this bug. Which operating system are you using? Can you reproduce this?

**Comment by QAQlinmiao** [comment]
Windows10

**Comment by QAQlinmiao** [comment]
This problem seems to be caused by F2 screenshots 

If the size of the screenshot is 2x 3x 4x, if you click F2, the ragdoll will be stuck, and it will never be able to move, and it can only be solved by CTRL+T.

**Comment by haubna** [comment]
How do you change the size of a screenshot? CTRL+T doesn't do anything for me, neither does CTRL+A. Still can't reproduce this bug.

**Comment by QAQlinmiao** [comment]
![UFZZGCSS{H~J}7CE2)L5~O3](https://user-images.githubusercontent.com/83525912/136659802-8f56ed6c-f253-457a-aa42-ae4b9f5290f4.png)
Not ctrl+T but F3+T Reload the resource pack

**Comment by haubna** [comment]
You told me that you are not using any other mods. Is this Optifine?

**Comment by QAQlinmiao** [comment]
really

**Comment by haubna** [comment]
Just scroll up.

**Comment by QAQlinmiao** [comment]
> Just scroll up.

？

**Comment by haubna** [comment]
To see that you mentioned not using any other mods.

**Comment by QAQlinmiao** [comment]
Sorry, I will pay attention to write MOD next time

**Comment by haubna** [comment]
Seems to no longer be an issue with Optifine.
