### ISSUE TITLE
Blocks and Ragdoll physics doesn't work with Optifine shaders

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#16]
When you use Optifine shaders with Physics enabled, You'll see that the game will use the original block particle instead of the Physics mod. Also, the physics (both block parts and mob parts) just stick and buggy to the camera.

**Comment by haubna** [comment]
Which version are you using?

**Comment by NaiNonTH** [comment]
> Which version are you using?

Optifine: G9 pre29
Physics: Latest version

**Comment by QAQlinmiao** [comment]
Have the same problem as you.
Same version.
![2021-07-16_14 35 05](https://user-images.githubusercontent.com/83525912/125903349-afac0d3c-abd0-463d-a467-b71e94cb96ea.png)

**Comment by haubna** [comment]
I can't reproduce this with physics 2.2.1, optifabric 1.11.18 and optifine 1.17.1 HD U G9 pre29. Try it again with those versions and let me know if it changes it.

**Comment by QAQlinmiao** [comment]
In the latest version of Optifine shaders, even the cloak will display an error
as the picture shows
![2021-07-16_14 49 08](https://user-images.githubusercontent.com/83525912/125905045-6167fef0-b0af-4237-a3e7-ae61784c6f0b.png)
![2021-07-16_14 49 13](https://user-images.githubusercontent.com/83525912/125905054-a16cfbf5-6b8f-473c-9f0c-4ec46d36c476.png)

**Comment by haubna** [comment]
Well this issue probably won't get sorted since Optifine is not supported. Fabric users should use Iris.

**Comment by haubna** [comment]
I've uploaded a new physics version. Please try these versions of each mod and let me know if the problem still exists.
physics 2.2.1, optifabric 1.11.18 and optifine 1.17.1 HD U G9 pre29

**Comment by NaiNonTH** [comment]
> Well this issue probably won't get sorted since Optifine is not supported. Fabric users should use Iris.

Understandable. I'll report this issue to the Optifine github then.

**Comment by haubna** [comment]
Optifine doesn't officially support fabric as far as I know so probably no luck there. As mentioned above let me know if the problem still exists with the following versions: physics 2.2.1+, optifabric 1.11.18 and optifine 1.17.1 HD U G9 pre29

**Comment by NaiNonTH** [comment]
> Optifine doesn't officially support fabric as far as I know so probably no luck there. As mentioned above let me know if the problem still exists with the following versions: physics 2.2.1+, optifabric 1.11.18 and optifine 1.17.1 HD U G9 pre29

It's still exists :(

**Comment by seanawesome** [comment]
Same problem here, and I can't use Iris because of its horrible compatibility issues.

**Comment by haubna** [comment]
Iris made a hook for my mod in version 1.16. It's still in the 1.17 version. They have to remove it to prevent any crashes. Iris dev already knows about that and will fix it in there future releases.

**Comment by haubna** [comment]
Iris Shaders and Optifine now work with version 2.4.2.
