### ISSUE TITLE
Fractured Cube Option [REQUEST]

### ISSUE THREAD

**Issue by Skittlq** [haubna/PhysicsMod#160]
I wanna see an option for blocks or even entities, a fractured cubes option, this idea comes from a mod called Fancy Block Particles (FBP), it makes particles have physics and makes it 3D, but keeps the block aesthetic.

The link takes you to an image that shows what I mean.
https://imgur.com/ZfiAoir

I would love to see this for blocks and even mobs.

**Comment by QAQlinmiao** [comment]
Your question is the same as 89

**Comment by NaiNonTH** [comment]
#89

**Comment by haubna** [comment]
Added in 2.6.0
