### ISSUE TITLE
Make Players/Entities Ragdoll in certain situations. [REQUEST]

### ISSUE THREAD

**Issue by Skittlq** [haubna/PhysicsMod#161]
All right, hear me out, add a server-side option, to make players or other entities enter ragdoll and go in third person when certain things happen to them, for example, getting hit by a minecart, getting hurt by explosions, falling from a high place, getting launched by the Ender Dragon, maybe getting shot by an arrow? and other things that could cause a person to collapse or get flung. It would be pretty funny but I'd assume it would be hard to code. It's the physics mod after all.

**Comment by MikeOxLongLOL** [comment]
Most likely no, this is a CLIENTSIDE physics mod and i think it will stay like that, if haubna will end up adding serverside features he would have to create 4 versions of the physics mod (one for fabric that is clientside, one for fabric that is serverside, one for forge that is clientside and one for forge that is serverside) i am pretty sure this can be executed different but yeah :/

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
