### ISSUE TITLE
[BUG] Fake Entity Blocks (boats, item frames, etc.) after breaking from PVP Server Compatibility

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#163]
**Describe the bug**
After you break entity blocks like item frames, boats, painting, etc. Those blocks will still appear and stay unbreakable. You can't interact them, But collisions and hitboxes are still working. This also occurs with dropping items after using /give command, which you can't pick them up.

**To Reproduce**
1. Install Physics Mod 2.5.15
2. Place some boat, painting, item frame, etc. then try breaking it.

**Screenshots**
https://imgur.com/a/GYycHaV

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.15

**Comment by haubna** [comment]
I just tried it, doesn't happen on my end. Which Modloader are you using? Fabric or Forge? Do you have any other mods installed that could cause this?

**Comment by QAQlinmiao** [comment]
I have the same problem with him

https://user-images.githubusercontent.com/83525912/136660417-7eefb50d-7ffa-458c-b002-047a307f4371.mp4

**Comment by haubna** [comment]
So does this persist with only Optifine and without the Physics Mod?

**Comment by NaiNonTH** [comment]
> I just tried it, doesn't happen on my end. Which Modloader are you using? Fabric or Forge? Do you have any other mods installed that could cause this?

I used Fabric

> So does this persist with only Optifine and without the Physics Mod?

**Edited:** I don't think it is. I tried removing OptiFine and the issue is still occured.

**Comment by NaiNonTH** [comment]
I can't test with the newest version of the OptiFine (OptiFine H1 U pre6) because OptiFabric is kinda outdated (https://github.com/Chocohead/OptiFabric/issues/392)

**Comment by NaiNonTH** [comment]
> So does this persist with only Optifine and without the Physics Mod?

Okay. I tried figuring this out and these are what I got.

     1. This issue only occurs on Physics Mod version 2.5.15
     2. This issue still occurs without any other mods (except Fabric API)
     3. This issue doesn't depend on the Fabric Loader version.
     4. This issue also doesn't depend on the Fabric API version. (tested on 0.41.0, 0.40.1, 0.39.2)

I do not know why you couldn't find this bug. But this would be a really hard issue that you (may) have to figure out.

@haubna

**Comment by haubna** [comment]
I've tried it again. Doesn't occur on my end.

**Comment by haubna** [comment]
https://user-images.githubusercontent.com/7816894/137692668-c6a1cbff-826d-4be0-b2bd-bae4d4c30f0a.mp4

**Comment by haubna** [comment]
I've tried it multiple times with multiple versions. I simply can't reproduce this bug. I am using Minecraft 1.17.1, Fabric API 0.41.0 and Physics Mod 2.5.15. No bug.

**Comment by NaiNonTH** [comment]
Mmm...That's weird

**Comment by haubna** [comment]
What's your operating system?

**Comment by NaiNonTH** [comment]
> What's your operating system?

Windows 10 Pro 64-bit

**Comment by haubna** [comment]
I am honestly clueless. It's hard to fix a bug that doesn't occur when I am trying it :o

**Comment by NaiNonTH** [comment]
Yeah. I still have no idea :(

**Comment by NaiNonTH** [comment]
@haubna 

Okay, I found it.

After I disabled PVP Server Compatibility setting, This issue was gone.

**Comment by NaiNonTH** [comment]
It has to be something with PVP Server Compatibility

**Comment by NaiNonTH** [comment]
Closing this issue and making a new one instead.
