### ISSUE TITLE
Ragdoll still needs enhancement

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#164]
Ragdolls are pushed far away by the force of entities (monsters, player creatures, etc.)
In reality, **it should be pushing a little distance or dragging**
But this is not the case in the mod
As soon as you jump, t**he rag doll will be kicked and fly to a far place**. As soon as you sprint, **the rag doll will be kicked far away**. This needs to be changed (_hope that it can be repaired next time_)
In addition, if you die in PVP, **you will not generate your own ragdoll.**

**Comment by FrostyIzHere** [comment]
it cracks me up everytime sprint-jumping on a ragdoll and it just flies high up.
you can make football minigame out of this

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
