### ISSUE TITLE
Knockback/Punch affecting ragdolls [REQUEST]

### ISSUE THREAD

**Issue by wojciechsacewicz** [haubna/PhysicsMod#165]
That would be a very nice feature, so if you killed something with a punch bow, it would get punched away, maybe make the option togglable, and scalable.

Another feature that would be great is that blocks destroyed with a tnt explosion could have the blocky type, but blocks destroyed by the player (hand, tools) would get fractured.

Have a nice day!

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
