### ISSUE TITLE
When amour pieces, tools and anvils break, they should shatter and fall to the ground. [REQUEST]

### ISSUE THREAD

**Issue by alftooka** [haubna/PhysicsMod#166]
Hi, my suggestion is if anything breakable that is equip-able to the player, (example: shields, armour, tools, weapons, totems) and things like anvils should shatter into pieces when broken.

Thanks :)

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
