### ISSUE TITLE
Fishing rod misaligned in first person on ultrawide screens [BUG]

### ISSUE THREAD

**Issue by anUrbanGoose** [haubna/PhysicsMod#169]
When playing on an ultrawide resolution (3840x1600 in my case) the fishing line is misaligned with the item.

![2021-10-15_17 06 09](https://user-images.githubusercontent.com/11893054/137510459-b4ae2411-6c7c-46ec-8c4b-f08ef3ca12ef.png)

**Comment by haubna** [comment]
Does this happen with the vanilla fishing line as well?

**Comment by anUrbanGoose** [comment]
Yeah it does, my bad.

**Comment by haubna** [comment]
Ok, hopefully Mojang fixes it at some point :P
