### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by UltraBlackLinux** [haubna/PhysicsMod#17]
Hey,
Please make this mod fully open source. It's a pain to use this mod because of it's many incompatibilities.
This mod's current Closed-source-open-source-limbo-status is just annoying.
Why is this mod closed source?
Thanks!

**Comment by haubna** [comment]
It stays closed source. Minecraft dev community was a dick to me.

**Comment by UltraBlackLinux** [comment]
> It stays closed source. Minecraft dev community was a dick to me.

Depends on how you ask there - They were nice to me

> Which incompatibilities are you talking about?

I can't name many at the moment, but OF shaders have problems with this for example. There are also quite a few other mods, that this physics mod breaks.

> And open source wouldn't solve any problem. It would just profit some individuals that would steal the code and fuck me over.

Open source is not about stealing code, it's about honor and trustworthiness. On top of that, code can even improve from the community.
If you are scared of someone using your code in their project, add a license, like the MIT license - They __must__ clarify, what code belongs to them. Like [this](https://github.com/UltraBlackLinux/MineMenuFabric/blob/71fdaf81ae86e41d3183c0447773b8f6d7cb3455/src/main/java/me/ultrablacklinux/minemenufabric/client/screen/MineMenuSelectScreen.java#L42) for example.

You mod has so much potential, but just locking it away is childish behavior.

> It would just profit some individuals that would steal the code and fuck me over.

https://stopmodreposts.org/

Please rethink your decision. Only showing us one file doesn't help anyone out.

**Comment by haubna** [comment]
It has an API and stays closed source. Respect my decision and stop being annoying for the 10th time. Childish behaviour is what you do.

**Comment by UltraBlackLinux** [comment]
> It has an API and stays closed source.

An api does not solve mod incompatibilites. It's also a pain to use libraries that have no maven.

> Respect my decision and stop being annoying for the 10th time. Childish behaviour is what you do.

The 10th time? I am for once telling you what is going on, but sure thing, go ahead. This is, why your mod has barely any users left.
You should make this github repo private again. It's currently useless.
