### ISSUE TITLE
Diving into the void with elytras and dying crashes the game [Fabric]

### ISSUE THREAD

**Issue by Snivyer1910** [haubna/PhysicsMod#17]
As the title says, diving into the void with elytras crashes the game, I'm using the blockify entites setting for getting this crash

https://paste.ee/p/SFIty

**Comment by haubna** [comment]
Crash is caused by replay mod. Currently this mod is not compatible with replay mod.

**Comment by Snivyer1910** [comment]
funny, because I wasn't recording when the crash happened

**Comment by haubna** [comment]
That doesn't matter.

**Comment by Snivyer1910** [comment]
alright, then I'll just remove replay mod, that mods has a lot of incompatibilites anyway, thanks for clarifying!

**Comment by Snivyer1910** [comment]
Crash happened again without replay mod
https://paste.ee/p/jBz26

**Comment by haubna** [comment]
You are using a bunch of mods. I can't tell you which is incompatible, sorry. Crash is not caused by my mod.

**Comment by Snivyer1910** [comment]
Got the crash with only fabric api and physics mod
https://paste.ee/p/1AojW

Exact conditions:
1. Use Physics Mod on a server that doesn't have physics mod
2. Go to the end with elytra and netherite armor enchanted
3. Jump into the void and activate the elytras
4. look directly downwards so you get the highest speed and dinstace from y 0 you can

**Comment by Snivyer1910** [comment]
I think I have my suspicions

I have keepInventory enabled

**Comment by Snivyer1910** [comment]
got it in a singleplayer world

https://paste.ee/p/LgQTb

**Comment by haubna** [comment]
Please use the latest version of the mod before sending in crash reports.
