### ISSUE TITLE
Cape Pos [HELP]

### ISSUE THREAD

**Issue by Medatur76** [haubna/PhysicsMod#170]
**Describe the bug**
My cape(when I stand still) is inside my armor/body. I didn't do this before.

**To Reproduce**
1. Install the mod
2. run the game

**Screenshots**
https://imgur.com/a/SpRs83h

Minecraft Version: 1.17.1
Physics Mod Version: 15

**Comment by haubna** [comment]
Do you use any other mods? I can't reproduce it with your description.

**Comment by Medatur76** [comment]
optifabric and optifine

**Comment by Medatur76** [comment]
What do I do?

**Comment by haubna** [comment]
I am using Optifabric 1.11.20 and Optifine 1.17.1 HD U G9 pre32 and everything works fine.
![2021-10-17_18 46 10](https://user-images.githubusercontent.com/7816894/137636920-01ba1613-2e7e-4a6d-ae1e-68dd6e752ce8.png)

**Comment by Medatur76** [comment]
Her
![Migrator Cape](https://user-images.githubusercontent.com/90143210/137637002-81ba79ba-1c05-4b94-adf7-3151df1700d9.png)
e
[Migrator Cape.dae.txt](https://github.com/haubna/PhysicsMod/files/7360442/Migrator.Cape.dae.txt)
:
Turn Migrator Cape.dae.txt into Migrator Cape.dae and put the files in the capes folder

**Comment by haubna** [comment]
Dude don't report a bug when you mess up the model creation... you didn't even mention that you made your own one...

**Comment by Medatur76** [comment]
Wdym I messedup the model?
