### ISSUE TITLE
Elytra dynamics Arcade 

### ISSUE THREAD

**Issue by Verona00** [haubna/PhysicsMod#174]
A fun elytra with real physics
Since childhood, I dream of real physics in minecraft. When they added Elytra, I wanted it to be real, but they never made a real one :(. Is it possible to do this in minecraft? Does your PhysX have this capability? Is there any program that would have this capability? If anyone knows, please let me know.

1- The closest found in minecraft is the Cool Elytra Roll:

https://user-images.githubusercontent.com/92803932/137963476-757303a5-bc0b-4a75-86d6-b4de7b66e650.mp4

Link: https://youtu.be/lSDdLaFasqg

2- After that, I saw a video with immersive vehicles mod, amazing how the helicopter works, it looks like bf4 physics, or almost:
Link: https://youtu.be/mK71NMne6u0

3- this helicopter is similar to the one made in unity:

https://user-images.githubusercontent.com/92803932/137964414-9386b86d-b39e-4468-92d1-7143f7e11256.mp4

Link: https://youtu.be/BR8ASoO8n5Q
The same helicopter in another video    Link: https://youtu.be/ne7tzS8PMd4
Is it possible to do this in minecraft?

4- the elytra would function like an airplane, flying upside down or sideways. using f (x) = ax² + bx + c, but more complete:

https://user-images.githubusercontent.com/92803932/137965023-b40ef05c-d555-4ba4-898d-84565e6903b3.mp4

Link: https://youtu.be/YYvxRAHyYA4

4.1- ignore the shots:

https://user-images.githubusercontent.com/92803932/137965310-68a62aa9-63ca-4bb5-bbaa-2af216d5ed25.mp4

Link: https://youtu.be/oufPmJkK0ZI

5- A fair and perfect elytra / plane for minecraft: 

https://user-images.githubusercontent.com/92803932/137965774-2261a7bf-655d-49fb-a363-8b9c7fd642d9.mp4

Link: https://youtu.be/pdrAVzDMz14

5.1- An older version of the project:

https://user-images.githubusercontent.com/92803932/137966137-0de66a01-048e-42b5-ae83-63db5cedafbd.mp4

Link: https://youtu.be/BYu8kN0Aq08

5.2- The mouse flight controller is the coolest and most interesting thing, is this possible?

6- another example, but the creator left the source:

https://user-images.githubusercontent.com/92803932/137966754-414a809f-df7b-4c62-8133-05ca4731f0a5.mp4

Link: https://youtu.be/87N7S0islxU

7- is it possible to add a fun and fluid elytra in Minecraft? With your Physx is it possible to do? If possible, could you add the Elytra dynamic arcade to minecraft? please. If it's not possible with your programs, do you know a program that works? Please, would anyone know the name of any program that works? David, if that's possible, and it's not in your plans or not feasible, I'm going to have to learn programming and make my mod.
please tell me if it's possible :)
please someone tell me if it's possible :)

signed "AR" : .

**Comment by caoqt1** [comment]
Sorry for blowing up but he's not going to add aerodynamics to Minecraft since this is a client side mod the most he will do to elytra's is ADD cloth physics for them not aerodynamics 🙄

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
