### ISSUE TITLE
PVP Server Compatibility Option causes Fake Entity Blocks (boats, item frames, etc.) after breaking them [BUG]

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#176]
**Describe the bug**
Ref. from issue #163 , I found out that the cause of this bug to happen is the PVP Server Compatibility option. In order to fix this, you have to turn off the PVP Server Compatibility option.

**To Reproduce**
1. Install Physics Mod v2.5.15 with any version of Fabric API
2. Launch the game
3. Enable PVP Server Compatibility Option in Physics Mod Option
4. Join any world and try placing some boats, item frames, paintings, etc. and break them.
5. You'll see that those entity blocks will stay there with their collision, But you can't break them anymore and you can break blocks through them.

**Screenshots**
Ref. from #163 --> https://imgur.com/a/GYycHaV

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.15

**Comment by haubna** [comment]
Finally a way to reproduce it! Didn't think of the PVP compat setting. Already fixed it in my dev version. Fix will be included in the next release! :)

**Comment by NaiNonTH** [comment]
> Finally a way to reproduce it! Didn't think of the PVP compat setting. Already fixed it in my dev version. Fix will be included in the next release! :)

Noice XD

**Comment by haubna** [comment]
Fixed in the latest version.
