### ISSUE TITLE
Goat simulator type ragdoll button. [REQUEST]

### ISSUE THREAD

**Issue by CatMaster8232** [haubna/PhysicsMod#177]
I want a type of ragdoll button that puts you in ragdoll mode. Using it, you could fling yourself if you push while moving, and use it to jump higher or to fit through gaps. It would probably put you in 3rd person as making that camera work would be really hard. And it would probably be toggleable. GIF for what happens in goat sim below.
![Ig1EZlC](https://user-images.githubusercontent.com/41759537/138974986-8a8713c0-d564-4a91-85f3-e3a7814cf764.gif)

**Comment by caoqt1** [comment]
Although I like this idea it might not happen since this mod is client side based so most likely not

**Comment by CatMaster8232** [comment]
> Although I like this idea it might not happen since this mod is client side based so most likely not

But there is the crumble feature. Don't see why not, and it'll be disabled by default like the crumble.

**Comment by MikeOxLongLOL** [comment]
> > Although I like this idea it might not happen since this mod is client side based so most likely not
> 
> But there is the crumble feature. Don't see why not, and it'll be disabled by default like the crumble.

yeah he did not consider that, i hope that this gets added

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
