### ISSUE TITLE
Snow and fluids physics [REQUEST]

### ISSUE THREAD

**Issue by tad-dufort** [haubna/PhysicsMod#178]
this is probably very hard to do real time and laggy so i dont expect it to be added quickly or at all but it would look really cool

**Comment by caoqt1** [comment]
No, just no

**Comment by MikeOxLongLOL** [comment]
> this is probably very hard to do real time and laggy so i dont expect it to be added quickly or at all but it would look really cool

dont listen to Dreyson, haubna will implement liquid physics

**Comment by haubna** [comment]
Added liquid physics.
