### ISSUE TITLE
Rendering bug with Ice and Fire

### ISSUE THREAD

**Issue by LoSilopante** [haubna/PhysicsMod#179]
Description
When ~~mob physics are enabled~~ both mods are installed, killing a dragon from the mod Ice and Fire causes the corpse of the dragon to not render until the players quits the world and enters back in.

1. Install both Ice and Fire, and the Physics Mod
2. Kill a dragon
3. The corpse of the dragon is invisible.

Minecraft Version: 1.16.5
Physics Mod Version: 1.3.4
Ice and Fire Version: 2.1.9
[Mention](https://github.com/Alex-the-666/Ice_and_Fire/issues/4259#issue-1035645669)

**Comment by haubna** [comment]
For a quick fix you can try to just disable the physics for the ice and fire mobs. Let me know if it works.

**Comment by LoSilopante** [comment]
Where's the option to disable features only for a particular mod?

**Comment by haubna** [comment]
Options -> Physics Settings -> Mob Settings -> Customize

**Comment by LoSilopante** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/24480520/139811693-749f2559-05a5-450a-8bf2-f48d2198354f.png)

I have no option to customize which mobs the mod works with, **but** even when disabling Mob Physics entirely the issue still occurs.

**Comment by MikeOxLongLOL** [comment]
Upgrade your physics mod version if you can, the version of physics mod you are using probably does not have the ability to turn off physics

**Comment by LoSilopante** [comment]
> 
> 
> Upgrade your physics mod version if you can, the version of physics mod you are using probably does not have the ability to turn off physics

But I'm literally using the latest version, I wrote it in my post...
```
Minecraft Version: 1.16.5
Physics Mod Version: 1.3.4
Ice and Fire Version: 2.1.9
```

**Comment by haubna** [comment]
This update is not available for 1.16. Not much that you can do about it,
sorry.

LoSilopante ***@***.***> schrieb am Di. 2. Nov. 2021 um 14:07:

**Comment by LoSilopante** [comment]
I guess this version will stay incompatible with mods that add death animations forever.

**Comment by haubna** [comment]
Not necessarily. Once the patreon goal gets reached I will backport the mod
to as many versions as possible.

LoSilopante ***@***.***> schrieb am Di. 2. Nov. 2021 um 14:31:
