### ISSUE TITLE
Banner Physics Load Distance [REQUEST]

### ISSUE THREAD

**Issue by Levi-Blackerman** [haubna/PhysicsMod#180]
Cloth physics for banners reduces FPS by a decent chunk, but the actual physics aren't that noticeable from a distance.

Being able to change the distance of which the banner physics are disabled, or just completely shortening the distance would help performance quite a bit.

Edit: I noticed it's mainly banners with patterns. the more complex the pattern the more of an effect it has on the fps e.g. an ominous banner decreases my fps from 144 to 90 while a simple creeper banner decreases it to like 137.

**Comment by haubna** [comment]
Yeah it mostly comes down to the rendering (as far as I've noticed). I will work on the performance once I added liquid physics! :)

**Comment by MikeOxLongLOL** [comment]
> Yeah it mostly comes down to the rendering (as far as I've noticed). I will work on the performance once I added liquid physics! :)

excuse me WHAT

**Comment by haubna** [comment]
Liquids got added and in the most recent version I also added a banner render distance slider for better performance!
