### ISSUE TITLE
Physics Coats (Cape that surrounds your body) [REQUEST]

### ISSUE THREAD

**Issue by DutchBaller** [haubna/PhysicsMod#181]
**Physics Coats**
Basically coats that have physics like imagine a cape that surrounds your whole character or almost that has physics and can have details and you can create them just like capes.

**Comment by haubna** [comment]
Before I can implement that I will need to make the cloth physics more robust (currently a coat would clip inside the body a lot of times).

**Comment by DutchBaller** [comment]
Okay well you can always take your time

**Comment by haubna** [comment]
Done.
