### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by TVHeadyt** [haubna/PhysicsMod#182]
i bought the patron but nothing happened i bought the Programmer Tier for the pro verison so can i just get the pro verison thats all i want.

**Comment by haubna** [comment]
You can download the pro version from the corresponding patreon post.

**Comment by TVHeadyt** [comment]
yeah ik but its not leting me on patron

**Comment by haubna** [comment]
You are probably not logged in then.

**Comment by TVHeadyt** [comment]
oh your right lol
