### ISSUE TITLE
Game crashes when trying to play singleplayer

### ISSUE THREAD

**Issue by MikeOxLongLOL** [haubna/PhysicsMod#183]
My game will crash with exit code 0 when trying to load into a singleplayer world, it usually crashes around 95% or crashes when it says loading world, but for some reason i can get into multiplayer just fine with no crashes, also i am testing this on linux

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.15

**Comment by haubna** [comment]
Include a crash log please.

**Comment by MayorBryce** [comment]
A latest.log file or a crash report helps!

**Comment by haubna** [comment]
Closed due to missing crash log.
