### ISSUE TITLE
(CLOSED) Toggle Block Removal

### ISSUE THREAD

**Issue by mc4539** [haubna/PhysicsMod#184]
One thing that frustrates me about this mod is the inability to disable physics-related block removal. Whenever a supporting block is removed from just about anything, all blocks above it (plus any supported arches or ceilings) are automatically removed. This is undesirable behavior, especially when using the mod in single-player simply for its visual effects.

**Comment by MikeOxLongLOL** [comment]
> One thing that frustrates me about this mod is the inability to disable physics-related block removal. Whenever a supporting block is removed from just about anything, all blocks above it (plus any supported arches or ceilings) are automatically removed. This is undesirable behavior, especially when using the mod in single-player simply for its visual effects.

you can literally turn it off in settings

**Comment by mc4539** [comment]
> you can literally turn it off in settings

What do you mean? I can turn off the block breaking effect, but I can't turn off blocks becoming removed from the world due to "physics".

**Comment by MikeOxLongLOL** [comment]
idk what you mean by "blocks becoming removed from the world due to "physics""

**Comment by mc4539** [comment]
Block collapsing can be turned off by going into Physics Settings > Server Settings > Collapse Blocks: OFF.

**Comment by mc4539** [comment]
I swear this mod needs better documentation.
