### ISSUE TITLE
new version is making me haev a loading screen that finishes then restarts[BUG]

### ISSUE THREAD

**Issue by RennyB00** [haubna/PhysicsMod#186]
hi sorry, so i downloaded a newer version of the physichs mod, and now whenever im on the loadign screen for minecraft the red screen goes away for a second after loading then comes back, and it does that forever

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.1

https://user-images.githubusercontent.com/93074614/140627166-939cc6da-4c77-4db5-b48e-4e0fd500a08b.mp4

5

**Comment by haubna** [comment]
You are using 139 mods. If you are using something that changes capes or banners it will break my mod.
