### ISSUE TITLE
Texture Transparency Issues with Sodium and Mob Death Physics [BUG]

### ISSUE THREAD

**Issue by Jenipherr** [haubna/PhysicsMod#188]
**Describe the bug**
When a mob dies and the death effect is set to anything but Disabled, all textures momentarily become invisible, leading to the world "flickering."

**To Reproduce**
With sodium installed, kill a mob while mob death effects are enabled.

Minecraft Version: 1.17.1
Physics Mod Version: Pro v15

**Comment by haubna** [comment]
Could've been related to PBR. Should be fixed in the most recent versions. Please reopen in case this problem still exists.
