### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#19]
In version 2.2.2
Witches and wandering merchants have problems
as the picture shows
![2021-07-17_17 38 57](https://user-images.githubusercontent.com/83525912/126033409-be19506d-ab09-4020-9461-675bf6bffe4e.png)
![2021-07-17_17 39 54](https://user-images.githubusercontent.com/83525912/126033411-7f41c4a4-1e89-458d-a26f-36cd1db0e555.png)

**Comment by QAQlinmiao** [comment]
And the drowned with the trident will make mistakes
![2021-07-17_22 05 30](https://user-images.githubusercontent.com/83525912/126039602-d88b9cdd-6753-4a71-aa87-f676c877ed8d.png)
![2021-07-17_22 05 39](https://user-images.githubusercontent.com/83525912/126039606-e5a3ef73-c586-46b7-bd55-91167a4cf456.png)

**Comment by haubna** [comment]
Thanks for the reports! Fixed in the newest version (2.2.5).
