### ISSUE TITLE
Incorrect info in forge mod list [BUG]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#190]
**Describe the bug**
In the forge mod list the entry for the physics mod lists the wrong version (1.0 instead of 1.3.4) it also links to a dead website not the current website (http://diebuddies.net/ instead of https://minecraftphysicsmod.com)

**To Reproduce**
load game, click mods, scroll down to physics mod

**Screenshots**
![image](https://user-images.githubusercontent.com/82549089/141921462-eb728739-e1f7-401c-9c82-4603b55b766a.png)

Minecraft Version: 1.16.5
Physics Mod Version: 1.3.4 forge

**Comment by haubna** [comment]
Old versions of MC won't get new updates.

**Comment by ChiefArug** [comment]
To add to this the mixin config file name is unhelpful, instead of being the modid its the old website. Makes debugging crashes very difficult.
I only found this because searching 'diebuddies curseforge' somehow brings up the CF page for this mod.
