### ISSUE TITLE
Ability to configure mod from forge mod list [REQUEST]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#191]
It would be very helpful to have the ability to change the mods configuration options from without the forge mod list menu

I am using minecraft 1.16.5, forge 36.2.6 and physis mod 1.3.4 forge

![image](https://user-images.githubusercontent.com/82549089/141921834-4a7806ba-891d-42cc-b10c-830e553824ff.png)

**Comment by haubna** [comment]
The mod is so complex by now that the config option of the Forge launcher wouldn't be enough!
