### ISSUE TITLE
[BUG] Infinite loading screen

### ISSUE THREAD

**Issue by stampyfan22** [haubna/PhysicsMod#192]
**Describe the bug**
I am unable to even load to the main menu.

Minecraft Version: Fabric 0.11.6 Minecraft 1.17.1
Physics Mod Version: pro v16

forced crash log is attached

[crash-2021-11-16_12.13.49-client.txt](https://github.com/haubna/PhysicsMod/files/7549570/crash-2021-11-16_12.13.49-client.txt)

**Comment by haubna** [comment]
Remove every mod that changes banners and capes (bannerpp).

**Comment by stampyfan22** [comment]
Unfortunately bannerpp apparently doesn't exist
this is a search in the entire directory

![explorer_0pyHpSL1Zq](https://user-images.githubusercontent.com/35874867/142060363-e32a4ff0-86a3-492b-9655-c7017145a753.png)
r

**Comment by haubna** [comment]
It is mentioned in the loaded mods though.

**Comment by stampyfan22** [comment]
I don't know what to say
heres the results when I search for just banner
That modlist says it has "more banner features" and "entity banners" but I removed entity banners 
![explorer_rj6tvHL1QB](https://user-images.githubusercontent.com/35874867/142060749-b18d644d-25ab-4afe-8a52-240ddc0fb981.png)

**Comment by haubna** [comment]
Just remove any mod that changes cape/banner behaviour.

**Comment by stampyfan22** [comment]
I have done that, entity banners was the only mod with banners even in its name, and as far as i know non of the other mods change banners and capes

**Comment by haubna** [comment]
What do you want me to do? I told you a solution for the problem. I am not going to go through your mod list and check everything for compatibility.

**Comment by stampyfan22** [comment]
fair enough sorry for wasting your time
