### ISSUE TITLE
Item drops create "phantom drops" [BUG]

### ISSUE THREAD

**Issue by nerdgh0st** [haubna/PhysicsMod#193]
**Describe the bug**
Throwing items into hoppers or sometimes picking drops up make a "phantom" version of it that stays there forever.

**To Reproduce**
Throw an item in a hopper or pick an item up

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.15

**Comment by haubna** [comment]
Couldn't reproduce this with Physics Mod version 2.5.18 and Minecraft 1.18. Should be fixed in the newest version.
