### ISSUE TITLE
Attack based physics. [REQUEST]

### ISSUE THREAD

**Issue by Amiiban** [haubna/PhysicsMod#194]
Attacking an enemy with a sword and finishing them with a hit to the head makes their head fall off, like the blocky enemy physics, but their torso and arms and legs are intact, like ragdoll physics. An axe blow to the head causes it to explode (fractured blood). This would double for any body part, kind of like the gore in fallout games. Enemies killed very close to explosions or creepers would do a fractured blood effect on all body parts. This could be toggled for every mob.

**Comment by rwilliaise** [comment]
Similar to #155

**Comment by Amiiban** [comment]
> Similar to #155

Mine specified the destruction of specific body parts, like the head or limbs.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
