### ISSUE TITLE
Voxel destruction [REQUEST]

### ISSUE THREAD

**Issue by Amiiban** [haubna/PhysicsMod#198]
A new block and mob destruction type, would split up blocks or mobs into each individual pixel on a normal 16x16 texture, Sort of like the destruction in Teardown.

**Comment by PessiPanto** [comment]
YES, I WAS JUST THINKING ABOUT THAT TOO

**Comment by MayorBryce** [comment]
I had that idea too! I made my own request, but this is the same thing!

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
