### ISSUE TITLE
[Suggestion] Allow / Deny List 

### ISSUE THREAD

**Issue by ArtixAllMighty** [haubna/PhysicsMod#2]
Suggestion,
 a list with blocks which we do not want to spawn particles from. 

I'm currently slightly bothered by the breaking of Shulker Boxes and Chests. 
I'd love to be able to exclude them.

But that's my opinion !

**Comment by haubna** [comment]
Yeah nice idea. I heard that a couple of times already. I am going to put that on the todo list :)

**Comment by Partonetrain** [comment]
Going to piggyback off of this. The same idea, but for mobs. If possible, a way to allow or deny mobs based on their namespace.

**Comment by haubna** [comment]
Implemented it in version 1.3.3 for mobs and blocks.
