### ISSUE TITLE
When Mob Physics are enabled, even on low settings, I get a crash.

### ISSUE THREAD

**Issue by StatusConnected** [haubna/PhysicsMod#2]
---- Minecraft Crash Report ----
// You're mean.

Time: 7/6/21, 11:07 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot read field "field_3502" because "box.field_3649[2]" is null
	at net.diebuddies.physics.PhysicsMod.addCuboid(PhysicsMod.java:344)
	at net.minecraft.class_630.handler$zzp000$renderCuboids(class_630.java:527)
	at net.minecraft.class_630.method_22702(class_630.java)
	at net.minecraft.class_630.method_22699(class_630.java:189)
	at net.minecraft.class_630.method_22699(class_630.java:197)
	at net.minecraft.class_630.method_22699(class_630.java:197)
	at net.minecraft.class_5597.method_2828(class_5597.java:23)
	at net.minecraft.class_922.method_4054(class_922.java:196)
	at net.minecraft.class_927.method_4072(class_927.java:49)
	at net.minecraft.class_927.method_3936(class_927.java:20)
	at net.minecraft.class_898.method_3954(class_898.java:178)
	at net.minecraft.class_761.method_22977(class_761.java:2197)
	at net.minecraft.class_761.method_22710(class_761.java:1799)
	at net.minecraft.class_757.method_3188(class_757.java:1510)
	at net.minecraft.class_757.method_3192(class_757.java:1150)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.diebuddies.physics.PhysicsMod.addCuboid(PhysicsMod.java:344)
	at net.minecraft.class_630.handler$zzp000$renderCuboids(class_630.java:527)
	at net.minecraft.class_630.method_22702(class_630.java)
	at net.minecraft.class_630.method_22699(class_630.java:189)
	at net.minecraft.class_630.method_22699(class_630.java:197)
	at net.minecraft.class_630.method_22699(class_630.java:197)
	at net.minecraft.class_5597.method_2828(class_5597.java:23)
	at net.minecraft.class_922.method_4054(class_922.java:196)
	at net.minecraft.class_927.method_4072(class_927.java:49)
	at net.minecraft.class_927.method_3936(class_927.java:20)

-- Entity being rendered --
Details:
	Entity Type: minecraft:spider (net.minecraft.class_1628)
	Entity ID: 27583
	Entity Name: Spider
	Entity's Exact location: 338.59, 64.40, -716.95
	Entity's Block location: World: (338,64,-717), Section: (at 2,0,3 in 21,4,-45; chunk contains blocks 336,0,-720 to 351,255,-705), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Entity's Momentum: -0.05, 0.15, -0.17
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_949@79b4d618
	Location: 1.28,-1.39,3.22 - World: (1,-2,3), Section: (at 1,14,3 in 0,-1,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -104.0625
	Delta: 0.34002316
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:178)
	at net.minecraft.class_761.method_22977(class_761.java:2197)
	at net.minecraft.class_761.method_22710(class_761.java:1799)
	at net.minecraft.class_757.method_3188(class_757.java:1510)

-- Affected level --
Details:
	All players: 1 total; [class_746['StatusConnected'/253, l='ClientLevel', x=337.31, y=64.00, z=-720.02]]
	Chunk stats: 1369, 1022
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,74,0), Section: (at 0,10,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 417754 game time, 665316 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:476)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, 1.17.zip, New Faithful Items.zip, Varied Magma Blocks.zip, Faithful+Overlays.zip, alternate-entities-v1-4.zip, Visual honey.zip, Gilded+Blackstone+Top+Add-on+1.0.zip, FaithfulClearVisionGlass.zip, OLG_1.1.3_1.16+.zip, Spyglass+model.zip, Invisble+World+Borders..zip, Simple+pixel+accurate+spyglasses (1).zip

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1932167248 bytes (1842 MiB) / 3154116608 bytes (3008 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8280
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f99
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6192
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 23383.05
	Virtual memory used (MB): 18547.91
	Swap memory total (MB): 15360.00
	Swap memory used (MB): 1699.43
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		antighost: AntiGhost 1.17-fabric0.34.9-1.1.4
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.1.20
		audiooutput: AudioOutput 0.0.4
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoreconnect: AutoReconnect 1.2.0
		bedrockify: BedrockIfy 1.1.1+mc1.17
		betterbiomeblend: Better Biome Blend 1.17.0-1.1.6-fabric
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		chat-up: Chat Up! 2.0
		clear-skies: Clear Skies 1.5.69
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colormeoutlines: Color Me Outlines 1.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		controlling: Controlling For Fabric 1.1.2
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		dynamicfps: Dynamic FPS 2.0.4
		eggtab: Egg Tab 2.0.0+1.16-fabric
		entityculling: EntityCulling-Fabric 1.3.1
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fastfurnace: FastFurnace 1.17-3.0
		firstperson: FirstpersonModel 2.0.2
		fpsdisplay: FPS-Display 1.4.0+1.17
		hatlist: Hat List 1.2
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.8.7-1.17
		krypton: Krypton 0.1.3
		lazydfu: LazyDFU 0.1.2
		loading-timer: Loading Timer 1.4.2+1.17
		loud_leads: Loud Leads 1.0.1+mc1.17
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.2
		multiconnect: MultiConnect 1.4.4
		multiconnect-api: MultiConnect API 1.4.4
		noanglebrackets: NoAngleBrackets 1.1.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		opitems: Op Items 1.2.0
		optifabric: OptiFabric 1.11.9
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		panorama_tweaker: Panorama Tweaker 1.0.1+mc1.17
		particlerain: Particle Rain 1.3.1
		physicsmod: Physics Mod 1.0.0
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		quitconfirm: QuitConfirm 1.3
		randomblockplacement: RandomBlockPlacement 1.17-fabric0.34.9-1.1.1
		skinswapper: Skin Swapper 2.1.0
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.0
		transliterationlib: TRansliterationLib 1.1.0
		voicechat: Simple Voice Chat 1.17-1.2.3
		waterdripsound: Drip Sounds 1.17-0.2.1
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.92, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/1.17.zip, file/New Faithful Items.zip (incompatible), file/Varied Magma Blocks.zip (incompatible), file/Faithful+Overlays.zip (incompatible), file/alternate-entities-v1-4.zip (incompatible), file/Visual honey.zip (incompatible), file/Gilded+Blackstone+Top+Add-on+1.0.zip (incompatible), file/FaithfulClearVisionGlass.zip (incompatible), file/OLG_1.1.3_1.16+.zip (incompatible), file/Spyglass+model.zip, file/Invisble+World+Borders..zip, file/Simple+pixel+accurate+spyglasses (1).zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Player Count: 1 / 8; [class_3222['StatusConnected'/253, l='ServerLevel[1.17 survival LP!]', x=337.31, y=64.00, z=-720.02]]
	Data Packs: vanilla (incompatible), file/afk display v1.1.0.zip, file/anti enderman grief v1.1.0.zip, file/armor statues v2.8.1.zip, file/double shulker shells v1.3.0.zip, file/dawndaycounter_1.16.5-1.02.zip, file/gem villagers v4.3.3.zip, file/durability ping v1.1.0.zip, file/item averages v1.3.0.zip, file/larger phantoms v1.2.1.zip, file/more mob heads v2.9.1.zip, file/player head drops v1.1.0.zip, file/track raw statistics v1.4.0.zip, file/track statistics v1.1.0.zip, file/treasure gems v1.2.2.zip, file/unlock all recipes v2.0.1.zip, file/wandering trades v1.5.0.zip, Fabric Mods
	OptiFine Version: OptiFine_1.17_HD_U_G9_pre24
	OptiFine Build: 20210628-002230
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 461.92
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17
	OptiFine jar version: OptiFine_1.17_HD_U_G9_pre24
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/danie/AppData/Roaming/1.17_but_with_fabric_loader/.optifine/OptiFine_1.17_HD_U_G9_pre24/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by haubna** [comment]
Should be fixed in the next mod release (which comes with a completely new physics engine). 2 or 3 days :)

**Comment by ArchVivi** [comment]
> Should be fixed in the next mod release (which comes with a completely new physics engine). 2 or 3 days :)

Will this new update fix compatibility with Iris?

**Comment by haubna** [comment]
> > Should be fixed in the next mod release (which comes with a completely new physics engine). 2 or 3 days :)
> 
> Will this new update fix compatibility with Iris?

Iris compatibility will be fixed on their side (as far as I know).

**Comment by caoqt1** [comment]
Oooh i am hyped for the new update, when will it come out?
