### ISSUE TITLE
Physics do not appear with Canvas Renderer

### ISSUE THREAD

**Issue by ender-blade** [haubna/PhysicsMod#20]
Minecraft 1.16.5, Fabric Loader 0.11.1
Canvas Renderer 1.0.1267, tested with both PhysicsMod 1.1.1 and 1.2.0

All "physics" from PhysicsMod--that's all fractures, 3D particles, and dismembered mob parts--do not appear at all when using Canvas Renderer. Block break with just their regular 2D particles, and mobs simply disappear when killed with no regular death animation in its place.

**Comment by haubna** [comment]
Canvas Renderer is not supported.
