### ISSUE TITLE
About the 2.2.5 version of the error

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#20]
About the 2.2.5 version of the error
First player problem, when I close part of the second layer, there will be a problem
as the picture shows
![clothes](https://user-images.githubusercontent.com/83525912/126044826-3aff337b-efd1-4668-ba33-72b111ea19d9.png)
![hat](https://user-images.githubusercontent.com/83525912/126044828-da4e1ab5-2863-45b0-a958-5dfcfe5688fe.png)
![右袖](https://user-images.githubusercontent.com/83525912/126044832-023dc642-bb23-43c7-9c9e-dde6c5668856.png)
![左裤腿](https://user-images.githubusercontent.com/83525912/126044835-ce485e5d-19f3-4e4a-a8d9-c315d2e9b534.png)
![左袖](https://user-images.githubusercontent.com/83525912/126044845-437cc55f-1c70-4fcd-9a98-8bd0eea42135.png)
The second one is that the enderman seems to have lost a purple eye
as the picture shows
![2021-07-17_17 27 55](https://user-images.githubusercontent.com/83525912/126044875-96778a0a-3cc5-45e0-8d02-0b08770f525b.png)
Find these problems temporarily

**Comment by haubna** [comment]
Should be fixed in version 2.2.6, thanks again for the report! :D
