### ISSUE TITLE
Option to disable config button in menu [REQUEST]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#200]
I would appreciate an option to remove the button that opens the in-game config so that config can be handeled in only the config file. I think it clutters the menu.

![image](https://user-images.githubusercontent.com/82549089/144109727-2f737604-3064-436b-b4f9-2e33c43b2174.png)

**Comment by ghost** [comment]
I would really like this feature because without it I cant use physics mod together with [Client Tweaks](https://www.curseforge.com/minecraft/mc-mods/client-tweaks-fabric) mod

![image](https://user-images.githubusercontent.com/82549089/144734811-79e4ce89-e3e9-4175-a112-95f416a10455.png)

**Comment by haubna** [comment]
I would say "Master Volume" and "Music" clutters the options. They already have a proper place under the "Music & Sounds..." settings. You can remove them in the Client Tweaks settings.
