### ISSUE TITLE
Client Crashes When Entering Server [BUG]

### ISSUE THREAD

**Issue by Toilet-Lord** [haubna/PhysicsMod#203]
**Describe the bug**
You can play for a while on the server with the mod installed in your mod folder but then it randomly crashes due to ?something? then you can't go back to the server until you uninstall the mod

**To Reproduce**
1. Get in server
2. Play
3. Game crashes
4. Game crashes when entering the server

**More Information**
I was able to re-enter the server after disabling most of the mod's features and when I disabled "Physics when punching a block" I was able to enter the server

Minecraft Version: 1.18
Physics Mod Version: physics-mod-2.5.17-mc-1.18-fabric.jar

Here's my lastest log so you can see the error, this is how I found out which mod was causing the crashes:
[latest.log](https://github.com/haubna/PhysicsMod/files/7646822/latest.log)

**Comment by haubna** [comment]
Update to 2.5.18. Should be fixed.

Toilet-Man ***@***.***> schrieb am Fr. 3. Dez. 2021 um 05:34:
