### ISSUE TITLE
PLEASE ADD GRASS PHYSICS!! [REQUEST]

### ISSUE THREAD

**Issue by PessiPanto** [haubna/PhysicsMod#205]
Grass physics are _**essential!!**_ How can you add vine physics but not grass physics? When you walk over some tall grass, just as with vines, it should get pushed out of the way.

**Comment by UrikaTractor** [comment]
yeah i think that would be cool!
maybe some small grass that is like in those fake physics videos?
have settings for grass physics render distance and stuff like that!

**Comment by haubna** [comment]
Done
