### ISSUE TITLE
Is the Forge version  still being worked on? [QUESTION]

### ISSUE THREAD

**Issue by Maenbrot584** [haubna/PhysicsMod#206]
Is the forge version still coming or not and if yes, whene?

**Comment by caoqt1** [comment]
It is, haubna has to maintain TWO versions of physics mod, and overall, fabric runs better and is more lightweight

**Comment by Maenbrot584** [comment]
Ok, thanks.

**Comment by haubna** [comment]
Yes, I am currently very lazy. But will come for sure!
