### ISSUE TITLE
Gravity setting? [REQUEST]

### ISSUE THREAD

**Issue by SpencerMeow** [haubna/PhysicsMod#207]
It would be great to see a setting to lower or raise the gravity of the physics, to have low gravity or 0 gravity, a bunch of gravity to make it look heavier, or to get crazy make everything float up to the sky, etc.

**Comment by haubna** [comment]
There is already an option for that. Physics Settings -> General Settings -> Gravity

**Comment by SpencerMeow** [comment]
> There is already an option for that. Physics Settings -> General Settings -> Gravity

Is that a fabric-only feature because I cannot find that anywhere in the settings or config of the latest Forge one.
