### ISSUE TITLE
Fix PVP Support

### ISSUE THREAD

**Issue by caoqt1** [haubna/PhysicsMod#208]
When pvp support is on, ragdolls are created when entitys are removed which is fine since pvp servers usually remove any entitie that dies but i would atleast like it so ragdolls spawn IF an entity has a health below or equal to 1, thanks!

**Comment by haubna** [comment]
It sadly doesn't work like that. PvP servers remove the entities with their latest heart amount. So if the player had 4 hearts and gets a 1 hit KO it removes it from the client even though it had 4 hearts.
