### ISSUE TITLE
Render bugs

### ISSUE THREAD

**Issue by Hayliox** [haubna/PhysicsMod#209]
So the vines and sugar cane (like in the video) seem to render incorrectly. By using bone meal on nether vines, it "breaks" from the initial vine into its own. Also, when walking through sugar cane, a "ghost block" stays in place. This also happens with the nether vines but I couldn't get it to be in the video. The only way I found of fixing this last part is by breaking a block nearby, as if it'd update the render. 

I'm on Windows 11, latest version of fabric 1.18.1. Using sound physics remastered, sodium and fabric api (along with physics mod pro)

**Comment by haubna** [comment]
Fixed in V19!
