### ISSUE TITLE
Issues in version 2.2.6

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#21]
First, the floating half-brick and some blocks of the stairs have no collision volume
The second rabbit's rag doll doesn't look right
![2021-07-18_14 07 14](https://user-images.githubusercontent.com/83525912/126057573-083fd697-2996-49fd-b4d2-639b42fa10e0.png)
Temporarily these problems

**Comment by haubna** [comment]
Can you explain how I can reproduce the staircase issue?

**Comment by QAQlinmiao** [comment]
https://user-images.githubusercontent.com/83525912/126060076-ca58196c-206e-424e-8c8d-11a4eb795cec.mp4


https://user-images.githubusercontent.com/83525912/126060119-40eb3b27-39f1-4a9f-b68c-9ba0c80c3636.mp4


https://user-images.githubusercontent.com/83525912/126060153-02686177-ca06-4820-b17d-d58183ace520.mp4

**Comment by QAQlinmiao** [comment]
In addition
Player's ragdoll
Too stiff

**Comment by haubna** [comment]
Fixed rabbit ragdoll
Reduced ragdoll stiffness
Fixed block collisions of translucent blocks
Available in version 2.2.7
Thanks again for telling me! :D
