### ISSUE TITLE
Add capes to mobs [REQUEST]

### ISSUE THREAD

**Issue by finogreofdoom** [haubna/PhysicsMod#210]
Let you put +All mobs or type the name of a specific mob
and press done and it shall give the mobs any cape you choose
from the menu like adding the capes to the players except with different mobs

**Comment by finogreofdoom** [comment]
I WANT IT

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
