### ISSUE TITLE
Infinite loading loop with the mod active[BUG]

### ISSUE THREAD

**Issue by xsizim** [haubna/PhysicsMod#213]
When I go to mc launcher and enter the game, on fabric 1.10.2 on 1.18.1, it allows me into the game, but it keeps on loading the screen over and over. Only happens if I have the mod loaded, every other mod I have is fine. (The screen after you launch mc, load shaderpacks or load resource packs) Also, I kinda reposted this because I accidentally closed it.

Install the mod (fabric ver), launch fabric 1.10.2 on 1.18.1.

Video of infinite loading loop
https://drive.google.com/file/d/1yu7nNkM1fbkWLmWitOwJ2ZPeCfAfhKCD/view?usp=sharing

Minecraft Version: <1.18.1 (1.10.2 Fabric)>
Physics Mod Version: <2.5.18 (Fabric - 1.18)>

**Comment by xsizim** [comment]
Might have to download the video, currently it cannot be previewed.

**Comment by haubna** [comment]
This happens when you have an incompatible mod installed. Most likely something that changes capes or banners.

**Comment by xsizim** [comment]
> This happens when you have an incompatible mod installed. Most likely something that changes capes or banners.

Its probably my Illumanations mod then, it changes lighting and stuff and also effects banners.

**Comment by haubna** [comment]
Yup that's most likely it. Will close the issue!

**Comment by xsizim** [comment]
> Yup that's most likely it. Will close the issue!

Okay, so that mod wasnt a issue, but, the Glowing Banners mod is incompatible Ig. That was the problem causing one. Also, great mod!
