### ISSUE TITLE
Broke the block a tree was connected to and not all of the tree fell[BUG]

### ISSUE THREAD

**Issue by xsizim** [haubna/PhysicsMod#214]
Just hopped into a new test work, broke a couple trees and one of them I broke (I broke the dirt block the tree was on/connected to) partially just stood there where it was. like the leaves part of it and a couple logs (acacia tree)

Break the block(s) a tree (maybe acacia only) is connected to, part of it stands. (Sometimes)

Tried to put a video in here of it but it was too big.

Minecraft Version: <1.18.1 (Fabric 1.10.2)>
Physics Mod Version: <Latest Fabric (2.5.18)>

**Comment by IncendiaryOCE** [comment]
Not a bug, you need to go Options > Physics Settings > Server Settings and choose the collapse limit. By default, the slider is at 100 blocks, you can increase that.

**Comment by xsizim** [comment]
Oh, I didn't know. I thought since it was a mod that said it would add full
realistic physics, that it would do all blocks and not have it to be
customized to that (sorry if it sounds rude/that im mad im not I just
didnt know)

**Comment by haubna** [comment]
This is a constraint to avoid lagging out low end PCs. You can always crank up the setting as high as you want. But the casual player doesn't want to fiddle with settings and wants a lag free experience as well! :)
