### ISSUE TITLE
Fire is affected by block physics [BUG]

### ISSUE THREAD

**Issue by EthanRStokes** [haubna/PhysicsMod#215]
**Describe the bug**
When fire breaks, it has the same physics as any other block. This is affected when using Fractured and Blocky Block physics

**To Reproduce**
Create a world. Make fire with flint and steel, and then punch it

**Screenshots**
Fractured
![image](https://user-images.githubusercontent.com/39657565/146113586-42ca4e2b-57a3-4f98-b051-4b241bc8b882.png)
Blocky
![image](https://user-images.githubusercontent.com/39657565/146113759-3b4f0ee8-601f-4de8-a080-abce94cf5428.png)

Minecraft Version: 1.18
Physics Mod Version: 2.5.18

**Comment by haubna** [comment]
How about simply turning block physics off for fire?
