### ISSUE TITLE
Rail and flowers physics[REQUEST]

### ISSUE THREAD

**Issue by finogreofdoom** [haubna/PhysicsMod#216]
We need these! They are mandatory

**Comment by tqoac** [comment]
What do you mean by "Rail Physics"

**Comment by caoqt1** [comment]
If you say rail physics like "rail/minecart new physics" then the hard answer is NO, this mod is supposed to be a client sided mod and i dont think the physics engine can do this type of crap, no.

**Comment by CaramelTurbine** [comment]
"rail and flowers" is super non-specific. Please for everyone's sanity, provide more detail.

**Comment by finogreofdoom** [comment]
I'm thinking about rail tracks and the way that they change shape if a heavy weight moves over them for instance, they would sag towards the middle

**Comment by caoqt1** [comment]
> I'm thinking about rail tracks and the way that they change shape if a heavy weight moves over them for instance, they would sag towards the middle

😮‍💨

**Comment by haubna** [comment]
No rail physics but added flower physics. Rail physics are so minor it doesn't really make sense, sorry!
