### ISSUE TITLE
Despawning Mobs still create ragdolls [BUG]

### ISSUE THREAD

**Issue by nerdgh0st** [haubna/PhysicsMod#218]
Despawning Mobs (exploding creepers included) still create ragdolls, even though they weren't killed by anything.

**To Reproduce**
Make a creeper explode. An inflated ragdoll of a Creeper should fly upwards and fall down, or for any entities, try roaming around for a bit in a 1.18 cave system and there should ragdolls of random cave monsters.

Minecraft Version: 1.18.1
Physics Mod Version: 2.5.18

**Comment by haubna** [comment]
Disable the PvP compatibility setting. Read through the description next
time.

nerdgh0st ***@***.***> schrieb am Do. 16. Dez. 2021 um 01:17:

**Comment by nerdgh0st** [comment]
Turned it off, but the bug still happens.

**Comment by haubna** [comment]
Disable it!

nerdgh0st ***@***.***> schrieb am Do. 16. Dez. 2021 um 01:39:

**Comment by haubna** [comment]
It should only happen for creepers. There is no way around it. Play on a server with a bigger entity range.
