### ISSUE TITLE
Knockback and Punch weapons cause ragdolls to fly further away [REQUEST]

### ISSUE THREAD

**Issue by JulioLeonardi** [haubna/PhysicsMod#219]

**Comment by caoqt1** [comment]
Iirc this would have to be done on the server since getting knockback from dead entity cannot be done on client, so probably no

**Comment by CaramelTurbine** [comment]
> Iirc this would have to be done on the server since getting knockback from dead entity cannot be done on client, so probably no

this requires no server interaction at all. Ragdolls are entirely client side, so upping their knockback speed on the ragdoll would change nothing on the server.

**Comment by caoqt1** [comment]
> > Iirc this would have to be done on the server since getting knockback from dead entity cannot be done on client, so probably no
> 
> this requires no server interaction at all. Ragdolls are entirely client side, so upping their knockback speed on the ragdoll would change nothing on the server.

No I mean getting the knockback from fucking punch and knockback enchanted weapons, I was referring to the title of the issue.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
