### ISSUE TITLE
Bug with POM shader packs

### ISSUE THREAD

**Issue by Byllfighter** [haubna/PhysicsMod#222]
**Describe the bug**
Bug with POM shader packs

**To Reproduce**
Enable shader pack and setup POM (I used chaoptic13 v9)
Block and mobs physics works buggy

**Screenshots**
![2021-12-17_18 45 54](https://user-images.githubusercontent.com/60580992/146579891-6afbdab0-761a-4321-b002-5b062a53ef14.png)
![2021-12-17_18 51 21](https://user-images.githubusercontent.com/60580992/146579911-b917ecd9-aa2f-4438-8b70-9d334df803f0.png)

Minecraft Version: 1.18
Physics Mod Version: v19

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
is it optifine?

**Comment by Bco1981** [comment]
I have same issue with Complimentary shader v4.3.3
Using Forge v39.0.0
preview_OptiFine_1.18.1_HD_U_H5_pre4.
Physics Mod 2.6.4

**Comment by Bco1981** [comment]
Physics Mod v2.6.6 still has this issue.

**Comment by haubna** [comment]
POM is now supported with the latest Iris PBR beta build.
