### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by ShadoUrufu** [haubna/PhysicsMod#223]
**Describe the bug**
The menu icon is hidden away in the clutter of my other options. Yes, I probably use too many mods. 

**To Reproduce**
Mods used: Way too long of a list, But Bedrokify, and Freelook add their own buttons, as you can see. I'm also running Optifine, but i'm not really sure which mod is actually doing this. 
Resource pack is Overgrowth.

**Screenshots**
[Options Menu](https://cdn.discordapp.com/attachments/250801422960951296/921878390494101534/unknown.png)

Minecraft Version: <1.18.1>
Physics Mod Version: <2.5.18>

**Comment by haubna** [comment]
Why would there be Master & Music sliders when there is a proper menu for that? Which mod dev does that? 😳

**Comment by haubna** [comment]
Note: you can remove them in the Client Tweaks settings.
