### ISSUE TITLE
Breaks When Used With Optifine

### ISSUE THREAD

**Issue by landontbr** [haubna/PhysicsMod#224]
When I run physics-mod-2.5.18-mc-1.18-forge.jar with OptiFine_1.18.1_HD_U_H4.jar in 1.18.1-forge-39.0.0, breaking blocks and killing mobs results in the object immediately disappearing rather than showing physics effects. When optifine is removed from my mods folder the physics mod works properly.

**Comment by haubna** [comment]
Optifine is no longer supported with Minecraft 1.18 by the Physics Mod. It is closed source and impossible to make it work with.

**Comment by landontbr** [comment]
Thank you for the quick response!

**Comment by haubna** [comment]
I've added Optifine support in 2.6.4 (except for liquid physics)!

**Comment by landontbr** [comment]
> I've added Optifine support in 2.6.4 (except for liquid physics)!

Great! Thank you
