### ISSUE TITLE
The problem of applying physics mode on a particular server (please solve it).

### ISSUE THREAD

**Issue by milkgang05** [haubna/PhysicsMod#225]
Some servers have applied plug-ins that cause certain phenomena when a player dies.
For example, the player's game mode changes, or it is made to teleport somewhere.
So, the physics mode is not working.
So I suggest a solution to this.

When something happens to the player,
I think it's good to create a player's body.

As mentioned above, if you teleport somewhere or change the game mode,
A body is created.

It also needs to be able to set the conditions for this.
Types of conditions include teleportation, game mode change, etc.

If it's made like this, this problem will be solved simply.

And I'm really enjoying your mode.
I appreciate your effort whenever I play the game.

When you solve this problem, users can use your mode on more servers.
Please solve the problem. Thank you always! ;)

(I used a translator to write this article. The sentence might not be accurate. Please understand that)

**Comment by haubna** [comment]
Enable PvP compatibility. It does exactly that.

**Comment by milkgang05** [comment]
What does that mean? I didn't understand. Isn't this going to be fixed?

**Comment by haubna** [comment]
There is already a setting for this in the game.

milkgang05 ***@***.***> schrieb am Do. 23. Dez. 2021 um 15:30:

**Comment by milkgang05** [comment]
Oh, really? Sorry, I don't think I found it. I'm sorry to take your precious time, but how do I set it up?

**Comment by milkgang05** [comment]
Oh, really? Sorry, I don't think I found it. I'm sorry to take your precious time, but how do I set it up?
