### ISSUE TITLE
Snow Physics [REQUEST]

### ISSUE THREAD

**Issue by RRRiderrr** [haubna/PhysicsMod#226]
The main idea: https://youtu.be/kerm3WS8SJo
It would be great to see slow snow appearance while snowfalling, how snow randomly falls off the roofs cause of wind, how snowballs act on hanging hatches. Also it would be nice to add feature like taking snowballs from recently appeared snow cover with the remaining trail of taking a snowball, also wanna see player and mobs trails on snow... So, everything like in video.

**Comment by MayorBryce** [comment]
A nice idea, but it would be rather performance intensive, don't you think?

**Comment by UrikaTractor** [comment]
> A nice idea, but it would be rather performance intensive, don't you think?

i agree 
and we already have something like the snowball

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
