### ISSUE TITLE
Softbody Physics [REQUEST]

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [haubna/PhysicsMod#228]
Softbody physics for slime blocks/slime mobs

**Comment by CaramelTurbine** [comment]
"memory foam" style footprints on things like snow, wool, (upcoming mud block), clay, sand, other soft blocks .ect

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
