### ISSUE TITLE
backport new features to 1.16 [REQUEST]

### ISSUE THREAD

**Issue by 3inya** [haubna/PhysicsMod#229]
maybe not all the features but it will be nice to have the new physics engine on 1.16

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
yea that won't ever happen and why do you even want to port it to some old version of Minecraft

**Comment by haubna** [comment]
It will happen though :P

m ***@***.***> schrieb am Mi. 29. Dez. 2021 um 14:33:

**Comment by 3inya** [comment]
Haubna, THANK YOU!

**Comment by haubna** [comment]
Done
