### ISSUE TITLE
Game initialization gets stuck on loading, infinitely retrying

### ISSUE THREAD

**Issue by cintlex** [haubna/PhysicsMod#23]
Only mod i am using is Fabric API, every time I try to load the game it will get stuck in a loading loop, constantly trying to load resources, giving up, and then loading again, which is only present with this mod. The log file is here:
https://paste.ee/p/405qc

**Comment by John-Paul-R** [comment]
Can reproduce on both mc 1.17 and 1.17.1 using mod version `2.3.0-mc-1.17.1`.

Potentially relevant, very insightful forum post: https://forums.spongepowered.org/t/mixin-conflicting-synthetic-bridge-target-method-name/25369/2

If I had to guess, this is the part you want (Hard to tell w/o src though):
> Avoid creation of the bridge method by decoupling the mixin from the superclass, use supermixins where shadowing of superclass members is required.

**Comment by haubna** [comment]
Thanks for the report and quick help guys! Fixed in version 2.3.1.
