### ISSUE TITLE
Settings bar clash

### ISSUE THREAD

**Issue by GalaxysWithFiles** [haubna/PhysicsMod#230]
**Describe the bug**
I have a mod that adds a sound/volume bar to the settings menu, and the mod goes over it.

**To Reproduce**
When using the mod (https://www.curseforge.com/minecraft/mc-mods/client-tweaks-fabric), it has a option to enable a master volume bar, and when you enable it it clashes with the phsyics mod setitngs

**Screenshots**
![image](https://user-images.githubusercontent.com/95949301/147425329-1f44a907-9b4f-44a0-a1a9-1d0ae131a2ed.png)

Minecraft Version: <1.18.1>
Physics Mod Version: <2.6.1>

**Comment by haubna** [comment]
I am always in debate whether I should change it or not but to be honest I think my settings button fits in way better then the master volume thing (that is already in music & sounds anyways).

**Comment by haubna** [comment]
Note: you can remove them in the Client Tweaks settings.
