### ISSUE TITLE
Food eating physics

### ISSUE THREAD

**Issue by GalaxysWithFiles** [haubna/PhysicsMod#231]
**A description of the requested feature**
Maybe have eating physics, could be cool if instead of flat particles it is the 3d little blocks like with the block particles.

**Comment by UrikaTractor** [comment]
ooh that sounds cool like little crumbs fall out when you are eating?

**Comment by haubna** [comment]
Already implemented it and it looked so wrong. Due to items having transparent parts the little blocks sometimess were half transparent and the 2D particles just looked way better then.

**Comment by haubna** [comment]
Implemented it with non transparent 3D particles.
