### ISSUE TITLE
Voxel-style Block Breaking [REQUEST]

### ISSUE THREAD

**Issue by MayorBryce** [haubna/PhysicsMod#232]
For block breaking, there are 2 block breaking enhancements. I request a third: a block breaking animation that break off cube-like pixels from a block. Similar to the block breaking animation, it would visually cause pixels to fly off elsewhere and in the center would be the item drop. This seems more Minecrafty.

**Comment by haubna** [comment]
There is a block breaking style called particles which looks pretty similar. Have you tried that one yet?

**Comment by caoqt1** [comment]
> There is a block breaking style called particles which looks pretty similar. Have you tried that one yet?

Pretty sure they mean that gradually small voxels break off the block the more it breaks

**Comment by haubna** [comment]
I know but this is simply not feasible. A simple 16 pixel texture would result in 16 * 16 * 16 physics objects. A total of 4096 simulated physics objects. One block would already lag your PC.

**Comment by MayorBryce** [comment]
Obviously not the entire block would be a voxel. First, physics would not be applied until actually breaking the block. Second, chunks would fall off instead of individual pixels. A slider would tell how many block breaking voxels would be rendered.

**Comment by MayorBryce** [comment]
For example, beefy computers would be able to use the slider to the full 4096 voxels. However the default might be 256 or less or something. Chunks of the object, such as maybe 100 or so voxels together would fall off as one physics object. Few would actually be individual voxels, as most, even 2 voxels together, would be one physics object.

**Comment by CaramelTurbine** [comment]
its a nice idea.
I imagine it working the same way the physics do in "Teardown".
There may be millions of individual voxels in a single stage, but the game keeps them manageable by not breaking them all apart at the same time. Most voxels stay together in one lump until they are hit again.
In fact, i think the raytracing is the biggest bottleneck in that game.

**Comment by MayorBryce** [comment]
It appears the block-breaking style "Particles" was recently added and I hadn't noticed. Sorry! This will work just fine.
