### ISSUE TITLE
Maybe port to bedrock [REQUEST] 

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [haubna/PhysicsMod#234]
I know this is probably imposable, but I own java and bedrock and maybe I just kind of wanted to see what it would look like

**Comment by caoqt1** [comment]
No, since bedrock is coded in c++ and this relies on a java port of Nvidia physX, would love to see it though.

**Comment by CaramelTurbine** [comment]
im sorry but the advanced modding system required to implement a custom physics engine is almost nonexistent in Minecraft bedrock. The only way a mod like this could possibly ever be ported to bedrock is through dll injection (like hacked clients) or if microsoft stopped being so stingy with their code.

**Comment by haubna** [comment]
What Caramel says.
