### ISSUE TITLE
Glass breaking physics [REQUEST]

### ISSUE THREAD

**Issue by finogreofdoom** [haubna/PhysicsMod#235]
Realistic glass breaking physics like in this video: https://www.youtube.com/watch?v=t-arGwqZog0
Except with fewer particles so it doesn't lag.

**Comment by CaramelTurbine** [comment]
we already have that

**Comment by UrikaTractor** [comment]
yeah, just set glass to have fracture block physics

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
