### ISSUE TITLE
Optifabric Workaround [REQUEST]

### ISSUE THREAD

**Issue by RyanCR03** [haubna/PhysicsMod#236]
Some Physics mod features work with optifabric but maybe there could be a config to remove the message when you join a world and a form of item physics disabling that lets you use other item physic mods.

**Comment by haubna** [comment]
No, it is about time to drop Optifine from your mod list. Don't use it, period. It doesn't even really enhance your performance. I love supporting innovative mods and Iris and Sodium are two of them. As far as using the other item physic mods there is nothing I can do about that, sorry.

**Comment by RyanCR03** [comment]
I don't use optifine for the performance, I use it for the extensive resource pack capabilities.

**Comment by haubna** [comment]
https://lambdaurora.dev/optifine_alternatives/

**Comment by RyanCR03** [comment]
i spent too many hours making my own resourcepack and im not going to switch everything to support all of those mods just for the pack to be less accessable to people.
![2021-12-29_14 27 15](https://user-images.githubusercontent.com/32957560/147700899-aac6fc48-5456-40fa-ab18-f58d043ddebe.png)

**Comment by haubna** [comment]
Those are mods that support the same features like optifine without any additional work. Just use those instead of Optifine.

**Comment by RyanCR03** [comment]
varied mob textures isnt even supported for 1.18 also im pretty sure these mods have different formats and file locations than optifine

**Comment by RyanCR03** [comment]
and my pack is also very big in terms of features and file size. its 16x and 200mb

**Comment by haubna** [comment]
Yeah but I still won't remove this message. Optifine is closed source and I can't support it because I don't know which things they do change in the rendering.

**Comment by RyanCR03** [comment]
i was just saying a config or something so it doesn't happen every time you start mc
