### ISSUE TITLE
Cannot blacklist modded blocks

### ISSUE THREAD

**Issue by Syampuuh** [haubna/PhysicsMod#237]
**Describe the bug**
Currently, the mod causes a client crash when breaking a [Storage Drawer](https://www.curseforge.com/minecraft/mc-mods/storage-drawers). This on its own is fine and to be expected because Storage Drawers uses its own fancy rendering system, so I can't really expect this mod to support that. The issue is that there does not appear to be any way to exclude modded blocks from the physics system. I have tried manually adding them to the block settings config as disabled, but this doesn't appear to work; they don't appear in the in-game menu, and the crash still occurs suggesting that the block is still trying to be fractured.
![](https://i.imgur.com/PpcFpK8.png)
(I also tried omitting the mod name to be sure, same results)
I'm not 100% sure if this is necessarily a bug or an oversight, but it would be nice to see some way to workaround this.

Minecraft Version: 1.18.1, Forge 39.0.9
Physics Mod Version: 2.6.3

**Comment by haubna** [comment]
You are absolutely right. Fix will come with the next update! :)
Can you send me the crash log as well? It shouldn't crash on non compatible blocks!

**Comment by haubna** [comment]
Storage Drawer blocks will be compatible with physics in the next update as well. Fixed the crash!

**Comment by Syampuuh** [comment]
Neat, that was fast. Thank you.

**Comment by haubna** [comment]
Fixed in 2.6.4
