### ISSUE TITLE
UPDATE - Wind Physics/Various Suggestions

### ISSUE THREAD

**Issue by ShotCosine** [haubna/PhysicsMod#238]
Something I've always wanted to see in the game:
_**Wind physics**_ - could work great with the upcoming smoke physics! - Update: CONFIRMED!
Physical rain & snow entities that could blow with the wind, maybe cosmetic dust storm particles in desert biomes and snow flurries flying across the screen- _just like in that one snow video we've all seen_
Certain block fractures like leaf blocks, hay bales, and cobwebs falling slower in wind
Fire physics with wind - _maybe fire entities can be slightly curved towards the opposite direction of wind_
Integration with new vine physics in grass and flowers

Other ideas:
**NEW IDEAS:**
An idea I came up with while playing: a customizable client-sided _**grab button**_ that lets users play around with dynamic block physics and ragdolls - _might open a new request for this with more detail_
Adding a slider in dynamic block settings that increases the interactive hitbox for blocks, since lanterns, chains, doors and trapdoors are static entities
Adding a slider that affects the max particles allowed in a scene to reduce lag immensely in intense scenarios

~~Swinging doors/trapdoors~~ - _added feature_
Bloody ragdolls, with blood decals added where attacks are landed - _possibly dismemberment based on where the attack was pointed at upon death using "blocky" physics models for the limbs_
~~Footprints in snow~~, _confirmed, see #259 for implementation suggestions_
Splashing particles in water with liquid physics - _right now water source and flowing water blocks cause continuous liquid physics source locations to stop, could be an issue_
Splash potion liquid physics - _might be hard to implement colored liquid based on which potion it is, not to mention modded potions and shaders, so it might be easiest to just use the same blue water_
Slime/honey jiggle physics - _not stretching like they do in the realistic youtube videos since that wouldn't be client side and wouldn't make sense in gameplay, but jiggling whenever an entity bumps into it or jumps onto it_

Edit: Added more description and added new feature suggestions

**Comment by CaramelTurbine** [comment]
In terms of possibility:
Particles and fire can be simulated with shaders.
Swinging trapdoors and doors probably wont work. what happens if place you place a trapdoor and then it swings shut and then you click on it. Does it open, or does it close? According to the physics mod, it looks like its closed, but according to the game logic, its still open.

**Comment by ShotCosine** [comment]
I thought about this while writing, since this mod is aiming to be as client-side as possible. Maybe if a door is opened it cracks slightly and then once you walk into it it pushes all the way open, but it wouldn't push the player. In other words if the door was in the "opened" state it could swing around freely until it is closed again. Trapdoors seem like they would be harder to implement. In terms of rain/snow, I should've described it as physical instead of "particle" where there are physical rain drops and snowflakes that could be blown in a direction by wind. The "wind physics" idea would just be blowing already added physics effects added with the mod around, like vines and smoke, maybe with some sound when walking around. I would love to see the vines, smoke effects, capes, banners etc. gently blowing around while walking through a town, it would really add to the atmosphere.

**Comment by UrikaTractor** [comment]
this is actually a really cool idea!

**Comment by haubna** [comment]
Added door and trapdoor physics

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
