### ISSUE TITLE
Just go make a game on a custom engine at this point [REQUEST]

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [haubna/PhysicsMod#239]
Soo, this is all feature requests and ideas provided by people. And we want these features to be implemented in max 2 weeks and yeah, good luck.
So we need water physics. Okay i mean lava physics cuz theres already a lot of flowing water.
- Snow physics
- Grass physics (everyone want that)
Entities new braking mode that breaks it on different pieces separated by changes in color. Basically each obj is piece of entity in the same color. Hope you got it
Yeah and also
- Leaves physics
- Fire physics
Since Physics mod is about physics (yeah) and realism added to the game, maybe just add RTX ULTRA HD graphics built-in shaders so players dont have to install optifine manually (also make it somehow run better with shaders than without :D)
- Rail physics (whatever is this)
- Flower physics
- Player third person view ragdoll
- Potato physics (so ill finally be able to throw some at my friends!!)
You could also add things that changes the game by 100% so it no more look like minecraft. Basically just fix the vines physics so their "ghost" position is not always in the same spot. Simplify - just make the mod with changes so players cant join servers, so they will learn that YOU CANT MODIFY THE GAME ON A SERVER WITH FRIKIN TNT BLOCK RAIN MOD
(or just make i possible somehow, idk)
- okay so we also need some Eating particles RTX physics
Ive just always somehow wanted to see particles of thing that am eating in 4K
- also wrecking ball physics
- make blocks destroy into 4096 pieces and btw optimize it somehow, so it runs smoothly at 120 FPS
- add physics  to flying entities so they can no more FLY INTO THE PLAYER LIKE THESE PHANTOM THING SO EASILY
- Wind physics
- Softbody physics
- Actually you can add advanced map editor to the game so players can add destructible blocks to the world CLIENT SIDED
- And make visuals better, add some bloom to the game (or just to the TNT explosions heh)
- Steal code from Unity and add Post Processing Volume (evry effect m8)
- also make camera mod built in so players can replay in slow motion what they just destroyed
(or just you know, borrow it from replay mod devs)
- make PRO VERSION actually CHEAPER (cuz i have 8$ left on my credit card, ofc one time payment to get all these features for LIFETIME!!!!!1!1!!!1!)

Thanks, hope youll add these soon. Best luck from Piotrek4 :D

**Comment by UrikaTractor** [comment]
what the hell are some of these

"destroy blocks into 4096 pieces and optimize it"
if they were going to do that they might as well make an entirely new game

**Comment by caoqt1** [comment]
Holy shit are you on LSD or what?

**Comment by caoqt1** [comment]
Alot of this you can't do (think about the limitations BUDDY, quit expecting everything out of this Jesus) and some of these won't be client side friendly

**Comment by PiotrekUnityDeveloper** [comment]
do you know what is a joke?
no sense of humor huh

**Comment by PiotrekUnityDeveloper** [comment]
> Alot of this you can't do (think about the limitations BUDDY, quit expecting everything out of this Jesus) and some of these won't be client side friendly

i mentioned it bro
* " just make the mod with changes so players cant join servers, so they will learn that YOU CANT MODIFY THE GAME ON A SERVER WITH FRIKIN TNT BLOCK RAIN MOD" *

**Comment by tqoac** [comment]
> > Alot of this you can't do (think about the limitations BUDDY, quit expecting everything out of this Jesus) and some of these won't be client side friendly
> 
> i mentioned it bro
> 
> * " just make the mod with changes so players cant join servers, so they will learn that YOU CANT MODIFY THE GAME ON A SERVER WITH FRIKIN TNT BLOCK RAIN MOD" *

well sorry for not seeing it YOU FUCKING LIBTARD

**Comment by caoqt1** [comment]
> do you know what is a joke? no sense of humor huh

well sorry for not seeing it YOU FUCKING LIBTARD

**Comment by PiotrekUnityDeveloper** [comment]
no problem bro

**Comment by CaramelTurbine** [comment]
if its a joke why is no one laughing?

**Comment by PiotrekUnityDeveloper** [comment]
as i said, no sense of humor

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
