### ISSUE TITLE
Snow physics

### ISSUE THREAD

**Issue by normy22331** [haubna/PhysicsMod#240]
I'm too lazy for a description so I leave a link of a video https://youtu.be/kerm3WS8SJo

**Comment by UrikaTractor** [comment]
i think that would be really hard to get close too tbh


but that swinging trap door is awesome

**Comment by PiotrekUnityDeveloper** [comment]
why not just import real life to computers

**Comment by PiotrekUnityDeveloper** [comment]
am sure your pc couldnt hold all these snow particles at 2 render disctance :/

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
