### ISSUE TITLE
particles when exploding tnt [REQUEST]

### ISSUE THREAD

**Issue by UrikaTractor** [haubna/PhysicsMod#241]
so i was thinking of a feature when you blow up tnt or a creeper explodes there is the normal stuff and then there is maybe pebbles flying everywhere/smoke maybe?

heres an example i made 

https://youtu.be/k1wVtbka1N4
i used the snowball physics for it but its kinda like that

**Comment by PiotrekUnityDeveloper** [comment]
okay, i just want to add that amount of these tnt particles should be optional by slider in mod settings

**Comment by UrikaTractor** [comment]
i agree

> okay, i just want to add that amount of these tnt particles should be optional by slider in mod settings

**Comment by finogreofdoom** [comment]
isn't that the particle setting

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
