### ISSUE TITLE
Blood physic-based particles [REQUEST]

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [haubna/PhysicsMod#242]
Okay, now for real. Blood physics
Red physic-based particles going out of hit/damaged entities.
Amount of particles controlled by slider _or more damage = more particles_

**Comment by PiotrekUnityDeveloper** [comment]
Okay now, its for real :D

**Comment by ShotCosine** [comment]
I heard somewhere that the liquid physics system used in the mod is used in other games for blood physics, maybe it can be applied here too!

**Comment by caoqt1** [comment]
> I heard somewhere that the liquid physics system used in the mod is used in other games for blood physics, maybe it can be applied here too!

Hell no, I don't want to kill mobs and have jello balls squirt out lol

**Comment by UrikaTractor** [comment]
> > I heard somewhere that the liquid physics system used in the mod is used in other games for blood physics, maybe it can be applied here too!
> 
> Hell no, I don't want to kill mobs and have jello balls squirt out lol

yeah i think they are talking about nvidia flex

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
