### ISSUE TITLE
Fire Physics [REQUEST] 

### ISSUE THREAD

**Issue by Sanchous12365** [haubna/PhysicsMod#243]
The idea came from your idea of physical smoke, I think realistic fire will work well with it.
https://youtu.be/igEoxfObBjU

**Comment by UrikaTractor** [comment]
the only way i could think of doing this is using physx but maybe haubna can do it

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
