### ISSUE TITLE
Player Ragdoll [REQUEST]

### ISSUE THREAD

**Issue by GamingBoi123** [haubna/PhysicsMod#246]
You Can Ragdoll Any Time you want when you hit a key on your keyboard. it automatically turns on F5 for you to see yourself falling or ragdolling. there will be a function in the options and you can turn it off

**Comment by caoqt1** [comment]
This wouldn't be server friendly

**Comment by caoqt1** [comment]
and plus, it was have to do ALOT of tracking and you cant use this on servers

**Comment by caoqt1** [comment]
but i would love to see it (sorry for 3 comments)

**Comment by Colin-J-Wood** [comment]
you could in theory install a separate mod that provides a /suicide command so you could pull this off yourself.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
