### ISSUE TITLE
Egg, Ender Pearl, Snowball model texture error[BUG]

### ISSUE THREAD

**Issue by YoBoiMike** [haubna/PhysicsMod#247]
whenever i throw snowballs and enderpearls and eggs and Round and Voxel model of these items are all texture errors just pink and black i dont have any resourcepack or any other mod

i just throw one and it just appears as that.

Minecraft Version: <1.18>
Physics Mod Version: <V26>

screenshot:

![picture png](https://user-images.githubusercontent.com/97084247/148023977-7f4f3b52-3d8e-4ebc-936f-ec3debc62cad.png)

**Comment by haubna** [comment]
Do you use any kind of resource pack? Any other mods installed?

**Comment by YoBoiMike** [comment]
i dont use any other resource pack or any other mod just only this mod

**Comment by haubna** [comment]
I've fixed a couple of texture related bugs in recent weeks. I couldn't reproduce this one. My best guess is that it is fixed. Please reopen the issue if you still have this problem.
