### ISSUE TITLE
issue:

### ISSUE THREAD

**Issue by QAQlinmiao** [haubna/PhysicsMod#25]
When the player teleports, that is, the tp command, a rag doll will appear
And if the monster suddenly disappears (that is, when it leaves the player a certain distance), a ragdoll will appear
Seems to be an early version existed, should fix.

**Comment by QAQlinmiao** [comment]
Oh, right after the player died
In the creatures near him, monsters also appeared rag dolls

**Comment by haubna** [comment]
Unfortunately there is no way to fix this since the client never receives the reason why a mob disappears.

**Comment by QAQlinmiao** [comment]
emmm... So is this problem unsolvable?

**Comment by haubna** [comment]
Yeah, I've looked into it in the past and the client only receives packets to remove entities from the world but not the reason why it is removing them.

**Comment by QAQlinmiao** [comment]
Okay, I know.
