### ISSUE TITLE
port to spigot [REQUEST]

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [haubna/PhysicsMod#250]
could you do that so I could play on servers and do a little trolling

**Comment by caoqt1** [comment]
Isn't spigot VERY different from forge/fabric?

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
I don't know I found a emote craft port but I guess it would not work sadly

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
