### ISSUE TITLE
Crashing when breaking a trapdoor and flying away [BUG]

### ISSUE THREAD

**Issue by ShotCosine** [haubna/PhysicsMod#253]
In the most recent update, I've experienced crashing having something to do with trapdoor physics.
It seems like the game crashes whenever I flip a trapdoor a couple times, break it, and then fly away. It has happened maybe 5 times, on brand new worlds and existing ones, only ever after breaking a trapdoor, and then leaving the area.
This was in one of the crash reports, right after creating a world, leading me to believe that it was because of this mod:

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8088ebeb0, pid=49624, tid=56556

JRE version: OpenJDK Runtime Environment Microsoft-28056 (17.0.1+12) (build 17.0.1+12-LTS)
Java VM: OpenJDK 64-Bit Server VM Microsoft-28056 (17.0.1+12-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
C  [PhysX_64.dll+0x3beb0]

No core dump will be written. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
https://github.com/microsoft/openjdk/issues
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x000001cbbbccc810):  JavaThread "Render thread" [_thread_in_native, id=56556, stack(0x000000a113800000,0x000000a113900000)]

Stack: [0x000000a113800000,0x000000a113900000],  sp=0x000000a1138fdfe0,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [PhysX_64.dll+0x3beb0]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 41207  physx.physics.PxRigidDynamic._setKinematicTarget(JJ)V (0 bytes) @ 0x000001cbc757d6ec [0x000001cbc757d6a0+0x000000000000004c]
J 53387 c2 net.diebuddies.physics.PhysicsWorld.update(D)V (1196 bytes) @ 0x000001cbc9f1c118 [0x000001cbc9f1aee0+0x0000000000001238]
j  net.minecraft.class_757.handler$egc000$render(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V+348
J 72474 c2 net.minecraft.class_757.method_3192(FJZ)V (1040 bytes) @ 0x000001cbcbdb8820 [0x000001cbcbdb87c0+0x0000000000000060]
J 61486 c2 net.minecraft.class_310.method_1523(Z)V (974 bytes) @ 0x000001cbcadffd64 [0x000001cbcadfe0e0+0x0000000000001c84]
J 62009% c2 net.minecraft.class_310.method_1514()V (262 bytes) @ 0x000001cbca550dc0 [0x000001cbca550c00+0x00000000000001c0]
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1483
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.1
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.1
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.1
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.1
j  net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(Ljava/lang/ClassLoader;)V+67
j  net.fabricmc.loader.impl.launch.knot.Knot.launch([Ljava/lang/String;Lnet/fabricmc/api/EnvType;)V+40
j  net.fabricmc.loader.impl.launch.knot.KnotClient.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000002000

Register to memory mapping:

RIP=0x00007ff8088ebeb0 PhysX_64.dll
RAX=0x0000000003000000 is an unknown value
RBX=0x000001cd77c32e70 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
RCX=0x0 is NULL
RDX=0x000000a1138fe070 is pointing into the stack for thread: 0x000001cbbbccc810
RSP=0x000000a1138fdfe0 is pointing into the stack for thread: 0x000001cbbbccc810
RBP=0x000000a1138fe1a0 is pointing into the stack for thread: 0x000001cbbbccc810
RSI=0x000001cd77c32e10 points into unknown readable memory: 0x00007ff808aa3058 | 58 30 aa 08 f8 7f 00 00
RDI=0x000000a1138fe070 is pointing into the stack for thread: 0x000001cbbbccc810
R8 =0x000001cd77c32ec0 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
R9 =0x0 is NULL
R10=0x00007ff80583f240 PhysXJniBindings_64.dll
R11=0x00000006dcb17ca8 is an oop: org.lwjgl.system.MemoryStack 
{0x00000006dcb17ca8} - klass: 'org/lwjgl/system/MemoryStack'
 - ---- fields (total size 5 words):
 - protected 'address' 'J' @16  1975451419376 (f21482f0 1cb)
 - private final 'size' 'I' @12  65536 (10000)
 - private 'pointer' 'I' @24  65472 (ffc0)
 - protected 'frameIndex' 'I' @28  1
 - private final 'container' 'Ljava/nio/ByteBuffer;' @32  a 'java/nio/DirectByteBuffer'{0x0000000652baa6c8} (ca5754d9)
 - private 'frames' '[I' @36  [I{0x00000006dcb17cd0} (db962f9a)
R12=0x0 is NULL
R13=0x00000007186fd570 is an oop: it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap 
{0x00000007186fd570} - klass: 'it/unimi/dsi/fastutil/objects/Object2IntOpenHashMap'
 - ---- fields (total size 8 words):
 - protected 'defRetValue' 'I' @12  0
 - protected transient 'mask' 'I' @16  8191 (1fff)
 - protected transient 'n' 'I' @20  8192 (2000)
 - protected transient 'maxFill' 'I' @24  6144 (1800)
 - protected final transient 'minN' 'I' @28  32 (20)
 - protected 'size' 'I' @32  3653 (e45)
 - protected final 'f' 'F' @36  0.750000 (3f400000)
 - protected transient 'containsNullKey' 'Z' @40  false
 - protected transient 'key' '[Ljava/lang/Object;' @44  a 'java/lang/Object'[8193] {0x0000000718701f50} (e30e03ea)
 - protected transient 'value' '[I' @48  [I{0x000000071879b1d8} (e30f363b)
 - protected transient 'entries' 'Lit/unimi/dsi/fastutil/objects/Object2IntMap$FastEntrySet;' @52  a 'it/unimi/dsi/fastutil/objects/Object2IntOpenHashMap$MapEntrySet'{0x00000007740a9680} (ee8152d0)
 - protected transient 'keys' 'Lit/unimi/dsi/fastutil/objects/ObjectSet;' @56  NULL (0)
 - protected transient 'values' 'Lit/unimi/dsi/fastutil/ints/IntCollection;' @60  NULL (0)
R14=0x000000a1138fe190 is pointing into the stack for thread: 0x000001cbbbccc810
R15=0x000001cbbbccc810 is a thread

Minecraft Version: 1.18.1
Physics Mod Version: v30

**Comment by haubna** [comment]
Does this happen in the latest version as well (Physics Mod Pro V32)?

**Comment by haubna** [comment]
Closed due to no response.

**Comment by ShotCosine** [comment]
My bad, was on vacation sorry for the late reply. I haven't experienced the crash so far, I'm sure full implementation of the trapdoor physics fixed this issue. I forgot to mention that I had the vine load distance set to 20 instead of 32, so that is my guess as to what was causing the crashing and is probably fixed with full implementation. If I experience more crashing, I will update.
