### ISSUE TITLE
Fresh animations doesn't work properly with Physics mod

### ISSUE THREAD

**Issue by RRRiderrr** [haubna/PhysicsMod#255]
Mob Physics set to ragdoll
After killing something like this happens:
![image](https://user-images.githubusercontent.com/77801822/149682894-48d19fab-427f-4362-8e30-a63080ca5bd5.png)

If I turn off this resourcepack - everything gets normal. Resourcepack uses optifine functions

**Comment by RRRiderrr** [comment]
This also happens to other mobs

**Comment by caoqt1** [comment]
Doesn't work as fresh animations change the mob models
