### ISSUE TITLE
Kill a witch broke the games textures

### ISSUE THREAD

**Issue by VoidofMercurio** [haubna/PhysicsMod#257]
**Describe the bug**
Everytime i kill a witch with the option of ragdoll or fractured or blocky all the textures glitch out.
**To Reproduce**
Kill a witch and happens sometimes when you go to the inventory it fix

**Screenshots**
![2022-01-17_12 16 53](https://user-images.githubusercontent.com/97907292/149813177-827c1cf7-8876-48e1-baca-5509189dab1f.png)

Minecraft Version: <1.18.1>
Physics Mod Version: <Physics 2.6.4 (Fabric - 1.18)>

**Comment by VoidofMercurio** [comment]
i still testing if another mob do that
but i seen only happen with the witch
idk if it have to do with this mod but the enderdragon dont spit fire when is it on the bedrock structure

**Comment by haubna** [comment]
Does the texture bug with the witch also happen with no other mod installed, only the Physics Mod installed?

**Comment by VoidofMercurio** [comment]
its happens with optifabric and with the complementary shaders

**Comment by VoidofMercurio** [comment]
i think happens only with shaders on

**Comment by VoidofMercurio** [comment]
but its the only mob that do that

**Comment by VoidofMercurio** [comment]
the only one that cause trouble is the witch and the ender dragon desappear

**Comment by PapiOphidian** [comment]
This occurs with Iris as well. Not just Optifabric. If author is saying nothing else is installed, then it might just be shaders

**Comment by haubna** [comment]
I've killed multiple witches now with the latest sodium (0.4.0-alpha6) and iris (1.2.0) version and it didn't cause any issue. Do you guys now any reliable way for me to reproduce it? Are resource packs involved?

**Comment by haubna** [comment]
Should be fixed in 2.6.6!
