### ISSUE TITLE
item physics like, actual stabbing while using a sword, swing chop animation when you cut a tree, realistic sand and gravel physics and actually stabbing the shovel into the gravel/sand

### ISSUE THREAD

**Issue by scidog06** [haubna/PhysicsMod#258]
i know this is a bit much, but maybe it would happen?

**Comment by YoBoiMike** [comment]
idk about the stabbing and animations and stuff but gravel and sand physics are cool suggestion

**Comment by UrikaTractor** [comment]
feel like the sand and gravel would be real preformance heavy but maybe only activate when falling and then disappear after a couple seconds

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
