### ISSUE TITLE
Advanced Snow Displacement [REQUEST]

### ISSUE THREAD

**Issue by HeyItsFerraro** [haubna/PhysicsMod#259]
I've seen other people request something similar to this, but the ones I've seen look unrealistic or unattainable.

What I'm requesting here is a feature that is seen in a lot of modern titles today (and some old), which is snow displacement, something identical to the one seen in Unturned's devlog seems completely attainable [(Unturned II Devlog #016)](https://youtu.be/5JkuV6QZ94k).

The dream is that ragdolls dragging across the floor, dropped items, water, explosions, falling blocks, and players crawling would all effect the snow and cause it to displace. However, if it were just footsteps I would still appreciate this addition 100%.

I'm not educated on game engine physics or coding, but I believe that the trick that AAA titles use to create this effect is just pushing the mesh under the ground to give the illusion of displacement when a player trots through some thick powder. For the sake of clarity, we'll call this "**physics snow**".

So what would happen is that on top of a snow block or snow tile in Minecraft would be a decently-thick layer of this **physics snow**, that simply gets pushed down into the block when something interacts with it to give the illusion of displacement, and if the block the **physics snow** was on were to be _broken_, the snow would break into a bunch of physics particles and fall down, with any surrounding **physics snow** edging at the end of the block. To visualize that last point, imagine the table in [this picture](https://softsolder.files.wordpress.com/2015/02/dsc08463-snow-mound-square-table.jpg) is a snow block, and you had just destroyed all the snow blocks around it. That is how the **physics snow** on top would look. I've attached some references below;

[Red dead Redemption 2, God Of War, & Horizon Zero Dawn](https://www.youtube.com/watch?v=SN7gtS1tv30&ab_channel=GHOSTGAMINGBEATS)

[Destiny 2 (Glitched out)](https://www.youtube.com/watch?v=nqbGdIt8qdg&ab_channel=TGOSeraph)

[Even Roblox has managed to do it](https://www.youtube.com/watch?v=LKnpitDeYhE&ab_channel=odysseytohome)

Icing on the cake would be if any displaced snow would be able to accumulate itself back up again if it snowed in-game. Another thing that would be nice is if torches, fires, lit furnaces, or other things of the sort had an opposite effect and actually dissipated any nearby snow, and it slowly went down. 

Let me know if anyone is opposed to the idea, and if the implementation would even be possible on Java.

**Comment by HeyItsFerraro** [comment]
Ignore the part about snowballs, I didn't realized they were actually in the game

**Comment by ShotCosine** [comment]
I feel like this is definitely possible in-game and could be the next step for the mod. Very well thought out idea. It wouldn't take much to make it look pretty convincing and realistic, the only question is how the physics snow would seamlessly connect with the rest of the snow outside of the circle of the player's area. Maybe non-interactable snow could be generated outside of the player's radius to keep the same level of snow without affecting performance, and then it turns interactable once the player gets close. Also, it looks like mud is being added in 1.19, maybe the same physics could apply!

**Comment by HeyItsFerraro** [comment]
@ShotCosine it made it in!
