### ISSUE TITLE
Piglin/zombified piglin/piglin brute ears fall off and zombie villager clothes dissapear

### ISSUE THREAD

**Issue by YaBoiPete23** [haubna/PhysicsMod#26]
So i noticed that when you kill a Piglin, zombified piglin, piglin brute there ears fall off and fall and disconnect from the ragdoll

With zombie villagers there clothes there wearing just disappear and wear a shirt thing like the villager before it was patched.

please fix this.

**Comment by QAQlinmiao** [comment]
There are also the following questions from version 2.3.1
The vindicator seems to have some problems
Haunted with missing legs and a wing
Piglin and Piglin_brute's rag dolls seem a bit stiff

**Comment by haubna** [comment]
Fixed with 2.3.3
