### ISSUE TITLE
Add Realistic Slime Physics

### ISSUE THREAD

**Issue by VartikOP** [haubna/PhysicsMod#262]
I realy love the youtube videos where they show slime physics like that its so satisfying so plz add slime physics.

**Comment by NoshaY2212** [comment]
YES!!!

**Comment by UrikaTractor** [comment]
like the idea but would probably be really hard to code

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
