### ISSUE TITLE
Doors are shown as both a physics entity and a regular Minecraft entity

### ISSUE THREAD

**Issue by cannon9009** [haubna/PhysicsMod#263]
For some reason, doors are shown as both the static minecraft entity _(the one without physics)_ and the Dynamic Block Physics entity _(the one that simulates the physics it should have)_. This happens for trapdoors too (I haven't tested with things like chains, vines, etc., but I assume it's the same with them as well since they're also under Dynamic Blocks).

https://user-images.githubusercontent.com/70039616/150284816-712802a6-6e10-4e68-8db9-05816861029d.mp4

I'm not entirely sure why it happens, but maybe it has something to do with mod compatibility? I have a good few mods installed and will be glad to post a list if necessary.

**Comment by haubna** [comment]
Yes it is a mod incompatibility.

cannon9009 ***@***.***> schrieb am Do. 20. Jän. 2022 um 07:27:

**Comment by cannon9009** [comment]
Okay. I will post my mod list and if anything's out of line, feel free to show me, and I'll go through and pest control.

[Minecraft Mods.txt](https://github.com/haubna/PhysicsMod/files/7902827/Minecraft.Mods.txt)

**Comment by PapiOphidian** [comment]
I tested this a few days ago and found the culprit to be lambdabettergrass. Disabling it or removing it for the time being should be fine

**Comment by cannon9009** [comment]
> I tested this a few days ago and found the culprit to be lambdabettergrass. Disabling it or removing it for the time being should be fine

Looks like that was the issue; I removed it and the doors are working perfectly!

If anyone else has this issue, disable or remove LambdaBetterGrass until the mods are compatible.

**Comment by PapiOphidian** [comment]
This should have stayed open since the dev is working on a compatibility update.

**Comment by haubna** [comment]
Fixed in Pro V35!
