### ISSUE TITLE
Block fractured chunk lifetime slider [REQUEST]

### ISSUE THREAD

**Issue by mrbuilder1961** [haubna/PhysicsMod#268]
**Description**
IMO, this is more something that should probably already be in the game. Anyways, I'm just requesting a lifetime controller in the config for ALL block settings. Right now, it just says that it's for the Block setting (it doesn't seem to be working but that's a different story), but I prefer Fractured. Enter problem: the little fractured chunks linger for like 4 seconds. Imagine insta-mining with this, my computer would just explode. Pretty please add some sort of control for this? Thanks for the mod, very impressive btw.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
