### ISSUE TITLE
Overlaping Buttons

### ISSUE THREAD

**Issue by Akorian** [haubna/PhysicsMod#27]
I am using a suite of other mods with the new physics mod. And some of them also alter the options menu. 
This leads to overlapping buttons in the pause menu.
![Minecraft_ 1 16 4 08_02_2021 12_19_04](https://user-images.githubusercontent.com/37375458/107213409-a8404900-6a08-11eb-82ae-e92f8c06854e.png)

**Comment by haubna** [comment]
I will keep my setting there. I think Master volume and music should stay in the settings "music & sounds". Don't know which mod alters this.

**Comment by koderian** [comment]
The mod I know that adds master & music slider to the options menu is Client Tweaks. I had the same problem with the overlapping however I easily fixed it by setting the sliders to false in the config/clienttweaks-client.toml file. 
```
masterVolumeSlider = false
#This adds back the music volume slider to the options screen. Saves you a click!
musicVolumeSlider = false
```
