### ISSUE TITLE
Crash with Rubidium [BUG]

### ISSUE THREAD

**Issue by WenXin20** [haubna/PhysicsMod#275]
**Describe the bug**
When any sodium forge mod is loaded with Physics, the game crashes after only a couple of seconds of loading. No crash report is created.
[latest.log](https://gist.github.com/WenXin20/2b3e27084e7766382aba235d216040c2#file-latest-log-L210)

**To Reproduce**
1. Install Rubidium & Physics
2. Load game
3. Crash

Minecraft Version: 1.18.1
Physics Version: 2.6.6
[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) Version: 0.4.0c

**Comment by haubna** [comment]
Sodium Forge is not supported. Use Fabric for sodium.

WenXin2 ***@***.***> schrieb am Di. 1. Feb. 2022 um 17:14:

**Comment by WenXin20** [comment]
Ah alright. Although I can't switch to fabric because of some other mods I use. I was trying rubidium since I would rather not use optifine.

**Comment by WenXin20** [comment]
Looks like rubidium fixed the incompat on their side :)
