### ISSUE TITLE
Physics settings button error

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#276]
**Describe the bug**
The physics mod settings menu conflicts with other options when other custom menu buttons are present (see screenshot)

**To Reproduce**
Have another mod that adds some option to the options menu

**Screenshots**
![image](https://user-images.githubusercontent.com/42788583/152060389-57f496ec-484b-4fb0-a2da-7279e5d34c45.png)

Minecraft Version: 1.18.1
Physics Mod Version: 2.6.6

**Comment by Dutchs** [comment]
This specific issue can be reproduced by adding [Client Tweaks](https://www.curseforge.com/minecraft/mc-mods/client-tweaks)

**Comment by haubna** [comment]
You can disable those 2 buttons in Client Tweaks. In my personal opinion "Master Volume" and "Music" should stay in "Music & Sounds" and the Physics Settings button is way more fitting there.
