### ISSUE TITLE
Ragdoll force on live creatures [REQUEST]

### ISSUE THREAD

**Issue by Amiiban** [haubna/PhysicsMod#278]
Hitting a mob with a weapon or having a mob push into something could activate a ragdoll force mechanic similar to when you hit enemies in games like skyrim and fallout 4. An example would be when a zombie is breaking down a door, instead of its hands clipping through the door, they push up against the door and collide with it, or when you shoot a villager with an arrow in the chest it buckles slightly even if it survives.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
