### ISSUE TITLE
Ragdolls can be dragged/moved with a lead Feature description [REQUEST]

### ISSUE THREAD

**Issue by SargRReal** [haubna/PhysicsMod#279]
So if you kill a mob, you can right click on it with a lead and pull it to your deep dark spooky corpse den pile bc you have ragdoll life times unreasonably high

**Comment by ShotCosine** [comment]
Check out #273

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
