### ISSUE TITLE
Support for Alex's Mobs ragdoll mobs [REQUEST]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#280]
**A description of the requested feature**
This mod https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

**Comment by caoqt1** [comment]
Ask the author of the mod to add support for the mod, mod creators have to add support for physics mod themselves.

**Comment by ghost** [comment]
> Ask the author of the mod to add support for the mod, mod creators have to add support for physics mod themselves.

https://github.com/Alex-the-666/AlexsMobs/issues/906
