### ISSUE TITLE
Particle count slider [REQUEST]

### ISSUE THREAD

**Issue by keanine** [haubna/PhysicsMod#281]
I've set block physics to particles and I've increased the physics object scale a little, however I would like to reduce the amount of particles that spawn when a block is broken if possible. A slider to allow for this would be ideal, and it may help with performance on some peoples machines.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
