### ISSUE TITLE
blood [REQUEST]

### ISSUE THREAD

**Issue by computerphysicschannel** [haubna/PhysicsMod#284]
Enemies or players bleeding when taking damage using the water system.

**Comment by caoqt1** [comment]
I am not having metaballs pop out of me when I take damage, I would prefer the 3d particles

**Comment by computerphysicschannel** [comment]
no small metaballs

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
