### ISSUE TITLE
Mob Physics based on weapon (sword/bow...) [REQUEST]

### ISSUE THREAD

**Issue by Rinmos** [haubna/PhysicsMod#285]
Divide Mob Physics to 3 separate options. so you can hit something with sword and slice it (Fractured), or hit it with bow and it wouldn´t slice because the arrow only sticks into the mob (Ragdoll), so there with bow fractured doesn´t make sence. The same for Customize each Mob rule to be divided to this 3 sections.

Now:
          Mob Physics: OFF, Fractured, Fractured Blood, Blocky, Ragdoll

My REQUEST:
          Mob Physics (Sword/Axe/Hoe/Shears...): OFF, Fractured, Fractured Blood, Blocky, Ragdoll
          Mob Physics (Bow/Crossbow/Trident...): OFF, Fractured, Fractured Blood, Blocky, Ragdoll
          Mob Physics (By themselves/Sun): OFF, Fractured, Fractured Blood, Blocky, Ragdoll

**Comment by UrikaTractor** [comment]
yeah that would be cool 
so creepers have fractured blood only when exploding  and stuff like that

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
