### ISSUE TITLE
PhysX PxRigidBodyExt::updateMassAndInertia[BUG]

### ISSUE THREAD

**Issue by SaiCode-DEV** [haubna/PhysicsMod#288]
**Describe the bug**
`D:\git\physx-jni\PhysX\physx\source\physxextensions\src\ExtRigidBodyExt.cpp (84) : warning : PxRigidBodyExt::updateMassAndInertia: inertia tensor has negative components (ill-conditioned input expected). Approximation for inertia tensor will be used instead.` 
Was spammed in Console all the time

**To Reproduce**
Wore the Kings cape and flew with a Elytra around, that shoun't be the bloblem

Minecraft Version: <1.18.1>
Physics Mod **Pro** Version: <v35 Fabric>

**Comment by haubna** [comment]
Which Pro version did you use?

**Comment by haubna** [comment]
Should be fixed by now.
