### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by CraftyShark99** [haubna/PhysicsMod#289]
Physics Settings Tab Overlayed by the standard settings

![image](https://user-images.githubusercontent.com/100386677/155619905-21ee5682-a305-4d17-9a05-3b854d4542ea.png)

Minecraft Version: 1.18.1
Physics Mod Version: 2.6.7

**Comment by haubna** [comment]
I don't remember the mod name that causes this but it contains the word "tweak" or something. You can disable the Master Volume and Music button in their menu.
