### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by FuriousG** [haubna/PhysicsMod#29]
This isnt an issue but... Could you make this but in 1.12.2? This isnt a requirement if you dont want to then you really dont have to
But if you do that would be great fully appreciated, I will say I wont give any money to help for this sorry, As my parents wouldnt let me and I dont know how to paypal the money to you if I have physical money and not money that is in a app type of thing. Again this is just a request that can be denied and isnt a demand that has to happen! 

Sincerely, 
               A random person on the internet that you dont know aka FuriousG

**Comment by haubna** [comment]
As mentioned in one of my YouTube comments I would like the Minecraft community to go forward. It destroys the eco system that players are stuck with old versions. That's why I will never support old versions and only the newest one will get updates.
