### ISSUE TITLE
disconnected kelp [BUG]

### ISSUE THREAD

**Issue by KaziiTheAvali** [haubna/PhysicsMod#292]
**Describe the bug**
idk why this happens but the block physics kelp sometimes unattaches.

**To Reproduce**
no clue. i was swimming around getting kelp and just found this

**Screenshots**
![image](https://user-images.githubusercontent.com/87594664/156351112-d407fd6c-f5e5-4bb0-897b-4a307110963b.png)

Minecraft Version: <1.18.1>
Physics Mod Version: <36V Pro>

**Comment by haubna** [comment]
Fixed with Pro V42
