### ISSUE TITLE
Game crashes on world gen.

### ISSUE THREAD

**Issue by Romoslayer** [haubna/PhysicsMod#293]
**Describe the bug**
Game crashes.
Mixin apply failed physicsmod.mixins.json:vines.MixinBlockRenderer

**To Reproduce**
I just created a new world with this mod and many others loaded.

Minecraft Version: 1.18.1-39.1.0
Physics Mod Version: 1.18-2.6.7

Minecraft Logs File:
https://drive.google.com/file/d/1C9x02a_DR751yjW6yHCDsqKZB_idPe2X/view?usp=sharing

**Comment by haubna** [comment]
Use Iris 1.2.0
