### ISSUE TITLE
Knockback and Punch work on entity's corpse

### ISSUE THREAD

**Issue by WaifuSlayer5057** [haubna/PhysicsMod#295]
when i use a knockback 2 sworrd and 1 hit any entity, it ll lok like it have a heartbeat instead get kill by a player so can you make Knockback and Punch work on entity's corpse
my english bad
:P

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
