### ISSUE TITLE
Different type of damage for different type of mob physic

### ISSUE THREAD

**Issue by ChocoMartini** [haubna/PhysicsMod#297]
Example
1. <your choice> mob physic for dead by explosive
2. <your choice> mob physic for dead by other things
3. <your choice> mob physic for dead by burning and lava
4. <your choice> mob physic for creeper explode itself

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
