### ISSUE TITLE
Trapdoor Swing Motion [REQUEST]

### ISSUE THREAD

**Issue by MaxBrag** [haubna/PhysicsMod#298]
As of the pro version of the mod on Patreon has the capability where a snowball can slightly make a TRAPDOOR move slightly back and forth and have a small swing animation.

I wonder if it is possible to have option(s) in the Dynamic Block settings for the TRAPDOOR type(s) to have an adjustable option of how much force TRAPDOOR(s) can move back and forth based on the impact of the snowball.

Thank you for reading this suggestion.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
