### ISSUE TITLE
Memory leak [BUG]

### ISSUE THREAD

**Issue by Cutie-Stacie** [haubna/PhysicsMod#299]
This mod gradually fills all available memory.

Minecraft Version: 1.18.1, Valhelsia enhanced vanilla
Physics Mod Version: 2.6.7

**Comment by haubna** [comment]
Did you by any chance use the 3D skin layer mod? If so this will be fixed in version 2.6.9.

**Comment by Cutie-Stacie** [comment]
This happens even when using only this mod and spark mod.

**Comment by haubna** [comment]
Do you know how to take a heap dump? If so maybe you can check what allocates so much memory like in issue #322

**Comment by Cutie-Stacie** [comment]
My [heap dump](https://drive.google.com/file/d/1lTMsZLbr_j5LQg4FU6JK8eV1lnopI_jj/view?usp=sharing) using Valhelsia Enhanced Vanilla modpack and physic mod. The memory was filled in about 5-10 minutes.

**Comment by haubna** [comment]
The issue got fixed with 2.6.9. The heap dump indicates the same issue as with #322 
Please let me know in case the problem persists with the new version!
