### ISSUE TITLE
Add Boob Physics /s [REQUEST]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#301]
Just a joke ofc! unless... nah! hahah! 👉👈 unless?

**Comment by NaiNonTH** [comment]
Boobs exist?

**Comment by MrPoker12** [comment]
Nice joke lmao

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
