### ISSUE TITLE
2-Tall Foliage Issues

### ISSUE THREAD

**Issue by Genious28** [haubna/PhysicsMod#303]
Bug1;
All of 2-Tall Foliage within a chunk becomes invisible after block/chunk update while running with Immersive Portals.

https://user-images.githubusercontent.com/97228026/158636773-e6c1d3a7-5bf7-4c50-99d0-27069a1af8b4.mp4

Bug2; 
2-Tall Foliage Collision does not remove default plant.
![2022-03-14_19 03 46](https://user-images.githubusercontent.com/97228026/158637039-7fea08f3-8a8e-4088-b111-e7a05e5954db.png)

**Comment by Genious28** [comment]
Also, Vines & Kelp.. basically, all the foliage with physics is having issues with Shaders - Sodium/Immersive Portals.

**Comment by haubna** [comment]
Yeah this is a known issue with Immersive Portals. I haven't implemented support for it yet.

**Comment by Genious28** [comment]
> Yeah this is a known issue with Immersive Portals. I haven't implemented support for it yet.

Yea, but the second one happens without Immersive Portals. I can get you a list of other mods I'm running with it.

**Comment by haubna** [comment]
Try the new version. It includes an indium fix which should solve the other problem!

**Comment by haubna** [comment]
Fixed.
