### ISSUE TITLE
A CODE TO PROGRAMM IN LITERATERAL WORDS

### ISSUE THREAD

**Issue by tolcraft** [haubna/PhysicsMod#304]
--->IF BUTTON "kICK" PUSHED SAVE NBT,INVENTORY,HEALTH;REPLACE THE MOB WITH A RAGDOLL> IF RIGHT CLICK ON A RAGDOLL______RAGDOLL FOLOW THE CENTER OF PLAYER"S SCREEN>IF RAGDOLL OF "KICKED" MOB DOESn'T MOVE FOR 5 SEC-------SUMMON MOB,GIVE HIM NBTs,INVENTORY and health.OH____IF MOB FLYES FOR 2 BLOCKS REMOVE 3HP. ALIVE RAGDOLL LIFETIME=customisable!

**Comment by caoqt1** [comment]
shut the hell up and talk normally
