### ISSUE TITLE
Please add sand/gravel physics!!! [REQUEST]

### ISSUE THREAD

**Issue by modbeastMC** [haubna/PhysicsMod#307]
Haubna can you please add ssand/gravel physics, I really want it added!!!

Something like this please: https://www.youtube.com/watch?v=ZEUstO76IA0

**Comment by MrPoker12** [comment]
It will be pretty buggy and laggy.

**Comment by demonwolfie** [comment]
so this would be so cool and fun and no it won't be buggy or laggy if he sets it to a timer until it de-spawns it will not be buggy or laggy

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
