### ISSUE TITLE
Crash on World-Load [BUG]

### ISSUE THREAD

**Issue by RPGShoulderDevil** [haubna/PhysicsMod#309]
Minecraft crashes whenever loading a world, whether loading an old one or creating a new one. Strongly suspect a rendering mod is at fault, specifically Oculus 1.2.2a (Since I'm a forge user and can't use Iris, and am fed up with Optifine). The crash seems due to vine behavior somehow, and possibly because Oculus is a port of Iris (maybe an older Iris version)

Thanks in advance for attention on this, and even more importantly, for making such an excellent, gorgeous mod!

Minecraft Version: 1.18.2
Physics Mod Version: Pro V36 Forge 1.18

[crash-2022-03-31_18.35.27-client.txt](https://github.com/haubna/PhysicsMod/files/8394092/crash-2022-03-31_18.35.27-client.txt)

**Comment by GordonHollow** [comment]
Also has same issue.
Now one of mods that i use - don't compat with opifine.
I try rubidium+oculus - and has that crash, cause physics don't compat with it

**Comment by haubna** [comment]
Oculus and Rubidium are now compatible. Make sure to use the latest version of both!
