### ISSUE TITLE
Hook physics to less generic events

### ISSUE THREAD

**Issue by Kevadroz** [haubna/PhysicsMod#31]
Right now physics trigger when a block is set to air, right? (with some exceptions, i think? I haven't seen the source, as it isn't public), thats too generic, it could be triggered by falling sand, pistons, /fills /setblocks, fish buckets, bee nests... without explicit exclusion. 

The point is: wathever is the way you trigger the physics, it trigger for too much cases, here its better to spawn less than enough than to spawn more.

I suggest to hook them to block breaking particles (no the particles themselves, but what spawns them for each broken block), and to the mob death animation.

The last time i checked was on 1.2.1, i think.

**Comment by haubna** [comment]
A client doesn't know why a block is set to something else. It just get's a packet with the new block data. Impossible.

**Comment by Kevadroz** [comment]
> I suggest to hook them to block breaking particles (not the particles themselves, but what spawns them for each broken block)

Yes but this has to come from somewere, it does not happen on /fills, but on actual block "breaks"

**Comment by haubna** [comment]
Server dependency will never be added because that needs the server to have the mod installed.
