### ISSUE TITLE
Incompatibility 

### ISSUE THREAD

**Issue by Th3DocCroc** [haubna/PhysicsMod#31]
This mod (2.3.3 ver.) doesn't allow the looting of mobs that the mod "RPGZ" adds, if mob physics is on.

It's no big deal as you can just disable mob physics, I just thought I'd inform you in case you were looking for more mod compatibility.

Btw, great mod. Nice performances, too!

**Comment by haubna** [comment]
Thanks for the info! :)

**Comment by haubna** [comment]
This might be fixed in newer versions. Let me know if it still persists.

**Comment by haubna** [comment]
#85

**Comment by haubna** [comment]
Closing due to no response.
