### ISSUE TITLE
[FABRIC] Crashing with Indium on v37 [BUG]

### ISSUE THREAD

**Issue by ShotCosine** [haubna/PhysicsMod#310]
**Describe the bug**
Instance of Minecraft with ONLY Sodium, Iris, Indium, and LambdaBetterGrass (a mod that uses Indium) and PhysicsMod v37 crashes upon world load.

Removing Indium fixes the crash. I suggest fixing this as soon as possible since almost every single fabric mod requires Indium and people are sure to complain if it won't work for them instantly.

**To Reproduce**
Load a world with Sodium, Iris, Indium, and PhysicsMod v37.

To fix, delete every mod that requires Indium and Indium.

**Screenshots**
Game crashes before world is able to load.

Minecraft Version: <1.18.2>
Physics Mod Version: <v37>

Crash Report:
[crash-2022-04-05_13.47.15-client.txt](https://github.com/haubna/PhysicsMod/files/8420707/crash-2022-04-05_13.47.15-client.txt)

Crash Log:
[indiumcrash.log](https://github.com/haubna/PhysicsMod/files/8420709/indiumcrash.log)

**Comment by haubna** [comment]
Fixed
