### ISSUE TITLE
An additional Feature for block collapsing  [REQUEST]

### ISSUE THREAD

**Issue by Whitepaper77** [haubna/PhysicsMod#312]
A feature in which similar to mod **that is not compatible with this mod in anyway,**

If you for example built out from a cliff side. You can only build a certain amount of blocks out before they collapse! this can be stopped with blocks as support beams making it feel more in terms of building. It would also make a large difference to the way people would build with this setting on being far more careful adding an extra challenge to Minecraft's _simplistic_ building style!

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
