### ISSUE TITLE
Minecraft Gravity Request

### ISSUE THREAD

**Issue by professorsaltshaker** [haubna/PhysicsMod#317]
Hi! I'm not exactly sure if this feature can be found in the block settings or gravity settings, so if it can, please tell me.

The issue is that blocks above a block that holds it up also fall when you break them. I don't have a problem with this feature, but I do wish there was a toggleable option for it. I like to build a lot of houses in a super flat world, so this can be a MAJOR problem for me. Thanks!  (I'm using the free version for 1.18.2 fabric)

**Comment by haubna** [comment]
You can disable that in physics settings -> server settings
