### ISSUE TITLE
Liquid physics huge enhancement

### ISSUE THREAD

**Issue by MrPoker12** [haubna/PhysicsMod#320]
Lets not forget about water physics. I really love them and it's fun to mess with but it isn't a lot useful and you must obtain required blocks to observe it. You should lower the effect (movement, exploding etc.) and implement them into real water as a replacement. The sea will have a wave but a river and a user created water source will be still (this can be changed in the menu as a user preference). Also having a water splash with white water effects. For shades just obtain the data like the normal water. I would really love to see that in Minecraft!

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
