### ISSUE TITLE
Memory leak in mirroredCuboids [BUG]

### ISSUE THREAD

**Issue by tr7zw** [haubna/PhysicsMod#322]
**Describe the bug**
During testing of animated skins with 3d layers(https://github.com/tr7zw/3d-Skin-Layers) I noticed after some time that mc was hitting it's memory limit. Managed to create a heapdump before it crashed, and somehow 4.1 million instances of my 3d skin layers ended up in the mirroredCuboids map at net.diebuddies.physics.PhysicsMod. Currently the mod regenerates the mesh on each frame change, I might change it to cache them over time. This is still an issue, since meshes seem to never get cleared out of the mirroredCuboids map. The map needs some kind of housekeeping logic (timeouts/weak reference/fixed size/etc) to prevent an infinite growth. The CustomizableCube objects are not referenced from anywhere outside of that map.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5133936/163684422-5dd4255a-6b97-4c5a-a653-a860b3d5e55d.png)

Minecraft Version: 1.18.1
Physics Mod Version: 2.6.7

**Comment by haubna** [comment]
Oh wow yeah, that was a pretty old and bad implementation of mine when I just started with Mixins and all that stuff. Will be fixed in version 2.6.9! Thanks for the heap dump and the report!

**Comment by tr7zw** [comment]
Glad to hear, since I'm not yet done with my stuff it's not released anyway, and if there is a fix in the next version I can skip to add any workaround/safeguards

**Comment by haubna** [comment]
Just released the fix. Only available for 1.18.2 though and Minecraft versions 1.17 and 1.16 won't receive any new updates. Just so you know in case you plan to backport your mod!
