### ISSUE TITLE
[1.18.2] Launch error in Forge 49.0.54

### ISSUE THREAD

**Issue by Baggytrousers27** [haubna/PhysicsMod#324]
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

Minecraft Version: 1.18.2 Forge 49.0.54
Physics Mod Version: physics-mod-2.6.10-mc-1.18.2-forge

[Crashlog](https://pastebin.com/nT6J1QTG)

**Comment by haubna** [comment]
My bad! Please redownload version 2.6.10. I applied a fix for it!
