### ISSUE TITLE
Obfuscate mod with physics mod  causes Minecraft crashed.

### ISSUE THREAD

**Issue by MrDomesticCat** [haubna/PhysicsMod#327]
Minecraft 1.16.5, physics mod 2.6.7.
I ruled out the other mods in turn and found that obfuscate mod was causing it. Here is my crash report.
[Crash report.zip](https://github.com/haubna/PhysicsMod/files/8527244/Crash.report.zip)

**Comment by MrDomesticCat** [comment]
How to fix it

**Comment by caoqt1** [comment]
> How to fix it

Be Patient

**Comment by haubna** [comment]
Has to be fixed within the obfuscate mod.
