### ISSUE TITLE
Incompatible with Indium 1.0.3 [BUG]

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#330]
**Describe the bug**
Upon launching the world with Physics mod and Indium 1.0.3, the game will be instantly crashed.

**To Reproduce**
1. Install Physics mod, Fabric API, and Indium
2. Run the game, then launch any world
3. The game crashed.

**Crash Report**
[crash-2022-04-25_09.29.32-client.txt](https://github.com/haubna/PhysicsMod/files/8551240/crash-2022-04-25_09.29.32-client.txt)

**Log**
[2022-04-25-3.log](https://github.com/haubna/PhysicsMod/files/8551242/2022-04-25-3.log)

Minecraft Version: 1.18.2
Physics Mod Version: 2.6.10

**Comment by haubna** [comment]
Use Indium 1.0.2 until I release a bugfix. They changed the name of a function.

**Comment by haubna** [comment]
Fixed with version 2.7.0
