### ISSUE TITLE
All blocks above selected block are broken as well[BUG]

### ISSUE THREAD

**Issue by komatosecowboi** [haubna/PhysicsMod#332]
**Describe the bug**
When breaking a single block, every block above will break with it. So when it comes to fine tuning a build - my entire build was destroyed because every block above was broken as well.

**To Reproduce**
I messed around with all the different variations of the configuration - even turned the block physics off; however it still continued to break the blocks above.

Minecraft Version: 1.18.2
Physics Mod Version: Lite

I absolutely love the mod that you have created and still have it - I would just love for this to be fixed so I can enjoy the mod in its entirety. Thank you.

**Comment by haubna** [comment]
This is a feature. You can disable it in physics settings > server settings.
