### ISSUE TITLE
Throwable physic objects [REQUEST]

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [haubna/PhysicsMod#334]
an feature that allows the player to bind throwable physic object on a specific key.
On that key press, a small phys obj (like a rock) would spawn with the velocity in the player head rotation dir

thats satisfying af

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
