### ISSUE TITLE
Bug description [BUG] everything from your mod is translucent when combined with the experimental pbr from iris

### ISSUE THREAD

**Issue by Skel200** [haubna/PhysicsMod#335]
**Describe the bug**
Everything like Ragdolls, particles, and fractured becomes translucent.
**To Reproduce**
Steps to reproduce the behavior. Download the latest pbr beta from iris and turn on advanced materials and turn on the bsl shaders with any pbr pack. 

**Screenshots**

Minecraft Version: <version>b1.18.2
Physics Mod Version: <version> latest

**Comment by homogoblin28** [comment]
same here, just using BSL shaders causes all fractured blocks / particles / not sure what to call them to become transparent

**Comment by haubna** [comment]
Fixed with version 2.8.4. It supports the latest PBR build from Iris.
