### ISSUE TITLE
Physics mod says it needs fabric 0.5.0 or later, when I am running 0.13.3

### ISSUE THREAD

**Issue by u12bdragon** [haubna/PhysicsMod#337]
_physics-mod-2.7.2-mc-1.18.2-fabric.jar_ Physics mod says it needs fabric 0.5.0 or later, when I am running 0.**13**.3, which is obviously a later version. Furthermore, version 0.5.0 was released in 2019, before 1.18 ever came out.

**Comment by haubna** [comment]
It is not talking about Fabric but rather the Fabric API :P
