### ISSUE TITLE
Game crash upon logging into vanilla server [BUG]

### ISSUE THREAD

**Issue by litoj** [haubna/PhysicsMod#338]
**Describe the bug**
When I try to log into a server (Hypixel for instance) with the latest version, the game says Joining world, and shortly after "Saving world" and quits

**To Reproduce**
Log onto mc.hypixel.net with the latest version of the mod installed.

Minecraft Version: 1.18.2
Physics Mod Version: 2.7.2

**Log**
[2022-05-08-3.log](https://github.com/haubna/PhysicsMod/files/8647589/2022-05-08-3.log)

**Comment by haubna** [comment]
Please always keep your mods up to date! You need Indium 1.0.3 + Iris 1.2.4 for it to work.

**Comment by litoj** [comment]
oh, I didn't know they got an update. In that case, for someone like me, could you make the mod require these versions?
