### ISSUE TITLE
Crash when join server [BUG]

### ISSUE THREAD

**Issue by xXagu676Xx** [haubna/PhysicsMod#339]
every time that i join a server, minecraft crashes

i had the 2.6.10 version and i worked fine, when i updated it to 2.7.2 it started crashing

Crash Log: https://pastebin.com/rVA1cV9L

Minecraft Version: 1.18.2
Physics Mod Version: 2.7.2

**Comment by haubna** [comment]
Update Iris and Indium to the latest version
