### ISSUE TITLE
Add active ragdolls.

### ISSUE THREAD

**Issue by Agentlj** [haubna/PhysicsMod#341]
For example ..... When a zombie is killed in the shoulder, he will hold it (or try) It can be done .... I don’t know how, well, for example, triggers ....

**Comment by ghost** [comment]
WHAT THE HELL, I JUST SUGGESTED THIS

**Comment by ghost** [comment]
Actually, Mines probably easier to impliment.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)

**Comment by Agentlj** [comment]
> Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)

Ummm, I'm can't. I'm has Ben banned from this discord server.
