### ISSUE TITLE
Tall Grass Ignores Physics and Duration Settings [BUG]

### ISSUE THREAD

**Issue by Sullos** [haubna/PhysicsMod#342]
**Describe the bug**
Tall grass is not following its settings when being broken. For example, I have set all blocks to fracture by default as well as have default animation. I individually set both normal grass and tall grass to have particles physics with vanishing animation. The normal short grass does this exactly, the block is broken, turns into particles and vanishes with no variance to duration at a setting of 1.20. Tall grass, however, set up identical to the short grass, when broken, breaks into two blocks pieces and vanishes after a longer amount of time, typically a few seconds, with a variance of a few seconds as well.

**To Reproduce**
Keep most mod settings default, except set tall grass to follow different duration, and variance durations, as well as different physics and animations. Break some tall grass. The tall grass does not follow its settings.

**Screenshots**

![2022-05-15_20 25 13](https://user-images.githubusercontent.com/33239800/168468211-86bf5e26-9ab2-4a0d-afd5-c6c0bd173deb.png)
![2022-05-15_20 25 18](https://user-images.githubusercontent.com/33239800/168468216-86ef0573-aac1-4971-94da-43c4669f6347.png)
![2022-05-15_20 25 27](https://user-images.githubusercontent.com/33239800/168468219-1d41fd43-43cb-48c7-afa4-506b3da041ee.png)
![2022-05-15_20 25 58](https://user-images.githubusercontent.com/33239800/168468224-a5992398-959b-4b4e-872f-e767af2a0133.png)

Minecraft Version: <1.18.2>
Physics Mod Version: <2.7.3>

**Comment by haubna** [comment]
Dynamic Block physics currently do not support custom animations. They also ignore the block break type because they need to stay attached to each other when being broken. Will be fixed in the next release. In the meantime you can deactive dynamic block physics for tall grass to have custom animations for them.

**Comment by Sullos** [comment]
Ah thank you so much for this, I only just came across this mod two days ago so I was still tinkering. This is good to know though, thank you.
Feel free to close this issue if you believe it is not relevant due to the current state of things, or if as you say, it should be fixed in the next release. 
Thank you

**Comment by haubna** [comment]
Once I release the fix I will close it, totally forgot to work on that!

**Comment by haubna** [comment]
Fixed in V48
