### ISSUE TITLE
Really messed up ragdolls. (This is a feature.)

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#343]
**A description of the requested feature**

A new ragdoll setting that, On death; Causes mobs ragdolls kick and flail instead of just flopping over.

This will only happen to mods that die from attacks with LESS that a configurable amount of damage. (Defaulting to 10.) Meaning insanely beefed up weaponry or TNT will cause any unlucky creepers hit to die instantly. (Much like in Insurgency.)

Hell, You could make it a PRO exclusive if you want, It would probably fit.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
