### ISSUE TITLE
DimensionalThreading Incompatibility | Physics Mod Thread Safety? [BUG]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#344]
**Describe the bug**
Breaking any block immediately crashes the game. See [here](https://crashy.net/6RmA1jg7IgiBCRzwmtd6) for all the crash info, client info, etc.

**To Reproduce**
1. Install Physics Mod and [DimensionalThreading](https://github.com/WearBlackAllDay/DimensionalThreading/releases/tag/v1.2.6).
2. Enter the world and break a block.

**Screenshots**
N/A

Minecraft Version: `1.18.2`
Physics Mod Version: `2.7.4-mc-1.18.2-fabric`

**Comment by haubna** [comment]
Thanks for the detailed report, fixed with version 2.7.5!

**Comment by ghost** [comment]
Thanks for such a quick response!

Quick question - I understand that currently "New Versions are only available on the official website", however, this makes it impossible to download them through modpack launchers, even though they are still freely available to download. This means that modpack authors must include them as overrides which sit in jar format directly inside of the modpack zip.

I couldn't find anything detailing your stance on distribution of the lite version in modpacks - is this okay?

**Comment by haubna** [comment]
That is no problem :)

Brittank88 ***@***.***> schrieb am Do. 19. Mai 2022 um 05:28:
