### ISSUE TITLE
Crash On Viewing Chisels & Bits Blocks In Options [BUG]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#345]
**Describe the bug**
As soon as the C&B blocks are visible in the options menu (for example, the customization menu), the game crashes immediately.
Further info: https://crashy.net/1wHw3GVl09QtHLNqtqfq

**To Reproduce**
1. Install this mod and [C&B for Fabric](https://www.curseforge.com/minecraft/mc-mods/chisels-bits-for-fabric).
2. Attempt to customise the blocks from C&B in the PhysicsMod options.

**Screenshots**
N/A

Minecraft Version: `1.18.2`
Physics Mod Version: `2.7.4-mc-1.18.2-fabric`

**Comment by haubna** [comment]
Thanks for the detailed report, fixed with version 2.7.5!
