### ISSUE TITLE
ReplayMod Extra Compatibility

### ISSUE THREAD

**Issue by MaxedOut1** [haubna/PhysicsMod#346]
Not a bug, or a problem with the mod. Just an easy change to the mod that would fix some unusual behaviour when using with replaymod.

Already mentioned this in discord but just putting it here too to remind you incase you forget.

To replace randomnumber generating with environment variables, such as for ragdolls generating random numbers based on the entities position. This would mean replaying the death back multiple times in the replaymod would have the same animation, making it much better to make cinematics and such.

Thank you! Amazing mod!

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
