### ISSUE TITLE
Bush Physics [REQUEST]

### ISSUE THREAD

**Issue by DAVIDJONES6969** [haubna/PhysicsMod#348]
You should make it so that when you walk in bushes they move and make it so they blow in the wind. You should also make it so that on rainy days the wind is increased and the bushes and trees blow more, This would make debris like sticks and leaves blow of trees possibly damaging the player if it hits the player or damaging blocks, etc...

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
