### ISSUE TITLE
Ragdoll Error

### ISSUE THREAD

**Issue by WenXin20** [haubna/PhysicsMod#35]
`Minecraft v1.16.5`
`Forge v36.0.13`
`Physics v1.3.1`

When an entity dies, it triggers an error in the log for me, but does not crash the game.
[Error Log
](https://gist.github.com/WenXin20/eee5444971a2f6f8f8220511c364f85a)

**Comment by haubna** [comment]
Ragdoll is only supported for a small amount of vanilla mobs for now.

**Comment by WenXin20** [comment]
It happened to both a vanilla and non-vanilla entities, such as the mooshroom cow.
