### ISSUE TITLE
Tree physics [REQUEST]

### ISSUE THREAD

**Issue by DAVIDJONES6969** [haubna/PhysicsMod#350]
Make it so that when you chop down trees, instead of all the blocks breaking it should fall over like in the mod Dynamic Trees mod.

**Comment by Asddrth** [comment]
Just combine dynamic trees mod with physics mod

**Comment by demonwolfie** [comment]
they need to add that be cuz the dynamic tree mod is not for anything higher than 1.12 so for people like me on 1.19 we can't use that mod so this would be a good thing to add

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
