### ISSUE TITLE
Rain physics [REQUEST]

### ISSUE THREAD

**Issue by DAVIDJONES6969** [haubna/PhysicsMod#355]
You should add Realistic rain physics into the game and make it so that when the rain hits the ground it splashes and forms puddles of water that is interactable.

**Comment by finogreofdoom** [comment]
That would lag.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
