### ISSUE TITLE
Dynamic Block (Debug?) Lines Visible [BUG]

### ISSUE THREAD

**Issue by Sullos** [haubna/PhysicsMod#356]
**Describe the bug**
Various Dynamic Blocks have what appears to be a debug line of some sort showing on or near the block/plant. This can be seen in the following pictures.

![2022-05-21_18 16 11](https://user-images.githubusercontent.com/33239800/169642704-0fa1ecb0-4881-4214-be79-77781384e598.png)
As can be seen on the cave vines, the bottom most block in a chain of cave vines has a straight red vertical line on its corners.
![2022-05-21_18 16 16](https://user-images.githubusercontent.com/33239800/169642713-97233686-d3d3-4efe-a371-922ae9544965.png)
This is similar with weeping vines, except the whole vines length and it is a green colour. As well as normal vines, with a thing black line on its edges (not corners).
![2022-05-21_18 16 21](https://user-images.githubusercontent.com/33239800/169642714-55ba7119-6b87-4a6e-aacf-75469d01e34e.png)
The neon equisetum (far left, better nether mod) was added as a test block to the dynamic physics blocks and can be seen to include a large amount of visible lines skewering out.
![2022-05-21_18 16 29](https://user-images.githubusercontent.com/33239800/169642716-8e304abc-fd14-4ec0-b348-096b03fd5903.png)
Finally is a picture showing with dynamic block physics turned on still
![2022-05-21_18 16 37](https://user-images.githubusercontent.com/33239800/169642719-a0d98b46-a40f-416a-9465-818a144e79dc.png)
And then turned off, indicating this has something to do with the lines being visible at all?

**To Reproduce**
Ensure Dynamic Blocks are enabled in settings, place any of the following blocks from the base vanilla game or even various other mods with the custom addition of the block/plant as a dynamic block:
Weeping vines, twisting vines, vines, neon equisetum (better nether), cave vines, tall grass, large fern, lilac, peony, rosebush, sunflower. 
In short, almost all of the blocks that are dynamic by default, excluding chains and sugarcanes as best as I can tell. Some of these blocks only have very small lines (vines, and lilac), whereas others, it is much more visible on (sunflower, neon equisetum etc).

**Other Information**
I have manually forced a crash in order to hopefully make life easier for you, here is the crash report:
[crash-2022-05-21_18.22.26-client.txt](https://github.com/haubna/PhysicsMod/files/8747276/crash-2022-05-21_18.22.26-client.txt)

Other things I have tried include: disabling all resourcepacks, shaderpacks, reducing all settings to lowest and up to highest, restarting game, messing with various physics mod settings. 
None have achieved any success.  
I'm hoping/imagining this is just an issue of dynamic block physics debug lines being set to 'on' in some setting, and it can be easily fixed by allowing these lines to be disabled, however, I just don't know.

Minecraft Version: <1.18.2 Fabric>
Physics Mod Version: <49 Pro Fabric>

Edit: Just to add to this a few hours later the lines on the cave vines seemingly have vanished, not sure why, all the rest have remained the same though. I'll also add I have also seen the lines appear on the corners of doors too, so long as they are dynamic.

**Comment by haubna** [comment]
Unfortunately this is not a debug line thing. It only happens with shaders + PBR enabled. For the time being you can disable PBR. Let me know if this fixes it for you. I've tested Sildurs, SEUS Renewed, Complementary and BSL shaders and couldn't observe this bug (without PBR).

Edit: seems to be related to resource packs. I just added Vanilla lab PBR and it creates the same bug (without PBR being enabled).

**Comment by haubna** [comment]
Fixed with Pro V50. Thank you for your detailed report!
