### ISSUE TITLE
Sand physics and gravel physics [REQUEST]

### ISSUE THREAD

**Issue by DAVIDJONES6969** [haubna/PhysicsMod#357]
You should make it so that when you break sand or gravel blocks they spread out into a dust like formation. Like in real like when you get sand or gravel and throw it on the ground it spreads out etc... Its hard to explain.

**Comment by finogreofdoom** [comment]
I agree

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
