### ISSUE TITLE
Fabric: Crash with versions 2.7.X

### ISSUE THREAD

**Issue by xXNickznXx** [haubna/PhysicsMod#360]
**Describe the bug**
Use a 2.7.X version of the mod, crashes with every version.

Tested it with 2.6.10 and its working.

Other used mods can be seen in the crash report.

**To Reproduce**
Try open a world

**Screenshots**
![image](https://user-images.githubusercontent.com/31235664/170118627-e761c1d2-ce34-4577-97f0-d4ba4436b4bd.png)

Minecraft Version: 1.18.2
Physics Mod Version: 2.7.X

Crash report: [crash-client.txt](https://github.com/haubna/PhysicsMod/files/8765744/crash-client.txt)

**Comment by haubna** [comment]
Update Indium + Iris

**Comment by xXNickznXx** [comment]
I actually had to update both and now it works, thanks!
