### ISSUE TITLE
Not responding on fabric with sodium

### ISSUE THREAD

**Issue by thiagoabreutnb** [haubna/PhysicsMod#361]
**Describe the bug**
when i open the game on sodium(fabric) the game simple dont respond it only works on forrge optfine.

**To Reproduce**
simple just open the game with sodium and the mod on fabric and done .

**Screenshots**
dont needed since it dont hhaves error.

Minecraft Version: <1.18.2>
Physics Mod Version: v49 pro

**Comment by haubna** [comment]
What do you mean by not respond? Are you using the fabric version of the mod?

**Comment by thiagoabreutnb** [comment]
yes i am using it

**Comment by haubna** [comment]
I need some more details to help you. It works fine on my end.

**Comment by thiagoabreutnb** [comment]
well i try to open ot when ittry to losds is freezes and dont reappnd  an
it persists
my pc: intel core i5 3.0ghz
8gb ram
ssd 110 gb and others


Em qui, 26 de mai de 2022 02:33, haubna ***@***.***> escreveu:

**Comment by haubna** [comment]
Send me a list of all your mods + versions

**Comment by thiagoabreutnb** [comment]
fabric 1.18.2 sodium , irium and physics mod

Em qui., 26 de mai. de 2022 às 13:04, haubna ***@***.***>
escreveu:

**Comment by haubna** [comment]
I don't know what irium is but I suppose you mean Iris and Indium. Make sure those are updated to the latest version.

**Comment by thiagoabreutnb** [comment]
Ok, buttt isnt sodium is needed forr indium and iris

Em qui., 26 de mai. de 2022 às 17:25, haubna ***@***.***>
escreveu:

**Comment by thiagoabreutnb** [comment]
![image](https://user-images.githubusercontent.com/93147849/170588212-ce582d5a-4fe7-4bba-9f20-98c08e235774.png)
without sodium

**Comment by thiagoabreutnb** [comment]
![image](https://user-images.githubusercontent.com/93147849/170588494-10c5668d-4c82-4d4d-b1ad-02200296b815.png)
with sodium

**Comment by thiagoabreutnb** [comment]
i wanna try others functions like water and snow physics

**Comment by thiagoabreutnb** [comment]
also both irris and indium arrerr on lastest verrsion

**Comment by haubna** [comment]
They aren't the latest version. You need Iris 1.2.4 and Indium 1.0.4.

**Comment by haubna** [comment]
I never said that you should remove sodium. Does it work now? Please send me a screenshot of your mods folder.

**Comment by thiagoabreutnb** [comment]
1.0.4? did u mean 1.0.3


Em sex., 27 de mai. de 2022 às 01:18, haubna ***@***.***>
escreveu:

**Comment by thiagoabreutnb** [comment]
![image](https://user-images.githubusercontent.com/93147849/170728790-03f2785d-7e9d-4b05-a5ee-6c6d41162ae5.png)
my mods folder

**Comment by thiagoabreutnb** [comment]
and still dont work

**Comment by thiagoabreutnb** [comment]
i found the problem
its not iris and indium
ITS SODIUM
ITS HIM WHOS CAUSING THE PROBLEM

**Comment by thiagoabreutnb** [comment]
LET ME TRY WITHOUT SODIUM

**Comment by thiagoabreutnb** [comment]
without sodium worrks but without it i cant use snow and water physics

**Comment by thiagoabreutnb** [comment]
wait
i can use it but  it will have laggy

**Comment by thiagoabreutnb** [comment]
send me a  fabric mod that is not sodium but it optmizes

**Comment by thiagoabreutnb** [comment]
like lithium

**Comment by thiagoabreutnb** [comment]
works now
