### ISSUE TITLE
Re upload Found...

### ISSUE THREAD

**Issue by VirtualGaming1** [haubna/PhysicsMod#362]
I have found a Re upload of this mode but pro version that no one need pay. @Haubna if you can DM me I will be able to send the link over to you.

File from the upload that I found:

physics-mod-pro-v43-forge-1.18.2.jar (THIS IS A TEXT NOT LINK)

It is on CurseForge and I have reported it to them as well.

**Comment by haubna** [comment]
Thanks, found it and reported it!
