### ISSUE TITLE
Menu element overlaps with others

### ISSUE THREAD

**Issue by semioniy** [haubna/PhysicsMod#363]
**Describe the bug**
Main menu element overlaps with others, and I can't find config to move the menu element / hide it.

**To Reproduce**
Install physics mod onto Better minecraft modpack (fabric).

**Screenshots**
![image](https://user-images.githubusercontent.com/21012972/170403364-5f69edaa-e918-4bd3-962b-39f77991403c.png)
Minecraft Version: 1.8.2
Physics Mod Version: 2.7.5

**Comment by haubna** [comment]
You can move the Master Volume and Music in the Client Tweaks config.

**Comment by semioniy** [comment]
Sure can, it would make far more sense to move physics settings to the bottom though.

**Comment by haubna** [comment]
It would make far more sense to keep Master Volume and Music in the Music & Sounds tab to be honest.

**Comment by semioniy** [comment]
Not really. You set up mod for your liking once and don't change it ever again. Sound on the other hand is something that is surroundings / speaker / headphones dependent and is probably used a bit more often than "effectively never again after the initial setup". That's only my opinion, of course.

**Comment by haubna** [comment]
Logically speaking "Master Volume and Music" is redundant since it already exists in the "Music & Sounds" tab (literally just 1 more click that won't kill your finger). Redundancy can be good when it comes to data storage but it is a bad practice in UI design. My choice is not based on personal preference but rather on UI design practices.

**Comment by semioniy** [comment]
Then how about a UX practice of giving users a choice instead of saying "here's what we deem right and if you don't agree, well tough luck, cause we know we're right". 
Anyway, this thing is most minor thing I could care about RN, just couldn't, and still can't agree with approach of giving the user one option, "cause it's the right one"...

**Comment by semioniy** [comment]
The mod is neat and I enjoy it, so good day do you, I'm out 😁
