### ISSUE TITLE
Add extra functionality for VR mods

### ISSUE THREAD

**Issue by DonFlymoor** [haubna/PhysicsMod#365]
**Add extra features so physics works better with VR**
It would be really cool to be able to throw items from your hand in VR with your arms velocity, to be able to interact with physics item with your hands, and to have mobs react to where you hit them (Fake mob ragdoll constrained to invisible mob's limbs? That would work well for decapitation, and would make all the animals feel more alive). Vivecraft and https://github.com/Sorenon/MCXR could be supported, although Vivecraft is more popular MCXR works on fabric.

Some other idea I had are opening chests with your hands with a moving lid, physics doors and trapdoors, and being able to hold onto items without putting them in your inventory.

**Comment by haubna** [comment]
Once I have a VR headset I will add support for it. Don't have enough room for it right now, sorry!

**Comment by DonFlymoor** [comment]
Sounds great! You could potentially use WMR dev, which simulates a headset on flatscreen.

**Comment by DonFlymoor** [comment]
Some more ideas: Stab sword into the ground, give joint constraints and spring physics to ragdolls to make them look even better, simulate mass of items using arm ik and block's toughness, gravity gloves and disabled radius pickup, physical interactions between held tools and blocks and hands and blocks, potions dumping physics liquid into your mouth, cauldron having splashy water, crafting tables with in world crafting, cracks and particles depending where you hit a block, actually throwing splash potions, food crumbling into pixels while eating, toss to place blocks. Physics could make Minecraft into an amazing VR game, instead of merely mediocre.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
