### ISSUE TITLE
The game crashes when running Physics Mod Pro V50 and indium

### ISSUE THREAD

**Issue by f4nem14s** [haubna/PhysicsMod#367]
The game crashes when running Physics Mod Pro V50 and indium

1) Run the game with Physics Mod Pro V50 and indium 1.0.2
2) The game crashes when creating or entering the world
3) Run the game with Physics Mod Pro V50 and indium 1.0.3
4) The game crashes on startup

Minecraft Version: 1.18.2
Physics Mod Version: 50

**Comment by haubna** [comment]
Update your Iris + Indium to the latest version
