### ISSUE TITLE
Physics Mod (physicsmod) has failed to load correctly - 1.16.5 Forge Server

### ISSUE THREAD

**Issue by Akrione** [haubna/PhysicsMod#37]
I'm getting a "_`java.lang.ClassNotFoundException: net.minecraft.client.renderer.IRenderTypeBuffer`_" error when I try to boot my 1.16.5 server, and says, "_Physics Mod has failed to load correctly_".

How can I troubleshoot this?

(Here's my crash log)
[crash-2021-02-10_21.24.05-fml.txt](https://github.com/haubna/PhysicsMod/files/5969232/crash-2021-02-10_21.24.05-fml.txt)

**Comment by WenXin20** [comment]
Hello, I got the same crash when using v1.3.3 and Forge v36.0.7. Version 1.3.1 did not crash the server.
[Crash Report](https://gist.github.com/WenXin20/1fbac5e8b88e1a0ba4511ef182151855)

**Comment by rafaelkai** [comment]
Same issue here

**Comment by haubna** [comment]
Mod is no longer maintained. Use older versions or fabric.
