### ISSUE TITLE
Not On Bedrock.

### ISSUE THREAD

**Issue by SedainyaTheHedgehog** [haubna/PhysicsMod#370]
Should Be On Bedrock. If it was that would be so awesome.

**Comment by InfernoDigital** [comment]
I agree! I don't know if it would ever make it over there, but I'd love to have physics on bedrock

**Comment by caoqt1** [comment]
While this would be cool, I don't see this coming any time soon, bedrock is coded in c++, not java, and this mod uses a port of PhysX for java, if we ever wanted support for bedrock, haubna would have to rewrite the entire mod.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
