### ISSUE TITLE
crash when clicking a button

### ISSUE THREAD

**Issue by Fefedu973** [haubna/PhysicsMod#371]
I use fancy menu to customize menus and there is a built in autoclicker to automatically click a button. when I connect to my server I have a message asking me to activate a resource pack so I activated the autoclicker on it but it crashes my game but it works again when I delete physics mod
[crash-2022-06-05_09.57.03-client.txt](https://github.com/haubna/PhysicsMod/files/8839560/crash-2022-06-05_09.57.03-client.txt)
[latest.log](https://github.com/haubna/PhysicsMod/files/8839561/latest.log)

Minecraft Version: 1.18.2
Physics Mod Version: pro v50

**Comment by haubna** [comment]
Fixed in 2.7.6 and Pro V51
