### ISSUE TITLE
Install fabric, version 0.52 or later [BUG]

### ISSUE THREAD

**Issue by THEVERYLOL30** [haubna/PhysicsMod#373]
**Describe the bug**
Tells me fabric version 0.52 or newer is required, but i cannot find the fabric version.

**To Reproduce**
Launch the game on th e fabric installation

**Screenshots**
![image](https://user-images.githubusercontent.com/86348485/172608801-7a160683-15ae-4c1d-9ae1-ca22352c3cca.png)

Minecraft Version: 1.19
Physics Mod Version: 2.8.0

**Comment by haubna** [comment]
It is talking about the Fabric API
