### ISSUE TITLE
Keep search contents on rule edit [REQUEST]

### ISSUE THREAD

**Issue by EthanRStokes** [haubna/PhysicsMod#374]
**A description of the requested feature**
A clear and concise description of what the request is.

When finishing editing a block rule, it should keep what was typed into the search box before editing the block
Same for editing other things.
This would make editing rules so much easier without having to re-type what you want every time.

**Comment by haubna** [comment]
Just added it and will be released in version 2.8.1, I will close this issue once it is available for download!

**Comment by haubna** [comment]
Released 2.8.1.
