### ISSUE TITLE
Entity corpses become black upon death (with shaders)

### ISSUE THREAD

**Issue by xx-underxcores-xx** [haubna/PhysicsMod#375]
**Describe the bug**
Entity corpses become black upon death while using shaders.

**To Reproduce**
Use newer Iris versions and Complementary shaders.

**Screenshots**
![2022-06-09_14 15 25](https://user-images.githubusercontent.com/107219743/172945894-349195fa-b1fc-4711-93a1-5d89e4b8df26.png)
![2022-06-09_14 15 56](https://user-images.githubusercontent.com/107219743/172945935-be164ee7-bb2c-4606-adc9-7dd2b89936a1.png)

Minecraft Version: 1.19
Physics Mod Version: 2.8.0 [Lite]

**Comment by haubna** [comment]
Not happening on my end. I am using the latest version (Iris 1.2.5 and Complementary 4.4). Do you have something like PBR enabled?
![2022-06-09_23 26 14](https://user-images.githubusercontent.com/7816894/172948285-0b0936ef-3de2-4cdc-906f-ae1088b62cf6.png)

**Comment by xx-underxcores-xx** [comment]
I don't think so? I went through shader settings and disabled each PBR/Normal Map option and nothing changed. It's either Iris, Complementary, or something in the Fabulously Optimized modpack (which I also doubt bc I went through and removed any entity-tweaking mods and still nothing changed).

**Comment by haubna** [comment]
I am using only Iris, Sodium and the complementary shaders (everything with default settings) and everything works fine. Try deleting your iris/shaderpack/sodium configs to reset them. It doesn't have to be an entity-tweaking mod that breaks this. Usually performance mods tend to break a lot of things.

**Comment by xx-underxcores-xx** [comment]
That's so strange. It's something in the bundled iris.properties file. I'll do some digging.

**Comment by xx-underxcores-xx** [comment]
Very odd. I'll consult the modpack devs, apologies. Have a good day.

**Comment by haubna** [comment]
Does it work with resetting the iris.properties file? Let me know if you figure out which setting causes that bug!

**Comment by xx-underxcores-xx** [comment]
So I tested each and every single mod I have, and it literally has to be Iris for some reason. They're perfectly visible without shaders on, but the moment I hit the Iris hotkey (which isn't attached to anything else, I've triple-checked) and shaders switch on, dark. I even switched between about 10 different in- and out-of-date shaders and they're black in every single one. I'm running on an intel mac however; any chance that could be the issue?

(Also I took down my comment stating that resetting iris.prop fixed it bc it didn't, all it did was disable shaders and I was too focused on the frogs to notice haha)

**Comment by haubna** [comment]
Could be mac related, not sure to be honest.

**Comment by enderprism** [comment]
I also have this issue and I am on Manjaro Linux with PolyMC launcher and Complementary Shaders 4.5 (latest version at the moment of writing). I have an AMD Ryzen 5 5600H and an AMD Radeon 5500. I use the Fabulously Optimized Modpack with some more mods. [Here is a Pastebin with all of my mods](https://pastebin.com/ehqi2isY). I am running in Minecraft 1.19 on Fabric. 
Physics Mod Version: 2.8.1 Lite

**Comment by haubna** [comment]
This might be fixed with version 2.8.2, let me know if it works now.

**Comment by RUTHINAS** [comment]
> This might be fixed with version 2.8.2, let me know if it works now.

Any chance to get the fix backported to 1.18.2?

**Comment by xx-underxcores-xx** [comment]
Sorry for not acknowledging sooner, the fix works perfectly!
