### ISSUE TITLE
Client Crash in Physics Mod with Storage Drawers

### ISSUE THREAD

**Issue by archonsd** [haubna/PhysicsMod#378]
Physics Mod:  **physics-mod-2.7.6-mc-1.18.2-forge.jar**
Storage Drawers:  **StorageDrawers-1.18.2-10.2.1.jar**
Forge:  **forge-1.18.2-40.1.47**

Crash when breaking empty 32-stack storage drawer:

```The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot read field "itemStackEntity" because the return value of "net.diebuddies.physics.PhysicsMod.getCurrentInstance()" is null
Exit Code: -1
```

Crash Report :  https://pastebin.com/bmHSaUkE

I was playing on a modded server of mine and it does not look like the server was impacted, only the client.

**Comment by archonsd** [comment]
FWIW, I can confirm it happens if you break a mostly full 2x2 storage drawer, also.

**Comment by haubna** [comment]
Should be fixed now.
