### ISSUE TITLE
request mod translation (PRO Version)

### ISSUE THREAD

**Issue by StarsShine11904** [haubna/PhysicsMod#379]
Sorry, but can you also support translation for the PRO version?

**Comment by haubna** [comment]
It is supported. There aren't any translations yet for any version except for english.

**Comment by StarsShine11904** [comment]
ok

**Comment by haubna** [comment]
Which language would you like to see in the future?

**Comment by StarsShine11904** [comment]
Traditional and Simplified Chinese

**Comment by StarsShine11904** [comment]
I want to try to translate this mod to make it more convenient for Chinese language players
Because only English is very inconvenient

**Comment by StarsShine11904** [comment]
By the way, I am not a PRO Version user, but I found the professional version on the Internet, but none of the versions I can find support translation

**Comment by StarsShine11904** [comment]
Although I am not a Pro Version user, I still hope to help translate this module

**Comment by StarsShine11904** [comment]
If you agree ...

**Comment by haubna** [comment]
Oh fuck off. Pirating stuff from a mod creator. Good job. Idiot.
