### ISSUE TITLE
Proportional destruction Particles

### ISSUE THREAD

**Issue by UltraBlackLinux** [haubna/PhysicsMod#38]
Hey, there,
there is a (1.12) mod that limits the destruction particles to the size of that block.
This is already kinda implemented, but, e.g. grass, seems to still be treated as a full block - like leaves:
https://user-images.githubusercontent.com/62404294/107848098-275ec400-6df1-11eb-828f-d9826177200a.mp4
Are you able to fix this?
Thank you!

**Comment by haubna** [comment]
You clearly have a lot of other stuff installed. Try it without data-packs, resource-packs and other mods. It works on my end. Use the latest version as well.
