### ISSUE TITLE
Entities turn transparent [BUG]

### ISSUE THREAD

**Issue by italon** [haubna/PhysicsMod#381]
Whenever killing a mob they turn transparent-like and flicker no matter which style of physics is used, no matter which entity is killed. Whenever destroying blocks the same thing happens.

**To Reproduce**
Kill entities. Destroy blocks.

**Screenshots**
![2022-06-18_12 18 32](https://user-images.githubusercontent.com/5409817/174449563-0774b1d2-8a22-406e-9deb-0ea68ba680fe.png)
![2022-06-18_12 18 40](https://user-images.githubusercontent.com/5409817/174449566-6276f31c-48b1-4fc9-8448-f17b909dbd18.png)

Minecraft Version: 1.19
Physics Mod Version: 2.8.1

**Side Note**
When I first started using this mod it worked fine but I think I tweaked some settings that might have caused this to happen. I've turned off any other kind of mod and resource pack to test but the issue remains. Is there a way to reset this mod to default settings? Deleting and reinstalling the mod does not reset anything.

Cheers.

**Comment by haubna** [comment]
PBR is not supported. Disable it in the shader settings.

**Comment by italon** [comment]
Wow, very quick and accurate response. Disabling 'Advanced Materials' while using BSL Shaders fixed this issue. Thank you!!
