### ISSUE TITLE
Piston Head Particles when off.

### ISSUE THREAD

**Issue by kicekkic** [haubna/PhysicsMod#383]
**Describe the bug**
So Basically when you power a piston and then turn it off, head (the part that moved) will make particles like it was broke.

**To Reproduce**
1. Place a piston
2. Place a lever or any redstone power source near it.
3. Start spamming the piston.

**Screenshots**
![2022-06-21_16 29 59](https://user-images.githubusercontent.com/80385701/174825189-73320472-a7fd-495e-9f62-b3a0adde11ae.png)

Minecraft Version: 1.16.5
Physics Mod Version: 2.6.7

**Comment by haubna** [comment]
Old versions are not supported and will receive no bugfixes.
