### ISSUE TITLE
Customisable Collapse Feature

### ISSUE THREAD

**Issue by Arachnosuchus** [haubna/PhysicsMod#385]
It's a bit annoying how every time I remove a wrongly placed block, my entire ceiling collapses. I'd like to keep Collapse for trees but maybe disable it for most other blocks. It would be nice if you could implement customisation options for the Collapse feature that allows to turn it off or set a custom distance for each block individually. Some implementation ideas:

1) Default values for block collapsing treshold based roughly on material toughness. (Toggleable.)

2) Toggleable Collapse on or off for every block. (Custom tresholds overwriting the default value.)

3) Each block has a structural integrity rating à la _Conan Exiles_ or _7 Days to Die_, represented by an integer. This integer decreases as the block's distance to the nearest "stable" block increases (a block that is connected to the floor, i. e. pillars or walls). A block will only collapse once its structural integrity reaches 0. That way parts of the ceiling that are connected to the walls closely enough won't collapse unless the wall is removed. (Individual collapse tresholds still customisable.)

**Comment by RufusVulpecula** [comment]
I really want something like this. There used to be mod that enabled collapse tat is based on the type of block. It would make mining a different experience, with the need to use support beams and cave-ins.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
