### ISSUE TITLE
Cant open Fabric

### ISSUE THREAD

**Issue by defautluser0** [haubna/PhysicsMod#387]
Fabric says it needs fabric 0.51 but there is no

**Screenshots**
![Fabric Loader 0 14 8 29_06_2022 14_46_30](https://user-images.githubusercontent.com/108409246/176440814-4df10a5d-040c-4adf-9dd7-3f3110ccb085.png)
![Instalador de Fabric 29_06_2022 14_46_44](https://user-images.githubusercontent.com/108409246/176440815-b613a562-d161-44bd-b742-c95cf29cdcc6.png)
![Instalador de Fabric 29_06_2022 14_46_54](https://user-images.githubusercontent.com/108409246/176440816-6cee1ed3-2c1d-4219-8f60-dd92cd69e565.png)

Minecraft Version: 1.18.2
Physics Mod Version: Pro

**Comment by haubna** [comment]
Google Fabric API and use it
