### ISSUE TITLE
[Forge] Client freezes when teleporting between dimensions with mob physics enabled

### ISSUE THREAD

**Issue by GrantGryczan** [haubna/PhysicsMod#39]
When I teleport between dimensions by any means (e.g. using `/execute in ... run tp ...` or another mod which allows for teleportation between dimensions), my client is unable to move or interact with anything until I relog. All I can do is look around. Everyone on the server is having this issue, and I have tested it in single player as well. It is consistently reproducible.

This issue occurs exclusively in survival and creative mode, not spectator, and no matter which two dimensions are being teleported between, as long as they are different dimensions.

Removing either Physics Mod or Immersive Portals fixes it. Setting mob physics to OFF before teleporting also fixes it. The only exception is when walking through an immersive portal; this is the only form of interdimensional teleportation which does not cause a client freeze.

**Comment by haubna** [comment]
Not a supported mod.
