### ISSUE TITLE
Physics mod general failure to load with forge 1.19-41.0.64 [BUG]

### ISSUE THREAD

**Issue by Bekos-von-Nimmerland** [haubna/PhysicsMod#390]
**Describe the bug**
Mod fails to load with new forge version installed.

**To Reproduce**
Install Forge 1.19-41.0.64.
Install Physics 2.7.6 (2.8.0 file from curseforge and/or 2.8.1 file from site).
Get crash.

**Log**
[crash-2022-07-08_13.36.52-client.txt](https://github.com/haubna/PhysicsMod/files/9070003/crash-2022-07-08_13.36.52-client.txt)

Minecraft Version: <1.19>
Forge Version: <41.0.64>
Physics Mod Version: <2.7.6> (<2.8.0>); <2.8.1>.

**Comment by haubna** [comment]
Thanks for the quick report, I already fixed it and will release it in about 2 hours (have to go shopping right now).

**Comment by haubna** [comment]
New versions with the fix are online now (I haven't changed the version number, just redownload 2.7.6 from curseforge or 2.8.1 from my website).
