### ISSUE TITLE
Unable to turn off smoke [BUG]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#394]
**Describe the bug**
I'm trying to crystal pvp with end crystals and each time I break a crystal there's a heap of smoke and I cant see.

**To Reproduce**
Turn off smoke physics in physics mod and end crystals will still produce physics smoke.

Minecraft Version: 1.19
Physics Mod Version: v54 Fabric

**Comment by haubna** [comment]
You're completely right, my bad! Will be fixed in V55! I will let you know when I release it :)
In the mean time you can use V53 to remove the smoke update.

**Comment by ghost** [comment]
sweet as thank you heaps for the quick reply and i will use the old one for now thanks :) good work btw

**Comment by haubna** [comment]
Fixed
