### ISSUE TITLE
game crashes whenever i try to join a world

### ISSUE THREAD

**Issue by buIIiestuff** [haubna/PhysicsMod#395]
the game works fine in the menu everything was fine, but when i create a world and join it the game crashes upon "joining world"
i didnt messed around with the settings
there were no other mods installed just the physics mod
I use mac, macOS high sierria 10.13.6 and the app curseforge to launch the modded profile
Minecraft Version: 1.19
Physics Mod Version: 2.8.1
the java crash log:
[java_2022-07-20-221538_MacBook-Pro.log](https://github.com/haubna/PhysicsMod/files/9155768/java_2022-07-20-221538_MacBook-Pro.log)

**Comment by haubna** [comment]
If you have an ARM CPU you are out of luck. Otherwise you could try to update your OS. The libraries I am using where built for Mac OS X 11.5.

**Comment by buIIiestuff** [comment]
i have intel cpu, i will update my os. Thank you!
