### ISSUE TITLE
realistic grass with physics [REQUEST]

### ISSUE THREAD

**Issue by demonwolfie** [haubna/PhysicsMod#396]
hey I think it would be a cool and fun feature to add is realistic grass with physics
across the whole world can you plz add this

**Comment by DonFlymoor** [comment]
I think that's a feature in the pro version, vine physics works on grass as well.

**Comment by finogreofdoom** [comment]
Haubna can't add this because grass hitbox is too small compared to tall grass where it has a larger hitbox

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
