### ISSUE TITLE
Make smoke and cloth toggable without pro [REQUEST]

### ISSUE THREAD

**Issue by PepeBigotes** [haubna/PhysicsMod#398]
Making an option to disable smoke and cloth physics beacuse a lot of people are suffering from performance issues and would like to disable them. Just like the item settings.

**Comment by haubna** [comment]
First things first "a lot of people are suffering" where did you make your questionaire to get this kind of information?
Secondly: next time before opening a issue on github look in the settings menu first.

**Comment by haubna** [comment]
You are right creepers and tnt indeed had smoke physics. Please redownload version 2.8.2, it should work now. What exactly do you mean with cloth physics?

**Comment by PepeBigotes** [comment]
> You are right creepers and tnt indeed had smoke physics. Please redownload version 2.8.2, it should work now. What exactly do you mean with cloth physics? 
I apologize for the exagerations, I though that the cloth setting is on whithout pro just like the smoke, but i didnt see any issues with the it at the moment. The smoke is now fixed, thanks.
