### ISSUE TITLE
pro features in free version  

### ISSUE THREAD

**Issue by rinkeChillow** [haubna/PhysicsMod#399]
smoke physics in the lite version [BUG]
when a creeper or tnt there is the new smoke physics that cant be turned off and can be annoying due to lag 

the steps are unknown for now
 happened by accident to a friend of mine  

no screenshots
screenshots not available yet

Minecraft Version: <1.19.0>
Physics Mod Version: <Fabric - Physics Mod 2.8.2>

**Comment by haubna** [comment]
You are right creepers and tnt indeed had smoke physics. Please redownload version 2.8.2, it should work now.
