### ISSUE TITLE
Crashing when you walk (1.17.1 Only)

### ISSUE THREAD

**Issue by AViewFromTheTop** [haubna/PhysicsMod#4]
Every time I try to walk (in both singleplayer and on servers,) the game crashes. I have no mods enabled other than physics and the Fabric API.
Log: https://paste.ee/p/9qERL

**Comment by haubna** [comment]
The mod currently only supports version 1.17. They changed a packet in the Minecraft protocol which causes this crash. Will be fixed with an official 1.17.1 release in the next days :)

**Comment by AViewFromTheTop** [comment]
Thank you! Must apologize I didn't know the update didn't support 1.17.1 yet. Hope all goes well!
