### ISSUE TITLE
Sildur's Vibrant Shaders and PhysicsMod breaks Light-emitting Blocks

### ISSUE THREAD

**Issue by BreezyBoi** [haubna/PhysicsMod#4]
Combining any of the Sildur's Vibrant Shaders (or the Enhanced Default) with the PhysicsMod makes many light-emitting blocks invisible.
[https://youtu.be/qEK6HxM7poU](https://youtu.be/qEK6HxM7poU)

**Comment by BreezyBoi** [comment]
I just realised you fixed this recently in the new uploads of PhysicsMod. You're updating/fixing really fast, nice work

**Comment by haubna** [comment]
Thanks :)
