### ISSUE TITLE
Item "Physics" on Fabric MC 1.16?

### ISSUE THREAD

**Issue by mihannnik** [haubna/PhysicsMod#40]
Can you add new fake item physics feature for old version of mod? The server I'm playing on won't be able to upgrade and i cant use this.

**Comment by QAQlinmiao** [comment]
He said he isn't going to port the mod to older versions.
https://user-images.githubusercontent.com/79011616/125273789-49466f00-e2db-11eb-954a-5f6e2d15bcdb.PNG
