### ISSUE TITLE
Physics mod pro feature (not in minecraft)

### ISSUE THREAD

**Issue by githubminecrafter** [haubna/PhysicsMod#400]
So, if you want the pro version of physics mod you have to pay money but i suggest to have a free trial of pro version physics mod. Then people can enjoy it at least for a few days.

**Comment by DonFlymoor** [comment]
Now there's an idea. The only con I can see is that enterprising people will modify the mod to make it have a permanent free trial, and others will redistribute that with a virus.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
