### ISSUE TITLE
Spectator can interact with physic objects [BUG]

### ISSUE THREAD

**Issue by procrastinatingFeroxz** [haubna/PhysicsMod#403]
If a spectator Interacts with physic objects, they will be able to push around the blocks and debris that they fly into

Minecraft Version: 1.19
Physics Mod Version: 2.7.6 (Fabric)

**Comment by haubna** [comment]
Are you sure that it is a spectator? Or is the player just invisible? Invisible entities will keep interacting with debris (by design choice).

**Comment by procrastinatingFeroxz** [comment]
Spectator

**Comment by haubna** [comment]
Ok, will fix it in the next release! :)

**Comment by procrastinatingFeroxz** [comment]
ok :)

**Comment by haubna** [comment]
I will keep the issue open and will notify you once it is fixed!

**Comment by procrastinatingFeroxz** [comment]
ok

**Comment by haubna** [comment]
Fixed in 2.8.4
