### ISSUE TITLE
Summoning will result in a false death of a mob [BUG]

### ISSUE THREAD

**Issue by procrastinatingFeroxz** [haubna/PhysicsMod#404]
Summoning the warden, illusioner, cave spider, blaze, drowned and the vindicator (and some other mobs) will result in the mods death animation

To reproduce this bug, find mobs that may have been forgotten, like the illusioner and the cave spider and spawn them via  the summon command

Minecraft Version: 1.19
Physics Mod Version: 2.7.6 (Fabric)

Note: I only have been able to try out a view mobs.

**Comment by haubna** [comment]
Are you in peaceful mode?

**Comment by procrastinatingFeroxz** [comment]
I was, sorry for the inconvenience :)
