### ISSUE TITLE
A few smoke suggestions

### ISSUE THREAD

**Issue by odvigajlo** [haubna/PhysicsMod#406]
1. Multi-Layered Wind. what if wind had several layers and each one will have different wind directions, intensity?

2. Vorticity. Smoke fells to flat right now so how about adding vorticity? so smoke will swirl ect.

3. Mushroom Clouds. Some energized release of smoke should make mushroom cloud for instance after exploding tnt

4. Buoyancy?. Maybe smoke should lose it buoyancy at height, or temperatures. For instance: cold temperatures, big height will cause smoke too fall. this would be cool because smoke would form anvil clouds in sky

**Comment by finogreofdoom** [comment]
I agree

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
