### ISSUE TITLE
[Forge] Config file generates at `.minecraft/configs/physics_config.json` instead of `.minecraft/config/physics-client.toml`

### ISSUE THREAD

**Issue by GrantGryczan** [haubna/PhysicsMod#41]
Forge configs go in the `config` folder, without an `s`. But this mod creates a `configs` folder with just its config in it, and it is in JSON format rather than the standard TOML format. This applies to both `physics_config.json` and `physics_server_config.json`. This was not an issue in earlier versions.

**Comment by haubna** [comment]
I removed my forge configs and made it the same as in fabric. Easier to develop both versions at the same time.
