### ISSUE TITLE
1.17.1 Forge

### ISSUE THREAD

**Issue by Litttlefish** [haubna/PhysicsMod#41]
The 1.17.1 Forge is out now.

Would you port it to forge?

**Comment by IMS212** [comment]
not the dev, but forge doesn't support mixins on 1.17.1, which this mod uses a ton of. so forge first needs to support mixin

**Comment by haubna** [comment]
As mentioned by IMS212, I need the mixin support for this mod to work.

**Comment by InteJason** [comment]
another question: will 2.0 be available in forge 1.16.5? The existing version kills fps :/

**Comment by haubna** [comment]
No sorry.

InteJason ***@***.***> schrieb am Fr. 20. Aug. 2021 um 15:34:

**Comment by IMS212** [comment]
Mixins now exist for Forge 1.17, though in a less than ideal state. (pretty much unsupported)

**Comment by haubna** [comment]
What do you mean by unsupported?

IMS212 ***@***.***> schrieb am Mo. 13. Sep. 2021 um 20:08:

**Comment by IMS212** [comment]
The forge team doesn't encourage or support the use of them almost at all, but it should work.

**Comment by haubna** [comment]
That's dumb.

IMS212 ***@***.***> schrieb am Mo. 13. Sep. 2021 um 20:30:

**Comment by haubna** [comment]
Ported it to Forge! Have fun :P
