### ISSUE TITLE
One time purchase [REQUEST]

### ISSUE THREAD

**Issue by DonFlymoor** [haubna/PhysicsMod#410]
**A description of the requested feature**
I would love to have the pro version of this amazing mod, as it really enhances my Minecraft experience, but I can't afford a $10 per month price tag. I understand why you have the monthly subscription - you deserve the coffee - but I also don't want to spend $10 for only one version without updates. Perhaps there could be another version that gets the fancy physics updated, say, every 3 months, but is a one time $15 purchase.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
