### ISSUE TITLE
Pixelized Destruction [REQUEST]

### ISSUE THREAD

**Issue by DonFlymoor** [haubna/PhysicsMod#411]
**A description of the requested feature**
Nothing much, just a way to shatter blocks into custom sized pixels (2x2,  4x4, 8x8, 16x16, ect.) like the physics particles. A balance between voxel anesthetics and cell fractures. Also for mobs. 

Potentially could support custom "crumbles" via particle physics, like bricks blocks becoming free bricks in mortar powder (via colors to support texture packs?) , honey pixels sticking to each other, glass pixels randomly sticking to each other glass pixel and only being one pixel thick, wood splintering, stone cobbling, and so on. Unashamedly inspired by teardown's physics, the practical interaction physics would admittedly be difficult to make.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
