### ISSUE TITLE
Even more realistic item physics [REQUEST]

### ISSUE THREAD

**Issue by DonFlymoor** [haubna/PhysicsMod#412]
**A description of the requested feature**
While items have perfect physics, blocks clip oddly through the ground. It would look better if they could act like cubes (with togglable stacking?), but might be more performance intensive. Also, putting a custom spin with a customizable random deviant might feel more like throwing items as opposed to completely random rotations. Perhaps you add custom spins to each item, so you could do things like skip stones across a river, or hurl swords at the ground.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
