### ISSUE TITLE
Surface Level Simple Water Physics [REQUEST]

### ISSUE THREAD

**Issue by CaramelTurbine** [haubna/PhysicsMod#415]
The water physics the mod uses at the moment are good, but they dont scale well so its not designed to be used for large bodies of water. Plus, its a physics system thats not tied to block positions, so you'd obviously get differences between the real water and the sim water. 

A solution for this is to use surface physics, similar to many fluid sim web experiments and AAA games. By either offsetting the block vertex positions (although that would require a high resolution mesh) or by changing the normal on the top face of water blocks, you could give the illusion of waves that only modify the surface of the water. I beleive its called "Heightfield water simulation".
Example: [WebGL Water](https://madebyevan.com/webgl-water/)
[Voxlementary](https://github.com/gri573/voxlementary) Shaders do something similar with its "Interactive Water" feature.

Because it modifies the water normals or vertex positions (maybe it could overwrite shader water normals somehow idk), it should work with shaders the same way the existing physics mod fluid sims do. This would make a cheap, efficient and still good looking alternative to the current expensive sims that cant be used for oceans or even lakes. These surface level fluids could simulate water ripples from rain, items, mobs, players and other physics objects interacting with it, have sim resolution options and only be simulated near the player to reduce lag.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
