### ISSUE TITLE
[BUG] Crash while killing geckolib entity. 

### ISSUE THREAD

**Issue by murao-kun** [haubna/PhysicsMod#417]
**Describe the bug**
Game crashes when you kill geckolib entity.

**To Reproduce**
Download Naturalist mod.
Download GeckoLib.
Create world.
Kill any Naturalist creature.

**Crash Report**
[crash-2022-08-03_17.12.52-client.txt](https://github.com/haubna/PhysicsMod/files/9252244/crash-2022-08-03_17.12.52-client.txt)

Minecraft Version: 1.19.1 FORGE
Physics Mod Version: 2.8.4

**Comment by haubna** [comment]
Bug is caused by SnailRenderer from Naturalist mod. Please report the issue to them. It says that there is a missing method. Also your Physics Mod version is way out of date. You are not using 2.8.4. You are using 2.7.6.

**Comment by haubna** [comment]
Update: I just tried it on Fabric, everything works fine there. It crashes on Forge. So the problem must be Forge related on their end.
