### ISSUE TITLE
Gameplay video containing smoke is weird [BUG]

### ISSUE THREAD

**Issue by Touch-Night** [haubna/PhysicsMod#418]
**Describe the bug**
Video containing smoke will looks different in full screen mode and half screen mode

**To Reproduce**
I don't know

**Screenshots**
![Screenshot_20220805_094727](https://user-images.githubusercontent.com/102669562/182984619-f5811e80-634b-4da2-a014-aba8b986ac39.jpg)
![Screenshot_20220805_094741](https://user-images.githubusercontent.com/102669562/182984632-598a4f14-1bfd-4c61-ae69-872823fa9d53.jpg)

Minecraft Version: Fabric 1.19
Physics Mod Version: 2.7.6

**Comment by haubna** [comment]
That's just how it works. Not a bug.

**Comment by Touch-Night** [comment]
But how?

**Comment by haubna** [comment]
I won't explain the technology, sorry.
