### ISSUE TITLE
Is there any way to disable the support physics[REQUEST]

### ISSUE THREAD

**Issue by Health1nspector** [haubna/PhysicsMod#421]
Basically you know when you destroy a block that is supporting a big platform, how that platform breaks? Is there anyway to fix it???

**Comment by haubna** [comment]
Physics Settings > Server/Collapse Settings

**Comment by Health1nspector** [comment]
> Physics Settings > Server/Collapse Settings

THANK YOU SO MUCH I DIDNT EVEN KNOW THERE WAS A PHYSICS SETTING!!
