### ISSUE TITLE
A "randomize physics" option.

### ISSUE THREAD

**Issue by xelotex** [haubna/PhysicsMod#422]
a option to randomize the animation of the block and mob physics, with high customizable options to configure, like filtering options to randomize ONLY between the selected animations and not just all of them.

you know, sometimes you will get ragdolls, other times fractured physics and so on... hope i had explain my self clearly.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
