### ISSUE TITLE
Entities play death effect when despawning (even without PVP server compatibility) [BUG] [FABRIC]

### ISSUE THREAD

**Issue by ridiche34** [haubna/PhysicsMod#430]
**Describe the bug**
When using a datapack to teleport an entity which can despawn very far away from the player, instead of just disappearing, it plays the death effect I have set, instead of simply disappearing, I do not have PVP server compatibility turned on, I do not belive this is intended behaviour, as in vanilla minecraft, when mobs die, they fall on their side, but when I run the exact same datapack, they just disappear.
I do have some client-side mods installed, but the problem seems unrelated

**To Reproduce**
I tried this on a server. To reproduce, make a datapack that teleports mobs away and install it on the server. Set mob physics to ragdoll and PVP server compatibility off. When the datapack's code runs, the mob ragdolls.

Minecraft Version: 1.19
Physics Mod Version: 58 (physics-mod-pro-v58-fabric-1.19.jar)

**Comment by CaramelTurbine** [comment]
Just... turn on PVP server Compatibility?

**Comment by haubna** [comment]
Should be fixed by now.
