### ISSUE TITLE
Block entity renderer crash when picking up a Totem of Preserving from the Charm mod

### ISSUE THREAD

**Issue by kingarthur0975** [haubna/PhysicsMod#433]
When I die and retrieve my items while playing with this mod and Charm, the game crashes with the exit message:

The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot read field "itemStackEntity" because the return value of "net.diebuddies.physics.PhysicsMod.getCurrentInstance()" is null
Exit Code: -1

Minecraft Version: 1.19.0
Physics Mod Version: 2.7.6

**Comment by haubna** [comment]
Update to the latest version from my website.
