### ISSUE TITLE
[Crash] Medieval weapons projectile crash on collision 

### ISSUE THREAD

**Issue by CasualJeremy** [haubna/PhysicsMod#434]
When the Medieval Weapons mod is installed, throwing a javelin crashes the game. 

https://gist.github.com/CasualJeremy/f1801239892b2057cc434f539338a19a

I put the error into the Medieval Weapons issues GitHub but they believe it is happening from this end. 

"Looks like better physics tries to cast the javelin entity to a living entity with a mixin."

**Comment by haubna** [comment]
Please update to Physics Mod 2.8.7, I am not sure if this problem already got solved. In case it persists please post a crash log with the new version. Thanks in advance!

**Comment by CasualJeremy** [comment]
https://gist.github.com/CasualJeremy/c6a76396cadf7a0187139dd96c1e96e2

I was able to kill a zombie villager without issue but I threw a javelin at a cow and it happened again.

**Comment by haubna** [comment]
I can't reproduce this error with only Medieval Weapons and Phyiscs Mod installed. Are you sure that my mod causes this crash?

**Comment by CasualJeremy** [comment]
You're right, I installed the two mod and it worked fine... Must be another mod then. Sorry about that!
