### ISSUE TITLE
Cloth physics on cape crash with Custom Player Models mod

### ISSUE THREAD

**Issue by Marsephel** [haubna/PhysicsMod#435]
When cloth physics is enabled on capes while running the Custom Player Models mod, frequent crashes will occur. Turning off cloth physics prevents crashes. 

Enable a custom model in the CPM mod and have a cape on with cloth physics enabled. Afer moving around enough a crash will eventually occur. 

Minecraft Version: 1.19.2
Physics Mod Version: Pro V65 1.19

![crash](https://user-images.githubusercontent.com/111594291/185706512-b354e9d6-8c92-438d-a9d4-fe47d92b2554.png)
[latest.log](https://github.com/haubna/PhysicsMod/files/9385415/latest.log)

**Comment by Marsephel** [comment]
Label should be compatibility, cannot figure out how to change label.

**Comment by haubna** [comment]
I will need a proper crash log to fix this issue. Thanks in advance!

**Comment by Marsephel** [comment]
> I will need a proper crash log to fix this issue. Thanks in advance!

Is the latest.log I attached not the log you need? If so please let me know how to get the correct one to you

**Comment by haubna** [comment]
The proper file can be found within the "crash-reports" folder and will be called "crash-thedate-client.txt"

**Comment by Marsephel** [comment]
> The proper file can be found within the "crash-reports" folder and will be called "crash-thedate-client.txt"
[crash-2022-08-20_18.44.51-client.txt](https://github.com/haubna/PhysicsMod/files/9388099/crash-2022-08-20_18.44.51-client.txt)

Here you go,

**Comment by haubna** [comment]
Thank you very much. It will be fixed in the next release!

**Comment by Marsephel** [comment]
Awesome, thanks for the replies!

**Comment by haubna** [comment]
Should be fixed with 2.8.9 :)

**Comment by Marsephel** [comment]
Awesome, thank you!
