### ISSUE TITLE
Weird with shaders

### ISSUE THREAD

**Issue by pz3rk** [haubna/PhysicsMod#436]
when I use shaders with this mod specifically nostalgia shaders the parts of blocks and mobs turn invisible with a line of texture.

just load up the mod with nostalgia or BSL shaders it should do it

**Screenshots**

![Desktop Screenshot 2022 08 21 - 19 13 13 75](https://user-images.githubusercontent.com/111711175/185815116-65e92929-944f-4046-b14c-bef186008faf.png)

![Desktop Screenshot 2022 08 21 - 19 13 34 84](https://user-images.githubusercontent.com/111711175/185815119-47b2694d-34dd-413c-a652-ec6e4818d96f.png)

![Desktop Screenshot 2022 08 21 - 19 14 04 07](https://user-images.githubusercontent.com/111711175/185815124-6c416b64-a388-4c1a-81ac-9eb5e7f67918.png)

![Desktop Screenshot 2022 08 21 - 19 14 29 87](https://user-images.githubusercontent.com/111711175/185815128-4d6c126b-0d8b-4855-bc49-7693078f8e2c.png)

![Desktop Screenshot 2022 08 21 - 19 19 48 96](https://user-images.githubusercontent.com/111711175/185815133-e62a9d97-cac5-4caa-9dd9-8b9118adb66a.png)

if those don't work then https://www.mediafire.com/file/cobstdtvc7k52ye/New+folder.zip/file

Minecraft Version: Java 1.19.2
Physics Mod Version: Latest as of Aug 21 2022

**Comment by haubna** [comment]
You are trying to use PBR textures without the proper Iris PBR build.
