### ISSUE TITLE
Smoke renders in vertical lines

### ISSUE THREAD

**Issue by niknal357** [haubna/PhysicsMod#437]
**Describe the bug**
When smoke is in front of blocks, it renders in lines, and not as on the website/videos I watched of it.

**To Reproduce**
I just lit a fire.
GPU: MSI Ventus 2x RTX3060

idk if important:
CPU: i9-9900KF (3.6 GHz)
OS: Windows 11 Pro Build 22622.575 (64 bit)

**Screenshots**
![2022-08-23_08 28 03](https://user-images.githubusercontent.com/46793548/186086939-b8d906bf-61f0-4907-ba39-597b5913c9bb.png)
![2022-08-23_15 57 43](https://user-images.githubusercontent.com/46793548/186177528-5be155cf-97cd-4dc5-b758-6d85fb2284b4.png)

Minecraft Version: 1.19
Physics Mod Version: 72

**Comment by haubna** [comment]
Update your Nvidia drivers, you probably have the one installed that causes all sorts of visual issues.

**Comment by DarianLStephens** [comment]
I'm having a very similar issue here. Just updated my NVidia drivers, but the problem remains.
Interestingly, the smoke is perfectly visible against the sky, but not any blocks.
