### ISSUE TITLE
Choose which blocks will collapse in Server settings [REQUEST]

### ISSUE THREAD

**Issue by finogreofdoom** [haubna/PhysicsMod#438]
**A description of the requested feature**

This will help a lot with breaking trees and fixing houses.

Eg. You want to break the oak planks in your house so you can replace them, well with this change it will be easier, because without this if you wanted to replace the oak planks you would have to break them all by hand/an axe. But with this change, you can pick only oak planks to collapse and then just mine one and they will all break.

**Comment by finogreofdoom** [comment]
![147882559-87ebf4b6-6241-4da6-91f0-bf4f096148af](https://user-images.githubusercontent.com/95974117/186741849-9e3555bd-eb77-4fd3-a6e5-720c798da40b.png)
Eg. There will be a customize button in the left corner

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
