### ISSUE TITLE
Fishing Line Physics and Leash Physics doesn't work [BUG]

### ISSUE THREAD

**Issue by xiaofan7520** [haubna/PhysicsMod#439]
Fishing Line Physics and Leash Physics doesn't work. Nothing is displayed.

**To Reproduce**
Just open it.→_→

<img width="1310" alt="屏幕截图 2022-08-28 121400" src="https://user-images.githubusercontent.com/91411649/187057136-577b8fd8-46fa-4230-baa8-56b9d5222e81.png">

Minecraft Version: <1.19.1>
Physics Mod Version: <physics-mod-pro-v75-fabric-1.19>
Other mod: only "fabric-api-0.58.5+1.19.1"

**Comment by haubna** [comment]
Fixed, please redownload V75! :)
