### ISSUE TITLE
Instant-Crash when breaking liquid-physics based blocks

### ISSUE THREAD

**Issue by EHE2** [haubna/PhysicsMod#440]
With Water phyiscs enabled I experience an immediate crash when breaking enchanting table or melon instead of expected physics-based liquid.

Tested with and without shaders/resource packs
[crash-2022-08-29_02.54.20-client.txt](https://github.com/haubna/PhysicsMod/files/9442246/crash-2022-08-29_02.54.20-client.txt)

**Comment by haubna** [comment]
Whoops, fixing it right now. Give me a couple of minutes!

**Comment by haubna** [comment]
New versions with the fix are online!
