### ISSUE TITLE
Dynamic blocks and normal blocks appearing at the same time 1.16.5 [BUG]

### ISSUE THREAD

**Issue by richardfrisk** [haubna/PhysicsMod#441]
**Describe the bug**
Dynamic blocks and normal blocks appearing at the same time when playing with the Create: Above and Beyond modpack

**To Reproduce**
*Install Create: Above and beyond
*Add Rubidium, Oculus and (of course) Physics mod for 1.16.5 (v36b) to the mod folder
*Start the game 
*Create a world, place a door and open it (the same happens with kelp, vine, etc.).

**Screenshots**
![image](https://user-images.githubusercontent.com/112427719/187280613-6fa621f6-eeb1-4b5f-871c-7f682310b7b4.png)

**Modlist**
- Create: above and beyond mods https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond
- Rubidium
- Oculus
- Physics mod for 1.16.5 (v36b)

Minecraft Version: 1.16.5
Physics Mod Version: v36b
[](url)

**Comment by richardfrisk** [comment]
**LOGS**
[2022-08-28-2.log.gz](https://github.com/haubna/PhysicsMod/files/9447457/2022-08-28-2.log.gz)
[latest.log](https://github.com/hau
[startup.txt](https://github.com/haubna/PhysicsMod/files/9447461/startup.txt)
bna/PhysicsMod/files/9447460/latest.log)

**Comment by haubna** [comment]
Probably due to Oculus and Rubidium. Old versions of the game no longer receive updates.
