### ISSUE TITLE
One button - all setting makes default [REQUEST x3]

### ISSUE THREAD

**Issue by 360WRACKER** [haubna/PhysicsMod#443]
Hello Mr haubna. This mod is making my child dream real.
 When i firs start the game I was stunned how grate it is, I also was messing with settings to turn off the collapse feature because it's not "vanilla friendly", and also I was trying another settings with mind that I can make every setting at default at any time, but it is not how its work.
 Maybe since I'm using Fabric version just reinstalling the physics-mod-2.8.10-mc-1.19-fabric and ForgeConfigAPIPort-v4.2.4-1.19.2-Fabric is not the solution, because save of the settings is in some different file.

Although big shoutout to F6 mode that same as old google Easter egg. 

So, my request is:
1. One button that makes all settings at default
2. Collapsing settings is turned off at default (or warning to make backup setting of the world before first star)
3. And for grater immersion, collapsing - affects tools strength because it's kinda op (same as FallingTree mod for example)

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
