### ISSUE TITLE
Mac Minecraft - Physics Mod outright crashes game [BUG]

### ISSUE THREAD

**Issue by MattRidge** [haubna/PhysicsMod#444]
**Describe the bug**
Starting the game up using Fabric on a Mac, and the game outright crashes. 

**To Reproduce**
Start a Mac game up with the lastest Fabric installed. 

**Screenshots**
![Screen Shot 2022-09-01 at 6 50 49 PM](https://user-images.githubusercontent.com/13275219/188025697-ade6c252-e51b-4ae1-b5a3-32fda9d1dfa0.png)

Minecraft Version: <1.19.2>
Physics Mod Version: <physics-mod-2.8.10-mc-1.19-fabric>

**Comment by ShoddyOfTheShoes** [comment]
Same issue here. Heres my crash log, hope it helps! [https://pastebin.com/Cjwed3qb](https://pastebin.com/Cjwed3qb)

**Comment by haubna** [comment]
You need at least MacOS 11.5 and even then it might not work.

**Comment by haubna** [comment]
Just updated MacOS natives with 2.8.11. Please let me know if it changes anything.

**Comment by ShoddyOfTheShoes** [comment]
Im using MacOS version 12.5.1 (Monterey) With physics mod 2.8.13 (free ver.) and Fabric API ver. 0.60.0 Same crash. Heres the crash log. [https://pastebin.com/Zf0zdrLs](https://pastebin.com/Zf0zdrLs)
Are you testing on an Intel mac? I am on the M1/silicon chip.

Edit: Sorry it took so long to respond!

**Comment by ShoddyOfTheShoes** [comment]
I took a quick look in the crash log, is it possible that this is the issue? "Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS" I don't believe there are any native PhysX binaries for ARM based chips. However it might be possible to compile one.

Edit: Found this! [https://github.com/NVIDIAGameWorks/PhysX/issues/472](https://github.com/NVIDIAGameWorks/PhysX/issues/472)

**Comment by TheFruxz** [comment]
Still a thing on macOS Ventura with Apple Silicon chip

**Comment by haubna** [comment]
You can try running it with rosetta (https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html). Let me know if that works for you!

**Comment by haubna** [comment]
Physics Mod 3.0.0 added Mac support.

**Comment by TheFruxz** [comment]
> Physics Mod 3.0.0 added Mac support.

Native Apple Silicon support, or only via Rosetta?
