### ISSUE TITLE
Some of the ragdolls are broken. 

### ISSUE THREAD

**Issue by Jake348** [haubna/PhysicsMod#445]
The villager, creeper, spider and pillager ragdolls are broken.
Pillager: https://user-images.githubusercontent.com/84816229/188240591-2e688dd3-ae25-41ce-bf41-1ede0808ec90.png
Creeper: https://user-images.githubusercontent.com/84816229/188240632-13accc68-36e9-48d7-a2a3-961c52bbd6c3.png
Spider: https://user-images.githubusercontent.com/84816229/188240688-dc6e879b-1073-47ef-a966-70998a3ee8c2.png
Villager: https://user-images.githubusercontent.com/84816229/188240750-ad3afeed-69bf-4b0b-ab2e-260c97f09ce9.png

Minecraft Version: <1.19.2>

Physics Mod Version: <2.8.10 forge>

**Comment by haubna** [comment]
Optifine bug. Please use another shader mod like Iris or Oculus for Forge.

**Comment by Jake348** [comment]
It works now.
