### ISSUE TITLE
Inability to Turn left or rite at random intervals

### ISSUE THREAD

**Issue by AshGale** [haubna/PhysicsMod#446]
Inability to Turn left or rite at random intervals. 
While playing all of a sudden you can't move properly. it's like you are stuck on a frame, or thread, and then it moves on.
It was worse on the 19.2 release, but after a quick 5 min on 18.2 version, happened once too.

I tried to mess with the settings a bit to turn this way down, on the hope maybe it's potentially some performance thing, but mouse in the UI stuttered a few times too.

Pc spec 3080, intel i9, (not sure what else spec would be relevant)
mods PhysicsMod Fabric and Soidum

**Comment by haubna** [comment]
This sounds like the garbage collector kicking in. That's not related to the physics mod.
