### ISSUE TITLE
no sprinting particle texture on quartz slabs

### ISSUE THREAD

**Issue by odogcuda340** [haubna/PhysicsMod#449]
there is no sprint particle texture on quartz slabs for some reason

sprint on quartz slabs to recreate

![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 10_6_2022 7_04_24 PM](https://user-images.githubusercontent.com/107427092/194439800-3a0b3b44-0839-489e-b32e-ef720e1b1a20.png)

Minecraft Version: 1.19.2

Physics Mod Version: 2.8.13a

**Comment by haubna** [comment]
Does this happen without a resource pack too? The slabs look really wonky :o

**Comment by haubna** [comment]
Closed due to not being able to reproduce it with the vanilla resource pack.
