### ISSUE TITLE
Will you add the smoke and weather physics to the 1.18.2 version?

### ISSUE THREAD

**Issue by LewdSenpaido** [haubna/PhysicsMod#450]
I've been using 1.18.2 because I didn't want to limit myself to a few mods but wanted immersive portals, so had to use 1.18.2 but now I'm sad there's no smoke which is what made me wanna get the pro version D: already paid and found out it doesn't work TnT wanted to make some cool things with smoke. Thanks.

**Comment by haubna** [comment]
Yes, I plan to backport all the features to 1.18.2.

**Comment by LewdSenpaido** [comment]
alright cool!  Idk if I should make a separate post for this but does 1.19 version have compatibility for Customized player models (ik thats a pain but jw) Sucks to have capes on and get kicked from the server when f5ing. Also removing cape seemed to fix which isnt something i care to much about. I think when using customized player models just causes a instant crash when you character dies. which is a pain to reopen the game every time with so many mods XD. I'm 99% sure its customized player models causing to happen, although i know jack squat about coding and stuffs.  Anyways sorry to pester ya with so many questions! I really appreciate the work you do! Mods really damn cool! Keep up the great work!

**Comment by haubna** [comment]
Done
