### ISSUE TITLE
Game crashed on create train.

### ISSUE THREAD

**Issue by LewdSenpaido** [haubna/PhysicsMod#451]
Got on Create train, worked fine switched to third person and game blew up!
 I picked up a parrot with carry mod (because I had another crash that crashes everyone when we try to use leads, went to station because i kicked my bird off the drivers seat by accident and was going to go to station to make it untrainified and back into blocks to put him back. clicked F5 so i could see and suddenly game closed. So this and using leads again would be awesome! (only mod really dont wanna remove is immersive portals so if you could tell if its something else thatd be helpful for removing it XD)

Minecraft Version: <1,18,2>
Physics Mod Version: <Latest for 1.18.2>
[crash-2022-10-14_16.55.24-client.txt](https://github.com/haubna/PhysicsMod/files/9790396/crash-2022-10-14_16.55.24-client.txt)

**Comment by haubna** [comment]
This bug is already fixed in 1.19. You will have to wait for a backport for now.
