### ISSUE TITLE
ciao ho un problema con il tuo abbonamento di 13 euro. non riesco a visualizzare la versione pro della tua mod della fisica su minecraft 

### ISSUE THREAD

**Issue by Ma2tia** [haubna/PhysicsMod#452]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

Minecraft Version: <version>
Physics Mod Version: <version>

**Comment by haubna** [comment]
Please send me a message on Patreon or Discord. Discord is the preferred way because other people will help you there while I am offline!
