### ISSUE TITLE
Minecraft Styled Features (Voxel Snow, Water, Smoke, Etc...)

### ISSUE THREAD

**Issue by ZombieGuildford** [haubna/PhysicsMod#453]
While the features of this mod are unique, they graphically don't fit within Minecraft.

So, what if in future there was an option to have these effects fit better in the Minecraft Style?

Voxelised Water, Smoke, and Snow, rather than the meshes, and particles used now?

Example for the Water: https://www.youtube.com/watch?v=qJa2w-7edKA

Snow would work similarly, but not flow, only deforming, and smoke would flow through the air.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
