### ISSUE TITLE
Crash with the weather physics [BUG]

### ISSUE THREAD

**Issue by xelotex** [haubna/PhysicsMod#454]
**Describe the bug**
when the weather goes thunder or rain the game crashes.

**To Reproduce**
/weather thunder.

**Screenshots**

Minecraft Version: <fabric 1.19.2>
Physics Mod Version: < pro v85 >

**Comment by haubna** [comment]
Please include a crash log. This doesn't happen for me.

**Comment by xelotex** [comment]
bruh sorry, i completely forgot, btw it seems to be some incompatibility with dynamic surroundings remastered, because i just remove it and it doesn't crash without it.
[crash-2022-10-23_15.32.31-client.txt](https://github.com/haubna/PhysicsMod/files/9847602/crash-2022-10-23_15.32.31-client.txt)

**Comment by haubna** [comment]
At first glance it doesn't seem to be caused by the physics mod. Optifine (probably in combination with dynamic surroundings) crashes the game.

**Comment by xelotex** [comment]
so i should report it to DS instead, right?

**Comment by haubna** [comment]
No but you could try if it still crashes with Dynamic Surroundings and Optifine installed + Physics Mod NOT installed. If so then you can report it to DS.

**Comment by xelotex** [comment]
you're right, the problem was  DS with Optifine, the problem seemed obvios because of the new weather physics, my bad i shouldn't have doubt about you're Godlike optimization skills.

**Comment by haubna** [comment]
No worries, I make a lot of mistakes too. Report it to the DS team and I am sure they will fix it soon! :)
