### ISSUE TITLE
Ragdoll for other mods

### ISSUE THREAD

**Issue by johanplima** [haubna/PhysicsMod#455]
Trying to complete remove leaves falling or block falling when I cut down a tree to use it with Dynamic Tree
![image](https://user-images.githubusercontent.com/47051875/198206077-e490f32e-b11b-4fdb-8c0d-703392fc2bff.png)

Already tested everything here on this tab, but it changes nothing on trees. 
![image](https://user-images.githubusercontent.com/47051875/198206164-f040a69a-4e9a-45eb-86c4-b110506fc1d0.png)

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
