### ISSUE TITLE
Crash on world gen or join with v87 and existing mod set

### ISSUE THREAD

**Issue by cyberneticlawngnome** [haubna/PhysicsMod#456]
I poked around with the free version enough to decide I wanted the pro version, only the pro version just hard crashes on me.  Crash report attached.

**Describe the bug**
Crash on world create/join.

**To Reproduce**
Add mod to existing modset, create or join world, get crash.

**Screenshots**

Minecraft Version: 1.19.2
Physics Mod Version: v87

[hs_err_pid30488.log](https://github.com/haubna/PhysicsMod/files/9890328/hs_err_pid30488.log)

**Comment by haubna** [comment]
Crash caused by sodium and iris version mismatch
