### ISSUE TITLE
Realistic Player Animation Overhaul

### ISSUE THREAD

**Issue by EndGITTER** [haubna/PhysicsMod#457]
A bit like Mo'Bends I guess.

**Comment by caoqt1** [comment]
> A bit like Mo'Bends I guess.

Why would there be the need to include player animations?

**Comment by EndGITTER** [comment]
idk just an idea cause mo bends was popular and idk a mod that does it for the most recent versions.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
