### ISSUE TITLE
Shader EntityID support [REQUEST]

### ISSUE THREAD

**Issue by null511** [haubna/PhysicsMod#458]
**Add support for shader Entity ID**
Since snow is using the gbuffer_entities program to render, it would be helpful to shaders for PhysicsMod to also provide a unique entity ID. For shaders using PBR materials, this is almost essential to maintain a consistent style.

Optifine docs:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L711-L724

**Comment by haubna** [comment]
entity id is 829925
