### ISSUE TITLE
Dynamic block physics don't work [BUG]

### ISSUE THREAD

**Issue by xelotex** [haubna/PhysicsMod#459]
**Describe the bug**
Dynamic blocks don't work

**To Reproduce**
install V89 of physics.

**Screenshots**
YouTube video: https://www.youtube.com/watch?v=G9Y3BtTqjjY

Minecraft Version: <1.19.2 fabric>
Physics Mod Version: <V89>
[2022-10-31-1.log.gz](https://github.com/haubna/PhysicsMod/files/9905584/2022-10-31-1.log.gz)

**Comment by haubna** [comment]
I couldn't find anything obvious in the log files. It might be due to incompatibility with the illuminations mod.

**Comment by haubna** [comment]
Should be fixed in the latest version. Sorry for the inconvenience!
