### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by lucaszischka** [haubna/PhysicsMod#460]
**Describe the bug**
Minecraft doesn't start. Crash log:

> ---- Minecraft Crash Report ----
> // Sorry :(
> 
> Time: 2022-11-01 19:54:41
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'!
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
> 	at net.minecraft.class_310.<init>(class_310.java:459)
> 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.ExceptionInInitializerError
> 	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:172)
> 	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> 	... 8 more
> Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS
> 	at de.fabmax.physxjni.Loader.load(Loader.java:38)
> 	at physx.NativeObject.<clinit>(NativeObject.java:7)
> 	... 11 more
> Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/yv/5hjsqnfj41q623lrkgrxyg540000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> 	at java.base/java.lang.System.load(System.java:1953)
> 	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71)
> 	at de.fabmax.physxjni.Loader.load(Loader.java:33)
> 	... 12 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
> 	at net.minecraft.class_310.<init>(class_310.java:459)
> 
> -- Initialization --
> Details:
> 	Modules: 
> Stacktrace:
> 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.19.2
> 	Minecraft Version ID: 1.19.2
> 	Operating System: Mac OS X (aarch64) version 13.0
> 	Java Version: 17.0.3, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 2511867408 bytes (2395 MiB) / 3690987520 bytes (3520 MiB) up to 12884901888 bytes (12288 MiB)
> 	CPUs: 8
> 	Processor Vendor: Apple Inc.
> 	Processor Name: Apple M2
> 	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
> 	Microarchitecture: unknown
> 	Frequency (GHz): 24.00
> 	Number of physical packages: 1
> 	Number of physical CPUs: 8
> 	Number of logical CPUs: 8
> 	Graphics card #0 name: Apple M2
> 	Graphics card #0 vendor: Apple (0x106b)
> 	Graphics card #0 VRAM (MB): 0.00
> 	Graphics card #0 deviceId: unknown
> 	Graphics card #0 versionInfo: unknown
> 	Memory slot #0 capacity (MB): 0.00
> 	Memory slot #0 clockSpeed (GHz): 0.00
> 	Memory slot #0 type: unknown
> 	Virtual memory max (MB): 16384.00
> 	Virtual memory used (MB): 11199.06
> 	Swap memory total (MB): 0.00
> 	Swap memory used (MB): 0.00
> 	JVM Flags: 7 total; -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Fabric Mods: 
> 		fabric-api: Fabric API 0.64.0+1.19.2
> 			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
> 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
> 			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
> 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
> 			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
> 			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
> 			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
> 			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
> 			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
> 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
> 			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
> 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
> 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
> 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
> 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
> 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
> 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
> 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
> 			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
> 			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
> 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
> 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
> 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
> 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
> 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
> 			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
> 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
> 			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
> 			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
> 			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
> 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
> 			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
> 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
> 			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
> 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
> 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
> 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
> 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
> 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
> 			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
> 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
> 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
> 			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
> 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
> 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
> 			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
> 			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
> 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
> 		fabricloader: Fabric Loader 0.14.10
> 		java: OpenJDK 64-Bit Server VM 17
> 		minecraft: Minecraft 1.19.2
> 		physicsmod: Physics Mod 2.8.13
> 	Launched Version: fabric-loader-0.14.10-1.19.2
> 	Backend library: LWJGL version 3.3.1 SNAPSHOT
> 	Backend API: Unknown
> 	Window size: <not initialized>
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: <disabled>
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	CPU: <unknown>

Minecraft Version: 1.19.2
Physics Mod Version: 2.8.13a

**Comment by haubna** [comment]
The new ARM CPUs from Apple are only supported in compatibility mode.
