### ISSUE TITLE
Support for Apple Silicon Macs [REQUEST]

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#461]
Please support Macs with the new apple silicon chip

I would love seeing the mod working on m1 macs, it could also be a pro-only feature.

**Comment by haubna** [comment]
You can try running it with rosetta (https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html). Let me know if that works for you!

**Comment by ShoddyOfTheShoes** [comment]
Running the Minecraft launcher through rosetta only effects the launcher, not the Java runtime. You cannot run the mod through rosetta because its just a form of archive, not an executable. I then tried running the Java UNIX executable through rosetta. However, for some reason UNIX executables also do not have the option to run through rosetta.

**Comment by haubna** [comment]
Another user confirmed that it works. You can ask him how he ran it with Rosetta. My guess is that he used the JVM executable to run with Rosetta. 

See #474

**Comment by Aces-and-Jacks** [comment]
well I don't really touch the jvm executable. I just used a specific launcher called prism launcher that happens to be able to work natively on apple silicon

**Comment by Aces-and-Jacks** [comment]
and used x86_64 temurin jre

**Comment by ShoddyOfTheShoes** [comment]
> well I don't really touch the jvm executable. I just used a specific launcher called prism launcher that happens to be able to work natively on apple silicon

I found out how to do so in the vanilla launcher! (All features work using latest non-pro with 1.19.2 fabric!) (I am using a M1 Mac)

1. Make sure you have fabric 1.19.2 installed, with the latest version of physics mod and fabric api inside your mods folder.

2. Goto https://adoptium.net/temurin/releases/?version=17. In the drop downs, set Operating system to MacOS, Architecture as x64, Package type as JDK, and Version as 17. 

3. Press the "tar.gz" download button.

4. After it downloads, unzip the file by double clicking it in finder, then move the unzipped folder to a place you can access easily.

5. Open the Minecraft Launcher, press the installations tab, and press on your Fabric 1.19.2 Installation.

6. At the bottom of the "Edit Installation" Menu, press the more options button.

7. On the right of the Java Installation text field, press browse. In the window that appears, goto the folder you unzipped and moved earlier.

8. Once you find the folder, navigate through it in this order: jdk-17.0.5+8 > Contents > Home > bin

9. Press on the "java" file inside the bin folder and click open.

10. Press save and launch fabric like you would normally, your done!

(If someone could test this with the latest version of Physics Mod Pro, that would be great!)

**Comment by DexterHaxxor** [comment]
Any updates on this? Is it hard to port the mod to Darwin arm64?
Hint: `clang -target arm64-apple-darwin source.c`

**Comment by wilebaldo** [comment]
> > well I don't really touch the jvm executable. I just used a specific launcher called prism launcher that happens to be able to work natively on apple silicon
> 
> I found out how to do so in the vanilla launcher! (All features work using latest non-pro with 1.19.2 fabric!) (I am using a M1 Mac)
> 
> 1. Make sure you have fabric 1.19.2 installed, with the latest version of physics mod and fabric api inside your mods folder.
> 2. Goto https://adoptium.net/temurin/releases/?version=17. In the drop downs, set Operating system to MacOS, Architecture as x64, Package type as JDK, and Version as 17.
> 3. Press the "tar.gz" download button.
> 4. After it downloads, unzip the file by double clicking it in finder, then move the unzipped folder to a place you can access easily.
> 5. Open the Minecraft Launcher, press the installations tab, and press on your Fabric 1.19.2 Installation.
> 6. At the bottom of the "Edit Installation" Menu, press the more options button.
> 7. On the right of the Java Installation text field, press browse. In the window that appears, goto the folder you unzipped and moved earlier.
> 8. Once you find the folder, navigate through it in this order: jdk-17.0.5+8 > Contents > Home > bin
> 9. Press on the "java" file inside the bin folder and click open.
> 10. Press save and launch fabric like you would normally, your done!
> 
> (If someone could test this with the latest version of Physics Mod Pro, that would be great!)

This is not working, is till crashing when loading the game with the mod on multiMC, but the mod is working ok, when you run on other Tlauncher, but that is not a safety launcher, and also is not a native laucher as MultiMC

**Comment by ghost** [comment]
But isn't performance with rosetta much worse than natively? I remember
having a lot of lag before switching to manymc (the first native mc
launcher)

**Comment by ShoddyTheShoe** [comment]
> of

Yes it is, but the mod will not run otherwise, so its the best we got.

**Comment by Aces-and-Jacks** [comment]
It was running fine when I did it. I had some optimization mods tho but I don't really know if that helped or not. It was also on the free version

**Comment by alextoddslick** [comment]
This does not run natively on M2 Max.

**Comment by ghost** [comment]
of course it doesn't. it's not native on any apple silicon chip. haubna
would have to completely rewrite the mod.

**Comment by wilebaldo** [comment]
> of course it doesn't. it's not native on any apple silicon chip. haubna would have to completely rewrite the mod.
> […](#)

I all ready ask that because before the mod was working, and he removed the support on mac. 

The other day I make the video about that, I know my english is not perfect but you can see how the mod before was working on mac but with the new version is not.

https://youtu.be/xSypL7cp_do

Also Haubna give the thanks to https://github.com/fabmax/physx-jni because he used that lib and if you go to see that link you can see they ready have the support for Native MacOS ARM64

**Comment by haubna** [comment]
The github link physx-jni indeed supports MacOS ARM64 but only for PhysX 5.1. I am still using PhysX 4.1 and will switch to PhysX 5.1 with the upcoming 1.20 update.

**Comment by gabinous** [comment]
nice

**Comment by PsydameousSharm** [comment]
Is there any way to do it on forge? I tried the tutorial for a forge mc 1.19.4, but it said that it was the wrong version, even after I did the 19, 20, and 17 ones from adoptium.

**Comment by ghost** [comment]
@PsydameousSharm why would you want to use forge in the forst place?

**Comment by PsydameousSharm** [comment]
Because all of my other mods are on it, and that's the one I was told to use first.

**Comment by wilebaldo** [comment]
> The github link physx-jni indeed supports MacOS ARM64 but only for PhysX 5.1. I am still using PhysX 4.1 and will switch to PhysX 5.1 with the upcoming 1.20 update.

ok, i will wait for the that update.

**Comment by ghost** [comment]
so you can use the mod without rosetta when using physx-jni 5.1?

**Comment by PsydameousSharm** [comment]
I think so

**Comment by ghost** [comment]
and how do i do it exactly?

**Comment by Aces-and-Jacks** [comment]
If you mean use pasx 5.1 then you can't because the physics mod uses physx 4.1

**Comment by ghost** [comment]
Will the PhysX 5.9 that was implemented in V145 also come to the lite version of the Physics Mod? Because I would love to play the mod on my m1 mac but im broke so i can't afford the pro version ;)

**Comment by haubna** [comment]
Yes it will! I haven't gotten any response as to if it works on M1/M2 Macs though (likely due to them not using the pro version because of the compatibility issue). I will upload it to my website, modrinth and curseforge in the upcoming days!

**Comment by ghost** [comment]
I will test the lite version as soon it comes out on my m1 pro mac! should
i write how it worked in this repository?

**Comment by haubna** [comment]
I just released Physics Mod 3.0.0 for Minecraft 1.20 which should work with M1 Macs! Please let me know if it actually works here since I don't own one myself.

**Comment by Aces-and-Jacks** [comment]
It works

**Comment by ibll** [comment]
Works on mine! Thanks! (2020 M1 Macbook Air)

**Comment by PsydameousSharm** [comment]
Will there be anytime soon when it comes to curseforge, or just the mods folder? I'm guessing that will just be when the 1.20 update comes out. 😢

**Comment by haubna** [comment]
It already is on curseforge!

**Comment by haubna** [comment]
Physics Mod 3.0.0 added Mac support.

**Comment by ghost** [comment]
It still crashes on my m1 pro mac when entering a world :(
[crash-2023-04-18_09.44.56-client.txt](https://github.com/haubna/PhysicsMod/files/11259229/crash-2023-04-18_09.44.56-client.txt)

**Comment by wilebaldo** [comment]
> Physics Mod 3.0.0 added Mac support.

Thanks, I will test tonight. Right now I don’t have a 1.20 snapshot ready in the computer to test.

**Comment by alextoddslick** [comment]
I will check if it works on m2- Alex ToddOn Apr 18, 2023, at 7:44 AM, Wilebaldo Alvarez ***@***.***> wrote:﻿

Physics Mod 3.0.0 added Mac support.

Thanks, I will test tonight. Right now I don’t have a 1.20 snapshot ready in the computer to test.

**Comment by wilebaldo** [comment]
I just want to confirm in my mac m1 max is not working. this is the error code I got.

https://paste.ee/p/20TJv

**Comment by PsydameousSharm** [comment]
How would I use it? I tried using the fabric API on Forge, but that didn't work and gave me some error. How do I install it via curseforge?

**Comment by haubna** [comment]
@wilebaldo you are not using it with the 1.20 snapshot. You are using 1.19.4...

**Comment by haubna** [comment]
@Nimblon you are using the completely wrong Minecraft version. You need the latest Minecraft snapshot.

**Comment by haubna** [comment]
@wilebaldo please use a proper 64-bit JVM. In your log it states:
```
Java path is:
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java


Checking Java version...
Java is version 17.0.6, using 32-bit architecture, from Eclipse Adoptium.


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.
```

**Comment by wilebaldo** [comment]
Always show me that message, the java version si the correct one.

But anyways, I change the launcher and now the mod is working everything is ok except when I try to go the menu to change the options.

This is the crash report.
https://paste.ee/e/iPY8o/0

[crash-2023-04-21_10.06.59-client.txt](https://github.com/haubna/PhysicsMod/files/11297895/crash-2023-04-21_10.06.59-client.txt)
![2023-04-21_10 18 52](https://user-images.githubusercontent.com/8034131/233697524-cf1c7c4a-80e8-4051-b7d0-219bbfc8ac60.png)
![2023-04-21_10 16 27](https://user-images.githubusercontent.com/8034131/233697599-5099bc8c-b0a2-4207-8c1c-170c441d211d.png)

**Comment by haubna** [comment]
@wilebaldo please use Physics Mod 3.0.3 with Snapshot 23w16a. And again... you need a 64-bit JVM for it to work on your Mac.

**Comment by wilebaldo** [comment]
Ok, now is working. Thank you very much. As soon as I can, I give you my thanks in your patreon.

![2023-04-21_11 27 05](https://user-images.githubusercontent.com/8034131/233709349-129c0eb2-874d-45d4-870f-b77e7db48519.png)


> you need a 64-bit JVM for it to work on your Mac.

Yes, I know the JVM is 64bit, because macOs is not allow anything is not 64 bits on the new AppleSilicon processors. That error show is 32bits is for the launcher I was used, now I change to new one and is not any more the error.

**Comment by PsydameousSharm** [comment]
Okay, one more question, then I'm done. I have JVM 64, and I have the correlating versions of the physics mod and fabric API, now, how do I use them on the snapshot? Unless I misheard, I can use Forge with it, but I'm not sure what to do. Obviously, it's something I'm missing, because everyone else can get it. Sorry Haubna for bothering you. I know it can get annoying, I just feel clueless, and want to get it so I can support you.

**Comment by wilebaldo** [comment]
> Okay, one more question, then I'm done. I have JVM 64, and I have the correlating versions of the physics mod and fabric API, now, how do I use them on the snapshot? Unless I misheard, I can use Forge with it, but I'm not sure what to do. Obviously, it's something I'm missing, because everyone else can get it. Sorry Haubna for bothering you. I know it can get annoying, I just feel clueless, and want to get it so I can support you.

I don't know if your using the oficial minecraft launcher, if is the case go to the mods folder and copy the fabric api and the physics mod there; important is remove the other mods for different version because later you will have conflicts.

In my case I use the MultiMC or the Prims Launcher because I can create a seperate instance for the different minecraft version and in each one with their own mods.
![Screenshot 2023-04-21 at 3 04 13 PM](https://user-images.githubusercontent.com/8034131/233741645-2d14f347-2d24-4de5-a03b-4ac4198fcbbc.jpg)
![Screenshot 2023-04-21 at 3 03 19 PM](https://user-images.githubusercontent.com/8034131/233741647-9c79b74d-5082-40d3-9e74-a13a0adf84e7.jpg)

**Comment by PsydameousSharm** [comment]
Is Prism Launcher safe? I checked, and it said it was a bit shady, but you would know better

**Comment by wilebaldo** [comment]
I hear something about that, but I'm not sure some of the developer is the same worked for the MultiMC, and Prism is a fork of that one. I just switched from MultiMC because Prism is a Native AppleSilicon, and MultiMC is a intel version that way always is show my JVM said is a 32bits when is 64bits.

**Comment by PsydameousSharm** [comment]
It works! Thank you so much! 
![Uploading Screenshot 2023-04-21 at 10.10.39 PM.png…]()

**Comment by Aces-and-Jacks** [comment]
> Is Prism Launcher safe? I checked, and it said it was a bit shady, but you would know better

Prism launcher should be safe. As far as I know they forked it because MultiMC wouldn't add any new features to it, like how Prism Launcher is intel and m1 native, and all the other features it has. The developers are pretty respectable and don't appear to be malicious from as far as I can tell

**Comment by Aces-and-Jacks** [comment]
Would the 3.0 update be back ported to the other versions in the future?

**Comment by jaykingsland** [comment]
**> Would the 3.0 update be back ported to the other versions in the future?**

I'm wondering the same as well (Fabric user)

**Comment by bellakeys** [comment]
Also wondering the same thing! I'm still on 1.19.2 & this would be the last perfect thing for my modded <3

**Comment by Forever2397** [comment]
![IMG_20230525_194009](https://github.com/haubna/PhysicsMod/assets/85401948/ce4e1631-d49b-474e-93a3-139a7ab4e046)

Why?  my physics mod is like this i tried for android ARM 64s there any solution?

**Comment by Aces-and-Jacks** [comment]
@Forever2397  The only thing I can think of is first narrow down to the bare minimum of mods needed. If it works normally add in other mods till you find which one is affecting it. If you already have the bare minimum make sure you have the correct version of the mod for whatever Minecraft version you're on.

Other than that I don’t know

**Comment by Ezekielman** [comment]
I know 1.19.2 is a bit behind now, but a version for that would be greatly appreciated. I play Hypixel Cops vs Crims, and it uses custom chat characters which break on Minecraft 1.20+. Having native physics mod for 1.19.2 would be great considering how well it would work with that particular game.

**Comment by Jolin-Kan** [comment]
So no ways to use physic mod in Minecraft 1.19.2 on m1 Mac?
I'm tring to play zombie invade 100 days......

**Comment by Ezekielman** [comment]
> So no ways to use physic mod in Minecraft 1.19.2 on m1 Mac? I'm tring to play zombie invade 100 days......

You can use Physics Mod on 1.19.2, but you can't run it natively. Assuming you have Rosetta 2 (you should, I think it's built in with M1 Macs), you can just use an intel version of Java in your launcher, which will make the mod work. It will just be a bit slower.
Here's a link to Intel java which you can install to use Physics Mod: [https://download.oracle.com/java/17/archive/jdk-17.0.12_macos-x64_bin.dmg](https://download.oracle.com/java/17/archive/jdk-17.0.12_macos-x64_bin.dmg)

**Comment by tamescrawl2** [comment]
Hi. I just wanted to ask if there is any way to run GPU liquids on my macbook air with a M3 chip. Maybe a compatible version or something?

**Comment by iliegavrill-star** [comment]
i want to make the premium on SKlaucher and i need help because im on windows

**Comment by Aces-and-Jacks** [comment]
> i want to make the premium on SKlaucher and i need help because im on windows
> 

This is a closed request for apple related support. Your windows help request has nothing to do with this current request. Make another issue request and wait for a response.
