### ISSUE TITLE
Grass Snow Description [BUG]

### ISSUE THREAD

**Issue by BUTTER-BEAR** [haubna/PhysicsMod#463]
**Describe the bug**
Grass Snow option has a bugged description, so its hard to know what exactly its supposed to do.

**To Reproduce**
Step 1: Open snow setting in physics mod 1.19.2 (unsure of other versions)
Step 2: Hover over "Grass Snow" and it should be bugged

**Screenshots**
![image](https://user-images.githubusercontent.com/84295470/200215987-d6139427-02e8-4945-81b6-854cbbcc5771.png)

Minecraft Version: 1.19.2
Physics Mod Version: pro-v89a-fabric
Log: Sadly there are no logs for this bug

**Comment by haubna** [comment]
Fixed in the snapshot. Will be backported to 1.18 and 1.19 once the new menu is finished!
