### ISSUE TITLE
Configs don't respect custom game directory [BUG]

### ISSUE THREAD

**Issue by DevScyu** [haubna/PhysicsMod#464]
### Describe the bug
**Expected:**
Config files to be saved into my custom game directory.
**Actual:**
Config files were saved to the `.minecraft` folder

### To Reproduce
Launch game with different game directory set in the launcher

My profile is set to `%APPDATA%/.wynntils`, however, configs are being saved to `%APPDATA%/.minecraft`
![image](https://user-images.githubusercontent.com/15234414/200563288-a07f6b49-d4e7-4677-818e-fea629b9887c.png)
![image](https://user-images.githubusercontent.com/15234414/200559259-33a3c5a6-7171-49e4-8c23-e1bff7fbcbbd.png)

### Version Information
 - OS: Tested on Mac and Windows
 - Launcher: Official Minecraft Launcher
 - Minecraft 1.18.2
 - Fabric Loader version 0.14.9
 - Mod Version: 2.7.8

**Comment by haubna** [comment]
Are you using the official Minecraft launcher? Because with the official one it works for me. Just making sure so I can reproduce the bug to fix it!

**Comment by DevScyu** [comment]
I am using the official minecraft launcher

**Comment by DevScyu** [comment]
Seems to be a new launcher bug: https://bugs.mojang.com/browse/MCL-22685

**Comment by haubna** [comment]
Ok, I will close this once the bug is fixed on Mojangs end.
