### ISSUE TITLE
Rain particles don't render on Forge servers [BUG]

### ISSUE THREAD

**Issue by paradoxuum** [haubna/PhysicsMod#465]
**Describe the bug**
Rain and dust particles stop rendering on Forge servers, but render fine on other servers, e.g. 1.18.2 Paper servers (haven't tested others but it should be the same). Particles render in singleplayer, and the issue is present regardless of whether Physics Mod is installed on the server.

Vanilla rain renders fine (i.e., from disabling weather particles), so this only applies to the new weather particles AFAIK.

**To Reproduce**
1. Run a 1.18.2 or 1.19.2 Forge server, the issue is apparent in both 40.1.84 (1.18 latest as of now), 40.1.74 and 43.1.47 (1.19.2 latest), but I haven't tested older versions.

2. Set the weather to rain or thunder

3. Rain and dust particles don't render at all, only rain splash particles are visible

**Screenshots**
![2022-11-08_18 24 16](https://user-images.githubusercontent.com/66765965/200645650-01c51911-23ab-47cc-9958-d1dac1da5361.png)
![2022-11-08_18 24 50](https://user-images.githubusercontent.com/66765965/200645659-f89cec39-e514-407a-94c0-26adcac7dbe6.png)

Minecraft Version: 1.18.2, 1.19.2
Forge Version: 40.1.84, 43.1.47
Physics Mod Version: v89a

**Comment by paradoxuum** [comment]
I'm assuming this could be related to the way Forge handles registries on servers, I've had an issue before when developing another mod where SoundEvents registered on the client were no longer registered when joining modded (Forge) servers. Looking at `debug.log`, this also happens with ParticleTypes. 

A possible fix for this could be registering ParticleTypes on the server as well (if it is the issue) - unfortunately I don't know of a way around this to allow it to be fully client-sided, if possible.

**Comment by haubna** [comment]
Fixed with Pro V92. Thanks for letting me know!
