### ISSUE TITLE
Crash when placing banner [BUG]

### ISSUE THREAD

**Issue by jschenke488** [haubna/PhysicsMod#471]
**Describe the bug**
Crash when placing banner
https://mclo.gs/ZZlWNNL
Iris is part of the stack trace, but the crash occurs even when shaders are disabled

**To Reproduce**
Place a banner, sometimes need to place multiple

**Screenshots**

Minecraft Version: 1.19.2
Physics Mod Version: 2.9.1

**Comment by haubna** [comment]
You are using the Pro version, right?

**Comment by haubna** [comment]
Can you reproduce this with only the Physics Mod installed? I suspect a mod is interfering banner stuff. I should be able to fix it without knowing which mod is causing it. Just want to make sure what the actual cause is.

**Comment by haubna** [comment]
Fixed with Pro V95.
