### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by Aces-and-Jacks** [haubna/PhysicsMod#474]
**Describe the bug**
crashes on launch

**To Reproduce**
download and play

**Screenshots**

Minecraft Version: <1.19.2>
Physics Mod Version: <2.9.2 quilt>

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/tCxeCPh

**Comment by Aces-and-Jacks** [comment]
also on mac if that matters

**Comment by haubna** [comment]
You can try running it with rosetta (https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html). Let me know if that works for you!

**Comment by Aces-and-Jacks** [comment]
it worked

**Comment by Aces-and-Jacks** [comment]
any chance on compatibility for arch64/m1?

**Comment by haubna** [comment]
For now not really because the API I am using isn't available for M1.

**Comment by Aces-and-Jacks** [comment]
ok
