### ISSUE TITLE
Weird menu effect [BUG]

### ISSUE THREAD

**Issue by Aces-and-Jacks** [haubna/PhysicsMod#476]
**Describe the bug**
In title green box outline appears pointing to nowhere. In options the physics mod button clashes with another options menu from a super secret settings mod

**To Reproduce**
Launch a game with different menu buttons in options
**Screenshots**
<img width="1512" alt="Screen Shot 2022-11-28 at 3 23 10 AM" src="https://user-images.githubusercontent.com/106651342/204229457-7c7ee1b7-48a8-4520-9104-dee868a883b1.png">
<img width="1512" alt="Screen Shot 2022-11-28 at 3 23 15 AM" src="https://user-images.githubusercontent.com/106651342/204229482-75114271-3e6a-46ae-8095-facb37bc8786.png">

Minecraft Version: <1.19.2>
Physics Mod Version: <2.9.2>

**Comment by Aces-and-Jacks** [comment]
should I provide a log?

**Comment by haubna** [comment]
All good. The green highlight thing will be fixed with the next release. Overlapping button should be resolved by the other mod. I am leaving my button there.

**Comment by Aces-and-Jacks** [comment]
ok. thanks

**Comment by Aces-and-Jacks** [comment]
<img width="966" alt="Screen Shot 2022-11-30 at 3 21 50 PM" src="https://user-images.githubusercontent.com/106651342/204900261-31b81a65-b6b9-4ad5-9172-a60a36cf504e.png">
would his button need to push yours to the side or be located in a different section?

**Comment by haubna** [comment]
Whatever the other mod creator prefers :)

**Comment by Aces-and-Jacks** [comment]
ok

**Comment by Aces-and-Jacks** [comment]
yeah im unable to ask him since I can't figure out gitea. There's no account creation or anything. Not asking for help, just saying that I'd be unable to ask
