### ISSUE TITLE
Text difficult to read

### ISSUE THREAD

**Issue by WenXin20** [haubna/PhysicsMod#477]
**Describe the bug**
- Text becomes difficult to read when the mod [Dark Mode Everywhere](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere) mod is installed 

**To Reproduce**

1. Install Dark Mode Everywhere
2. Open menu

**Screenshots**
![image](https://user-images.githubusercontent.com/12000593/206354972-e31fe2b7-e974-4cbb-ad47-8a204f10bc2c.png)

Minecraft Version: 1.19.2
Physics Mod Version: 2.9.2

**Comment by haubna** [comment]
It seems to force text rendering to white. You should report this to the dark mode everywhere creator.

**Comment by WenXin20** [comment]
Ah, good point
