### ISSUE TITLE
every time a warden, ender dragon, villager, wandering trader, or a pillager is killed (without any mods) the ragdoll limbs act weird[BUG]

### ISSUE THREAD

**Issue by stanford02931** [haubna/PhysicsMod#479]
1.19.2

**Comment by haubna** [comment]
Do you have an example video?

**Comment by CrafterRa** [comment]
i have the same error and i hate it i set the mobs whos ragdolls arent correct to something else but would like when every mob could ragdoll maybe you look in the lite version of the mod because it works in pro

**Comment by CrafterRa** [comment]
video size is to big but i noticed that mobs with a human like skeleton like zombies ragdolls work but mobs with a diffrent like skeletons like creepers, spiders ,pilligers etc are very broken in joints,  i have the newerst lite version maybe you could look if it happens on you device i have pc with windows 11

**Comment by CrafterRa** [comment]
here a screenshots
![2022-12-30_22 05 14](https://user-images.githubusercontent.com/97358503/210112416-6e4fa5c2-3cc2-4259-a3e8-180600c2792c.png)
![2022-12-30_22 05 21](https://user-images.githubusercontent.com/97358503/210112417-9d796911-954f-4108-93b6-993e80d8b6e3.png)
![2022-12-30_22 05 22](https://user-images.githubusercontent.com/97358503/210112418-de2616ac-eeaf-416b-a596-a05741136ab9.png)
![2022-12-30_22 05 36](https://user-images.githubusercontent.com/97358503/210112419-cb9c2ae3-cc9e-43bb-a12b-4543a42430c0.png)
![2022-12-30_22 07 17](https://user-images.githubusercontent.com/97358503/210112422-808bfa8e-bc67-48d9-8e30-752d65959d80.png)

**Comment by CrafterRa** [comment]
nevermind it was a different error for me

**Comment by haubna** [comment]
Fixed with 2.11.6
