### ISSUE TITLE
request: different fracturing shapes depending on block material

### ISSUE THREAD

**Issue by Beanieboi21** [haubna/PhysicsMod#483]
for example: dirt can have very small pieces, wood can be rectangular or long with a pointy tip, stone, is normal i guess, and cobble stone can be more round like pieces, etc... it doesn't have to be like those, they are just examples of my idea.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
