### ISSUE TITLE
Shaders Dont Work [BUG]

### ISSUE THREAD

**Issue by FixikMC** [haubna/PhysicsMod#484]
**Describe the bug**
I put rubidium and oculus for shaders to work (it says so there) and when I start the world, minecraft crashes.

**To Reproduce**
1. Put rubidium
2. Put the Oculus
3. Put Physics
4. Run Minecraft with shaders (I used BSL)
5. Go to your any world
6. Minecraft crashes.

**Screenshots**
I don't have screenshots of the bug, but I know it was like that.

Minecraft Version: 1.19.2
Physics Mod Version: v89 (Forge) v91 - 90 (Fabric)

**Comment by haubna** [comment]
This is an oculus bug. Please contact their dev, or visit their discord for help.
