### ISSUE TITLE
Compability with GeckoLib [REQUEST]

### ISSUE THREAD

**Issue by TheRealPicasso** [haubna/PhysicsMod#485]
GeckoLib mods are incompatible with the Physicsmod sometimes.

Example: McDoom mod (fabric)

**Comment by CrafterRa** [comment]
does this mod has animations why would you need GeckoLib? its just a physics mod

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
