### ISSUE TITLE
Mobs without human build skeletons ragdolls joints a broken  [BUG]

### ISSUE THREAD

**Issue by CrafterRa** [haubna/PhysicsMod#486]
**Describe the bug**
Ragdoll joints of mods without the ragdoll build of players are complettly broken and wrong in position

**To Reproduce**
select mob physics type ragdoll and kill a creeper or spider etc

**Screenshots**
![2022-12-30_22 05 14](https://user-images.githubusercontent.com/97358503/210111667-ee1c2212-e3eb-4d23-a2ad-6cb4b9fbb6c2.png)
![2022-12-30_22 05 21](https://user-images.githubusercontent.com/97358503/210111669-758f7e4b-ec55-40a1-a4ca-f0761647afe1.png)
![2022-12-30_22 05 22](https://user-images.githubusercontent.com/97358503/210111672-b8675aca-f47b-430f-a1e4-0c737ba518b4.png)
![2022-12-30_22 05 36](https://user-images.githubusercontent.com/97358503/210111673-fcdad5bf-9e1a-4f5a-9cd1-3396e800d66f.png)

Minecraft Version: 1.19  forge 41.1.0
Physics Mod Version: 2.9.4 1.19.X

**Comment by haubna** [comment]
Optifine is not supported, please use Iris + Sodium on Fabric or Oculus + Rubidium on Forge.
