### ISSUE TITLE
Armor on ragdolls [REQUEST]

### ISSUE THREAD

**Issue by CrafterRa** [haubna/PhysicsMod#488]
**A description of the requested feature**
when mobs die there lose there Armor, Request add Armor on Ragdolls maybe with nbt would be cool

before
![2022-12-30_22 24 23](https://user-images.githubusercontent.com/97358503/210112693-a680d184-06e4-461c-8ba9-b0db17756e84.png)
after killed
![2022-12-30_22 24 30](https://user-images.githubusercontent.com/97358503/210112705-fe04ad6f-46cc-4491-8940-ffd0bf407a71.png)

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
