### ISSUE TITLE
Portal physics similar to the rick and Morty portal.

### ISSUE THREAD

**Issue by 5Grn** [haubna/PhysicsMod#489]
Though once you go through the portal your camera is no longer looking at the portal, I think it would be a cool subtle addition to make it so, for instance, if you ran through a nether portal but didn't actually get teleported, the portal would have wiggle physics.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
