### ISSUE TITLE
Physics don't work in the Nether?

### ISSUE THREAD

**Issue by MianReplicate** [haubna/PhysicsMod#49]
Using Fabric 1.17.1

Mob physics work in the nether (but the mobs go through the floor), however block physics just don't work. It's just vanilla minecraft particles, but in the overworld everything works completely fine. (Haven't tested The End)

If this helps, I'm using a nether mod called Better Nether and also I'm using a mod like Optifine called Sodium but I don't really think this has anything to do with it since the mod works in the overworld.

Log
[latest.log](https://github.com/haubna/PhysicsMod/files/6882187/latest.log)

Picture of mods
![image](https://user-images.githubusercontent.com/60836125/127084126-22c0a21e-4abb-45ef-838c-9ef79e006340.png)

**Comment by haubna** [comment]
Immersive portals is causing this issue. I hope I can fix this in future releases!

**Comment by haubna** [comment]
Immersive portals works now with the physics mod (2.4.9).
