### ISSUE TITLE
Block collision physics

### ISSUE THREAD

**Issue by 5Grn** [haubna/PhysicsMod#490]
It would be cool for certain blocks to react a certain way when reacted with, such as landing on sand would create a (regenerating) hole made of cubic pixels from the sand that would fly out in all directions. Another could be slime blocks warping out of shape if you land on them from high enough or push them with a piston. hay blocks could act the same in similar circumstances as well.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
