### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by patglabs** [haubna/PhysicsMod#493]
**Describe the bug**
when I try to download the newest release on the physics mod website it doesn't work it shows error 404

**To Reproduce**
try and download physics mod lite 2.9.5 fabric 1.18.2 

**Screenshots**
![image](https://user-images.githubusercontent.com/97562509/210414643-096c88bd-d8f4-41d8-a828-650d1d52950e.png)

Minecraft Version: <fabric 1.18.2>
Physics Mod Version: <2.9.5>
-thanks

**Comment by haubna** [comment]
Thanks for letting me know. Fixed now!

**Comment by patglabs** [comment]
thanks
