### ISSUE TITLE
Cloud Physics

### ISSUE THREAD

**Issue by odvigajlo** [haubna/PhysicsMod#496]
**Cloud Physics** This feature will try to simulate realistic clouds using simple techniques.
More into how it **can** work:
First will be to get some data of current conditions,
When saving conditions it will take in account: Terrain Elevation, Biome's Temperature, Biome's Humidity/Rain Chance

Cloud Behaviour/ Texture Stuff:
Then we need to generate texture similarly to ocean's wave intensity:
**Density texture**
Clouds will shape using density texture

Here's how density texture will generate:
High Elevation, High Temperature -> Medium Density
High Elevation, Low Temperature -> High Density
High Elevation, High Humidity -> High Density
High Elevation, Low Humidity -> Low Density
Med Elevation, High Temperature -> Medium Density
Med Elevation, Low Temperature -> Medium Density
Med Elevation, High Humidity -> High Density
Med Elevation, Low Humidity -> Low Density
Low Elevation, High Temperature -> Medium Density
Low Elevation, Low Temperature -> High Density
Low Elevation, High Humidity -> High Density
Low Elevation, Low Humidity -> Low Density

Based on these ^ density texture will generated, after what it will be distorted by some noise for extra detail/randomness
and constantly by wind, then clouds will render using density texture

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
