### ISSUE TITLE
Realistic Clouds? [REQUEST]

### ISSUE THREAD

**Issue by ImDeltaxe** [haubna/PhysicsMod#498]
Wondering if there any intension to add physics to clouds. I'm so tired of the boring clouds that are just always movingin ONE direction.
Even if the clouds were still vanilla shaped, having them move randomly or with the wind would be great and feel better with the rain.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
