### ISSUE TITLE
[Suggestion] Open source the mod

### ISSUE THREAD

**Issue by Redo11** [haubna/PhysicsMod#5]
Let's add something to community! Open sourcing will mean, that you will have people to help you code this, bugfix it, and it allows other modders to more easily implement better support. If you are scared, that someone might steal your work, you can select a licence that will prevent that and still most people instead of stealing your mod and claiming as their will just send a PR with all their changes and tweaks. Of course, it's yours of choice, but community would appreciate you making this open.

**Comment by haubna** [comment]
There is no point in open sourcing this. Once finished this mod will work with every block/mob without the mod devs doing anything. Usually the more devs involved in a project, the more chaotic it will get. Especially in a modding community with a lot of inexperienced programmers.
