### ISSUE TITLE
overlays on skins breaking

### ISSUE THREAD

**Issue by ArchredCommunityFounder** [haubna/PhysicsMod#5]
stuff like zombie pigmen, drowneds, pillagers, piglins, but most noticeably players.

the engine doesn't make the overlays work properly. instead the engine makes them separate.

here is what some look like.
![overlays breaking again](https://user-images.githubusercontent.com/45907107/125175862-1a29e380-e19d-11eb-94de-583c16a78bc2.png)
![overlays breaking](https://user-images.githubusercontent.com/45907107/125175863-1b5b1080-e19d-11eb-86f0-d4f35d00e537.png)

**Comment by haubna** [comment]
When you use blocky physics? For players this should be fixed when you use ragdolls. Not sure if I ever gonna fix this for non ragdolls. For ragdolls however this should be fixed once I start implementing wider support!

**Comment by ArchredCommunityFounder** [comment]
i don't know how to reply. so i'll just comment to reply. I was using ragdolls. just happens the mobs i used where not affected by ragdolls. so they go to blocky instead. and i've used ragdolls for a while. players have the same issue. i'm not sure if it's something i'm doing wrong. or something else.

edit: could it have something to do with my version? i'm using 1.3.4 (forge)

**Comment by haubna** [comment]
In the newest version (2.0.1 for MC 1.17.1) ragdolls for player work without problems. Legacy versions of Minecraft will not receive any updates due to time constraints.
