### ISSUE TITLE
Black Smoke [REQUEST]

### ISSUE THREAD

**Issue by formerlyEmber** [haubna/PhysicsMod#504]
**The Smoke feature could be colored black or maybe a dark grey instead of light grey?**
It would feel very immersive to be stuck in a burning room with the black smoke obscuring your vision as you claw at the door yelling for help, but its too late, your friend won't ever forgive you for recklessly jump-running through his farm.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
