### ISSUE TITLE
Game crashes shortly after loading world[BUG]

### ISSUE THREAD

**Issue by Zerks** [haubna/PhysicsMod#505]
Whenever I load in my minecraft world, around a few seconds after loading into the world the game crashes, I have no other mods installed besides the pro version of the physics mod, iris shaders, and sodium. 

Minecraft Version: 1.19.3
Physics Mod Version: v102
[latest.log](https://github.com/haubna/PhysicsMod/files/10369912/latest.log)

**Comment by haubna** [comment]
Could you provide a crash log? Other than that it could be the selected shaderpack and the current instability with Nvidia drivers.

**Comment by haubna** [comment]
Closed due to no response
