### ISSUE TITLE
Door Glitch Issue [BUG]

### ISSUE THREAD

**Issue by vvouivre** [haubna/PhysicsMod#506]
**Doors get stuck and will not go back to their normal spot.**
They continue to vibrate and freak out until a player either exits the dimension or disconnects from the game. This can cause epilepsy due to the way the door violently shakes trying to get back to its spot. I suggest that a solution could be to just reset the door back to how it was after a few moments. (Or be forced to be hinged to a side.)

**To Reproduce**
1. Boot up MC
2. Get on a world (or make your own server)
3. Close the door on your friend (or yourself) 
4. Watch the door get stuck on their body (or you to get stuck). 
5. Moving around will now completely mess up the door, forever, potentially. LOL

**Screenshots:**
Listed below, here: https://mega.nz/file/p9pBEY6T#p2OmU8-GmzuEzGLlmTSvMd14SKrRNwrrmsl6uB5P_hg
(File is like 200 mb. Way too big for github!)

**Minecraft Version: 1.19.3
Physics Mod Version: V102**

**Comment by haubna** [comment]
You can disable player collision for doors in the settings under dynamic blocks > customize to prevent that.
