### ISSUE TITLE
Make it free for 2 or 1 week so peoples can enjoy. (If you make it free, more peoples want to download the mod) and also don't forget to add the flood physics. [REQUEST]

### ISSUE THREAD

**Issue by SyahfizanAkmal3060** [haubna/PhysicsMod#508]
Make it free for 2 or 1 week so peoples can enjoy. (If you make it free, more peoples want to download the mod). I Love your mods, with realistic physics!!! Is the best physics mod ever I played!! But sadly :( I'm using the lite one. So please make it free just for one or two weeks.
Add: Add the flood physics:
How its works when there is rain or thunder, the water will increase similar to the flood on Kelantan (Its already ended).
Next, I will think other enchaments, bye!!
From: Syahfizan Akmal (Malaysia)
To: Haubna (UK or US maybe??)

**Comment by Thisguybernie** [comment]
I agree

**Comment by SyahfizanAkmal3060** [comment]
Thanks,
and also developers make it free

**Comment by rom3ox** [comment]
I would buy the pro version of the mod if i could check that my custom 200+ would work ok before buying. I dont want the pro version free because its a hard and nice work, but i dont want to buy to play on my 2000 hours world without knowing if it will crash or even load.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
