### ISSUE TITLE
Snow golem loses its pumpkin when killed

### ISSUE THREAD

**Issue by James103** [haubna/PhysicsMod#51]
When you kill a Snow Golem with the Physics Mod enabled, there is no pumpkin on the resulting corpse, even if the Snow Golem was never sheared.
![image](https://user-images.githubusercontent.com/37945304/127100448-c8f92442-c382-423e-b8e4-e4fc5b37802a.png)

Excerpt from MultiMC Log:
```
Java is version 16.0.1, using 64-bit architecture, from AdoptOpenJDK.

Mods:
  [✔️] fabric-api-0.37.1+1.17
  [✔️] physics-mod-2.3.5-mc-1.17.1

[00:02:05] [main/INFO]: Loading for game Minecraft 1.17.1
```

**Comment by haubna** [comment]
Fixed snow golem ragdoll and added pumpkin.
