### ISSUE TITLE
Bedrock

### ISSUE THREAD

**Issue by NotSasuke11** [haubna/PhysicsMod#510]
Please re-create these physics for bedrock.

**Comment by b1ek** [comment]
i dont think that there is a mod API for bedrock

**Comment by TigerGTC** [comment]
to be fair he could make a data pack for the bedrock edition but it would require the skills of c++

**Comment by tqoac** [comment]
> to be fair he could make a data pack for the bedrock edition but it would require the skills of c++

Not even that, you'd have to create / find a whole new physics engine that you could use.

**Comment by caoqt1** [comment]
#234 Not happening any time soon.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
