### ISSUE TITLE
Water source/flowing water lvl 8 surface is invisible

### ISSUE THREAD

**Issue by xllifi** [haubna/PhysicsMod#511]
**Describe the bug**
Water source/flowing water lvl 8 surface invisible when placed

**Expected behaviour**
Water source/flowing water lvl 8 surface will be visible

**To Reproduce**
Obtain a bucket of water
Place the bucket of water

**Screenshots**
![image](https://user-images.githubusercontent.com/70767436/211328661-13c8c75d-4ac6-421d-a7ac-25415b33c6db.png)

Minecraft Version: 1.19.2
Physics Mod Version: v103

**Comment by haubna** [comment]
I can't reproduce this in Fabric. Might be due to the Quilt loader?

**Comment by haubna** [comment]
Should be fixed with v106.
