### ISSUE TITLE
Game crashing on startup 

### ISSUE THREAD

**Issue by NITROZEUS27** [haubna/PhysicsMod#512]
**Describe the bug**
Im playing with quilt loader and when I launch the game with the mod my game crash . I think its some kind of relied to iris ' I use iris mod for shaders.  (plus , I play on win10)

**To Reproduce**
install and lunch game 

**Screenshots**
Not a screenshot but , :  The game crashed whilst initializing game
Error: java.lang.AbstractMethodError: Receiver class net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_5944 invokeCreateShader(java.lang.String, java.util.Optional, net.coderbot.iris.pipeline.newshader.ShaderKey)' of interface net.diebuddies.mixins.ocean.MixinNewWorldRenderingPipelineInvoker. 

Minecraft Version: 1.19.2
Physics Mod Version: physics-mod-pro-v103a-fabric-1.19.x

**Comment by haubna** [comment]
Make sure to use at least Iris 1.4.3 then it will work!
