### ISSUE TITLE
Can not re-enable Block collapse [BUG]

### ISSUE THREAD

**Issue by Yerribrine** [haubna/PhysicsMod#514]
I simply can not turn on again the collapse of blocks back again, I have reinstalled the mod, and already delete the config files but it just simply does not work.

1.19.3
2.9.4-mc (Forge)

**Comment by haubna** [comment]
It only works if you are in Singleplayer, otherwise you need to install the mod on the server.

**Comment by Yerribrine** [comment]
Thank you, it is on Single player but still not working, also I re installed al the .minecraft but still not work

**Comment by haubna** [comment]
Are you sure you enabled it in Physics Settings > Collapse?

**Comment by Yerribrine** [comment]
Yes, gentle man, here is a video, I post it here because the web does not allow me to upload +10 MB
https://youtu.be/bhxbLPQVSVE

**Comment by haubna** [comment]
Does any weird errors show up in latest.log?

**Comment by Yerribrine** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/122360104/211538096-712d7501-5e5b-4573-99e9-6c077d40852a.png)
Nothing weird too.

**Comment by haubna** [comment]
Seems like it is broken. You can switch to Fabric in the meantime.

**Comment by Yerribrine** [comment]
Thank you

**Comment by Yerribrine** [comment]
Good day!

**Comment by haubna** [comment]
Fixed in latest Pro versions. Fix will be included in Physics Mod 2.9.6 Lite version.
