### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by xonstudios** [haubna/PhysicsMod#516]
java.lang.reflect.InvocationTargetException: null
![image](https://user-images.githubusercontent.com/122398515/211642173-0b3e1a08-53f3-4a52-91f7-809e2614fa63.png)

i just bought the full version
i dont know what this means

Minecraft Version: 1.19.2
Physics Mod Version: 2.9.3*

**Comment by haubna** [comment]
The full version is not on Physics Mod version 2.9.3. Send me a list of your mods + your operating system.
