### ISSUE TITLE
Crash on Startup With Valkyrien Skies Installed

### ISSUE THREAD

**Issue by Syclusion** [haubna/PhysicsMod#519]
Game insta-crashes when valkyrien skies is loaded with it, the vs2 devs refuse to fix as this is closed source code. Please fix this

**Comment by haubna** [comment]
Include a crash log and I will have a look

**Comment by Syclusion** [comment]
[latest.log](https://github.com/haubna/PhysicsMod/files/10396563/latest.log)

**Comment by haubna** [comment]
This is not the crash log. Crash logs are in the "crash-reports" folder.

**Comment by Syclusion** [comment]
Strange, its not generating one. Tried multiple instances, just gives exit code 1 and stops instantly only things generated are these
[debug.log](https://github.com/haubna/PhysicsMod/files/10396616/debug.log)
[latest.log](https://github.com/haubna/PhysicsMod/files/10396617/latest.log)
[2023-01-11-1.log.gz](https://github.com/haubna/PhysicsMod/files/10396618/2023-01-11-1.log.gz)

**Comment by Syclusion** [comment]
If i use a dif launcher I can get a bit of a longer log but this is all i can get
[everything it says.txt](https://github.com/haubna/PhysicsMod/files/10396634/everything.it.says.txt)

**Comment by haubna** [comment]
The last one helps, thanks!

**Comment by haubna** [comment]
It will no longer crash with the physics mod installed
