### ISSUE TITLE
Crash when loading with Iris Sodium 1.17

### ISSUE THREAD

**Issue by elijah-schulman** [haubna/PhysicsMod#52]
[crash-2021-07-27_13.51.04-client.txt](https://github.com/haubna/PhysicsMod/files/6887667/crash-2021-07-27_13.51.04-client.txt)

**Comment by IMS212** [comment]
This is a known issue, and will be fixed in the next release of Iris coming soon.

**Comment by IMS212** [comment]
This should have been fixed in the latest Iris release (there are still issues with Physics mod + Iris, but the crash should not happen.)

**Comment by haubna** [comment]
Tested it with latest Iris version and complementary shaders and it works fine.
