### ISSUE TITLE
please add compatibility with weather storms and tornados mod

### ISSUE THREAD

**Issue by Aero-Plays** [haubna/PhysicsMod#520]

**Comment by haubna** [comment]
The crash doesn't seem Physics Mod related (from the crash report I inspected on the discord). It seems to crash with Iris/Oculus installed.

**Comment by Aero-Plays** [comment]
that's not what I meant, i was wondering if you could make it so the weather effects in the physics mod could work with that mod because it overrides the weather in Minecraft
