### ISSUE TITLE
Infinite floating smoke [BUG]

### ISSUE THREAD

**Issue by jtx46** [haubna/PhysicsMod#525]
Fresh world found a cool seed to start a playthrough but In my world I have a empty block space that seems to create Infinite Physic Smoke particles without any noticeable causes. (see picture)

**To Reproduce**
World seed : 121825627925
World generates with water leaking into the portal to heck, but in my troubleshooting I Blocked all the water ways that could reach the Lava pool, as I first assumed that the partials were created from the water reaching the Lava down under. But that didn't fix the issue. Block coordinates are X0Y0Z0, which might help narrow down the issue. Also disabling the Smoke feature in Mod config, makes the smoke go away, ie Non smoke is from Mod not Minecraft itself.

Pics:
![2023-01-12_21 51 56](https://user-images.githubusercontent.com/55775703/212436221-c1e7deaa-4679-468e-b9eb-3a26f80547a2.png)
![2023-01-12_21 52 25](https://user-images.githubusercontent.com/55775703/212436233-c73ce617-0551-4ab9-b654-a70f31b9122a.png)
![2023-01-13_17 08 45](https://user-images.githubusercontent.com/55775703/212436242-281258b3-89c9-4e41-bd26-f18a7bf5dc51.png)
![2023-01-12_21 52 31](https://user-images.githubusercontent.com/55775703/212436257-55ad25ff-64ad-4829-b368-b18a8c143748.png)

Minecraft Version: 1.19.2 Modded Fabric
Physics Mod Version: v107 Fabric

**Comment by haubna** [comment]
Fixed in V110
