### ISSUE TITLE
Witherstorm mod compatibility [REQUEST]

### ISSUE THREAD

**Issue by Thisguybernie** [haubna/PhysicsMod#526]
Just tried the 2 mods together and its crashed the game. Maybe you could make those 2 compatible. They have a lot of potential. Crackers witherstorm mod.

**Comment by haubna** [comment]
Do you have a crash log? This would help a lot.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
