### ISSUE TITLE
Particles are seen through walls when picking up items (1.19.2 Forge) [BUG]

### ISSUE THREAD

**Issue by kennylux** [haubna/PhysicsMod#528]
When I break a block and pick it up (it seems it's caused just by picking up something), particles are seen through walls for a brief moment. I've read in the last Physics Mod's changelog that it had to do something with particles, so I thought it could be caused by this update. I installed Physics Mod 2.9.6 and it fixed the bug, so most likely it's your mod that was causing it.

Version of MC: 1.19.2
Version of Physics Mod that caused the bug: 2.9.7 (Forge)

To reproduce:
For example, place a torch behind a wall, break some block and pick it up.

**Comment by haubna** [comment]
Doesn't seem related to the physics mod since it doesn't happen when only the physics mod is installed. If you can reproduce it with only the physics mod installed please open a new issue. Thanks!
