### ISSUE TITLE
Creeper explode and Game crash [BUG]

### ISSUE THREAD

**Issue by TheRealBubReal** [haubna/PhysicsMod#529]
Bug Report

Summary:
Minecraft crashes with error code -1073741819 when a Creeper explodes, but only in a specific world and the crash does not always occur. Additionally, the game sometimes freezes for a short period of time.

Steps to reproduce:

Launch Minecraft
Load the specific world where the issue occurs
Spawn a Creeper
Allow the Creeper to explode
Observe the crash and the error code -1073741819 (if it occurs) and/or the game freezing
Expected Results:
The Creeper should explode and cause damage to any nearby players and blocks, and the game should not crash or freeze.

Actual Results:
The game crashes and displays the error code -1073741819, or the game freezes for a short period of time, but only when the Creeper explodes in the specific world.

Notes:

The crash occurs inconsistently when a Creeper explodes in the specific world.
This issue is reproducible only in the specific world.
The error code -1073741819 could not be identified by me as a specific error, please check with developers.
The game freezing after the crash might be caused by the same problem

System Information:

Operating System: Windows 11
Minecraft Version: 1.18.2
Physics Mod Version: V109

**Comment by TheRealBubReal** [comment]
the game freezes only when smoke is on

**Comment by haubna** [comment]
This might be fixed in the next release, I will let you know when it is online.

**Comment by haubna** [comment]
V110 is online, please let me know if it still happens.

**Comment by TheRealBubReal** [comment]
no unfortunately is not fixed but I found out that the game only lags or crashes when smoke is on otherwise goes nomal and have also noticed that it is the same with ghast but so far it is not crashed with them yet

**Comment by haubna** [comment]
Are you using Optifine?

**Comment by TheRealBubReal** [comment]
No, I use sodium with iris shaders

**Comment by haubna** [comment]
Fixed with v147
