### ISSUE TITLE
Tree chopping physics [REQUEST]

### ISSUE THREAD

**Issue by TigerGTC** [haubna/PhysicsMod#530]
when you break a block of a tree, all the rest of the tree attached to it will fall over like chopping a real tree. Kind of like the dynamic tree physics just a more realistic and vanilla feeling.

**Comment by aeluabik** [comment]
+1 on this

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
