### ISSUE TITLE
Chain physics [REQUEST]

### ISSUE THREAD

**Issue by TigerGTC** [haubna/PhysicsMod#531]
you can connect a chain from wherever you want to like a wall to the floor, and if someone were to walk into it it would get pulled by the player but at a certain point the player can not walk further because the chain is not stretchy.

**Comment by JoyousCreeper1059** [comment]
doesn't sound visual, this is a purely visual mod

**Comment by JustAHuman-xD** [comment]
Yeah this would not be something to be added to the mod as it is a client sided mod for visuals not for interactions

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
