### ISSUE TITLE
Water has no collision

### ISSUE THREAD

**Issue by MJonah** [haubna/PhysicsMod#532]
**Describe the bug**

Man kann durch Wasser einfach durchlaufen ohne Collision und man kann nicht mehr schwimmen.

You can walk through water without collision and you are not able to swim.

**To Reproduce**

Wasser mit Wassereinmer platzieren und durchlaufen bzw. einfach in einen Fluss etc. springen.

Place a water source with a bucket and walk through it or jump into the next nearby river to test it.

**Screenshots**

https://user-images.githubusercontent.com/76984555/212976105-fff9df99-294c-4d10-8b3f-5c94e772692c.mp4

(In survival mode as well)

**Version**

Minecraft Version: 1.19.2 Fabric
Physics Mod Version: Pro v110 1.19.2 Fabric

**Comment by haubna** [comment]
Seems like you are using other mods too. This issue is not present with only the physics mod pro installed. Can you send me a list of your installed mods? I am also not editing any kind of horizontal movement so my best guess is that this problem is not caused by my mod.

**Comment by MJonah** [comment]
Wait...
Ok i'll check

**Comment by MJonah** [comment]
![image](https://user-images.githubusercontent.com/76984555/213028521-d69c928b-0d69-4d9d-b092-556fdf49281e.png)

**Comment by MJonah** [comment]
Yes it's not your mod i'm sorry.

**Comment by haubna** [comment]
No problem! :P

**Comment by MJonah** [comment]
It was the mod Indium btw.

**Comment by lojokey** [comment]
so what mods caused it???

**Comment by MJonah** [comment]
> so what mods caused it???
> 
> 
> 
> 

It was an old version of Indium

**Comment by lojokey** [comment]
im using the last version of indium but its still not working :((
