### ISSUE TITLE
Cape Physics and Water Physics Bug

### ISSUE THREAD

**Issue by JoyousCreeper1059** [haubna/PhysicsMod#533]
**Describe the bug**
The cape acts as it the water physics isn't there

**To Reproduce**
have a physics cape on, go on ocean physics, and press F5 to see your cape

**Screenshots**
![image_2023-01-17_174545964](https://user-images.githubusercontent.com/113858316/213028769-e173e752-a951-49c3-bc59-6bb58cb74f7d.png)
![image_2023-01-17_174616210](https://user-images.githubusercontent.com/113858316/213028840-e9a62069-1090-4924-b68b-fe2cd725e8ee.png)

Minecraft Version: 1.18.2
Physics Mod Version: 110

**Comment by haubna** [comment]
Fixed with V149.
