### ISSUE TITLE
Smoke Physics Glitch

### ISSUE THREAD

**Issue by Craftomancer** [haubna/PhysicsMod#538]
When I use any shaders (I use BSL but, it doesn't work with any other shader either) the smoke continues to glitch out then in multiple times and, it gives an error: OpenGL Error: 1282 (Invalid Operation)

Just put on a shader and then for me it'll glitch out.
![Uploading bug physics mod.png…]()

Minecraft Version: <Fabric Loader 0.14.12 1.19.2>
Physics Mod Version: <v111 Fabric 1.19.2>

**Comment by haubna** [comment]
In case you use Optifine please switch to Iris + Sodium. I will also need a full list of mods that you use.
