### ISSUE TITLE
The wind doesn't stop blowing even when it's already cloudless

### ISSUE THREAD

**Issue by EryYysZ** [haubna/PhysicsMod#539]
Hi, so I found a very annoying issue while playing on the newest version of the physics mod. It involves the wind, that once it startes to  rain, rapidly silences all other sounds until theres nothing left exept an endless wind. After leaving the game and relaunching it everything goes back to normal

I don't know If that's important, but I'm playing on a few other mods
They shouldn't be a problem, because none of them changes the way that the sound behaves

Minecraft Version: 1.19.2
Physics Mod Version: physics-mod-pro-v111-fabric-1.19.2

**Comment by haubna** [comment]
Please always test without other mods installed before reporting bugs. Let me know if it changes something.

**Comment by haubna** [comment]
This should be fixed with V112. Thanks for reporting the issue!
