### ISSUE TITLE
Mod not working on Windows 7 [BUG]

### ISSUE THREAD

**Issue by MarwanTube9** [haubna/PhysicsMod#542]
the mod isn't working!!!

everytime i start minecraft
it shows me an error

![image_2023-01-19_025718](https://user-images.githubusercontent.com/123095629/213483427-76184a4d-93da-46be-aa9d-1aa574a4419e.png)

Minecraft Version: 1.16.5
Physics Mod Version: 2.6.9

**Comment by haubna** [comment]
Macs are not officially supported. Solution can be found here: https://github.com/haubna/PhysicsMod/issues/461#issuecomment-1332775496
