### ISSUE TITLE
Can't hear any sound except wind sounds when raining for a bit

### ISSUE THREAD

**Issue by ShadowmeC3** [haubna/PhysicsMod#544]
I turned me wind volume up while it was raining and after a minute all sounds turned off except wind sounds

turn wind sounds up while its raining and then wait

uhhh....

Minecraft Version: <1.19.2>
Physics Mod Version: <2.9.7>

**Comment by haubna** [comment]
Thanks for the report! Found the bug, will be fixed in the next release!

**Comment by haubna** [comment]
Fixed in V112
