### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by Kaiji-Key** [haubna/PhysicsMod#547]
**Describe the bug**
I'm using the Prism launcher and I downloaded the latest version of the Physics Mod through CurseForge, using Prism's built-in modpack downloader. Minecraft boots fine but I get the error shown in the attached image.

**To Reproduce**
Download the mudpack through Prism and attempt to launch the game.

**Screenshots**
<img width="851" alt="Screenshot 2023-01-20 at 2 29 00 PM" src="https://user-images.githubusercontent.com/123205194/213792021-4a175547-5438-48f3-815c-adfec12462ec.png">

Minecraft Version: 1.19.3
Physics Mod Version: 2.9.7 (Forge 1.19.3)

**Comment by haubna** [comment]
Are you on MacOS? If that's the case, check this out: https://github.com/haubna/PhysicsMod/issues/461#issuecomment-1332775496
