### ISSUE TITLE
Game crashes after a while using a modded server on fabric

### ISSUE THREAD

**Issue by MastroLupo** [haubna/PhysicsMod#548]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-01-20 21:57:52
Description: unverified physics mod copy

java.lang.Throwable: couldn't verify copy
	at net.diebuddies.render.MainRenderer.lambda$verifyAndUtility$1(MainRenderer.java:824)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1974011464 bytes (1882 MiB) / 6006243328 bytes (5728 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1273
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2802
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31011.30
	Virtual memory used (MB): 26780.49
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 877.41
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.1.0
		adorn: Adorn 3.8.0+1.19.2
		adventurez: AdventureZ 1.4.17
		allaybottle: Allay in a Bottle 1.1.0
		another_furniture: Another Furniture 2.1.2-1.19.2
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.62
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.2+0
		basicshields: Basic Shields [Fabric] 1.4.0-1.19.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		bclib: BCLib 2.1.5
		beaconoverhaul: Beacon Overhaul 1.7.3+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		betteranimationscollection: Better Animations Collection 4.0.5
		bettercombat: Better Combat 1.5.3+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		bettersleeping: BetterSleeping 0.6.1+1.19
			bettersleeping-core: BetterSleeping Core 0.6.1
			org_apache_commons_commons-text: commons-text 1.9
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.9.0
		bettertridents: Better Tridents 4.0.1
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bountiful: Bountiful 3.0.0
		camerautils: Camera Utils 1.19.2-1.0.3
		campanion: Campanion 4.1.2+fabric
		capybara: Capybara 2.0.1
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chat_heads: Chat Heads 0.7.1
		chimes: Chimes 1.1.4
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		collective: Collective 6.22
			collective-fabric: Collective (Fabric) 5.22
		combatroll: Combat Roll 1.1.1+1.19
		comforts: Comforts 6.0.3+1.19.2
			spectrelib: SpectreLib 0.10.0+1.19
		companion: Companion 3.1.2
		connectiblechains: Connectible Chains 2.1.4+1.19.2
		continuity: Continuity 2.0.1+1.19
		cosmetic-armor: Cosmetic Armor 1.4.0
		craftablesaddle: Craftable Saddle 1.19.2-1.6.3-[FABRIC]
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		creativecore: CreativeCore (Fabric) 2.9.3
		creaturesfromthesnow: Creatures from The Snow 4.0.1+1.19.2
		crittersandcompanions: Critters and Companions 1.19.2-1.0.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1.4
		cyclepaintings: Cycle Paintings 3.0
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dehydration: Dehydration 1.3.3
		diagonalfences: Diagonal Fences 4.2.3
		dragonloot: DragonLoot 1.1.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.5_1
		drinkbeer: Drink Beer 3.2.2-1.19.2
		dsurround: Dynamic Surroundings: Remastered Fabric Edition 0.1.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		dungeons_arise: When Dungeons Arise 2.1.54
		eatinganimationid: Eating Animation 1.9
		ecologics: Ecologics 2.1.11
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchantinginfuser: Enchanting Infuser 4.2.2
		endgoblintraders: End Goblin Traders 1.5.1
		environmentz: EnvironmentZ 1.3.5
		expandeddelight: Expanded Delight 0.2.5
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		fabricshieldlib: Fabric Shield Lib 1.6.1-1.19
			mm: Manningham Mills 2.3
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		fishofthieves: Fish of Thieves 2.1.1
		forgeconfigapiport: Forge Config API Port 4.2.10
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		forgivenessmod: Forgiveness 1.3.3
		forgivingvoid: Forgiving Void 7.0.0
		friendsandfoes: Friends&Foes 1.6.5
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		frycmobvariants: Mob Variants 1.0.2+1.19.2
		galosphere: Galosphere 1.19.2-1.2.1
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 2.3
			omega-config: OmegaConfig 1.2.2-1.18.1
		graveyard_biomes: The Graveyard Biomes 1.6
		handcrafted: Handcrafted 2.0.2
		hookshot: Hookshot 26.0
		horseexpert: Horse Expert 4.0.0
		illagerslovearmor: IllagersLoveArmor 1.0.2+1.19
		illuminations: Illuminations 1.10.11
		immediatelyfast: ImmediatelyFast 1.0.5
		immersive_armors: Immersive Armors 1.5.0+1.19.2
		immersive_weathering: Immersive Weathering 1.19.2-1.2.5
		indium: Indium 1.0.9+mc1.19.2
		interactic: Interactic 0.1.11+1.19
		inventorytotem: Inventory Totem 3.0
		iris: Iris 1.4.5
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 4.0-1.19.2
		kiwi: Kiwi Lib 8.1.2
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		leatheredboots: Leathered Boots 1.0.0.2
		libraryferret: Library ferret 3.0.0
		lithium: Lithium 0.10.4
		lovely_snails: Lovely Snails 1.1.0+1.19
		malilib: MaLiLib 0.13.0
		mcdar: MC Dungeons Artifacts 1.5.2-1.19
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcwlights: Macaw's Lights and Lamps 1.0.4
		medievalorigins: Medieval Origins 1.19.x-4.1.3
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.1.20
		moreberries: More Berries 1.5.1
		morefrogs: More Frogs 1.19.x-1.2.3-fabric
		morevillagers: More Villagers 4.0.2
		mysticaloaktree: Mystical Oak Tree 1.19.2-1.6
		mythicupgrades: Mythic Upgrades 1.5
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		notenoughanimations: NotEnoughAnimations 1.6.2
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		paradise_lost: Paradise Lost 2.0.2-beta+1.19.2
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.8.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.6.1+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.9.7
		player-animator: Player Animator 0.4.0
		playtics_deco: PlayTics Deco 1.0
		probablychests: Probably Chests 0.5.5-1.19.2
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		realisticsleep: Realistic Sleep 1.6.0
		repurposed_structures: Repurposed Structures 6.1.3+1.19.2
		rottencreatures: Rotten Creatures 1.0.1
		roughlyenoughitems: Roughly Enough Items 9.1.580
			error_notifier: Error Notifier 1.0.9
		seasons: Fabric Seasons 1.4-BETA+1.19
		simplehats: SimpleHats 1.19.2-0.1.6
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		soulfired: Soul fire'd 3.0.0.0
		starterkit-fabric: Starter Kit (Fabric) 4.1
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0-beta.4
		supplementaries: Supplementaries 1.19.2-2.2.29
		t_and_t: Towns and Towers 1.10
			blue_endless_jankson: jankson 1.2.1
		takesapillage: Takes a Pillage 1.0.4
		terrablender: TerraBlender 2.0.1.130
		terralith: Terralith 2.3
		texelspaintings: TexelsPaintings 6.0.0
		the_bumblezone: The Bumblezone - Fabric 6.6.2+1.19.2
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tlc: The Lost Castle 1.0.0
		torchhit: Torch hit! 6.0.1.0
		totw_additions: Towers of the Wild: Additions 1.2.3
		transparentarmor: Transparent Armor 0.0.2-1.19
		transportables: Transportables 1.2.1
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.9
		treechop: HT's TreeChop 0.17.0
		trinkets: Trinkets 3.4.1
		tumbleweed: Tumbleweed 0.5.1
		twilightforest: The Twilight Forest 4.2.333
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			porting_lib: Porting Lib 2.1.642+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.642+1.19.2
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.642+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.642+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.642+1.19.2
				porting_lib_models: Porting Lib Models 2.1.642+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.642+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.642+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.642+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.642+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.642+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.642+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.642+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.642+1.19.2
						porting_lib_common: Porting Lib Common 2.1.642+1.19.2
		universalenchants: Universal Enchants 4.2.9
			extensibleenums: Extensible Enums 4.0.0
		unstructured: Unstructured 0.5.3+1.19.2
		untitledduckmod: Untitled Duck Mod 0.6.1
		variant_bookshelves: Variant Bookshelves 1.2.4
		variantcraftingtables: Variant Crafting Tables 3.2.9
		villagers-follow-emeralds: Villagers Follow Emeralds 1.3.0
		vinery: Vinery 1.1
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		wardenwalkers: Warden Walkers 1.1
		waystones: Waystones 11.1.0
		weaponmaster: YDM's Weapon Master 3.0.2
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.5
		woof: Woof 3.0.0-1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			owo: oωo 0.8.2+1.19
		wthit: wthit 5.13.4
		xaeroworldmap: Xaero's World Map 1.28.7
		xercamusic: Music Maker Mod fabric-1.19.2-1.0.1
		yigd: You're in Grave Danger 1.4.6
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: ComplementaryShaders_v4.6
		Profile: LOW (+4 options changed by user)
	NEC status: No NEC detected
	Flywheel Backend: Off

**Comment by haubna** [comment]
You need an active internet connection or you are sharing your code. You are not allowed to do so and this will result in a permanent ban.
