### ISSUE TITLE
Mod thinks Bees die when going in hive.

### ISSUE THREAD

**Issue by Ynaught** [haubna/PhysicsMod#55]
It's funny but it has to do with the ragdoll part of the mod. Whenever a Bee goes into a hive, it then spawns a dead bee ragdoll corps due to how the bee is removed from the world.

I can't seem to find any events to check if a Bee is entering a hive before spawning a corps.

**Comment by James103** [comment]
Same occurs for general entity despawning (i.e. a despawning zombie generates a "dead zombie" corpse), lightning (a villager struck by lightning generates a "dead villager" corpse when it shouldn't), and conversions between entity types (Zombie Villager -> Villager generates a "dead zombie villager" corpse, Piglin -> Zombified Piglin generates a "dead piglin" corpse).

**Comment by QAQlinmiao** [comment]
The problem seems to be no solution, because in Question 25 I have mentioned similar problems

**Comment by haubna** [comment]
No solution to this problem unfortunately.
