### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by Armaanxgill** [haubna/PhysicsMod#557]
**Describe the bug**
Snow not compatible with SEUS shader. Strange Shadow Values appear and vanish.

**To Reproduce**
Physics Mod
Sodium
Iris
SUES Shaders ( all types )

**Screenshots**

Minecraft Version: 1.19.2
Physics Mod Version: V114

**Comment by haubna** [comment]
Shader bug, try using another shaderpack.
