### ISSUE TITLE
One time purchase or subscription

### ISSUE THREAD

**Issue by TheZoidMaster** [haubna/PhysicsMod#559]
I really want to buy the pro version, but don't want it to get outdated, so I wanted to know, if I buy the pro version, do I get permanent access to the download, or is it subscription-based?

**Comment by haubna** [comment]
From the discord:
- Q: Can I still use it after the subscription has ended?
+ A: Yes you will be able to use it forever (as long as you don't lose the file or access to your patreon account). Just no new updates.
