### ISSUE TITLE
Ocean Rendering with modded liquids [BUG]

### ISSUE THREAD

**Issue by WenXin20** [haubna/PhysicsMod#560]
**Describe the bug**
- The Bumblezone's sugar water and other modded liquids don't render in the bumblezone dimension with ocean physics enabled. 
- Modded liquids render as water or won't render at all when placed in the overworld

**To Reproduce**
1. Use an ender pearl on a bee hive to teleport to the bumblezone
2. Find sugar water in the dimension
3. Place modded liquids in the overworld, such as [Bumblezone's](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge) sugar water or [Pokecube's](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi) Distortic Water

**Screenshots**
![image](https://user-images.githubusercontent.com/12000593/216133854-42bbcc5a-0563-4193-81dd-65336200f6a3.png)
![image](https://user-images.githubusercontent.com/12000593/216133879-c90ffc2f-5bbc-462f-ac81-303bae196fcd.png)
![image](https://user-images.githubusercontent.com/12000593/216134423-7e38e0fc-949a-435d-853b-3dc643b97dfc.png)

Minecraft: v1.19.2
Physics Mod: v116b
Rubidium: v0.6.2

**Comment by WenXin20** [comment]
It looks like water will render in modded dimensions now with the newest update, but modded liquids still render with the vanilla water texture

**Comment by haubna** [comment]
The system doesn't support multiple textures for water. No way to fix it, I will close this since the original issue is fixed.
