### ISSUE TITLE
Feature description [REQUEST]

### ISSUE THREAD

**Issue by Rhsurhsrjxr** [haubna/PhysicsMod#562]
Idea: When you make hewn wood, the bark falls out of it.

![maxresdefault_1](https://user-images.githubusercontent.com/89747212/216395504-89b23015-8dc1-4f2d-895b-e047ee76aa10.jpg)

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
