### ISSUE TITLE
[Render thread/ERROR]: Unreported exception thrown!

### ISSUE THREAD

**Issue by Baesir** [haubna/PhysicsMod#564]
Description: Minecraft crashes when "joining" world (single player)

To Reproduce: Try to load into your single player world with Physics Mod AND latest Sodium release (0.4.9)

Minecraft Version: 1.19.3 (Fabric Loader 0.14.14)
Physics Mod Version: Physics Mod Pro v116b Fabric

[2023-02-07-7.log](https://github.com/haubna/PhysicsMod/files/10672979/2023-02-07-7.log)

[crash-2023-02-07_02.54.31-client.txt](https://github.com/haubna/PhysicsMod/files/10672981/crash-2023-02-07_02.54.31-client.txt)

Edit: should have maybe put "Compatibility" label?

**Comment by haubna** [comment]
I just released v120 which fixes the compatibility with the newest Iris and Sodium version.
