### ISSUE TITLE
Possible crash related to the latest version [BUG]

### ISSUE THREAD

**Issue by ChromaPIE** [haubna/PhysicsMod#565]
**Describe the bug**
The game randomly crashes, mostly when trying to render items in EMI or REI. Can't stand a 2-minute messing around. Tried rolling back to the last version, played for a while without crashes. However it's still possibly an incompat issue with mods other than the mentioned ones.

**To Reproduce**
1. Have both the latest version of Physics and EMI/REI then launch the game, enter a world
2. Start messing around. Opening inventory, looting chests, stuff like that
3. Game will randomly commit a crash. If you have REI that crash screen will do a nice jumpscare and make your heart skip one beat or two. 

Minecraft Version: 1.19.2
Physics Mod Version: 2.10.2

**Comment by haubna** [comment]
Please include a crash log.

**Comment by ChromaPIE** [comment]
oops forgot about the log but it's not needed anymore. Crash happened again with 2.10.1 so maybe it's not even related to Physics. Closing it for now and if I found something new about it I'll do a follow up here.

**Comment by haubna** [comment]
Ok perfect!
