### ISSUE TITLE
Incompatible with Sodium 0.4.9 [Incompatibility]

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#566]
**Describe the bug**
Whenever you enter the world with Physics Mod and Sodium 0.4.9, the game instantly crashes with this crash report:
[crash-2023-02-08_19.52.41-client.txt](https://github.com/haubna/PhysicsMod/files/10685800/crash-2023-02-08_19.52.41-client.txt)

**To Reproduce**
1. Install Physics Mod, Sodium, and Fabric API
2. Launch Minecraft
3. Enter any world
4. *crashes*

Minecraft Version: 1.19.3
Physics Mod Version: 2.10.2

**Comment by haubna** [comment]
You are using Physics Mod 2.10.0, please update to 2.10.2

**Comment by NaiNonTH** [comment]
Ow, my bad.
