### ISSUE TITLE
Add fractured type of the Block Breaking/Sprinting/etc. Particles [REQUEST]

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#567]
**A description of the requested feature**
As I've suggested the Block Breaking Particle — #89, there's only one added: vanilla-like block breaking/sprinting particles. I mean, many block particle styles are added to this mod, so why not block-breaking particles too? It would be so great to see Minecraft particles completely realistic, both normal particles, breaking, sprinting, everything.

**Comment by haubna** [comment]
Block breaking particles as physics are in the game. I don't know what you mean.

**Comment by NaiNonTH** [comment]
Alright, I'm making it clear: add the fractured type of block sprinting/breaking particles; the existing one is only just the blocky type, so it would be great if there's another choice.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
