### ISSUE TITLE
Physics dosn't work on most block entities and TNT dosn't work [BUG]

### ISSUE THREAD

**Issue by zndrmn** [haubna/PhysicsMod#568]
**Describe the bug**
Physics dosn't work on most block entities and TNT dosn't work

**To Reproduce**
Place the blocks and break the blocks

**Screenshots**

https://user-images.githubusercontent.com/77690119/217566628-89b0cee9-89a7-4ea6-b98a-b2457499de3a.mp4

Minecraft Version: `1.19.3`
Physics Mod Version: `>=2.10.2`

**Comment by haubna** [comment]
Thanks for the report. I wasn't aware of that issue. Will be fixed in the next update!

**Comment by haubna** [comment]
Released 2.11.0 with the fix!
