### ISSUE TITLE
No "Get Code", so I can't use the PRO mod...

### ISSUE THREAD

**Issue by ksorah1** [haubna/PhysicsMod#569]
**Describe the bug**
The free version was working. I paid for the PRO version but nothing happend with the PRO version when I run the game...

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

Minecraft Version: 1.19.2
Physics Mod Version: [Physics Mod Pro V121 - Big Performance Improvements & Fixes](https://www.patreon.com/posts/physics-mod-pro-78450106)
Forge 43.2.0

**Comment by haubna** [comment]
Make sure to download it and remove the lite version from your mods folder! If you need further help join the discord mentioned in the patreon post!

**Comment by ksorah1** [comment]
Hello,

I have obviously removed the lite version. 

Besides I was using optifine, and to test I removed it, and instead I put :
Oculus 1.2.8a
Rubidium 0.6.2

And nothing else.

The PRO version I downloaded just doesn't work, it's like I didn't put anything in my mod directory (except Oculus and Rubidium)

![2023-02-09_175826](https://user-images.githubusercontent.com/112913359/217884446-96bdcca6-e694-479a-8910-3d65da30377f.jpg)

**Comment by haubna** [comment]
You have the fabric version installed but you need the forge version

**Comment by ksorah1** [comment]
Indeed...

I'm holding back from saying what I think about this... On the reasons for the error, the time lost... Thank you for help.

**Comment by ksorah1** [comment]
I had to play with Rubidium because your waves aren't working with optifine, but Rubidium has no "connected textures" support, so with the "Patrix" texture pack the grass for exemple is buggy and make all ugly...

That was a bad experience for me.

**Comment by haubna** [comment]
Have a look at https://lambdaurora.dev/optifine_alternatives/

**Comment by ksorah1** [comment]
Rubidium is already an alternative, the problem is that it does not support the "connected textures" or something, and cause this :
![2023-02-09_195334](https://user-images.githubusercontent.com/112913359/217909918-88f8d0ab-94aa-406f-922a-414ca63e884f.jpg)

**Comment by haubna** [comment]
I know, check out the link. You will probably have to switch to Fabric for a better experience.

**Comment by ksorah1** [comment]
Ah ok I will take a look tomorrow, thank you.

I had dropped fabric for other reasons, it never ends...

**Comment by ksorah1** [comment]
When I try to load Physics with Fabric (on a new clean install with multiMC), I get this :
![2023-02-10_101556](https://user-images.githubusercontent.com/112913359/218052224-ea6bf0a7-f796-4f30-9848-3b5104bc2a38.jpg)
![2023-02-10_101020](https://user-images.githubusercontent.com/112913359/218052233-c3121bff-f620-41e7-b075-e2d6c47f5c54.jpg)
![2023-02-10_101509](https://user-images.githubusercontent.com/112913359/218052239-9b439d51-1650-4293-984e-e9d3892fff06.jpg)

**Comment by haubna** [comment]
Install Fabric API

ksorah1 ***@***.***> schrieb am Fr. 10. Feb. 2023 um 10:17:

**Comment by ksorah1** [comment]
Ok with the continuity mod and plenty of other mods (sodium etc) it's finaly working, only 60/70fps with 3070ti instead of 90/100 with forge but working...

Thank you.
