### ISSUE TITLE
When a wall torch is broken it makes glitchy red fragments

### ISSUE THREAD

**Issue by GeoSingularity** [haubna/PhysicsMod#57]
This doesn't happen for torches on the ground
![2021-07-28_23 47 21](https://user-images.githubusercontent.com/88125324/127428403-80c6e218-c722-482b-9c14-2abb4190b3d3.png)

**Comment by haubna** [comment]
I will include other block options in the future which fixes this (not fracturing certain blocks).

**Comment by haubna** [comment]
Version 2.4.0 allows you to change the type of block fracturing for certain blocks. So you can change it to blocky for torches and this will fix it.
