### ISSUE TITLE
Ocean physics should be not be enabled if ice is covering the water

### ISSUE THREAD

**Issue by BLUEChester** [haubna/PhysicsMod#572]
In the images provided, you can see that ocean physics are taking a substantial amount of performance even though the water/ocean isn't visible at all. (The water/ocean is under the ice)

I marked this as a feature as I think there should be an option to 'disable ocean physics if ice block is above water'. Not sure if this is the right way to do it but I think there should be some sort of fix to this. Thanks for the mod, and this new debug menu is cool!
![image](https://user-images.githubusercontent.com/68225807/218255453-d048cfe0-a96a-4234-8c8b-3b1d9a6b9525.png)

![image](https://user-images.githubusercontent.com/68225807/218255439-04d48d66-5fee-497b-8d77-cc4eaf38774f.png)

**Comment by haubna** [comment]
Unfortunately the system is not designed to do so. I will however improve the CPU overhead significantly in future updates. But those are probably 3+ months away since my focus is currently on other features.

**Comment by BLUEChester** [comment]
No worries, it's definitely not the biggest issue and not a priority, no rush!

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
