### ISSUE TITLE
Morning Fog physics [REQUEST]

### ISSUE THREAD

**Issue by 1MiloAC** [haubna/PhysicsMod#573]
Fog physics, specifically so that in the mornings/evenings of the day it would be more foggy in general, but this fog would respond to physics, such as accumulate in low areas or enter into building if a block hole is open etc etc. Would dissipate by noon time.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
