### ISSUE TITLE
slowly add pro features [REQUEST]

### ISSUE THREAD

**Issue by daxasauras** [haubna/PhysicsMod#574]
**A description of the requested feature**
A clear and concise description of what the request is.
slowly add pro features to not pro and add better pro features like in 1.20 add physics for archaeology and add 1 (depending on how many more pro feature physics you add pro features to non pro

**Comment by daxasauras** [comment]
please

**Comment by FrozenDragon0** [comment]
Would be nice but I get the feeling this isn't gonna happen unfortunately.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
