### ISSUE TITLE
Dynamic blocks crashes game

### ISSUE THREAD

**Issue by DibsterPlayz** [haubna/PhysicsMod#575]
**Describe the bug**
When enabling dynamic blocks, my gpu and cpu go to 100% and my pc freezes up for a second and minecraft crashes. This has never happened before so it could be a version issue. My specs are i7-9700k, RTX 3070, 64GB Ram

**To Reproduce**
Enable dynamic blocks while using patrix 128x.

**Screenshots**
![Screenshot 2023-02-17 150257](https://user-images.githubusercontent.com/125700526/219792741-c08310da-4757-4fb6-999b-4732ba0577c9.png)

Minecraft Version: <1.19.2>
Physics Mod Version: <v121a fabric>
[latest.log](https://github.com/haubna/PhysicsMod/files/10771686/latest.log)

**Comment by haubna** [comment]
Try reducing your resource pack resolution.

**Comment by haubna** [comment]
This is most likely due to your game running out of memory (at least that are the same symptoms I get when running out of it).
