### ISSUE TITLE
Crash with version 2.11.0 (when exiting the game)

### ISSUE THREAD

**Issue by Aeldit** [haubna/PhysicsMod#576]
**Describe the bug**
The game crashes when clicking the Quit Game button

**To Reproduce**
Install the version 2.11.0 of the mod with the quilt loader

**Screenshots**
Here are the 2 parts of the log where the crash is mentioned
![image](https://user-images.githubusercontent.com/81476169/220750571-d8129389-c5f9-45df-9f76-5d1530a0a090.png)
![image](https://user-images.githubusercontent.com/81476169/220750678-6c837b27-5d54-4107-98f5-b86a616bebe0.png)

Minecraft Version: 1.19.3
Physics Mod Version: 2.11.0

**Comment by haubna** [comment]
2.11.1 which fixes those issues is now online on modrinth and my website. Curseforge will follow shortly. Thanks for the quick report!
