### ISSUE TITLE
Entire caves crumble above you [BUG]

### ISSUE THREAD

**Issue by DesertCookie** [haubna/PhysicsMod#577]
**Describe the bug**
When destroying a block, the majority of blocks around it will crumble too. Sometimes an entire cave will crumble around you until there's sky above.

**To Reproduce**
Install the mod with Fabric. Originally, we also had installed it in the server which we though might be causing the bug but after a full reinstall it still happens and it does so in singleplayer too.
 
Minecraft Version: 1.19.2
Physics Mod Version: 2.10.1 and 2.11.1
Fabric Version: 0.14.13 and 0.14.14

**Comment by haubna** [comment]
This is the collapse feature. You need to disable it in physics settings > collapse.

**Comment by DesertCookie** [comment]
Is this a client- or server-side option? I suspect the latter but if not I'm wondering why this is the default as it doesn't seem to be an intended behaviour and if every new user had to disable it on their end manually.

We'd started a new world and due to entire caves collapsing above us, we had multiple chests of stone and dirt within an hour of playing. That doesn't seem very realistic and unintuitive to me which is why I identified it as a bug initially.

Thanks a lot.
