### ISSUE TITLE
Bug description [BUG] Blood particles not existing

### ISSUE THREAD

**Issue by Herobattler** [haubna/PhysicsMod#578]
**Describe the bug**
There are no blood particles

**To Reproduce**
kill an animal in Minecraft

**Screenshots**

Minecraft Version: <version> 1.19.2
Physics Mod Version: <version>[2.11.2](https://www.curseforge.com/minecraft/mc-mods/physics-mod/files/4411401)

**Comment by haubna** [comment]
You need to set the ragdoll mode to ragdoll blood
