### ISSUE TITLE
This mod doesn't mesh well with OptiFabric

### ISSUE THREAD

**Issue by InfernoDigital** [haubna/PhysicsMod#58]
I use OptiFabric to use Optifine when playing on the Fabric loader, but using optifine and this mod in tandem breaks the animations for the physics particles, tying the particles and physics bodies to your head movement. If someone could take a look at it and fix that bug it would be epic, as this mod with optifine shaders looks amazing!

**Comment by haubna** [comment]
Optifine is not supported for Fabric. Future releases of Iris will be supported so I suggest using them!
