### ISSUE TITLE
Cloth Customization Not Working For Select Players

### ISSUE THREAD

**Issue by JoyousCreeper1059** [haubna/PhysicsMod#580]
**Describe the bug**
When you add a player to the cloth tab, it doesn't add them to the selection box.

**To Reproduce**
Press the change entity button, then type in their name, and press enter.

**Screenshots**
![image](https://user-images.githubusercontent.com/113858316/221388766-ba5c7847-9b3e-4f8d-b2e7-da774d95dc2f.png)
![image](https://user-images.githubusercontent.com/113858316/221388768-06d2776d-3a4d-4c4a-8570-535b12b4b56f.png)
![image](https://user-images.githubusercontent.com/113858316/221388769-f90f230d-9a01-4c4e-b51e-d77de6d56f33.png)

Minecraft Version: 1.18.2
Physics Mod Version: v127

**Comment by JoyousCreeper1059** [comment]
(I hope those images explain it well enough, if not, I can tamper with my recording software)

**Comment by haubna** [comment]
Fixed in V129 (I hope this is what you meant).
