### ISSUE TITLE
Support Apple Silicon Macs natively [REQUEST]

### ISSUE THREAD

**Issue by crystall1nedev** [haubna/PhysicsMod#582]
**A description of the requested feature**
This is basically a duplicate of past issues on this repository, however it's been a while since the last. physx-jni was updated to support compiling for ARM64 macOS machines, so now it's only down to this mod being updated to support Apple Silicon Macs without Rosetta.

I'm a Mac developer myself, and I understand that Rosetta is easy to use and helps relieve development, however it is not a long term solution. Apple created it to make the transition to Apple Silicon easier, and give time for developers to move their code to support ARM64. For this mod, the time is now. 

Using Rosetta tanks Minecraft performance because you need to run 2 JITs. Adding this mod makes it almost unusable. Natively, this mod can avoid those issues.

Please, update the libraries to what's currently available upstream.

**Comment by haubna** [comment]
Do not create duplicates, physx-jni for PhysX 4.1 didn't receive ARM64 macOS support.

**Comment by crystall1nedev** [comment]
But 0.4.13 did receive support, and #151 showed that it was possible to use that version with Physics Mod and have the game be playable, with the mod working as intended.
