### ISSUE TITLE
Using ocean physics alongside supported shaders results in it looking like a flat normal minecraft shader ocean

### ISSUE THREAD

**Issue by caligine1** [haubna/PhysicsMod#583]
It just looks like a normal shader ocean. The wave topology change is still there, I just cant see it. The ocean physics only works when I disable shaders.

I used complementary re-imagined, but any of the supported shaders causes the same issue. I'm using Oculus+Rubidium (Forge v43.2.0). I'm using an amd gpu.

![2023-02-28_21 43 37](https://user-images.githubusercontent.com/126641045/222042568-9bd373e4-22a0-4b0d-a6a9-9255739c017e.png)
![2023-02-28_21 43 08](https://user-images.githubusercontent.com/126641045/222042621-d96fe7d8-d80c-4de8-916f-d15ade94c978.png)

Minecraft Version: 1.19.2
Physics Mod Version: 130

**Comment by haubna** [comment]
Update to reimagined r2.0

caligine1 ***@***.***> schrieb am Mi. 1. März 2023 um 05:09:
