### ISSUE TITLE
Cannot get cloth elytra to display [BUG]

### ISSUE THREAD

**Issue by XDom367** [haubna/PhysicsMod#586]
**Describe the bug**
Cloth physics Elytra refuses to display in-game.

**To Reproduce**
I downloaded v131 Fabric, ran using Quilt 0.17.11 1.19.2, and this issue seems to not be a mod incompatibility but some sort of bug (due to the few mods I am using)

**Screenshot**
My current mods folder. This issue started with 170+ mods installed, I reduced my mods folder to major performance mods and it still persisted.

Minecraft Version: Quilt Loader v0.17.11 MC v1.19.2
Physics Mod Version: v131 Fabric
![image](https://user-images.githubusercontent.com/126047992/222338670-46a91d5c-3cc1-459f-9b1a-6c07f5d22a13.png)

**Comment by haubna** [comment]
Make sure to not have force armor enabled in cloth settings. You also need to equip an elytra.

**Comment by XDom367** [comment]
Thank you, solved
