### ISSUE TITLE
Crash With Confetti Creepers Server Plugin And Smoke Physics

### ISSUE THREAD

**Issue by JoyousCreeper1059** [haubna/PhysicsMod#587]
**Describe the bug**
When a confetti creeper explodes when smoke physics is enabled, the game freezes, then crashes.

**To Reproduce**
Go to a server with the Confetti Creepers plugin, and have a confetti creeper explode near you when smoke physics is enabled

**Log**
https://mclo.gs/Gkdku6S

Minecraft Version: 1.18.2
Physics Mod Version: v131

**Comment by haubna** [comment]
Fixed with v147
