### ISSUE TITLE
No valid patreon pledge

### ISSUE THREAD

**Issue by OGKingOhio** [haubna/PhysicsMod#588]
i copied code and paste it and it say no valid patreon pledge, i don't know why it say that, please remove verify code feature it annoying.

**Comment by haubna** [comment]
Make sure to wait a couple of minutes after buying it. Also very important to make sure you are logged in with the right account (not a creator account)!

**Comment by OGKingOhio** [comment]
Ok but it didn't work

**Comment by haubna** [comment]
Contact me on patreon

**Comment by OGKingOhio** [comment]
how i contact you? by the way i download pro for free, because i feel like 10 bucks is too much.
