### ISSUE TITLE
Cascade Breaking on by default and in the wrong category

### ISSUE THREAD

**Issue by labree** [haubna/PhysicsMod#590]
I used an older version of the mod and cascade breaking wasn't a thing by default so I never minded it, but recently I updated the mod since I switched launders to MultiMC. As I was working on my creative project in creative whenever I broke a block I placed by mistake it broke a huge chunk of my build and it annoyed me to no end. It took a whole goose chase to find the setting that caused this, and it's not even under the block physics tab which is not intuitive. I got the mod for the item physics and not the extra breaking/block physics like this. I highly suggest making this setting off by default since people that would like cascade breaking would likely look for it themselves. I also hope this gets to be under block physics as well instead of under server settings.

**Comment by haubna** [comment]
It was always on by default (in every single version of it) and I will keep this behaviour.
