### ISSUE TITLE
Dynamic blocks and Normal block at the same time

### ISSUE THREAD

**Issue by Deemitry88** [haubna/PhysicsMod#592]
**Describe the bug**
The Dynamic Block and the Vanilla Blocks are showing at the same time

**To Reproduce**
Place any Dynamic Block (door, sugar cane...) interact with it and voilà, Dynamic and Normal at the same time

**Screenshots**
![image](https://user-images.githubusercontent.com/91915462/223468915-229395d9-195c-47a6-9cf6-60076a1ebb7b.png)
![image](https://user-images.githubusercontent.com/91915462/223468975-769dbb80-dd68-4bdf-bc88-09bb9b3d3a4f.png)

Minecraft Version: 1.19.3
Physics Mod Version: V132

**Comment by ZakarTaylor** [comment]
this has been happening to me too and idk how to fix it either.

**Comment by haubna** [comment]
This happens when you use an incompatible mod or an outdated version of some mods. Try updating everything.

**Comment by Deemitry88** [comment]
> This happens when you use an incompatible mod or an outdated version of some mods. Try updating everything.

The only mod I had was the Physics mod (and fabric api)

**Comment by Deemitry88** [comment]
Fixed ! I just had to install sodium (and Indium)
