### ISSUE TITLE
Player cloth customization getting removed randomly [BUG]

### ISSUE THREAD

**Issue by shivam-choudhury513** [haubna/PhysicsMod#593]
I use the physics mod pro v131 with complementary shaders, in oculus, a port for iris in forge, and when I customize the cloth, it turns off randomly when I go a couple of chunks away from where I first applied the customizations.

I use the following mods

- Oculus
- Create
- Flywheel
- Physics Mod Pro
- Rubidium
- World Edit

Minecraft Version: <1.18.2>
Physics Mod Version: v131-Forge

**Comment by haubna** [comment]
This happens due to using multiple accounts. Make sure you don't share it.
