### ISSUE TITLE
Complementary shaders ocean rendering fault [BUG]

### ISSUE THREAD

**Issue by shivam-choudhury513** [haubna/PhysicsMod#594]
I use oculus with complementary shaders, a shader type I thought was compatible, but in random positions in the world, the ocean doesn't render and other ocean chunks around still render fine.
Minecraft Version: <1.18.2>
Physics Mod Version: v131-forge
<img width="883" alt="Screenshot 2023-03-09 at 7 26 32 AM" src="https://user-images.githubusercontent.com/85714212/224022984-071d4ce6-d447-4a9f-8d86-1dba7dcc5ff0.png">
sion>

**Comment by haubna** [comment]
This might be due to a problem with oculus. If you can consistently reproduce this with fabric + iris + sodium + the latest physics mod pro version please reopen the issue, thanks!
