### ISSUE TITLE
Ragdoll Velocity Slider [REQUEST]

### ISSUE THREAD

**Issue by IceBlossom** [haubna/PhysicsMod#596]
In version 2.9.6, the one I currently use, the ragdolls would get thrown really far. It was actually quite funny, and is one of the main reasons why I haven't updated to a later 1.19.2 version of the mod.

 So, I was wondering, if there could be a feature which changes how much ragdolls are affected when it gets thrown by a mob/player, or what happens to the mob when it dies. The default could be what is normally, and then this slider could, at the max, make even the lightest tap make bodies go across an, I don't know, 60 block area. 

As a gamer that likes funny ragdolls, this would be an amazing feature to add. Thank you :)

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
