### ISSUE TITLE
problème avec le code pro

### ISSUE THREAD

**Issue by samboss760** [haubna/PhysicsMod#602]
**Describe the bug**
j'ai acheté la version pro, mais impossible d'obtenir le code
il ne me donne pas le code ni dans la barre pour original ni dans l'url

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/24505412/224554409-2a39655a-1cfd-4819-b8aa-36a666b880c2.png)

Minecraft Version: 1.19.3
Physics Mod Version: v134

**Comment by haubna** [comment]
Contact me on patreon.
