### ISSUE TITLE
Updater thread uses 100% CPU for the lifetime of the client [BUG]

### ISSUE THREAD

**Issue by Ampflower** [haubna/PhysicsMod#603]
**Describe the bug**
Cloth Updater Thread at `net.diebuddies.physics.verlet.ClothUpdater.run()` is being ran constantly, presumably in a while/for true loop.

**To Reproduce**
- Start the game.
- Look at a task manager that can give which thread is using the CPU
- Alternatively, take a JFR dump.

**Screenshots**
![JFR view](https://cdn.discordapp.com/attachments/834483421068918785/1084551967633854645/image.png)
![htop](https://cdn.discordapp.com/attachments/834483421068918785/1084549745642577950/image.png)

Minecraft Version: 1.19.3
Physics Mod Version: 2.11.6, also occurred in 2.11.1

**Comment by haubna** [comment]
You are right, forgot to add a sleep to not stress the CPU, my bad! Will be fixed with 2.11.8!

**Comment by haubna** [comment]
Just released 2.11.8 containing the fix. Thanks for the report!
