### ISSUE TITLE
Bug with new version 135

### ISSUE THREAD

**Issue by TheVirusNVGM** [haubna/PhysicsMod#606]
**Describe the bug**
after update 135, I conducted crash tests and all kinds of calls to lower the fps, and noticed that when breaking a tree and mud with grass, the blocks take simple models, which was not in previous versions, and if I break blocks from modifications, then the lower texture of the tree is generally taken, the same with dirt from another mod - a random texture is taken. After I checked the eggs, I saw that they bounce in the default settings, but still set them to fragmentation and, as there were lags with a large number, they remained.

**To Reproduce**
start game with new mod version

**Screenshots**
![2023-03-13_16 17 11](https://user-images.githubusercontent.com/73340173/224715374-5651964b-6282-4392-9ae6-2d8932c56ec3.png)
![2023-03-13_16 17 12](https://user-images.githubusercontent.com/73340173/224715384-f2bd5776-b71b-424d-8477-adabe50c84d5.png)
![2023-03-13_16 19 37](https://user-images.githubusercontent.com/73340173/224715389-c065e905-f068-4cd1-a8f5-7cb6bef2ecec.png)
![2023-03-13_16 24 49](https://user-images.githubusercontent.com/73340173/224715391-7c008718-736a-4cfa-96f3-d730ebc9bde9.png)
![2023-03-13_16 17 06](https://user-images.githubusercontent.com/73340173/224715396-ae4d2405-9b22-48e6-83f1-1854d5c072ec.png)
![2023-03-13_16 17 08](https://user-images.githubusercontent.com/73340173/224715401-38638071-f0e6-49cf-8cc4-fe5af47e9e3f.png)

Minecraft Version: <version>
Physics Mod Version: 135

**Comment by haubna** [comment]
Closed due to duplicate.
