### ISSUE TITLE
Bug description: Triangle lighting glitch

### ISSUE THREAD

**Issue by Herobattler** [haubna/PhysicsMod#607]
**Describe the bug**
Triangle lighting glitch happening with block particles and ragdolls of entities

**To Reproduce**
Break blocks with particles enabled and kill entites with ragdoll selected.

**Screenshots**

Minecraft Version: 1.19.2
Physics Mod Version: Physics 2.11.8

**Comment by haubna** [comment]
Please provide screenshots and more information of your problem.

**Comment by Herobattler** [comment]
![2023-03-15_23 13 18](https://user-images.githubusercontent.com/109031824/225456131-dfc4ac63-f8b9-40fc-af1e-564e865763b2.png)

**Comment by Herobattler** [comment]
![2023-03-15_23 15 41](https://user-images.githubusercontent.com/109031824/225456512-06f5ecb2-482a-4f82-82ab-91f11c1f1b6a.png)

**Comment by haubna** [comment]
A list of the installed mods would also be helpful, thanks!

**Comment by Herobattler** [comment]
[Mods.txt](https://github.com/haubna/PhysicsMod/files/10985458/Mods.txt)

**Comment by Herobattler** [comment]
Shader used: https://www.curseforge.com/minecraft/customization/complementary-shaders/files

**Comment by haubna** [comment]
Changed it to compatibility due to it being a compatibility issue with Optifine.
