### ISSUE TITLE
Weird snow at render distance edge [COMPATABILITY]

### ISSUE THREAD

**Issue by XDom367** [haubna/PhysicsMod#609]
**Describe the bug**
There are some very funky-looking snow blocks at the edge of my render distance. This is mostly caused by the better FPS distance mod.

**To Reproduce**
I will include screenshots of my settings and mod folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/126047992/226127726-671e6ce5-46a0-4d49-bb82-491d99c86432.png)

![image](https://user-images.githubusercontent.com/126047992/226128017-99348532-cae1-48ad-be61-3b00248855c7.png)

![image](https://user-images.githubusercontent.com/126047992/226128152-a8036942-af4a-432c-b1d7-d560ef6a6eae.png)

Minecraft Version: 1.19.2 Fabric
Physics Mod Version: v140 1.19.2 Fabric

**Comment by XDom367** [comment]
I figured out that the better FPS distance mod mostly causes this issue. Turning this mod off helps significantly, but the very large blocks of snow are still there.

MOD ON:
![image](https://user-images.githubusercontent.com/126047992/226129323-5f75befc-64de-40b9-b5ab-13b61115f285.png)

MOD OFF:
![image](https://user-images.githubusercontent.com/126047992/226129330-026da47d-fd10-42de-abb5-51472ef062d4.png)

Maybe you should add this mod to the Known Incompatibilities channel.

**Comment by haubna** [comment]
The very large blocks are due to level of detail (improves performance). Increase it to get rid of the lower quality at far distances.
