### ISSUE TITLE
important features suggestion

### ISSUE THREAD

**Issue by Nicknaem** [haubna/PhysicsMod#61]
first of all, I just want to say thanks to you, this mod looks and works awesome
the mod seems pretty configurable but I'm missing two very important features in configuration 
one is to have ability to set custom collapse block count for whatever block I want, now count is global setting
  for example to set 2 blocks on top of destroyed stone block to fall
  and for trees to set 10 blocks to fall 
second feature is ability to set falling blocks random nubmer
  for example I have stone block settings like this:
  stone_block - collapseCount: 2, randomCount: 3
this time when destroying stone block, 2 more top blocks should fall automatically and 0, 1, 2, 3 blocks should be added to collapseCount randomly.
now on each stone block destroying you should get random collapse counts 2, 3, 4, 5

**Comment by haubna** [comment]
The collapsing feature will be reworked in the future. Currently the focus is on the physics side.
