### ISSUE TITLE
Clouds dissappear with  Shader + Ocean turned on [BUG]

### ISSUE THREAD

**Issue by Lendill** [haubna/PhysicsMod#612]
**Describe the bug**
Hi,
I currently use Minecraft 1.18.2 with Forge 40.2.0 +preview_OptiFine_1.18.2_HD_U_H9_pre2 + physics mod (newest) with complementary shader 4.7.1 (newest)

**To Reproduce**
Start the game, have ocean physics and shader activated and the clouds won´t appear. Turn ocean physics off and the clouds dissappear. 
The clouds only appear if ocean physics are completly turned off. Although if I toggle the water ripples setting on and off and back they appear for a second and then get disabled again. 

If I disable enable "use vanilla overlay" under /shaderoptions/sky it will show the clouds from the rp but with some other visual bugs:
![2023-03-24_11 35 10](https://user-images.githubusercontent.com/103329416/227499087-52bc618c-822e-4d6a-8402-6021fc8b4859.png)

**Screenshots**
- Added - 
![2023-03-24_11 16 44](https://user-images.githubusercontent.com/103329416/227495673-88385f4e-a81c-4fef-a6a8-c8f857869822.png)
![2023-03-24_11 16 53](https://user-images.githubusercontent.com/103329416/227495692-4da8434e-f408-4962-8726-13306feb28b4.png)

Minecraft Version: <version>
1.18.2 with Forge 40.2.0

Physics Mod Version: <version>
pro-v141-forge 1.18.2 (The one with optifine support)

**Comment by haubna** [comment]
Thanks for the report, update with fix will be uploaded on monday!

**Comment by haubna** [comment]
Fix is now online with V142
