### ISSUE TITLE
Crashed on loading screen with M1 Pro Ventura on 1.19.4 [BUG]

### ISSUE THREAD

**Issue by PsydameousSharm** [haubna/PhysicsMod#613]
When I load it it says

Physics Mod (physicsmod) has failed to load correctly 
Java.lang.reflect.InvocationTargetException:null

I tried disabling all other mods, but the same error still happened.

Minecraft Version: 1.19.4
Physics Mod Version: 2.11.10
[crash-2023-03-25_18.29.05-fml.txt](https://github.com/haubna/PhysicsMod/files/11070558/crash-2023-03-25_18.29.05-fml.txt)

**Comment by haubna** [comment]
M1/M2 Macs are currently not supported.

**Comment by PsydameousSharm** [comment]
I get that, but it did work for one login, but it stopped after I reopened it. Is there any way to have it run on my M1 pro?

**Comment by haubna** [comment]
For now you can try this: https://github.com/haubna/PhysicsMod/issues/461
Other than that you will have to wait for Minecraft 1.20. Physics Mod for Minecraft 1.20 will switch to a newer engine which supports M1 Macs!

**Comment by haubna** [comment]
Physics Mod 3.0.0 added Mac support.
