### ISSUE TITLE
Please add [Request]

### ISSUE THREAD

**Issue by DerbiXX** [haubna/PhysicsMod#614]
In the game on Minecraft servers and so on, after the destruction of blocks, as well as after the appearance of ragdolls. Ragdolls, blocks and other physical objects are not synchronized with other people, in a situation a player who is close to me does not see my block (ragdoll) located in one place or another, and I do not see that block (ragdoll) which the player sees. Please make a general physics of objects.

В игре на серверах майнкрафт и прочее, после разрушения блоков, так-же после появления рэгдолов. Рэгдоллы, блоки и прочие физ объекты не синхронизируются у других людей, в крации игрок находящийся близко ко мне не видит мой блок (рэгдолл) находящий в том или ином месте, а я не вижу тот блок (рэгдолл) который видит игрок. Просьба сделать общую физику объектов.

Minecraft Version: <1.19 1.18 1.17 1.16>
Physics Mod Version: <1.19 1.18 1.17 1.16>

**Comment by haubna** [comment]
Feature suggestions only in my discord please

**Comment by DerbiXX** [comment]
My nickname is in the DerbiXX discord, I will write soon and ask you to
notice me, because my offer is extremely important. In which of the
channels in the discord to write?

пн, 27 мар. 2023 г. в 13:17, haubna ***@***.***>:
