### ISSUE TITLE
Mob ragdolls and other death physics not showing [BUG]

### ISSUE THREAD

**Issue by icofs223** [haubna/PhysicsMod#615]
**Describe the bug**
Mob ragdolls and other death physics not showing, mobs when they die only disappear

**To Reproduce**
Simply kill a mob with any of the mob death physics settings enabled.

**Screenshots**
N/A

Minecraft Version: 1.19.4 fabric
Physics Mod Version: Latest Lite version for fabric

**Comment by haubna** [comment]
Yeah this was a bug in 2.11.10. Please download 2.11.10a.
