### ISSUE TITLE
Game crashes (EXCEPTION_ACCESS_VIOLATION) [BUG]

### ISSUE THREAD

**Issue by ciaens** [haubna/PhysicsMod#616]
**Describe the bug**
The game crashes.

**To Reproduce**
I really don't know. Sometimes it happens when I'm afk, or when I break a block.
The game does not crash at launch, but rather at a random moment, after more than 15/20 minutes of play.

Minecraft Version: <1.19.4>
Physics Mod Version: <2.11.10>

I didn't crash until recently (1 week). Maybe it due to a recent update.
I tested my pc stability and found no problem (memtest86, stress tests, etc).

Here are some logs, I didn't send all of them because they are pretty much the same.

[hs_err_pid3892.log](https://github.com/haubna/PhysicsMod/files/11073361/hs_err_pid3892.log)
[hs_err_pid9892.log](https://github.com/haubna/PhysicsMod/files/11073363/hs_err_pid9892.log)

Here is the only logs related to the mod I could find.
[infos.txt](https://github.com/haubna/PhysicsMod/files/11073397/infos.txt)

**Comment by haubna** [comment]
This is most likely a driver bug, make sure to update to the latest driver. Which GPU are you using?

**Comment by ciaens** [comment]
I'm using the latest nvidia driver (531.41), with a 40 series card. I also have the nvidia toolkit installed.

**Comment by haubna** [comment]
Which other mods are you using?

**Comment by haubna** [comment]
Ok I've identified an issue but I am not 100% sure if this will fix your crash. I will upload 2.11.11 with the fix in about an hour!

**Comment by haubna** [comment]
Update is now online on my website + modrinth (curseforge will follow shortly). Let me know if you still crash!

**Comment by ciaens** [comment]
Yes I do have a lot of mods. I'll test the new version and will let you know if I still crash. If I don't crash until next week I'll close this issue. Thx for your quick support.
  Here is the list :
  [✔] alternate-current-mc1.19-1.5.0
  [✔] animatica-0.5+1.19
  [✔] cem-0.7.3_S10_1.19.4
  [✔] cloth-config-10.0.96-fabric
  [✔] completeconfig-2.3.1
  [✔] continuity-3.0.0-beta.21.19.3
  [✔] CullLessLeaves-1.1.0
  [✔] dynamic-fps-2.2.0
  [✔] entity_texture_features_fabric_1.19.4-4.3.5
  [✔] entityculling-fabric-1.6.2-mc1.19.4
  [✔] fabric-language-kotlin-1.9.2+kotlin.1.8.10
  [✔] fabrishot-1.9.1
  [✔] fallingleaves-1.15.0+1.19.4
  [✔] glslmc-0.1.3
  [✔] ImmediatelyFast-1.1.11+1.19.4
  [✔] indium-1.0.15+mc1.19.4
  [✔] iris-mc1.19.4-1.6.0-beta.3
  [✔] krypton-0.2.2
  [✔] lambdabettergrass-1.5.0+1.19.4
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.19.4-0.11.1
  [✔] modmenu-6.1.0-rc.4
  [✔] MouseTweaks-fabric-mc1.19.4-2.24
  [✔] no-telemetry-1.7.0
  [✔] physics-mod-2.11.10a-mc-1.19.4-fabric
  [✔] qfapi-6.0.0-beta.2_qsl-5.0.0-beta.1_fapi-0.76.0_mc-1.19.4
  [✔] quilt_loading_screen-5.0.0+1.19.3-rc1
  [✔] reeses_sodium_options-1.5.0+mc1.19.4-build.72
  [✔] sodium-fabric-mc1.19.4-0.4.10+build.24
  [✔] soundphysics-fabric-1.19.4-1.1.0
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] visuality-0.7.0
  [✔] YetAnotherConfigLib-2.3.0
  [✔] Zoomify-2.9.2

**Comment by ciaens** [comment]
Well it's not a joke, but I crashed again. I first dismissed it on bad luck, but the crash report contains more info (it seems). 
I also changed jvm from Eclispe Adoptium to GraalVM.
I crashed when I toggled shaders off.
[hs_err_pid7732.log](https://github.com/haubna/PhysicsMod/files/11129258/hs_err_pid7732.log)

**Comment by ciaens** [comment]
Has no one seems to be crashing, I'll close this as it may be a specific problem with my config.
