### ISSUE TITLE
Patreon servers [BUG]

### ISSUE THREAD

**Issue by Miokzz** [haubna/PhysicsMod#618]
**Describe the bug**
Patreon server is bug?

**To Reproduce**
When I put the key at one and saying that the patreon servers are unstable what can I do to fix this (forge edition)

**Screenshots**
![image](https://user-images.githubusercontent.com/129634675/229325095-fc8d9f3a-114a-4ca7-9d12-fe7e3b74b3bb.png)

Minecraft Version: <1.19.4>
Physics Mod Version: <V.143>

**Comment by Maxime66410** [comment]
Same here !

**Comment by haubna** [comment]
Should be fixed by now (or you are using the wrong patreon account).
