### ISSUE TITLE
Always Time out [BUG]

### ISSUE THREAD

**Issue by Maxime66410** [haubna/PhysicsMod#619]
I just want enter Physics Mod Code.

-> Open Link
-> Get Code
-> Wait

![image](https://user-images.githubusercontent.com/37190601/229368877-9b9ee0e7-8d57-4792-a9f4-3f471d34d36c.png)
![image](https://user-images.githubusercontent.com/37190601/229368905-c6b2e36a-60e7-45f3-b672-6a4971f8310a.png)

Minecraft Version: 1.19.3 Forge 44.1.0
Physics Mod Version: v143 forge 1.19.3

**Comment by haubna** [comment]
Should be fixed by now (or you are using the wrong patreon account).
