### ISSUE TITLE
CPM Cloth Reset

### ISSUE THREAD

**Issue by JoyousCreeper1059** [haubna/PhysicsMod#621]
**Describe the bug**
Every time the game reloads the cloth (whether it be changing dimensions, or every 30 seconds), the cloth fully disappears, and doesn't come back

**To Reproduce**
Have a custom model equipped, and wait 30 seconds, and your cloth will disappear

Minecraft Version: 1.18.2
Physics Mod Version: v143c

**Comment by JoyousCreeper1059** [comment]
also happens on v146

**Comment by haubna** [comment]
Please place custom cloth in your cloth_local folder. You are placing it in the wrong folder.

**Comment by JoyousCreeper1059** [comment]
they're in the correct folder, it only happens when a custom model is active

**Comment by haubna** [comment]
Maybe you have another cloth piece equipped that doesn't allow for your custom one to be equipped.
