### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by AaronSalsa4k** [haubna/PhysicsMod#622]
**Describe the bug**
trapdoors appear to be bugged in the physics mod. Also, I'd like to add that I am using faithful x32

**To Reproduce**
not sure how to reproduce this bug, I was flying around to test the mod, came across a desert structure, (per the "terralith" biome/structure mod), and the spawned trapdoors in the structure were not in the correct position.
**Screenshots**
![2023-04-15_07 08 04](https://user-images.githubusercontent.com/130840629/232225334-a1d5972b-1593-4f25-a452-7efae0399088.png)

Minecraft Version: <1.19.4/fabric>
Physics Mod Version: <physics-mod-pro-v146-fabric-1.19.4> (newest)

**Comment by haubna** [comment]
This is due to the collision with fences. Simply disable collision for trapdoors under physics settings -> dynamic blocks -> customize.
