### ISSUE TITLE
Changes to Modrinth release

### ISSUE THREAD

**Issue by Boy0000** [haubna/PhysicsMod#625]
Would be nice if the Modrinth release versions described platform and mc-version
Since Modrinth lacks any sort of filtering of the "Notifications" screen, it gets rather tricky to find say fabric 1.19.4 versions
Suggest the release be as the image below but for example: `3.0.0-fabric-1.19.4` or some pattern that makes it easier knowing

![image](https://user-images.githubusercontent.com/62521371/232894033-fd2cfdb5-1bf2-4915-99ca-de4ead8de28e.png)

**Comment by haubna** [comment]
Isn't that an issue with modrinth itself? Check the download here it contains all the information about fabric/forge/quilt: https://modrinth.com/mod/physicsmod/version/CtkgyDWg
Adding it in the version would result in redundant data display which looks not so good in my opinion.

**Comment by Boy0000** [comment]
It is indeed a Modrinth issue but there have been issuws open for it for 1.5 years.
Talked to them again and they seem to finally be working on it now so might not be necessary

**Comment by haubna** [comment]
Perfect!
