### ISSUE TITLE
Game crash when the player dies [BUG]

### ISSUE THREAD

**Issue by turbomulot** [haubna/PhysicsMod#627]
**Describe the bug**
If you die while the physics mod is installed, your game will crash

**To Reproduce**
Kill yourself, the game will crash as soon as the game over menu appears

Minecraft Version: 1.19.2
Physics Mod Version: v148

**Comment by turbomulot** [comment]
[crash-2023-04-19_17.23.11-client.txt](https://github.com/haubna/PhysicsMod/files/11274784/crash-2023-04-19_17.23.11-client.txt)

**Comment by BlizzLee** [comment]
I too have been experiencing frequent crashing today. I disabled the Physics Mod and I am no longer having issues.
[crash-2023-04-19_21.31.47-client.txt](https://github.com/haubna/PhysicsMod/files/11277435/crash-2023-04-19_21.31.47-client.txt)

**Comment by RlackBights** [comment]
Just ran into the same problem today, a solution I found was disabling the physics for the players exclusively. This can be done in the Mob Settings, and after clicking on Customize at the bottom you can look up minecraft:player. Afterwards, you can just set the Physics Type off, this fixed it for me. Hope this helps!!

**Comment by haubna** [comment]
Fix is online with 2.12.2, sorry for the inconvenience!
