### ISSUE TITLE
Physics Mod causing frequent crashes (1.19.4)

### ISSUE THREAD

**Issue by BlizzLee** [haubna/PhysicsMod#628]
**Describe the bug**
When I attempt to join a server or create a new singleplayer world, my game decides to just crash. When I uninstall the Physics Mod I no longer have any issues.

**To Reproduce**
Try to join a server like Hypixel or create a new world

Minecraft Version: 1.19.4
Physics Mod Version: 3.0.1

I've decided to upload 2 crash logs. One for when I try to join a multiplayer server (Hypixel), and one for when I try to create a singleplayer world.
[Singleplayer Crash.txt](https://github.com/haubna/PhysicsMod/files/11277555/Singleplayer.Crash.txt)
[Server Crash.txt](https://github.com/haubna/PhysicsMod/files/11277556/Server.Crash.txt)

**Comment by haubna** [comment]
Fix is online with 2.12.2 and 3.0.2, sorry for the inconvenience! Also Physics Mod 3.0.1 is for Minecraft 1.20 and not Minecraft 1.19.4.
