### ISSUE TITLE
Game crashes after world loading to 100% M1 Max

### ISSUE THREAD

**Issue by RTQS1792** [haubna/PhysicsMod#629]
**Describe the bug**
The game will crash with this mod every time the world load to 100%. The error message is below:
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_8251 com.mojang.blaze3d.systems.RenderSystem.getVertexSorting()'
It seems like it is calling a function in the native game that doest exist ??

**To Reproduce**
Steps to reproduce the behavior.
Just download the mod and put it in the mod folder without any further action.

Minecraft Version: 1.19.4 (same issue after enable content from 1.20.4)
Physics Mod Version: 3.0.3

**Comment by RTQS1792** [comment]
I did try the method provided in the tutorial about M1 and M2 support and it still produces the same result
Link of tutorial: https://github.com/haubna/PhysicsMod/issues/461#issuecomment-1332775496

**Comment by RTQS1792** [comment]
I did try the method provided in the tutorial about M1 and M2 support and it still produces the same result
Link of tutorial: https://github.com/haubna/PhysicsMod/issues/461#issuecomment-1332775496

**Comment by RTQS1792** [comment]
I did try the method provided in the tutorial about M1 and M2 support and it still produces the same result
Link of tutorial: https://github.com/haubna/PhysicsMod/issues/461#issuecomment-1332775496

**Comment by haubna** [comment]
You need to use the Minecraft snapshots not 1.19.4
