### ISSUE TITLE
Launcher Crashes before open 

### ISSUE THREAD

**Issue by LowkieEric** [haubna/PhysicsMod#631]
**Describe the bug**
cant even open mc 

**To Reproduce**
download better MC modpack 1.19.2 and it should crash 

**Screenshots**
says exit 1 launcher crash 
Logs https://gyazo.com/bd269ca5d1d6dc0bc08eb85e45d32447

Minecraft Version: 1.19.2
Physics Mod Version: v149

**Comment by haubna** [comment]
Please make sure Iris + Sodium are the latest version (Iris 1.6.2).
