### ISSUE TITLE
Error creating ragdoll for bats [BUG]

### ISSUE THREAD

**Issue by ciaens** [haubna/PhysicsMod#632]
**Describe the bug**
The game freeze for dozens of seconds.

**To Reproduce**
Install Minecraft 1.19.4, Forge 45.0.49, Optifine HD U I4, Physics Mod (latest) for forge 1.19.4.
I'm using patrix rp, with freshanimations.

**Logs**
https://mclo.gs/OGd2TKT

Minecraft Version: 1.19.4
Physics Mod Version: v151 I suppose

**Comment by ciaens** [comment]
Related to freshanimation

**Comment by haubna** [comment]
Fresh Animations (and any kind of animation changing resource packs) are not supported.
