### ISSUE TITLE
Barrier block particles use physics [BUG]

### ISSUE THREAD

**Issue by JasonHorkles** [haubna/PhysicsMod#633]
**Describe the bug**
When holding a barrier block, the particles they spawn use physics so you can't actually see the barriers

**To Reproduce**
Place barriers and hold the barrier block

**Screenshots**
Without mod:
![image](https://user-images.githubusercontent.com/51760372/235324024-2509dd06-d078-4d36-8468-1ef3c6ac871d.png)

With mod active:
![image](https://user-images.githubusercontent.com/51760372/235324084-ab233a40-e263-4b3e-99da-61db41eea694.png)

---

Minecraft Version: 1.19.4
Physics Mod Version: 2.12.3

**Comment by haubna** [comment]
You can disable it yourself in blocks -> customize

**Comment by JasonHorkles** [comment]
I tried, didn't make a difference
