### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by lkwjwoxjj** [haubna/PhysicsMod#634]
When game load in this screen appear
![Screenshot_2023-05-01-13-31-24-55](https://user-images.githubusercontent.com/132251123/235417492-87f8a6e6-7d4a-482b-bfe5-1ba62db193ca.jpg)

Minecraft Version: <1.19.4>
Physics Mod Pro Version: <151> <152> also happened

**Comment by lkwjwoxjj** [comment]
@haubna pls help

**Comment by haubna** [comment]
MacOS is only supported with Minecraft 1.20

**Comment by lkwjwoxjj** [comment]
> MacOS is only supported with Minecraft 1.20

How can i play forge 1.20?
