### ISSUE TITLE
VertexBufferWriter Unexpected Error

### ISSUE THREAD

**Issue by Baesir** [haubna/PhysicsMod#635]
I load into my world, and after a little looking around the game saves and crashes.

Tested playing the game with and without Physics Mod 152, the error only occurs with the mod on. 

Crash log attached! 

[crash-2023-05-01_02.37.49-client.txt](https://github.com/haubna/PhysicsMod/files/11363948/crash-2023-05-01_02.37.49-client.txt)

Edit: Using the latest Soium + Iris + Indium

**Comment by MarkinSCode** [comment]
I have the same problem. Error appears when using Sodium 0.4.11

**Comment by EduardoJauch** [comment]
I confirm. Just upgraded sodium/iris/indium to the latest version and Physics Mod (Pro) crashes the game. In my case, when trying to load it.

**Comment by emongev** [comment]
Im having the same issue, though it happens only when theres rain, and it started happening recently when i updated sodium and iris.
