### ISSUE TITLE
Game crashing upon joining a world [BUG]

### ISSUE THREAD

**Issue by BlackDiamond3180** [haubna/PhysicsMod#636]
**Describe the bug**
My game simply crashes no matter what world I load into..
**To Reproduce**
Add Iris and sodium mods together with the replay mod and the Physics mod and then load into a game (It could also just be that I am using an AMD GPU (the 6700xt)) 

Minecraft Version: <1.19.4>
Physics Mod Version: <3.0.3-mc-23w16a>

**Comment by haubna** [comment]
Fixed with the latest versions
