### ISSUE TITLE
Enabling ocean option breaks lighting [BUG]

### ISSUE THREAD

**Issue by Telezhka-the-First** [haubna/PhysicsMod#640]
**Description**
For some reason enabling Ocean option of this mod breaks handheld item lighting. As only the option is disabled or during the first second of it being enabled, lighting works fine. The problem is definitely not in RAM. Disabling and turning to the absolute minimum every option in the Ocean category doesn't change the situation. Ocean itself seems to work as intended.

**To Reproduce**

1) Install the mods I used.
[mod_list.txt](https://github.com/haubna/PhysicsMod/files/11392525/mod_list.txt)
2) Toggle Ocean option on and off to observe the issue.

**Screenshots**
![2023-05-04_05 39 12](https://user-images.githubusercontent.com/90337398/236099514-8712c4ea-0bb8-464a-a409-10e7f624ac7a.png)

![2023-05-04_05 39 51](https://user-images.githubusercontent.com/90337398/236099479-33cb3664-e2cf-4bd2-9ac8-c4888b23f7f2.png)

![2023-05-04_05 40 34](https://user-images.githubusercontent.com/90337398/236099424-67a2471f-ac2c-41ce-9bea-9c1c238ada0e.png)

Minecraft Version: 1.19.2
Physics Mod Version: Physics Mod Pro v153 Forge 1.19.2

**Comment by haubna** [comment]
This should be fixed by now
