### ISSUE TITLE
Adding a one block tall block doesn't affect "Dynamics Blocks" with player interaction

### ISSUE THREAD

**Issue by HARYA301** [haubna/PhysicsMod#641]
**Describe the bug**
When you try add a one block tall block witht the Customize setting in "Dynamics Blocks", the block doesn't get affect by player when it walks close to the block unlike tall grass block which does.

**To Reproduce**
Go to "dynamics blocks", then "Customize", then add a block like grass, after match with physic style to "Vine", match the setting as close as possible to tall grass. Look in game and notice it doesn't work.

Minecraft Version: 1.19.4
Physics Mod Version: Pro 153b

**Comment by haubna** [comment]
This is not a bug but intended. You would be able to push it inside blocks which is not good.

**Comment by HARYA301** [comment]
Well you could limitate this for vegetation only
