### ISSUE TITLE
Trapdoors are buggy when on top of fences

### ISSUE THREAD

**Issue by Garwinium** [haubna/PhysicsMod#647]
**Describe the bug**
Trapdoors go positively wacky when placed on top of fences

**To Reproduce**
Place a trapdoor on top of a fence

**Screenshots**
![image](https://user-images.githubusercontent.com/92835818/236961759-a325b2bb-a66f-401e-b40d-76689385783a.png)
![image](https://user-images.githubusercontent.com/92835818/236961900-76c87412-e797-469d-9e38-c3f6b8c72987.png)

Minecraft Version: 1.19.4
Physics Mod Version: 2.12.4 Fabric

If I had to guess this is prolly being caused by fences having 1.5 block high hitboxes, so maybe physics objects could treat them as having 1 block high hitboxes? (assuming that this is the problem ofc)

**Comment by haubna** [comment]
Disable collisions for them in dynamic blocks > customize
