### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaSlime123** [haubna/PhysicsMod#648]
**Describe the bug**
Game crashes.

**To Reproduce**
Start the game.

**Screenshots**
N/A.

Minecraft Version: <version>
Physics Mod Version: You made your Pro version public (which you should've done when posting this mod and should know by MC's EULA terms.), which was nice.
![image](https://user-images.githubusercontent.com/51277766/236977197-aa8222a0-acbc-4c07-ad72-260508b53b9f.png)

**Comment by haubna** [comment]
No crash log included

**Comment by MagmaSlime123** [comment]
None is provided. I can give a log if wanted.
