### ISSUE TITLE
Mob and block settings reset sometimes

### ISSUE THREAD

**Issue by CrispyMuffin** [haubna/PhysicsMod#65]
changing mob and block behavior with the mod can be pretty tedious, so its a bit annoying that these settings seem to reset every now and then. it could be happening everytime i install a new mod, cause it was fine yesterday, but reset after i installed a minor mod this morning.

while im at it, do you think it'd be possible to add a filter to the list? like hostile/friendly mobs, undead, nether, etc? if not, would it be possible to add an image next to each mob/block in the list? it would make the process a lot easier. the pictures are already in the game, so i'd guess it would be possible to add it?

**Comment by haubna** [comment]
I've changed the config folder in a previous update that's why the settings were reset. I won't add pictures but I will probably add a search feature in the future.

**Comment by haubna** [comment]
Added a search box in version 2.4.5 for all settings menues.
