### ISSUE TITLE
Particles bug

### ISSUE THREAD

**Issue by Mrgaton** [haubna/PhysicsMod#650]
**Describe the bug**
Minecraft crash when entering on the sea when the particle of the splash

**To Reproduce**
Splash yourself into the water.

Physics Mod Version: physics-mod-pro-v153-fabric-1.19.2

[message (6).txt](https://github.com/haubna/PhysicsMod/files/11445953/message.6.txt)
n>

**Comment by haubna** [comment]
Don't mismatch versions of the mod. Tested setups can be found here: https://minecraftphysicsmod.com/installation
