### ISSUE TITLE
Shader and Ocean Physics running at same time = game crash

### ISSUE THREAD

**Issue by Shrinkiatrist** [haubna/PhysicsMod#651]
My game will crash if a shader and ocean physics are running at the same time. Either one alone works fine, but as soon as I run the other the game will crash. I've tested compatibility with 5 different shaders, but I always get the same error message with this accompanying crash report:

![Screenshot 2023-05-10 183858](https://github.com/haubna/PhysicsMod/assets/133179543/67b505b9-925c-426d-81db-71d9589ca101)

[Crash Report.txt](https://github.com/haubna/PhysicsMod/files/11447362/Crash.Report.txt)

Mod List:
fabric-api-0.80.0+1.19.4
modmenu-6.2.2
optifabric-1.13.24
optifine_1.19.4

Minecraft Version: 1.19.4 fabric and optifine
Physics Mod Version: v153b-fabric-1.19.4

**Comment by Mrgaton** [comment]
i got similar crash but only when entering the sea when the particles are maded

**Comment by haubna** [comment]
Optifabric is not supported
