### ISSUE TITLE
Crashing when any shader used with optifine.

### ISSUE THREAD

**Issue by Mahadbaloch** [haubna/PhysicsMod#652]
Also heavily distorts screen and changing shader in main menu either fixes it or screen goes gray permanently.
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-05-11 15:26:00
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.optifine.shaders.Program.getAlphaState()" because "programNew" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.optifine.shaders.Shaders.updateAlphaBlend(Shaders.java:4356)
	at net.optifine.shaders.Shaders.useProgram(Shaders.java:4020)
	at net.diebuddies.compat.Optifine.useOceanShadowShader(Optifine.java:219)
	at net.diebuddies.render.OceanRenderer.bindOceanShader(OceanRenderer.java:349)
	at net.diebuddies.render.OceanRenderer.render(OceanRenderer.java:113)
	at net.diebuddies.render.LiquidRenderer.render(LiquidRenderer.java:80)
	at net.diebuddies.render.MainRenderer.renderLiquid(MainRenderer.java:719)
	at net.minecraft.client.render.WorldRenderer.handler$ddg000$renderLiquid(WorldRenderer:8489)
	at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:608)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4995)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1505)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:1191)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.shaders.Shaders.updateAlphaBlend(Shaders.java:4356)
	at net.optifine.shaders.Shaders.useProgram(Shaders.java:4020)
	at net.diebuddies.compat.Optifine.useOceanShadowShader(Optifine.java:219)
	at net.diebuddies.render.OceanRenderer.bindOceanShader(OceanRenderer.java:349)
	at net.diebuddies.render.OceanRenderer.render(OceanRenderer.java:113)
	at net.diebuddies.render.LiquidRenderer.render(LiquidRenderer.java:80)
	at net.diebuddies.render.MainRenderer.renderLiquid(MainRenderer.java:719)
	at net.minecraft.class_761.handler$ddg000$renderLiquid(class_761.java:8489)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:608)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4995)
	at net.minecraft.class_757.method_3188(class_757.java:1505)

-- Affected level --
Details:
	All players: 1 total; [class_746['mahadblackhole'/18, l='ClientLevel', x=-24.16, y=64.00, z=-296.25]]
	Chunk stats: 1369, 929
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,46,0), Section: (at 0,14,0 in 0,2,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4199087 game time, 7678 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:580)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: Default, FreshAnimations_v1.7.zip, §e§l§k.zip+§6§lRe-Archery+§e§l§k.zip, EmbellishedStone-1.19-1.0.0.zip, STONEBORN+-+1.19+-+V3.1.zip, witchrework.zip, creepermax123-s-jellyfish.zip, creepermax123-s-better-spiders.zip, Detailed_Hearts_(1.18-1.18.1).zip, CreeperLoadingScreen.zip, 6hell-epack.zip, Magical_Bookshelves_(v1).zip, Vanilla-PBR-1-3-0.zip, Golem's+Family.zip, Better+Campfire+1.19.zip, genshinelytra.zip, pigeons, connectibles-e1140.zip, Totemlotl, Spyglass+of+memes+v2.zip, Fabric Mods, minecraft/physicsmod, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 587155312 bytes (559 MiB) / 3154116608 bytes (3008 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GT 745A
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x0fe3
	Graphics card #0 versionInfo: DriverVersion=25.21.14.2531
	Graphics card #1 name: Intel(R) HD Graphics 4600
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0412
	Graphics card #1 versionInfo: DriverVersion=20.19.15.4380
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 24999.28
	Virtual memory used (MB): 15948.43
	Swap memory total (MB): 8701.95
	Swap memory used (MB): 201.54
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.1.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		advancementplaques: Advancement Plaques 1.4.6
		adventurez: AdventureZ 1.4.16
		alloy_forgery: Alloy Forgery 2.0.16+1.19
		ambientsounds: Ambient Sounds (Fabric) 5.2.5
		architectury: Architectury 6.3.49
		auditory: Auditory 0.0.3-1.19.x
		bclib: BCLib 2.1.2
		bettercombat: Better Combat 1.4.5+1.19
		betterend: Better End 2.1.1
		bettersculksensor: BetterSculkSensor 1.1.8
		betterthirdperson: Better Third Person 1.9.0
		bookshelf: Bookshelf 16.1.11
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		capybara: Capybara 1.0.8
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carpet: Carpet Mod 1.4.84
		charmofundying: Charm of Undying 6.0.0+1.19.2
		chiseled-bricks: Chiseled Bricks 1.2-1.19
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 5.11
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.2+1.19.2
			spectrelib: SpectreLib 0.10.0+1.19
		connectiblechains: Connectible Chains 2.1.3+1.19.2
		crawl: Crawl 0.11.1
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.8.5
		diagonalfences: Diagonal Fences 4.2.3
		display_case: Display Case Mod 1.0.3
		do_a_barrel_roll: Do a Barrel Roll 2.2.0+1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.1.0-rc5
		dsurround: Dynamic Surroundings: Remastered Fabric Edition 0.1.0
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		easyanvils: Easy Anvils 4.0.5
		easymagic: Easy Magic 4.3.2
		ecologics: Ecologics 2.1.10
		edenring: EdenRing 0.6.4
		effective: Effective 1.3
			midnightlib: MidnightLib 0.5.2
		enchdesc: EnchantmentDescriptions 13.0.3
		endrem: End Remastered 5.2.0
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.5.11
		geckolib3: Geckolib 3.1.29
			com_eliotlash_mclib_mclib: mclib 19
		geodes: More Geodes 1.5.1
		ghastly_wail: Ghastly Wail 1.1.1
		giantspawn-fabric: Giant Spawn (Fabric) 3.3
		glowingbanners: Glow Banners 1.2.0
		grindenchantments: Grind Enchantments 2.0.0+1.19.2
		guicompass-fabric: GUI Compass (Fabric) 2.8
		iceberg: Iceberg 1.0.46
		itemscroller: Item Scroller 0.17.1
		java: OpenJDK 64-Bit Server VM 17
		jumpyboat: Jumpy boat 3.0-1.19
		malilib: MaLiLib 0.13.0
		megachicken: Megachicken 1.0.3
		megaparrot: Megaparrot 1.0.7-1.19.2
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		mythicmetals: Mythic Metals 0.16.4+1.19.2
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		optifabric: OptiFabric 1.13.16
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
		physicsmod: Physics Mod 2.12.4
		player-animator: Player Animator 0.3.5
		presencefootsteps: Presence Footsteps 1.6.2
			kirin: Kirin UI 1.11.1
		puzzleslib: Puzzles Lib 4.3.12
		reinfchest: Reinforced Chests 2.2.0+1.19
			reinfcore: Reinforced Core 3.0.3+1.19
		reinfshulker: Reinforced Shulker Boxes 2.2.0+1.19
		replaymod: Replay Mod 1.19.1-2.6.8
		roughlyenoughitems: Roughly Enough Items 9.1.562
			error_notifier: Error Notifier 1.0.9
		shouldersurfing: Shoulder Surfing Reloaded 2.2.18
		skylorlib: SkyLib 1.5.1
		soulsweapons: Marium's Soulslike Weaponry 0.9.6
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.15
		spiderstpo: Spiders 2.0 1.19.2-2.0.2
		structory: Structory 1.0.1
		tlc: The Lost Castle 1.0.0
		tlskincape: TLSkinCape 1.27
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tooltipscroller: Tooltip Texts Scroller 1.0.0
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		trinkets: Trinkets 3.4.0
		untitledduckmod: Untitled Duck Mod 0.6.1
		visualworkbench: Visual Workbench 4.2.0
		voidz: VoidZ 1.0.9
		xaeroworldmap: Xaero's World Map 1.30.1
	Launched Version: Fabric 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce GT 745A/PCIe/SSE2 GL version 3.2.0 NVIDIA 425.31, NVIDIA Corporation
	Window size: 925x530
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/FreshAnimations_v1.7.zip, file/§e§l§k.zip+§6§lRe-Archery+§e§l§k.zip (incompatible), file/EmbellishedStone-1.19-1.0.0.zip, file/STONEBORN+-+1.19+-+V3.1.zip, file/witchrework.zip (incompatible), file/creepermax123-s-jellyfish.zip (incompatible), file/creepermax123-s-better-spiders.zip (incompatible), file/Detailed_Hearts_(1.18-1.18.1).zip (incompatible), file/CreeperLoadingScreen.zip (incompatible), file/6hell-epack.zip (incompatible), file/Magical_Bookshelves_(v1).zip (incompatible), file/Vanilla-PBR-1-3-0.zip, file/Golem's+Family.zip, file/Better+Campfire+1.19.zip, file/genshinelytra.zip (incompatible), file/pigeons, file/connectibles-e1140.zip (incompatible), file/Totemlotl (incompatible), file/Spyglass+of+memes+v2.zip (incompatible), Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['mahadblackhole'/18, l='ServerLevel[Creativing]', x=-24.16, y=64.00, z=-296.25]]
	Data Packs: vanilla, Fabric Mods, file/New-Desert-Temple.zip (incompatible)
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Enhanced+Default+v1.14+Fancy.zip
	OpenGlVersion: 3.2.0 NVIDIA 425.31
	OpenGlRenderer: GeForce GT 745A/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	Suspected Mods: Physics Mod (physicsmod), Minecraft (minecraft), Fabric Loader (fabricloader)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.2
	OptiFine jar version: OptiFine_1.19.2_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/uzair/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.2_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>

![n](https://github.com/haubna/PhysicsMod/assets/110735899/50ffffb6-8b22-4f09-9762-3ab8ee8d0883)

This was my actual screen when I turn ocean physics on(all water invisible instantly then crash). I tested the features and ocean physics seem to be causing the crash with every shader. Even the ones supposed to be compatible. Is there a shader setting im supposed to change?

**Comment by haubna** [comment]
Optifabric is not supported
