### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by Shrinkiatrist** [haubna/PhysicsMod#655]
Game will crash on launch if physics mod is in mods folder. Error message and crash report:

![Error](https://github.com/haubna/PhysicsMod/assets/133179543/b6162f25-3f59-49e6-b339-d880755ba471)

[Crash Report.txt](https://github.com/haubna/PhysicsMod/files/11456970/Crash.Report.txt)

Mod folder:
fabric api 0.80.0
iris 1.6.1
sodium 0.4.10

Minecraft Version: 1.19.4 (fabric loader 0.14.19)
Physics Mod Version: pro v153b fabric 1.19.4

**Comment by haubna** [comment]
V153 is for Sodium 0.4.11 (which got removed due to bugs). Stick to V152 for now.
