### ISSUE TITLE
Game crash with sodium

### ISSUE THREAD

**Issue by 1JackBean** [haubna/PhysicsMod#656]
**Describe the bug**
Game Crashes when Sodium and Physics mod are loaded together 

**To Reproduce**
have sodium and physics mod in mod folder then join world

Minecraft Version: <1.19.4>
Physics Mod Version: <2.12.4>

**Comment by Tursiops-G** [comment]
Try going back to Physics Mod Ver. 2.12.3
It appears that version 2.12.4 has been pulled from distribution.

**Comment by haubna** [comment]
2.12.4 is for Sodium 0.4.11 (which got removed due to bugs). Stick to 2.12.3 for now.
