### ISSUE TITLE
**Pojavlauncher** with **phisic mod pro (fabric)** and fabric api is crashing

### ISSUE THREAD

**Issue by adex345** [haubna/PhysicsMod#658]
1. Log: 
``` --------- beginning with launcher debug Info: Launcher version: LOCAL-20230508 Info: Architecture: arm64 Info: Device model: vivo V2041 Info: API version: 33 Info: Selected Minecraft version: fabric-loader-0.14.19-1.19.2 Info: Custom Java arguments: "" logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. logcat: Unexpected EOF! This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log messages as quickly as they were being produced. If you have enabled significant logging, look into using the -G option to increase log buffer sizes. ERROR: Unable to get more log. Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache Added custom env: AWTSTUB_WIDTH=1054 Added custom env: FORCE_VSYNC=false Added custom env: POJAV_NATIVEDIR=/data/app/~~pPRgVmgESbX8WSJYMMSfBA==/net.kdt.pojavlaunch.debug-NRzF6udywUjIAPrRZ7VLcA==/lib/arm64 Added custom env: REGAL_GL_VERSION=4.5 Added custom env: REGAL_GL_VENDOR=Android Added custom env: LIBGL_MIPMAP=3 Added custom env: allow_higher_compat_version=true Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin Added custom env: LIBGL_NOINTOVLHACK=1 Added custom env: force_glsl_extensions_warn=true Added custom env: LIBGL_NORMALIZE=1 Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~pPRgVmgESbX8WSJYMMSfBA==/net.kdt.pojavlaunch.debug-NRzF6udywUjIAPrRZ7VLcA==/lib/arm64 Added custom env: POJAV_RENDERER=opengles2 Added custom env: LIBGL_ES=2 Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink Added custom env: MESA_GLSL_VERSION_OVERRIDE=460 Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17 Added custom env: MESA_GL_VERSION_OVERRIDE=4.6 Added custom env: allow_glsl_extension_directive_midshader=true Added custom env: REGAL_GL_RENDERER=Regal Added custom env: AWTSTUB_HEIGHT=486 Initialising gl4es v1.1.5 built on Apr 10 2023 22:23:50 Using GLES 2.0 backend loaded: libGLESv2.so loaded: libEGL.so Using GLES 2.0 backend Hardware Full NPOT detected and used Extension GL_EXT_blend_minmax detected and used FBO are in core, and so used PointSprite are in core, and so used CubeMap are in core, and so used BlendColor is in core, and so used Blend Subtract is in core, and so used Blend Function and Equation Separation is in core, and so used Texture Mirrored Repeat is in core, and so used Extension GL_OES_mapbuffer detected Extension GL_OES_element_index_uint detected and used Extension GL_OES_packed_depth_stencil detected and used Extension GL_OES_depth24 detected and used Extension GL_OES_rgb8_rgba8 detected and used Extension GL_EXT_texture_format_BGRA8888 detected and used Extension GL_OES_depth_texture detected and used Extension GL_OES_texture_stencil8 detected and used Extension GL_EXT_texture_rg detected and used Extension GL_EXT_color_buffer_float detected and used Extension GL_EXT_color_buffer_half_float detected and used high precision float in fragment shader available and used Max vertex attrib: 32 Extension GL_OES_standard_derivatives detected and used Extension GL_ARM_shader_framebuffer_fetch detected and used Extension GL_OES_get_program_binary detected and used Number of supported Program Binary Format: 1 Max texture size: 16383 Max Varying Vector: 31 Texture Units: 16/16 (hardware: 128), Max lights: 8, Max planes: 6 Extension GL_EXT_texture_filter_anisotropic detected and used Max Anisotropic filtering: 16 Hardware vendor is ARM GLSL 300 es supported GLSL 310 es supported and used GLSL 320 es supported Max Color Attachments: 8 / Draw buffers: 8 sRGB surface supported EGLImage to Texture2D supported EGLImage to RenderBuffer supported ignore MipMap Targeting OpenGL 2.1 No hack in shader converter to define overloaded function with int Not trying to batch small subsequent glDrawXXXX try to use VBO glXMakeCurrent FBO workaround enabled FBO workaround for using binded texture enabled Force texture for Attachment color0 on FBO Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done Force normals to be normalized on FPE shaders glX Will try to recycle EGL Surface Current folder is:/ 2023-05-17 12:30:17,015 main ERROR appender Console has no parameter that matches element Policies [12:30:17] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19 [12:30:17] [main/INFO]: Loading 59 mods: 	- catalogue 1.7.0-1.19.2 	- fabric-api 0.76.0+1.19.2 	 |-- fabric-api-base 0.4.15+8f4e8eb390 	 |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 	 |-- fabric-biome-api-v1 9.1.1+16f1e31390 	 |-- fabric-block-api-v1 1.0.2+e415d50e90 	 |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90 	 |-- fabric-client-tags-api-v1 1.0.5+b35fea8390 	 |-- fabric-command-api-v1 1.2.16+f71b366f90 	 |-- fabric-command-api-v2 2.2.1+413cbbc790 	 |-- fabric-commands-v0 0.2.33+df3654b390 	 |-- fabric-containers-v0 0.1.41+df3654b390 	 |-- fabric-content-registries-v0 3.5.2+7c6cd14d90 	 |-- fabric-convention-tags-v1 1.3.0+4bc6e26290 	 |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 	 |-- fabric-data-generation-api-v1 5.3.8+413cbbc790 	 |-- fabric-dimensions-v1 2.1.35+0d0f210290 	 |-- fabric-entity-events-v1 1.5.4+9244241690 	 |-- fabric-events-interaction-v0 0.4.34+562bff6e90 	 |-- fabric-events-lifecycle-v0 0.2.36+df3654b390 	 |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490 	 |-- fabric-item-api-v1 1.6.6+b7d1888890 	 |-- fabric-item-groups-v0 0.3.39+9244241690 	 |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890 	 |-- fabric-keybindings-v0 0.2.23+df3654b390 	 |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 	 |-- fabric-loot-api-v2 1.1.13+83a8659290 	 |-- fabric-loot-tables-v1 1.1.16+9e7660c690 	 |-- fabric-message-api-v1 5.0.7+93d8cb8290 	 |-- fabric-mining-level-api-v1 2.1.24+33fbc73890 	 |-- fabric-models-v0 0.3.21+c6af733c90 	 |-- fabric-networking-api-v1 1.2.11+10eb22f490 	 |-- fabric-networking-v0 0.3.28+df3654b390 	 |-- fabric-object-builder-api-v1 4.2.2+d8ef690890 	 |-- fabric-particles-v1 1.0.14+4d0d570390 	 |-- fabric-recipe-api-v1 1.0.1+413cbbc790 	 |-- fabric-registry-sync-v0 0.9.32+9244241690 	 |-- fabric-renderer-api-v1 1.2.1+1adbf27790 	 |-- fabric-renderer-indigo 0.8.0+1adbf27790 	 |-- fabric-renderer-registries-v1 3.2.24+df3654b390 	 |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 	 |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390 	 |-- fabric-rendering-v0 1.1.27+df3654b390 	 |-- fabric-rendering-v1 1.12.1+d8ef690890 	 |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 	 |-- fabric-resource-loader-v0 0.8.4+edbdcddb90 	 |-- fabric-screen-api-v1 1.0.32+4d0d570390 	 |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 	 |-- fabric-sound-api-v1 1.0.2+c4f28df590 	 |-- fabric-textures-v0 1.0.24+aeb40ebe90 	 |-- fabric-transfer-api-v1 2.1.6+413cbbc790 	 \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 	- fabricloader 0.14.19 	- java 17 	- menulogue 1.0.1-1.19.2 	- minecraft 1.19.2 	- physicsmod 2.12.4 	- sodium 0.4.4+build.18 	 \-- org_joml_joml 1.10.4 [12:30:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT [12:30:18] [main/INFO]: Compatibility level set to JAVA_16 [12:30:18] [main/INFO]: Compatibility level set to JAVA_17 [12:30:18] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found [12:30:20] [main/WARN]: Error loading class: software/bernie/geckolib3/renderers/geo/IGeoRenderer (java.lang.ClassNotFoundException: software/bernie/geckolib3/renderers/geo/IGeoRenderer) [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.preprocessor.JcppProcessor was not found physicsmod.mixins.json:iris.MixinJcppProcessor from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/newshader/ExtendedShader (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/newshader/ExtendedShader) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.pipeline.newshader.ExtendedShader was not found physicsmod.mixins.json:iris.MixinExtendedShaderAccessor from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/ProgramSet (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/ProgramSet) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.ProgramSet was not found physicsmod.mixins.json:iris.MixinProgramSet from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/optifine/shaders/Shaders (java.lang.ClassNotFoundException: net/optifine/shaders/Shaders) [12:30:20] [main/WARN]: Error loading class: net/optifine/shaders/ShadersCompatibility (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersCompatibility) [12:30:20] [main/WARN]: Error loading class: net/optifine/shaders/Programs (java.lang.ClassNotFoundException: net/optifine/shaders/Programs) [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline was not found physicsmod.mixins.json:ocean.MixinNewWorldRenderingPipeline from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline was not found physicsmod.mixins.json:ocean.MixinNewWorldRenderingPipelineInvoker from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/ProgramSource (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/ProgramSource) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.ProgramSource was not found physicsmod.mixins.json:ocean.MixinProgramSource from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.preprocessor.JcppProcessor was not found physicsmod.mixins.json:ocean.MixinJcppProcessor from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/ProgramSet (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/ProgramSet) [12:30:20] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.ProgramSet was not found physicsmod.mixins.json:ocean.MixinProgramSet from mod physicsmod [12:30:20] [main/WARN]: Error loading class: net/optifine/util/BlockUtils (java.lang.ClassNotFoundException: net/optifine/util/BlockUtils) [12:30:20] [main/WARN]: Error loading class: ca/spottedleaf/starlight/common/light/StarLightEngine (java.lang.ClassNotFoundException: ca/spottedleaf/starlight/common/light/StarLightEngine) [12:30:20] [main/WARN]: Error loading class: link/infra/indium/renderer/render/TerrainRenderContext (java.lang.ClassNotFoundException: link/infra/indium/renderer/render/TerrainRenderContext) [12:30:35] [main/INFO]: Building optimized datafixer [12:30:59] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions: 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath. 	b) Add the JAR that contains the shared library to the classpath. [12:30:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics. [12:30:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics. [12:31:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [12:31:07] [Render thread/ERROR]: Failed to verify authentication com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401 	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?] 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?] 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?] 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?] 	at net.minecraft.class_310.method_31382(class_310.java:711) [client-intermediary.jar:?] 	at net.minecraft.class_310.<init>(class_310.java:431) [client-intermediary.jar:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?] Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.11.49.jar:?] 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?] 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?] 	... 9 more [12:31:07] [Render thread/INFO]: Setting user: adex [12:31:11] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo. Registered forkAndExec ---- Minecraft Crash Report ---- // Oh - I know what I did wrong! Time: 2023-05-17 12:31:16 Description: Initializing game java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'! 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) 	at net.minecraft.class_310.<init>(class_310.java:459) 	at net.minecraft.client.main.Main.method_44604(Main.java:205) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.ExceptionInInitializerError 	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:229) 	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) 	... 8 more Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform LINUX 	at de.fabmax.physxjni.Loader.load(Loader.java:38) 	at physx.NativeObject.<clinit>(NativeObject.java:7) 	... 11 more Caused by: java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.debug/cache/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.so: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/cache/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64 .so on a AARCH64 platform) 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method) 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) 	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source) 	at java.base/java.lang.Runtime.load0(Unknown Source) 	at java.base/java.lang.System.load(Unknown Source) 	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71) 	at de.fabmax.physxjni.Loader.load(Loader.java:33) 	... 12 more A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) 	at net.minecraft.class_310.<init>(class_310.java:459) -- Initialization -- Details: 	Modules: Stacktrace: 	at net.minecraft.client.main.Main.method_44604(Main.java:205) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) -- System Details -- Details: 	Minecraft Version: 1.19.2 	Minecraft Version ID: 1.19.2 	Operating System: Linux (aarch64) version Android-13 	Java Version: 17-internal, N/A 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 3907225376 bytes (3726 MiB) / 4404019200 bytes (4200 MiB) up to 4404019200 bytes (4200 MiB) 	CPUs: 4 	Processor Vendor: 0x41 	Processor Name: 	Identifier: 0x41 Family 8 Model 0xd0b Stepping r0x2p0 	Microarchitecture: unknown 	Frequency (GHz): -0.00 	Number of physical packages: 1 	Number of physical CPUs: 1 	Number of logical CPUs: 8 	Graphics card #0 name: unknown 	Graphics card #0 vendor: unknown 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: unknown 	Virtual memory max (MB): 9959.95 	Virtual memory used (MB): 7623.64 	Swap memory total (MB): 6144.00 	Swap memory used (MB): 1139.20 	JVM Flags: 3 total; -Xms4200M -Xmx4200M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar 	Fabric Mods: 		catalogue: Catalogue 1.7.0-1.19.2 		fabric-api: Fabric API 0.76.0+1.19.2 			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290 			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390 			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90 			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390 			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90 			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790 			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390 			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90 			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490 			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890 			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690 			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890 			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90 			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490 			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890 			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690 			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390 			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90 			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590 			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90 			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490 		fabricloader: Fabric Loader 0.14.19 		java: OpenJDK 64-Bit Server VM 17 		menulogue: Menulogue 1.0.1-1.19.2 		minecraft: Minecraft 1.19.2 		physicsmod: Physics Mod 2.12.4 		sodium: Sodium 0.4.4+build.18 			org_joml_joml: joml 1.10.4 	Launched Version: 1.19.2 	Backend library: LWJGL version 3.2.3 SNAPSHOT 	Backend API: Unknown 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric' 	Type: Client (map_client.txt) 	CPU: <unknown> #@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/crash-reports/crash-2023-05-17_12.31.16-client.txt ``` 
2. Configuration
 - Minecraft version: fabric-loader-0.14.19-1.19.2
 - Mods: catalogue-fabric-1.7.0-1.19.2.jar, sodium-fabric-mc1.19.2-0.4.4+build.18.jar, fabric-api-0.76.0+1.19.2.jar, cloth-config-8.2.88-forge.jar, menulogue-fabric-1.0.1-1.19.2.jar, physics-mod-pro-v153-fabric-1.19.2.jar - Render holy gl4es
 - Java: internal 17
 - Ram: 4200mb/3800mb free(more allocated than free but it isnt problem because pojav dont see swap)/8000mb+4000swap_mb
 - JVM launch arguments: none
 - Use aternate surface rendering: no
 - Check libraries after downloading: yes
3. device vivo Y72 5G (V2041) 
4. system: Funtouch OS 13 Global (android 13) 

My phisic mod pro jar file is downloaded from patreon

**Comment by adex345** [comment]
There is no crash report bcs it don't exist!

**Comment by caoqt1** [comment]
The most likely cause for this is because your phone is arm64, which physics mod doesn't support.

**Comment by haubna** [comment]
ARM64 is not supported.
