### ISSUE TITLE
Blur Effect w/ Various Triggers[BUG]

### ISSUE THREAD

**Issue by BullyTheCode** [haubna/PhysicsMod#659]
**Description**
Some kind of shader(?) effect blurs vision.  Can be triggered in several ways but also happens randomly.  Created a small example video showing the effect:  https://i.imgur.com/G5LHxFL.mp4

**To Reproduce**
Normally it seems to behave like a 'splash' effect?  Such as when first entering water, or leaving water.  After a few moments the effect will go away.  But it can persist if you're lingering at the surface of water.  At first this seemed to be only around large bodies of water, and not placed water blocks or shallow sources.  But I've seen it happen randomly with no water around, as well as getting 'splashed' by particle effects of falling water.  In the attached video above, it even seemed to trigger when throwing an item that would 'splash' into the water.  So it seems to be detecting a splash and clouding vision?

**Screenshots**
Video 1:  https://i.imgur.com/G5LHxFL.mp4
Video 2:  https://i.imgur.com/iAIv2bX.mp4   (happens towards the end)

**Mods & Potential Cause**
I was testing this on the current AoF6 Modpack ( All of Fabric 6 - 1.5.4 ).
Performed add/remove/restart actions with mods until I narrowed it down to one:  Tempad
(https://www.curseforge.com/minecraft/mc-mods/tempad)
Removing tempad from the modpack appears to have completely resolved the issue.  Appears to be a mod that creates a floating door to teleport through.  Door has a blur effect, but not sure why it's interacting with the Physics 'splash' detection.

Minecraft Version: 1.19.2
Physics Mod Version: physics-mod-pro-v151-fabric-1.19.2

**Comment by haubna** [comment]
My guess is that it doesn't properly reset some OpenGL behaviour. Maybe the mod author can resolve this bug on their end.

**Comment by haubna** [comment]
Closed due to being fixed
