### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by laravieira** [haubna/PhysicsMod#66]
This happen one time, my game studently close by an crash. I was in my local paper server (not on my machine, but on my local network), I was killing mobs in a XP mob farm. I attach an screenshot at F3 of my game, same position as the crash time.

[crash-2021-08-04_19.00.40-client.txt](https://github.com/haubna/PhysicsMod/files/6934654/crash-2021-08-04_19.00.40-client.txt)
![2021-08-04_19 11 23](https://user-images.githubusercontent.com/40150947/128261977-a2a94930-2e9a-40b9-a3ae-08c0bea8623c.png)

**Comment by haubna** [comment]
Please update to version 2.4.4. This issue got fixed in version 2.3.6.
