### ISSUE TITLE
Conflict between Physics Mod Pro and Double Slabs mod [BUG]

### ISSUE THREAD

**Issue by michlbro** [haubna/PhysicsMod#660]
**Describe the bug**
Upon placing a campfire inside of a player causes the client to crash.
This is due to the campfire being placed vertical (Yes, I know, it's cursed).

**Logs**
https://bytebin.lucko.me/LvHZvIJYyX -- Thanks to NotEnoughCrashes preventing my PC from blowing up.

**To Reproduce**
Install Double Slabs mod (https://www.curseforge.com/minecraft/mc-mods/double-slabs)
Place a campfire in the same position as the players torso against a wall.

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/96602061/5582602b-0d5a-4c74-aad0-999987490e1f)

Minecraft Version: 1.19.2
Physics Mod Pro Version: physics-mod-pro-v151-forge-1.19.2

**Comment by haubna** [comment]
If you reproduce this crash and then include the latest.log (in logs folder) I might be able to fix it :)

**Comment by michlbro** [comment]
Here you go, https://pastebin.com/5SpgZi3U. Enjoy. (I have no clue how you people manage to fix a bug from one log...)

**Comment by haubna** [comment]
This is probably not helping you but it will be fixed in the next 1.20 update!
