### ISSUE TITLE
Gpu Liquids not it does not work

### ISSUE THREAD

**Issue by oriolprogamer712** [haubna/PhysicsMod#665]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-05-29 20:48:20
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "physx.common.PxCudaContextManager.getAddress()" because "value" is null
	at physx.physics.PxSceneDesc.setCudaContextManager(PxSceneDesc.java:568)
	at net.diebuddies.physics.DynamicsWorld.<init>(DynamicsWorld.java:88)
	at net.diebuddies.physics.PhysicsWorld.<init>(PhysicsWorld.java:181)
	at net.diebuddies.physics.PhysicsMod.<init>(PhysicsMod.java:558)
	at net.diebuddies.physics.PhysicsMod.getInstance(PhysicsMod.java:538)
	at net.minecraft.class_761.handler$zkc000$physicsmod$getSnowWorldViewProjection(class_761.java:4471)
	at net.minecraft.class_761.method_22710(class_761.java)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at physx.physics.PxSceneDesc.setCudaContextManager(PxSceneDesc.java:568)
	at net.diebuddies.physics.DynamicsWorld.<init>(DynamicsWorld.java:88)
	at net.diebuddies.physics.PhysicsWorld.<init>(PhysicsWorld.java:181)
	at net.diebuddies.physics.PhysicsMod.<init>(PhysicsMod.java:558)
	at net.diebuddies.physics.PhysicsMod.getInstance(PhysicsMod.java:538)
	at net.minecraft.class_761.handler$zkc000$physicsmod$getSnowWorldViewProjection(class_761.java:4471)
	at net.minecraft.class_761.method_22710(class_761.java)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['ORIOL'/125, l='ClientLevel', x=-6.50, y=89.00, z=-6.50]]
	Chunk stats: 225, 109
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,98,0), Section: (at 0,2,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 122 game time, 122 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: fabric, programmer_art, minecraft:physicsmod, vanilla

-- System Details --
Details:
	Minecraft Version: 1.20 Pre-release 7
	Minecraft Version ID: 1.20-pre7
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1433407168 bytes (1367 MiB) / 2617245696 bytes (2496 MiB) up to 4060086272 bytes (3872 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce 610M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1058
	Graphics card #0 versionInfo: DriverVersion=23.21.13.9135
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 9872.05
	Virtual memory used (MB): 8037.34
	Swap memory total (MB): 6000.00
	Swap memory used (MB): 1099.24
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3872M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.82.1+1.20
			fabric-api-base: Fabric API Base 0.4.28+b04edc7add
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.33+4d8536c9dd
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+348a9c64dd
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1dd
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.38+c2e6f674dd
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.19+fb8d95dadd
			fabric-command-api-v1: Fabric Command API (v1) 1.2.31+f71b366fdd
			fabric-command-api-v2: Fabric Command API (v2) 2.2.10+b04edc7add
			fabric-commands-v0: Fabric Commands (v0) 0.2.48+df3654b3dd
			fabric-containers-v0: Fabric Containers (v0) 0.1.60+df3654b3dd
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.6+b3f2574bdd
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+a8e62fb2dd
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebedd
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.9+ec0bbba5dd
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.50+b04edc7add
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.20+4d8536c9dd
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.2+cf56d794dd
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.60+df3654b3dd
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.37+b04edc7add
			fabric-item-api-v1: Fabric Item API (v1) 2.1.25+4d8536c9dd
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.6+b3f2574bdd
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+fb8d95dadd
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3dd
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.19+dcb9d1cadd
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.36+b04edc7add
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.40+9e7660c6dd
			fabric-message-api-v1: Fabric Message API (v1) 5.1.5+fb8d95dadd
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.46+4d8536c9dd
			fabric-models-v0: Fabric Models (v0) 0.3.34+fb8d95dadd
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.7+b04edc7add
			fabric-networking-v0: Fabric Networking (v0) 0.3.47+df3654b3dd
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.5+4d8536c9dd
			fabric-particles-v1: Fabric Particles (v1) 1.0.27+f1e4495bdd
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.17+df34a274dd
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.5+4d8536c9dd
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.0+01ca5976dd
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.0+dc5320eddd
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.43+df3654b3dd
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.32+afca2f3edd
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.25+fb8d95dadd
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.46+df3654b3dd
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.5+fb8d95dadd
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+e6c7d4eedd
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.6+f7923f6ddd
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.5+8aafb887dd
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.26+fb8d95dadd
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+fb8d95dadd
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.1+e78ef151dd
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.1.2+df34a274dd
		fabricloader: Fabric Loader 0.14.20
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20-beta.7
		physicsmod: Physics Mod 3.0.4
	Launched Version: fabric-loader-0.14.20-1.20-pre7
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce 610M/PCIe/SSE2 GL version 3.2.0 NVIDIA 391.35, NVIDIA Corporation
	Window size: 1280x657
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: fabric, programmer_art, minecraft:physicsmod (incompatible), vanilla
	Current Language: es_es
	CPU: 8x Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['ORIOL'/125, l='ServerLevel[Mundo nuevo]', x=-6.50, y=89.00, z=-6.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
Minecraft Version: <version>
Physics Mod Version: <version>

**Comment by haubna** [comment]
Your GPU is too old
