### ISSUE TITLE
Minecraft Fabric 1.19.4 crashing

### ISSUE THREAD

**Issue by foxiergo** [haubna/PhysicsMod#667]
### Version information

fabric-loader-0.14.21-1.19.4

### Reproduction Steps

The game crashed whilst unexpected error 
Error: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/render/vertex/VertexBufferWriter

### Crash Report file

[crash-2023-06-01_19.09.51-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11627457/crash-2023-06-01_19.09.51-client.txt)

### Additional information

_MC crashing with this msg:_
**The game crashed whilst unexpected error 
Error: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/render/vertex/VertexBufferWriter** 

I am using the latest version of Physics Mod Pro.
But when I put doors, hatches (in the flat world) I get the game crashes. Just recently, I tried to create a normal world, hoping to see the realistic ocean, but after the message "Generate World" appeared another "Save World" and mc crashed with this error (conclusion: the ocean and physics of dynamic blocks for some reason not working) (sodium and all its addons latest version)

This is where I downloaded the [Physics Mod Pro](https://ko-fi.com/post/Physics-Mod-Pro-P5P2KPTM6) from

**Comment by haubna** [comment]
Please make sure to use the latest Pro version with Sodium 0.4.10.
