### ISSUE TITLE
"GL_OUT_OF_MEMORY" [BUG]

### ISSUE THREAD

**Issue by Rad586** [haubna/PhysicsMod#668]
**Describe the bug**
When using physic mod 2.12.3, game crashes after running a while, and making it crash even after I removed the physic mod later. Couldn't narrow down the mod list since idk how to clear gpu memory(I did some search but still have no idea...), making it requires a pc restart💀. But feel free to ask for more tests if you cant reproduce that.
_But 2.11.5 works fine._
**To Reproduce**
Install physic mod 2.12.3, run the game(use shader to speed up the process).
**Screenshots**
No, but I got log(no crash report generated):
[2023-06-03-6.log.txt](https://github.com/haubna/PhysicsMod/files/11642913/2023-06-03-6.log.txt)
Minecraft Version: 1.18.2
Physics Mod Version: 2.12.3

**Comment by haubna** [comment]
You can enable the physics debug menu (in minecract keybind settings) and check how much GPU memory the physics mod uses.

**Comment by Rad586** [comment]
Hmm, the issue was gone somehow. Will comment if it appers again..
