### ISSUE TITLE
GUI Physics Key Bind [BUG]

### ISSUE THREAD

**Issue by JasonHorkles** [haubna/PhysicsMod#669]
**Describe the bug**
Setting the GUI physics key bind to nothing will cause the mod to toggle the physics when any Alt button is pressed

**To Reproduce**
1. Open key binds
2. Click on the GUI Physics key bind and press Esc to set it to nothing
3. Press the Alt key

Minecraft Version: 1.19.4
Physics Mod Version: 2.12.3

**Comment by haubna** [comment]
Tested with fabric 1.19.4. Doesn't happen there.

**Comment by JasonHorkles** [comment]
Weird, looks like it is only on my main computer. I'll have to investigate further

**Comment by haubna** [comment]
Thanks!

**Comment by srnyx** [comment]
This is happening to me too, I have the keybind not bound but it's triggering whenever I use "extra" keys (ones that are identified as `scancode.XXX` when binding them in Minecraft [volume/media controls])
Minecraft: 1.19.4
Physics Mod: 2.12.3
Fabric: 0.14.21
Mods: https://paste.srnyx.com/uhefevecag.yaml

**Comment by srnyx** [comment]
This is still happening to me, can this issue be re-opened? @JasonHorkles @haubna
