### ISSUE TITLE
[BUG] Dynamic blocks collide with invisible hitboxes of fences

### ISSUE THREAD

**Issue by VOLKOUL** [haubna/PhysicsMod#671]
When placing a trapdoor over a fence, the trapdoor will tilt sideways / start glitching all over (it is very inconvenient for builders). 
Making it ignore certain blocks (like fences) would be great!
This occurs in every version of the mod.

**Comment by haubna** [comment]
That is the official hitbox of the fences. Nothing to fix there. You can disable the collision of trapdoors in the dynamic block settings -> customize.
