### ISSUE TITLE
[1.19.4] Crash "bannerMaterial" is null

### ISSUE THREAD

**Issue by MrKashew** [haubna/PhysicsMod#672]
Minecraft Version: 1.19.4
Physics Mod Version: pro-v152
[crash-2023-06-12_22.36.09-client.txt](https://github.com/haubna/PhysicsMod/files/11730965/crash-2023-06-12_22.36.09-client.txt)

**Comment by haubna** [comment]
I can't pin it down to which mod causes this incompatibility (probably a banner mod). You will have to test it yourself by using the thanos method (removing half of the mods and see if it fixes the problem, then repeat the process if it is not fixed).

**Comment by MrKashew** [comment]
@haubna does it make sense to add a check for `bannerMaterial != null` before accessing value to prevent incompatibilities

**Comment by haubna** [comment]
That fix will come with the latest 1.20.1 release, I don't know though if that will fix your issue.

**Comment by MrKashew** [comment]
The issue is with Kobolds structure generation, I’ll try it together (pro) once the release is out, as it happened on 1.20.1 for me too

**Comment by haubna** [comment]
Released the version, in case the crash still exists please open up a new issue. Thanks for the report!
