### ISSUE TITLE
Incompability with lambda better grass [BUG]

### ISSUE THREAD

**Issue by JohnWeak1** [haubna/PhysicsMod#673]
**Describe the bug**
the physics mod causes the grass textures from lambda better grass to not work on some grass blocks

**To Reproduce**
use lambda better grass mod with the physics mod

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/42245432/62c62ab9-8048-457a-bff2-7a913d2244a2)

Minecraft Version: 1.20
Physics Mod Version: pro v155 fabric
Mod Loader : Quilt Loader v0.19.0
Mod loader API : Quilted API 7.0.1+0.83.0

**Comment by haubna** [comment]
I am pretty sure my mod doesn't change anything there.
