### ISSUE TITLE
[Bug] Toggle physics keybind breaks for all future game launches when toggled off before closing the game

### ISSUE THREAD

**Issue by Justsnoopy30** [haubna/PhysicsMod#674]
**Describe the bug**
The toggle physics keybind stops working after restarting the game with physics off.

**To Reproduce**
1. Turn off physics features with the keybind
2. Close the game
3. Reopen and observe that the toggle no longer works to enable physics features

Minecraft Version: 1.20.1
Physics Mod Version: Pro V155

**Comment by haubna** [comment]
This is not a bug, the keybind is meant to disable everything while playing and then reenabling it.
