### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by Agentlj** [haubna/PhysicsMod#675]
In the newest version of this mod, I lost the GPU fluid physics, although in the previous version I had physics for the snapshot. So, I tried to spawn the liquid through the console, but I only had a very strong lag and there was no liquid.

GPU:GTX1650 CPU:FX-8320e  RAM:12 (not feel 8)

Minecraft version <1.20>
Physics mod version <155>

**Comment by haubna** [comment]
Works fine for me. You probably spawned it on a wrong location.

**Comment by Agentlj** [comment]
> Works fine for me. You probably spawned it on a wrong location.

check this https://www.youtube.com/watch?v=APGn5lXrn-M        i have only physics mod and fabric api
