### ISSUE TITLE
Ragdoll Velocity Changing

### ISSUE THREAD

**Issue by Ezekielman** [haubna/PhysicsMod#676]
When player ragdolls are spawned, they will often jump up in the air. Falling from a high place, or just generically dying will usually cause them to do so. I was thinking that a possible enhancement would be to have an option to turn that off, or adjust the jump velocity.

If not, then that's fine.

**Comment by haubna** [comment]
Please don't post feature suggestions here, thanks! The right place for it is on my discord server.
