### ISSUE TITLE
Disabling shaders crash the game [BUG]

### ISSUE THREAD

**Issue by ciaens** [haubna/PhysicsMod#677]
**Describe the bug**
The game crashes.

**To Reproduce**
Load a world with shaders activated.
Press K (or other bind button) to disable the shader.

**Screenshots**
[youtube video](https://youtu.be/HSqwvolaFfg)

Minecraft Version: 1.20
Physics Mod Version: for fabric 1.20

List of the mods: 
        - alternate-current 1.6.0
	- c2me 0.2.0+alpha.10.88
	- citresewn 1.1.3+1.20
	- cloth-config 11.0.99
	- cull-less-leaves 1.2.0
	- dark-loading-screen 1.6.14
	- dynamicfps 2.3.0
	- fabric-api 0.83.0+1.20
	- fabric-language-kotlin 1.9.5+kotlin.1.8.22
	- fabricloader 0.14.21
	- fabrishot 1.9.2
	- fallingleaves 1.15.0+1.19.4
	- immediatelyfast 1.1.15+1.20.1
	- iris 1.6.4
	- java 17
	- krypton 0.2.3
	- minecraft 1.20
	- modmenu 7.0.1
	- mousewheelie 1.11.1+mc1.20-pre2
	- no-telemetry 1.7.0
	- physicsmod 3.0.5
	- reeses-sodium-options 1.5.1+mc1.20-build.74
	- sodium 0.4.10+build.27
	- sound_physics_remastered 1.20-1.1.1
	- starlight 1.1.2+fabric.dbc156f
	- visuality 0.7.0+1.20
	- yet_another_config_lib_v3 3.0.1+1.20
	- zoomify 2.10.0
[hs_err_pid15052.log](https://github.com/haubna/PhysicsMod/files/11763250/hs_err_pid15052.log)

**Comment by haubna** [comment]
Which shaderpack did you use? I can't reproduce it on my end. What is your hardware? As far as I know this could be a driver bug and updating them might help.

**Comment by ciaens** [comment]
I tested with multiple shaderpacks and all crashed (in the video it's NostalgiaVX).
Ryzen 7 5800x, 32Gb @ 3200MHz, RTX 4090 (latest drivers).
I've updated my drivers. With the latest version the crash seems to be gone. Or maybe it was a mod compatibility.

**Comment by haubna** [comment]
Ok good. Thanks for letting me know!
