### ISSUE TITLE
layered blocks bug?

### ISSUE THREAD

**Issue by Gooworld** [haubna/PhysicsMod#678]
![2023-06-16_00 35 42](https://github.com/haubna/PhysicsMod/assets/136759208/5e7ac2ab-6b72-4089-a18c-0b1a30d39615)
minecraft 1.19.2 fabric

**Comment by haubna** [comment]
I don't know where the bug is in this picture. I need a better description.

**Comment by caoqt1** [comment]
> I don't know where the bug is in this picture. I need a better description.

It looks like theres two seperate bamboos, one with physics, one without.
![image](https://github.com/haubna/PhysicsMod/assets/51724932/df3487c6-1b2e-4f44-8730-590cdeb5ad3d)

**Comment by haubna** [comment]
Oh this usually happens when you use an unsupported mod (like mismatched indium, iris, sodium versions and so on). Try using the ones listed here: https://minecraftphysicsmod.com/installation
