### ISSUE TITLE
Blocks aren't collapsing with the collapse setting on.

### ISSUE THREAD

**Issue by AydenAG** [haubna/PhysicsMod#679]
When I break a block at the bottom of a tree, the rest of the tree doesn't collapse even with the collapse setting on and off.

Minecraft Version: 1.20.1
Physics Mod Version: V155

**Comment by haubna** [comment]
You need to be running the server. Fabric or Forge? Other mods used?

**Comment by renjiadong-sys** [comment]
> 

i have this problem too.i open the collapse option but they dont collapse,the collape number is not zero.i play 1.20.1 and forge .u mean if i wanna let it collapse ,i must  play mc in a server?

**Comment by renjiadong-sys** [comment]
> You need to be running the server. Fabric or Forge? Other mods used?你必须运行服务器。织物还是锻造？使用其他mods？

i have this problem too.i open the collapse option but they dont collapse,the collape number is not zero.i play 1.20.1 and forge .u mean if i wanna let it collapse ,i must play mc in a server?

**Comment by renjiadong-sys** [comment]
> You need to be running the server. Fabric or Forge? Other mods used?你必须运行服务器。织物还是锻造？使用其他mods？

and i am singlegame mode,physics mod pro

**Comment by renjiadong-sys** [comment]
> You need to be running the server. Fabric or Forge? Other mods used?

i use v155 too

**Comment by fedat0r** [comment]
Hi mates, have same issue on 1.58 pro too (Forge)! Collapsing  simply not working at all. Mining made hard again, anyone found out how to fix??

**Comment by fedat0r** [comment]
> Hi mates, have same issue on 1.58 pro too (Forge)! Collapsing simply not working at all. Mining made hard again, anyone found out how to fix??

I have also tried to start the server and joined, played on the server, but having the same issue - no collapsing on the server.

Minecraft 1.20.1
Physics 1.58 Pro Forge
Forge 47.1.39

Think it is a bug

**Comment by MoonyMonke** [comment]
yeah i think it only works in the older versions it´s a bug

**Comment by haubna** [comment]
Sorry for the late response. Fixed with the most recent versions!
