### ISSUE TITLE
Physics mod logo In Warthunder

### ISSUE THREAD

**Issue by MJMALTE32** [haubna/PhysicsMod#682]
After I downloaded the mod from curseforge (with some others) I had massive lag Spikes so I deleted the physics mod. This was when the 1.20 version was new. Yesterday while playing warthunder the physics mod logo appeared in the top left corner and I don’t know how to get rid of it. 
Recreation: download physics mod from curseforge for the 1.20 version, delete the mod after running Minecraft and start warthunder 

physics mod: first 1.20 version
Minecraft: 1.20 fabric
Warthunder: the newest update

**Comment by haubna** [comment]
This is not related to the physics mod but rather the curseforge launcher. Please try to ask them for help on this topic.
