### ISSUE TITLE
[BUG] [PERFORMANCE] [CRITICAL] Physics mod disables particle culling with Rubidium 

### ISSUE THREAD

**Issue by VOLKOUL** [haubna/PhysicsMod#687]
Physics mod disables particle culling with Rubidium. This is a very problematic thing as large modpacks get a **MASSIVE performance drop** with this feature disabled.
The bug occurs on every version of the physics mod. Re-enabling particle culling won't work, as it will reset to off when the settings tab closes. 
I am not aware whether this is a Physics Mod thing or a Rubidium thing, so apologies in advance in case this isn't on your side)

**Comment by haubna** [comment]
This is not a bug. Particle culling is actually very slow and got removed in new releases. Disabling it improves performance.
