### ISSUE TITLE
Dynamic blocks do not follow the "physics type" setting when breaking them [BUG]

### ISSUE THREAD

**Issue by Slooshie1** [haubna/PhysicsMod#688]
**Describe the bug**
When I break a dynamic block, such as a door or trapdoor, the block takes on the "blocky" physics type, despite my main rule for block breaking physics being "particles". Changing the main rule nor the physics type for individual blocks makes a difference. This has only been happening on my 1.20.1 instance, not my 1.19.4 instance.

**To Reproduce**
1. Enable dynamic blocks
2. Place a door or trapdoor
3. Break the door/trapdoor
4. See that it stays stiff and falls to the ground as if it were set to be "blocky" regardless of main rule or physics type setting

Minecraft Version: 1.20.1
Physics Mod Version: v156 Fabric

**Comment by haubna** [comment]
This is intended behaviour by default. You can change it under physics settings > dynamic blocks > customize.

**Comment by Slooshie1** [comment]
That’s the problem; I tried to use the customize menu and it does not work

**Comment by Slooshie1** [comment]
> Changing the main rule nor the physics type for individual blocks makes a difference.
