### ISSUE TITLE
game crash when using shaders

### ISSUE THREAD

**Issue by BIGMANCHEESE** [haubna/PhysicsMod#69]
when i use iris shaders mod, it works fine, until i actually turn on shaders. Then, as soon as i break a block, it crashes. I can tell its probably the physics mod error because it mentions mixin in the crash report several times.
My laptop is not the problem because it has an i5-10300H and a 1650ti and 8gb of ddr4 2933mhz ram . I tried seus renewed and bsl shaders and the same issue occurs

crash report:
[crash-2021-08-07_09.47.27-client.txt](https://github.com/haubna/PhysicsMod/files/6948847/crash-2021-08-07_09.47.27-client.txt)
Thanks for your time and reading this

**Comment by haubna** [comment]
You use version 2.3.3. Please update to the latest version.

**Comment by BIGMANCHEESE** [comment]
oh sorry ok
