### ISSUE TITLE
Visual issue [Compatibility\Bug]

### ISSUE THREAD

**Issue by xzTWINzx** [haubna/PhysicsMod#692]
While there is snow on the ground, you can look through the ground under the map.

Tp on snowy biome, and look at snow -_- .

Minecraft Version: <1.19.4>
Physics Mod Version: <152 fabric>

how fix this?

![2023-07-07_22 07 34](https://github.com/haubna/PhysicsMod/assets/88400050/259507a9-f495-463f-b6c7-6273008e0831)
![2023-07-07_22 07 40](https://github.com/haubna/PhysicsMod/assets/88400050/85e04ce0-2a99-4be0-8d6b-c7a9b1ed216b)
![2023-07-07_22 07 51](https://github.com/haubna/PhysicsMod/assets/88400050/ea8c8c93-8f0b-485d-adc4-dc2ec11bc238)

mod list and shaders :
![2023-07-07_22 08 09](https://github.com/haubna/PhysicsMod/assets/88400050/7ad20758-0f09-4909-993e-ea709587a7dd)
![2023-07-07_22 08 13](https://github.com/haubna/PhysicsMod/assets/88400050/72f714fe-540d-41c8-a57e-4ab1e4f6ab10)
![2023-07-07_22 08 20](https://github.com/haubna/PhysicsMod/assets/88400050/56e9098a-eb85-4543-b4d6-3ffed8974057)
-----------------
![2023-07-07_22 08 22](https://github.com/haubna/PhysicsMod/assets/88400050/d93ff390-085d-4b08-a08f-490ff034e1ab)
![2023-07-07_22 08 27](https://github.com/haubna/PhysicsMod/assets/88400050/8788719f-6686-4dba-836b-dc97b8fca3f2)
![2023-07-07_22 08 30](https://github.com/haubna/PhysicsMod/assets/88400050/3def54ff-48fb-4c1e-a29c-36a59e37ef00)
![2023-07-07_22 08 34](https://github.com/haubna/PhysicsMod/assets/88400050/d007c7cc-3755-4079-8e98-76c4c462a1a2)
![2023-07-07_22 08 36](https://github.com/haubna/PhysicsMod/assets/88400050/0929a0c5-3dc1-4167-9b94-3bd87a4ca8e3)
![2023-07-07_22 08 39](https://github.com/haubna/PhysicsMod/assets/88400050/2a51a8b5-a68e-46ec-91a4-16f584ed8267)
![2023-07-07_22 08 42](https://github.com/haubna/PhysicsMod/assets/88400050/60eb2501-b711-42f4-b957-0abaa058dd3d)
![2023-07-07_22 08 45](https://github.com/haubna/PhysicsMod/assets/88400050/3020d07c-8603-441e-9702-0c25973373b4)
![2023-07-07_22 08 47](https://github.com/haubna/PhysicsMod/assets/88400050/9f52e983-b728-44a2-92a3-a87b335641f3)
![2023-07-07_22 08 50](https://github.com/haubna/PhysicsMod/assets/88400050/43a84d1d-6db4-414e-bd13-d6e15e9c4cac)
![2023-07-07_22 08 52](https://github.com/haubna/PhysicsMod/assets/88400050/8a37a443-109d-479c-9f47-2cdf2c8bb729)
![2023-07-07_22 08 55](https://github.com/haubna/PhysicsMod/assets/88400050/885517b1-1f7b-40d5-82da-1aadca0bf7c4)
![2023-07-07_22 08 57](https://github.com/haubna/PhysicsMod/assets/88400050/4e4a415e-aace-4ad7-9fd1-bf3f2d6e46f2)
![2023-07-07_22 08 59](https://github.com/haubna/PhysicsMod/assets/88400050/ed3e1bcf-16cb-4f4f-bfc4-1e252319e65d)
![2023-07-07_22 09 01](https://github.com/haubna/PhysicsMod/assets/88400050/891dbcdd-42a8-4619-a0e2-c1d06a4e8e3c)
![2023-07-07_22 09 06](https://github.com/haubna/PhysicsMod/assets/88400050/884555b9-55ed-40fd-83ae-f766b7c3a7b2)
![2023-07-07_22 09 09](https://github.com/haubna/PhysicsMod/assets/88400050/c0eefb5f-0140-4fd4-8aa9-793dc5cb4c84)

**Comment by xzTWINzx** [comment]
![2023-07-07_22 21 45](https://github.com/haubna/PhysicsMod/assets/88400050/ca6f35e3-db71-488c-bd70-2904d1285102)

**Comment by cptbuzzy** [comment]
hey i have a similar setup to yours and i just went through all of my mods, i believe the more culling mod is the problem, removing it solved the issue for me. hope this helps!

**Comment by xzTWINzx** [comment]
> hey i have a similar setup to yours and i just went through all of my mods, i believe the more culling mod is the problem, removing it solved the issue for me. hope this helps!
I didn't remove the mod, I just disabled block state culling
![image](https://github.com/haubna/PhysicsMod/assets/88400050/501b7bca-e518-4fbc-8058-e3952b21a5eb)
