### ISSUE TITLE
Water Bug [Partial Blackness of screen]

### ISSUE THREAD

**Issue by dangerdynamite** [haubna/PhysicsMod#693]
**Describe the bug**
When enchantment table or melon is broken It produces water which causes blackness of an area of the screen for some time.
![Screenshot 2023-07-11 232757](https://github.com/haubna/PhysicsMod/assets/139267568/c3d15a26-e27d-409a-9ac8-3bdbc2f0a648)

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**
![Screenshot 2023-07-11 233016](https://github.com/haubna/PhysicsMod/assets/139267568/40c17c7e-527e-451c-8cc8-bf58cc771153)
![Screenshot 2023-07-11 232757](https://github.com/haubna/PhysicsMod/assets/139267568/88cb5c29-5cb3-47c0-9369-d929db4a411d)

Minecraft Version: <version>
Physics Mod Version: <v.156-forge:1.20.1>

**Comment by haubna** [comment]
Most likely your shaderpack is not very happy with the liquid physics. You can disable them in the settings.

**Comment by dangerdynamite** [comment]
Thank you for your response
