### ISSUE TITLE
If u punch fire to remove it you get the texture particles for breaking it. that is not how it should look

### ISSUE THREAD

**Issue by Djemtheman05** [haubna/PhysicsMod#696]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

Minecraft Version: <version>
Physics Mod Version: <version>

**Comment by MalevolentWulf** [comment]
It's not just fire, grass, chests etc also do it....I think anything that does not take up a full block space and also when item physics is toggled on...I'll have to double check

**Comment by haubna** [comment]
Just disable block physics or change the block type in physics settings -> blocks -> customize
