### ISSUE TITLE
Weather particles do not render after logging on to a Forge server.

### ISSUE THREAD

**Issue by MalevolentWulf** [haubna/PhysicsMod#697]
https://github.com/haubna/PhysicsMod/issues/465#issue-1440700520

The above Linked issue has re-emerged as off V155,

The issue does not happen when in single player and it happens even when the physics mod is the only one active
It should be noted however, that I am using oculus and rubidium as well as complementary shaders reimagined v2.2

thank you for making this fantastic mod for minecraft :) and I hope this bug report helps!

**Comment by niykko** [comment]
I want to add that I am experiencing the exact same Issue, using oculus and rubidium as well. Only happens when joining a forge server.

**Comment by haubna** [comment]
Fixed with v159. Thanks for the report!
