### ISSUE TITLE
Moving blocks by pistons spawns particles [Fabric]

### ISSUE THREAD

**Issue by ArtixAllMighty** [haubna/PhysicsMod#7]
Example : 
https://streamable.com/r5arpi

Moving blocks by pushing them with a piston spawns in particles.

**Comment by ArtixAllMighty** [comment]
The mod isn't open source, maybe never, but my educated guess after some hints from you, would be : 

instead of checking of blocks get set to air, try using the _Break Block Event_ , which I know is a thing on Forge. 
Never worked with Fabric, so I can't tell if there's a solution there

**Comment by haubna** [comment]
This event is a server side event and doesn't work on the client. But nice try :P

**Comment by ArtixAllMighty** [comment]
oh damn. true

**Comment by haubna** [comment]
Well sometimes the solution stares just right into your eyes. The method that I inject into for getting block placements looks like this
`private void setBlockState(BlockPos pos, BlockState state, boolean isMoving)`
yeah guess what isMoving is for. Fixed in the newest release :)
