### ISSUE TITLE
Ragdolls for the player become blocky when using a Figura avatar when going to 3rd person and opening your inventory once.

### ISSUE THREAD

**Issue by SkyTheNerd** [haubna/PhysicsMod#7]
When using the ragdoll option, player ragdolls don't work when using any figura avatar when in 3rd person and randomly. Even ones that don't modify the vanilla player model. It only works before 2.0.0.

**Comment by haubna** [comment]
What is Figura? Modded entities are not supported by ragdolls.

SkyTheNerd ***@***.***> schrieb am So. 11. Juli 2021 um 18:27:

**Comment by SkyTheNerd** [comment]
@haubna Figura is a mod that makes it so you can have more capability with Minecraft skins using block bench and the Lua coding language. (basically the bedrock avatar creator in java edition but better)

the physics mod doesn't use the figura avatars as the ragdoll. it uses the vanilla model but when you are in 3rd person, it's blocky instead of ragdoll.

**Comment by SkyTheNerd** [comment]
I just found out if you hold an item, it becomes blocky.

**Comment by SkyTheNerd** [comment]
So I found out that if you go in 3rd person at all, the ragdoll doesn't work, it only works if you're holding no items.

**Comment by SkyTheNerd** [comment]
also if you open the inventory, it doesn't work.

**Comment by SkyTheNerd** [comment]
I think if the model is on screen, it stops being a ragdoll.

**Comment by SkyTheNerd** [comment]
This Is way to messy, ill just make another issue and make it more in-depth.
