### ISSUE TITLE
Shattering mobs option not really working

### ISSUE THREAD

**Issue by RobinYH** [haubna/PhysicsMod#70]
Some mobs such as zombies skeletons and witches don't completely shatter with the "shatter" mob option selected. When they die only their heads shatter and the rest of them disappear. These are my options in case they have something to do with it: 
![options-physics](https://user-images.githubusercontent.com/78818923/128603782-3295d7a2-4b64-47e1-895e-13f5772a224a.PNG)

**Comment by haubna** [comment]
Thanks for the report! Fixed in version 2.4.6
