### ISSUE TITLE
Ocean physic bug with shader water reflection

### ISSUE THREAD

**Issue by tawan256** [haubna/PhysicsMod#703]
With ocean physic on, water reflection randomly switch between what it should be and visual bug all the time

version : 1.19.2
forge : 43.2.21 (also 43.2.14)
rubidium : 0.6.2
oculus : 1.6.4
physic mod v152 (also v151)

tested shader
BSL 8.2 & 8.2.04
Complementary 4.5.1

**Comment by WRCUno** [comment]
SAME, same setup and everything

**Comment by haubna** [comment]
You can find the proper mods for your MC version here: https://minecraftphysicsmod.com/installation
In case it still doesn't work please update to the latest Minecraft version.
