### ISSUE TITLE
Crash upon entering nether.

### ISSUE THREAD

**Issue by Zarkaros** [haubna/PhysicsMod#705]
So my friend is playing with a modpack and each time he tries to enter the nether, doesn't matter where, his game crashes. He singled it down to the physics mod causing it, but doesn't know the exact cause of the issue.
[hs_err_pid22944.log](https://github.com/haubna/PhysicsMod/files/12141617/hs_err_pid22944.log)
This is the crash log he gave me.

**Comment by MalevolentWulf** [comment]
Looks like you may have ran out of virtual memory when the nether loads in, try changing the allocated ram in java arguements to 4gigabytes and see if that fixes it....6gigabytes might be too much to handle with that comp, also is he running the server on the same comp?

**Comment by Zarkaros** [comment]
Alright, I'll tell him to try that. And no, he isn't hosting the server, just plays on it.

**Comment by astro-angelfish** [comment]
I guess it is a memory corruption (but not a security issue) in a JNI module of PhysicsMod. I've reported it at https://github.com/fabmax/physx-jni/issues/61 with a simple fast analysis. For now I think we might need to disable the dynamic blocks like vines and trapdoors or just remove the whole mod for temporary workaround.

I can randomly and usually get access to the nether in my client without changing any of the memory arguments, so I don't think it is a memory allocation failure mentioned by @MalevolentWulf, which usually mentions `malloc`, `SomeClass::new` or `HeapAlloc` in the crash report. And my game even crashes with a max memory below 4GB or at 8GB.

**Comment by haubna** [comment]
This bug got fixed with Pro V148 and Lite 3.0.6. If the problem still comes up please open up a new issue. Thanks for the report!
