### ISSUE TITLE
Mob Physics Dont Work [BUG]

### ISSUE THREAD

**Issue by defautluser0** [haubna/PhysicsMod#706]
**Describe the bug**
Mob Physics dont work

**To Reproduce**
Kill any mob
Not get Physics

**Video**
https://github.com/haubna/PhysicsMod/assets/108409246/163d5c92-56cb-466d-8bef-2bbd93bfeec1

Minecraft Version: 1.20.1
Physics Mod Version: 157

**Comment by haubna** [comment]
You probably have incompatible mods installed.
