### ISSUE TITLE
Issue with Falling Leaves Mod [BUG]

### ISSUE THREAD

**Issue by Nomokuto** [haubna/PhysicsMod#707]
**Describe the bug**
Normally the falling leaves of the Falling Leaves mod are 2D. Physics Mod turns them into little 3D cubes.

**To Reproduce**
Just install both mods. I used Quilt/Fabric. Works fine when I remove Physics Mod.

Minecraft Version: 1.20.1
Physics Mod Version: physics-mod-pro-v157-fabric-1.20.1

**Comment by halflumi** [comment]
Because of this, it also seems to overwrite the life span of the particles from Falling Leaves, making them disappear too fast.

**Comment by haubna** [comment]
I will have a look at it!

**Comment by haubna** [comment]
Fixed this a while ago and forgot the mention it here, sorry!
