### ISSUE TITLE
Segmentation fault on Linux side

### ISSUE THREAD

**Issue by astro-angelfish** [haubna/PhysicsMod#709]
**Describe the bug**
When switching world from Overworld to nether, the game has a chance to freeze because of a SIGSEGV signal.

It seems like to be a null pointer dereference in somewhere at https://github.com/fabmax/PhysX/blob/webidl-bindings/physx/source/physx/src/NpRigidDynamic.cpp#L402-L413 according to a simple fast analysis by myself, but I have not confirmed where has caused the null pointer.

**To Reproduce**
1. Build some piston that moves an iron trapdoor at the top of the nether, above the bedrock layer, and a minecart should be on the trapdoor.
2. Return to the overworld
3. Enter the nether again, there is a little chance to freeze the game
4. If not freezing, try for a few more times
5. If freezing, check the log and core dump, java will show something like
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8c95ee9cbc, pid=3365, tid=3368
#
```

**Screenshots**
The game freezes, so screenshots are not available

Minecraft Version: 1.20.1
Physics Mod Version: pro-v156-fabric-1.20.1

The hs_err file is attached below. The core dump is not available because of the limitation of github.
[hs_err_pid3365.log](https://github.com/haubna/PhysicsMod/files/12211327/hs_err_pid3365.log)

**Comment by astro-angelfish** [comment]
This issue seems to be the same as https://github.com/haubna/PhysicsMod/issues/705, but with a little more analysis.
And I should report this at https://github.com/fabmax/physx-jni.

**Comment by astro-angelfish** [comment]
JNI developers claims this is not their fault, and seems to be problems with GC of the JVM in rag-doll objects if their claims are true.

**Comment by haubna** [comment]
Do you have GPU liquid physics enabled?
EDIT: I've just uploaded a new v157a file on my latest patreon post. Let me know if that fixes your issue (I was unable to reproduce the crash).

**Comment by astro-angelfish** [comment]
> Do you have GPU liquid physics enabled? EDIT: I've just uploaded a new v157a file on my latest patreon post. Let me know if that fixes your issue (I was unable to reproduce the crash).

GPU liquid physics is disabled, and the issue persists in v175 with the same error. Should I provide a save that can reproduce the error? It was on a Minecraft vanilla server when the game crashes and a crash on single player world rarely happens.

**Comment by haubna** [comment]
I was able to reproduce it on my end and it should hopefully be fixed with v158. Please let me know if you still crash!

**Comment by astro-angelfish** [comment]
> I was able to reproduce it on my end and it should hopefully be fixed with v158. Please let me know if you still crash!

Sorry about that my little server was closed so I'm not able to reproduce that anymore. I'll close this issue and if it happens again anytime I'll reopen.
