### ISSUE TITLE
Suggestion: Option to reduce visual clutter while mining

### ISSUE THREAD

**Issue by Khodyn** [haubna/PhysicsMod#71]
When you are trying to mine, the broken pieces can get in the way especially when digging down. An option to immediately shrink or sweep away any physics objects in front of you while mining would be quite helpful, perhaps it could also fracture whole physics blocks in your way if you have Blocky physics set.

**Comment by haubna** [comment]
I am not going to do something that individual. You can already shrink physics if they are occluding.
