### ISSUE TITLE
GPU water physics are invisible [BUG]

### ISSUE THREAD

**Issue by Beanieboi21** [haubna/PhysicsMod#710]
**Describe the bug**
when I use /liquids it says the liquids spawned but I don't see them but when I break blocks where I spawned it or put ragdolls, they still get effected by the water physics. I also tried using the first release of GPU liquids: v154, and even removed all other mods and shaders, but still the same. my video card is Nvidia GeForce GTX 1650, so it should work, right? maybe it's a video setting that does something to it? or something with my copy of Minecraft, or computer? the first time I tried GPU liquids, it worked fine.  idk...

**To Reproduce**
Minecraft 1.20.1 with fabric loader version 0.14.21 installed, physics mod pro fabric v154a - v157 in mods folder, along with fabric api, sodium and iris (i also tried without sodium and iris) go into any world and use GPU liquids command, and if it works fine for you,...           ...I- idk

**Screenshots**
![idk how to add a picture](https://github.com/haubna/PhysicsMod/assets/119360231/6788b044-6306-4201-a0b7-470712b10407)

Minecraft Version: <fabric 1.20.1>
Physics Mod Version: <fabric 154a - 157>

**Comment by haubna** [comment]
You can try it with Iris + Sodium. If it still doesn't work then you are out of luck.
