### ISSUE TITLE
Door Duplication on 157a [BUG]

### ISSUE THREAD

**Issue by AqueleHaru** [haubna/PhysicsMod#712]
**Describe the bug**
The doors are duplicated and the snow is acting weird

**To Reproduce**
Install 157a

**Screenshots**
<img width="295" alt="image" src="https://github.com/haubna/PhysicsMod/assets/61639486/2c1ba44c-eb96-48dc-ada7-cc43be76264c">

Minecraft Version: <1.20.1>
Physics Mod Version: <157a>

**Comment by AqueleHaru** [comment]
<img width="895" alt="image" src="https://github.com/haubna/PhysicsMod/assets/61639486/31653978-4c7f-4a06-859a-a666b51523ea">

https://github.com/haubna/PhysicsMod/assets/61639486/9e661501-b59f-4797-a611-e260ba069d1f

**Comment by AqueleHaru** [comment]
update: all things like tall grass, doors, are duplicated.

**Comment by haubna** [comment]
Please install the proper Sodium + Iris version (Sodium 0.5 and Iris 1.6.5)

**Comment by AqueleHaru** [comment]
Im using sodium 0.5 and iris 1.6.5.

**Comment by AqueleHaru** [comment]
@haubna

**Comment by AqueleHaru** [comment]
Its a Indium mod bug, i'll wait till it update. thanks!

**Comment by AqueleHaru** [comment]
@haubna 
<img width="719" alt="image" src="https://github.com/haubna/PhysicsMod/assets/61639486/90d0ea6e-3f1a-4d25-87a4-92e80dd0c4ca">

thats what Indium dev saids.

**Comment by haubna** [comment]
Yup there was an oversight on my end. I thought indium hasn't changed the function that I mixin into. Should be fixed by now. Sorry for the inconvenience!
