### ISSUE TITLE
Trap doors on top of closed gates have collision issues.

### ISSUE THREAD

**Issue by nobu-sh** [haubna/PhysicsMod#714]
**Describe the bug**
When placing a trapdoor on top of a fence gate that is closed it bugs out very heavily. If the gate is open it acts as intended though.

**To Reproduce**
Place closed fence gate, place trap door on top.

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/61068742/0db451e9-079a-436d-8c6c-ad10f178c4be)

Minecraft Version: 1.20.1
Physics Mod Version: pro-v157a-fabric-1.20.1

**Comment by haubna** [comment]
You can disable collision for trapdoors in physics settings -> dynamic blocks -> customize
