### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jesse1233454** [haubna/PhysicsMod#715]
Whenever i put the mod into the mod folder and boot it up, i get this error message when i hit play.

put it in the mod folder and press play, then hit play again to open the minecraft cleint

Minecraft Version: 1.16.5
Physics Mod Version: 2.6.9
 
Full text: The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

![image](https://github.com/haubna/PhysicsMod/assets/141692680/92855681-bfe4-41b4-900e-154a60fbc688)

**Comment by haubna** [comment]
This old version no longer is supported.
