### ISSUE TITLE
Dynamic blocks issue with Continuity [BUG]

### ISSUE THREAD

**Issue by 1SN0** [haubna/PhysicsMod#716]
### **Describe the bug**
For dynamic blocks, the game renders the actual door along with the animation

### **To Reproduce**
Physics mod pro + Continuity
(Fabric 1.20.1)

### **Screenshots**

https://github.com/haubna/PhysicsMod/assets/138936344/e87a82e7-b988-4aa0-bf43-fcf232ac9723

**Comment by AqueleHaru** [comment]
it's caused if you're using with indium. it happened to me.

**Comment by haubna** [comment]
Should be fixed with v158. Please reopen a new issue if the problem still persists!

**Comment by ixradioactivexi** [comment]
it's still happening on v158
