### ISSUE TITLE
Game crashes when trying to "blockify" enities when using sodium 5.0 [CRASH]

### ISSUE THREAD

**Issue by Ferogreywolf7** [haubna/PhysicsMod#718]
**Describe the bug**
Game crashes when entities die using sodium mod
Crash report: https://pastebin.com/B1MTS7H7
Using fabric 0.14.21

**To Reproduce**
Add sodium 5.0 and physics mod v157 to the game and join a world/server. Go near a mob and kill it

**Screenshots**

Minecraft Version: <1.20.1>
Physics Mod Version: <157>

**Comment by haubna** [comment]
Thanks for the report, please update to v158!
