### ISSUE TITLE
Only apply physics to entities if they played their death animation before despawning

### ISSUE THREAD

**Issue by Khodyn** [haubna/PhysicsMod#72]
Why isn't this default behavior already? Would fix #55 and the issues mentioned [in this reply.](https://github.com/haubna/PhysicsMod/issues/55#issuecomment-888691200)

**Comment by haubna** [comment]
True. Haven't thought about the death animations yet. I will give it a try. But I am not sure if it would seamlessly work. If it results in way dirtier code I will probably not do it (like inserting in all different death animations).

**Comment by haubna** [comment]
Let me know if it works in version 2.4.7 (it should). I already did the ragdolls on death animations except that I had a fallback method which got triggered whenever a mob got removed from the client (due to some special cases like the ender dragon and for mods that add mobs like the ender dragon).

**Comment by Khodyn** [comment]
> Let me know if it works in version 2.4.7 (it should). I already did the ragdolls on death animations except that I had a fallback method which got triggered whenever a mob got removed from the client (due to some special cases like the ender dragon and for mods that add mobs like the ender dragon).

Works great, thanks! Looks seamless.
