### ISSUE TITLE
Massive Frame Drops When (Big) Explosions Happen [BUG]

### ISSUE THREAD

**Issue by IceBlossom** [haubna/PhysicsMod#720]
**Describe the bug**
Whenever a big, multi-entity explosion happens, such as fighting the Wither or blowing up a decent amount of TNT, the game will lock itself to 20 or lower FPS. 

**To Reproduce**
Spawn the Wither and let it mess around a bit, or place 3 or more TNT next to each other.

**Videos:**

https://github.com/haubna/PhysicsMod/assets/78196119/03a7c2c3-800a-4a03-a6aa-b0b65ebb7734

https://github.com/haubna/PhysicsMod/assets/78196119/608786bb-52c1-4531-9e3a-b14aa2edc7b6

Minecraft Version: 1.20.1, with Sodium 0.5
Physics Mod Version: 3.0.5b

The frame rate reverts back to normal after a little while or if you quit then re-enter a world, so I presume this has to be an issue surrounding particles.

**Comment by haubna** [comment]
Wow this bug was even deeper than expected. It could cause lag the longer you played. Although the drop in framerate during the explosion might happen due to the amount of particles it shouldn't have been lagging when mining a single block afterwards. This should be fixed with v158a and 3.0.6. Thanks for the report!

**Comment by IceBlossom** [comment]
> Wow this bug was even deeper than expected. It could cause lag the longer you played. Although the drop in framerate during the explosion might happen due to the amount of particles it shouldn't have been lagging when mining a single block afterwards. This should be fixed with v158a and 3.0.6. Thanks for the report!

No problem! Glad I could help make the mod better! Now, I shouldn't have my frame rate die while playing MCC Island. :D
