### ISSUE TITLE
Punching mobs crashes game. [1.20.1]

### ISSUE THREAD

**Issue by Sebimmortal** [haubna/PhysicsMod#721]
Whenever I punch a mob my game lags and then just crashes. I don't know what happened or if it is my computer that caused it. i was on Minecraft 1.20.1, and using the most recent version of physics mod (3.0.6). I was using the fabric loader play the game.

HOW TO REPRODUCE:

1. Punch a mob
2. The game crashes

Can someone please help.

**Comment by haubna** [comment]
Please update your iris + sodium (and other mods). Next time also include a crash log please.
