### ISSUE TITLE
A Massive Amount of Log Spam[BUG]

### ISSUE THREAD

**Issue by IceBlossom** [haubna/PhysicsMod#723]
**Describe the bug**
Whenever moving in a multiplayer server, such as Hypixel or MCC Island, anytime the player moves, tons of warnings get thrown out.

**To Reproduce**
Just move around in a multiplayer server (however, this only affects some servers)

**Screenshots/Other Media**
[latest.log](https://github.com/haubna/PhysicsMod/files/12340947/latest.log)
https://www.youtube.com/watch?v=oRzTrxJh7So

Minecraft Version: 1.20.1 w/ Sodium 0.5.0
Physics Mod Version: 3.0.6

That number spam is weird too, but I don't think it's related to Physics Mod.

**Comment by Wreckoning90125** [comment]
The number spam is definitely also physics mod. I'm having only that issue.

**Comment by Jim3535** [comment]
I noticed I have the same issue with the physics mod and the Prism Launcher. It only happens in multiplayer. It also appears that the number spam doesn't make to the actual log file.

What I suspect might be happening is that the physics mod is writing numbers to the console, and the Prism Launcher is picking it up. 

I have attached the minecraft log file, as well as the log as captured by Prism while it's running a short session on a test install. This is only with fabric and the Physics mod installed.

[latest.log](https://github.com/haubna/PhysicsMod/files/12534319/latest.log)
[Prism Captured Log.txt](https://github.com/haubna/PhysicsMod/files/12534320/Prism.Captured.Log.txt)

![Log screen](https://github.com/haubna/PhysicsMod/assets/120746893/810dd688-799a-4348-880a-67a793d0417a)

**Comment by haubna** [comment]
The error happens due to a malformed physics mesh. Probably due to some weird things Hypixel does.

**Comment by haubna** [comment]
@Jim3535 the log spam regarding your issue is fixed with Pro V149 and Lite 3.0.7.

**Comment by haubna** [comment]
I narrowed the error down. It was due to Hypixel creating entities with a hitbox width/height/depth of 0/0/0 (essentially no hitbox). Fixed in Pro V149 and Lite 3.0.7. Thanks for the report!
