### ISSUE TITLE
Bug description [BUG] I Cant Seem to find the Create new Animation button Anywhere

### ISSUE THREAD

**Issue by JakeSmiley000** [haubna/PhysicsMod#725]
The Create new animation button is not showing up or i just forgot where it was.
Can you Please Show/Tell me Where The "Create New Animation" Button is, i Really appreciate it

Minecraft Version: v1.18.2
Physics Mod Version: 2.12.3

**Comment by haubna** [comment]
Options > Physics Settings > Animations > Create Animation at the bottom
