### ISSUE TITLE
Mob/block selections not saving

### ISSUE THREAD

**Issue by RobinYH** [haubna/PhysicsMod#73]
Whenever I restart the game, the options for what mobs/blocks do what animation doesn't seem to save. I personally don't like the ender dragon becoming ragdoll and just falling through the end island when I kill it! (that also might be another bug)

**Comment by haubna** [comment]
None of this is happening on my end. Can you include logs? Mods used and so on.

**Comment by RobinYH** [comment]
> None of this is happening on my end. Can you include logs? Mods used and so on.

[latest.log](https://github.com/haubna/PhysicsMod/files/6953642/latest.log)

**Comment by haubna** [comment]
So my best guess is that you use immersive portals that is causing this issue. Not sure about the options thing though.
