### ISSUE TITLE
[FEATURE REQUEST] Make it possible to have MULTIPLE "Can link" in one single block

### ISSUE THREAD

**Issue by GuardianWorld** [haubna/PhysicsMod#730]
So, was messing around with wanting to work Physics mod with the AdditionalLanterns mod, and that mod adds like... 300 types of lanterns and 40 chains.
I wanted to make all COMBINATIONS, but... with the config (Vines) file being 12MBs (400.000 lines) the mod simply ERASED the second coming of each block and left me with a measly 10.000 lines... (300kb)... It does not want to do all combinations i guess

[physics_vines_client_config_Working.txt](https://github.com/haubna/PhysicsMod/files/12489972/physics_vines_client_config_Working.txt)

The WORKING TXT is the one i'm using right now, and the mess that isn't working is:
[physics_vines_client_config.txt](https://github.com/haubna/PhysicsMod/files/12489980/physics_vines_client_config.txt)

I made this monster with this code by the way https://github.com/GuardianWorld/PhysicsConfig_AdditionalLanterns

**Comment by haubna** [comment]
Feature requests only in the discord. I will keep it in my mind though to add that. It is currently a technical limitation and would need a significant rewrite of the vine system.
