### ISSUE TITLE
[1.20.1 Forge pro-v158a] Rain not showing on server but shows on singleplayer

### ISSUE THREAD

**Issue by MrKashew** [haubna/PhysicsMod#731]
Tested with ONLY this mod installed on Forge 47.1.43
Server running the same forge version - with no mods
Rain / downfall is visible with same configs on singleplayer but not when joining the server
[latest.log](https://github.com/haubna/PhysicsMod/files/12495353/latest.log)
[debug.log](https://github.com/haubna/PhysicsMod/files/12495354/debug.log)
![image](https://github.com/haubna/PhysicsMod/assets/53996665/20d651b6-15b0-4132-af5c-36e32341b328)
note the rain droplets on the floor
Configuration used:
[physicsmod configs.zip](https://github.com/haubna/PhysicsMod/files/12495363/physicsmod.configs.zip)

**Comment by MrSteveOff** [comment]
use fabric, forge is cronge

**Comment by haubna** [comment]
Fixed with v159. Thanks for the report!

**Comment by MrSteveOff** [comment]
****
