### ISSUE TITLE
I can't load my world if both physics mod pro and rubidium are installed.

### ISSUE THREAD

**Issue by gitguette** [haubna/PhysicsMod#732]
If both physics mod pro and rubidium are running, and I attempt to load a world, the game crashes after varying times.

To reproduce:
1. Use the physics mod pro and rubidium mods on forge.
2. Launch game with a world saved.
3. Load said world.

Info:
Minecraft Version: 1.20.1 Forge
Physics Mod Version: 3.0.5

**Comment by haubna** [comment]
Here are the supported versions: https://minecraftphysicsmod.com/installation
