### ISSUE TITLE
GUI Physics incorrectly activating [BUG]

### ISSUE THREAD

**Issue by srnyx** [haubna/PhysicsMod#733]
This is the same as https://github.com/haubna/PhysicsMod/issues/669, although it's closed so I thought I'd make a new issue (as the bug still occurs)

I have the keybind "not bound" but it's triggering whenever I use "extra" keys (ones that are identified as `scancode.XXX` when binding them in Minecraft [aka volume/media controls])

Minecraft: 1.20.1
Physics Mod: 3.0.7
Fabric: 0.14.22
Mods: [paste.srnyx.com/ufosugatuq.yaml](https://paste.srnyx.com/ufosugatuq.yaml)

**Comment by PanoptesDreams** [comment]
Same! This has affected every physics version I have used in the last few months.
I even went to the extent of rebinding it to F24, a key not on my keyboard.

My question for @srnyx is if you're using the Pro version or not.
I am.

MC: 1.18.2, 1.19.x, 1.20.x

**Comment by PanoptesDreams** [comment]
Also thank you for highlighting the fact it was **media keys** that was causing this to occur, means I can fix it immediately by pressing any media key again *phew*

**Comment by srnyx** [comment]
> My question for @srnyx is if you're using the Pro version or not. I am.

I'm using the free version

**Comment by haubna** [comment]
Will be fixed in the next release. Thanks for the report!

**Comment by PanoptesDreams** [comment]
@haubna why are pro versions labeled in the hundreds, yet free versions seem to be SEMVER

Edit: It's confusing when trying to make reports.

**Comment by PanoptesDreams** [comment]
> > My question for @srnyx is if you're using the Pro version or not. I am.
> 
> I'm using the free version

Thank you. This confirms it affects **ALL** versions, pro or not.
Like I said I've noticed this behavior in older versions, I'm pretty sure this is a long-standing bug.

**Comment by haubna** [comment]
From a user perspective a simple iterative number scheme is easier to understand (that's what also got reported on my discord several times, that they like the simplicity of it). That's why I went with it. Internally I use the scheme of the lite version.

**Comment by PanoptesDreams** [comment]
> From a user perspective a simple iterative number scheme is easier to understand (that's what also got reported on my discord several times, that they like the simplicity of it). That's why I went with it. Internally I use the scheme of the lite version.

I prefer the Pro version labeling for end users, but as a dev I much prefer proper use of semver, at least embedded somewhere in metadata.

**Comment by haubna** [comment]
Fixed with Pro v162 and Lite 3.0.9a
