### ISSUE TITLE
Create mod crashes on forge and not fabric when breaking a block

### ISSUE THREAD

**Issue by ziadrrr** [haubna/PhysicsMod#736]
**Describe the bug**
Game goes into black screen on Create mod if you break a large water wheel
it only happens on Forge i have tested it both on 1.19.2 and 1.20.1 i also made sure there isn't other mods apart from physics and Create mod. i have played Fabric before it never crashed before when these two installed 
**To Reproduce**
Steps to reproduce the behavior.
place large water wheel then break it on forge version of Minecraft with both Create and physics mod installed i have only tested it with large water wheel and the small one which it dosn't crash the game it just the large one i am not sure if there is any other block that crashes the game
**Screenshots**
A video of the bug: https://clipchamp.com/watch/r9LhUIHlNQD

Minecraft Version: <1.19.2/1.20.1>
Physics Mod Version: <latest version of both minecraft versions>

**Comment by ziadrrr** [comment]
so is it fixed? 😁

**Comment by Tsumiki129** [comment]
i have this same issue if it helps i got it to brake and list out of memory 1.20.1
 forge 47.2.1

**Comment by haubna** [comment]
This should technically be fixed with the latest versions. If not please reopen a new issue. Thanks for the report!
