### ISSUE TITLE
Block falldown doesn't work[BUG]

### ISSUE THREAD

**Issue by AyakariRuka** [haubna/PhysicsMod#738]
**Describe the bug**
I have kept all the options in the default settings, but the collapsing blocks did not work as expected. It had a noticeable effect when I was using version 154, but it stopped working when I upgraded to version 156 to version 160. I have tried reinstalling all the files and isolating them for separate versions, and effects like ocean and smoke are working fine. Only the collapsing effect is not working.
By the way,I'm very sure I kept Collapse open.

Minecraft Version: <1.20.1>
Forge Version:<1.20.1-47.1.46>
Physics Mod Version: <V156-160 Pro>

**Comment by AyakariRuka** [comment]
![2023-09-21_10 24 18](https://github.com/haubna/PhysicsMod/assets/102884228/7cac36c0-efeb-4cda-afb1-86241beea769)
like this.

**Comment by AyakariRuka** [comment]
![2023-09-21_10 24 18](https://github.com/haubna/PhysicsMod/assets/102884228/832a0b17-f33a-42b4-907e-30f817138199)
like this

**Comment by AyakariRuka** [comment]
![2023-09-21_10 24 18](https://github.com/haubna/PhysicsMod/assets/102884228/53eb0090-24cb-4746-8a64-5bfb9f2a35ce)

**Comment by haubna** [comment]
Thanks for the report, Fixed with v160a (v160 Forge 1.20.2 also contains the fix)!
