### ISSUE TITLE
Crash when breaking end portal block or respawning ender dragon [BUG]

### ISSUE THREAD

**Issue by Lerrycapetime** [haubna/PhysicsMod#739]
**Describe the bug**
When respawning the ender dragon it has a chance to crash, assume it might be the crystals doing it?
When entering creative and breaking the completed end portal block that sends you to the end, it'll crash. (not the frames.) 
Can be prevented if you turn off physics for that block. 
If you need a log file I can send but should be easy to reproduce this crash.

Minecraft Version: FORGE 1.20.1 - 47.1.46
Physics Mod Version: Latest. Physics 3.0.8 (Forge 1.20.1)

**Comment by haubna** [comment]
Crash log would be nice, thanks!

**Comment by ItIsNotAPlayer** [comment]
Also happens on the gateway block.
[crash-2023-09-30_18.01.08-client.txt](https://github.com/haubna/PhysicsMod/files/12774401/crash-2023-09-30_18.01.08-client.txt)

**Comment by haubna** [comment]
That's an interesting crash, I wasn't able to reproduce this one until I removed sodium + iris. It crashes due to missing texture coordinates and as it seems sodium + iris supply those but vanilla Minecraft doesn't. Will ship the fix in the Lite 3.0.9 and Pro v161.

**Comment by haubna** [comment]
New versions with the fix are now online. Thanks for the report!
