### ISSUE TITLE
Incompatibility with LabPBR textures 'n shaders

### ISSUE THREAD

**Issue by tajemniktv** [haubna/PhysicsMod#74]
Hey, so I'm using Vanillaccurate + Complementary Shaders and sadly this happens 

LabPBR turned on

https://www.youtube.com/watch?v=6Jwhfs8X0Z8

LabPBR turned off

https://www.youtube.com/watch?v=XUKzGcvxA7s

F3 Screenshot:
<a href="https://ibb.co/61zvykB"><img src="https://i.ibb.co/ZY5Hf0m/2021-08-10-02-33-08.png" alt="2021-08-10-02-33-08" border="0"></a>

**Comment by haubna** [comment]
Have you tried that combination with the Iris Shaders mod? If so could you let me know if this problem exists there as well? Seems like it's binding a wrong texture though.

**Comment by tajemniktv** [comment]
Iris mod does not support PBR textures (Except Complementary Integrated PBR option). With Integrated ones enabled, the grass block fractures are red (Screenshot). 

Default texturepack:
![2021-08-10_18 15 12](https://user-images.githubusercontent.com/12156943/128901284-937279a4-e239-48b8-ab14-066f7b7fc89a.png)

Vanillaccurate:
![2021-08-10_18 16 38](https://user-images.githubusercontent.com/12156943/128901326-5533ba8b-404f-46d3-ab96-0438eccfba54.png)

**Comment by anotherbender** [comment]
im having the same issue, using optifine + complementary shader PBR + vanillaaccurate

**Comment by doanamo** [comment]
For me something similar happens with BSL Shaders and Vanilla PBR, where I see rainbow/glitching textures on fratures/ragdolls, but only if I have parallax enabled in the shader.

**Comment by haubna** [comment]
Yeah happens cuz I only bind the main texture atlas, will be fixed in future releases :)

**Comment by haubna** [comment]
Fixed in the latest version.
