### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by Miki1234556** [haubna/PhysicsMod#740]
When i use seus Ptgi her 3.0 with forge splashes are black snow are black and when i break block it only destroy one block and this happens with all texturepacks

**Comment by haubna** [comment]
PTGI is not supported

**Comment by Miki1234556** [comment]
Hodilton used ptgi

W dniu pt., 22.09.2023 o 11:53 haubna ***@***.***> napisał(a):

**Comment by Miki1234556** [comment]
But when i switcha to Seus renewd i have same Buga

W dniu pt., 22.09.2023 o 12:33 Mikołaj Lamcmański <
***@***.***> napisał(a):

**Comment by Miki1234556** [comment]
W dniu pt., 22.09.2023 o 12:34 Mikołaj Lamcmański <
***@***.***> napisał(a):
