### ISSUE TITLE
modded banners crash the game [BUG]

### ISSUE THREAD

**Issue by gitguette** [haubna/PhysicsMod#741]
**Describe the bug**
trying to place down a banner with a pattern added with mods when banner physics are enabled.

**To Reproduce**
-download the physics mod, and a mod that adds banner patterns, such as alex's mobs or rats.
-launch a world, and obtain one of these modded banner patterns
-craft a banner using this pattern(the patter also doesn't show up in the loom interface)
-place the banner down
-immediate crash

**Screenshots**
no screenshots

Minecraft Version: 1.20.1, forge 47.1.3
Physics Mod Version: 3.0.5

**Comment by haubna** [comment]
Include the crash log

**Comment by gitguette** [comment]
[full log](https://mclo.gs/peSJsjr)
also, the banner doesn't show a texture in the inventory

**Comment by haubna** [comment]
Please update your physics mod version. This issue got fixed already! Thanks for the report anyways :)
