### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by Miki1234556** [haubna/PhysicsMod#742]
When i use ANY shader i have
Black splashes 
Block falldown dont work
And Please help me

**Comment by haubna** [comment]
Please provide more information and open a new issue.

**Comment by Miki1234556** [comment]
So when i use shader for example SEUS renewed splashes color is black and when i destroy block blocks above dont break when i destroy one block in Cave blocks above dont fall

**Comment by haubna** [comment]
SEUS can't render transparent particles that is why they turn black (nothing I can do about it). Block collapsing should be fixed with the latest version.
