### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by wycats0** [haubna/PhysicsMod#743]
**Describe the bug**
The mod Physics crashes with Rubidium

**To Reproduce**
1. Open a Minecraft modded with Forge Modloader, Physics Mod and Rubidium.
2. Create or open a world.
3. The game will crash.

Minecraft Version: 1.20.1
Forge Modloader: 47.1.3
Physics Mod Version: physics-mod-pro-v160-forge-1.20.1
[crash-2023-09-22_18.02.38-client.txt](https://github.com/haubna/PhysicsMod/files/12704607/crash-2023-09-22_18.02.38-client.txt)

**Comment by haubna** [comment]
Here is the list of supported rubidium/oculus versions: https://minecraftphysicsmod.com/installation
