### ISSUE TITLE
Falldown

### ISSUE THREAD

**Issue by Miki1234556** [haubna/PhysicsMod#744]
When i break block blocks above dont break

Minecraft Version: 1.20.1
Physics Mod V160 forge

**Comment by haubna** [comment]
Thanks for the report, Fixed with v160a (v160 Forge 1.20.2 also contains the fix)!

**Comment by Miki1234556** [comment]
Thanks you are great

W dniu niedz., 24.09.2023 o 16:29 haubna ***@***.***>
napisał(a):
