### ISSUE TITLE
Water transparency bugged with ocean physics

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#745]
When ocean physics is enabled the transparency of the water when you are underwater and looking up, bugs out and is no longer visible.

Reproduceable while using Chocapic13 V9 Extreme preset Shader while underwater with ocean physics enabled (and maybe other shaders)

Ocean physics off:
![2023-09-23_13 23 57](https://github.com/haubna/PhysicsMod/assets/39260503/dba25017-1fd4-4bed-b17c-e6f1de82954e)
Ocean physics on:
![2023-09-23_13 24 17](https://github.com/haubna/PhysicsMod/assets/39260503/4e87e1a0-7a66-44f5-8d20-0165559ac87b)

Minecraft Version: 1.20.2
Physics Mod Version: 1.20.2 fabric

**Comment by haubna** [comment]
Bug will be fixed with Pro v162. Thanks for the report! :)

**Comment by haubna** [comment]
v162 is now online.
