### ISSUE TITLE
Embeddium support suggestion

### ISSUE THREAD

**Issue by GordonHollow** [haubna/PhysicsMod#748]
It's like Rubidium, but kinda have less problem with many mods.
But Physics mod don't support it, and embeddium devs say this can't be fixed on their end

**Comment by haubna** [comment]
I will stick to only one port for now and that is Rubidium. Alternatively you can use Optifine with Forge.

**Comment by GordonHollow** [comment]
Just check - latest rubudium crashes with latest Physics too, so maybe there is fix coming later, and it possibly can fix embeddium too

Cause rn, both rubidium and embeddium latest ver - depends on the same Sodium ver

**Comment by haubna** [comment]
Updated it, you might want to give it a try now. Someone said that it works with embeddium as well :)
