### ISSUE TITLE
[BUG] Broken with latest version of Rubidium

### ISSUE THREAD

**Issue by HockeyZman2000** [haubna/PhysicsMod#749]
Heavy fps drop upon loading into a world, anything affected by the mod appears to be doubled (almost like how you see double with eyes crossed). After about 10 seconds, game freezes and then crashes.

 To reproduce, load Rubidium alongside the pro version of Physics mod.

[latest.log](https://github.com/haubna/PhysicsMod/files/12732549/latest.log)

Minecraft Version: 1.20.1
Forge Version 47.1.47
Physics Mod Version: Pro Version 160a Forge
Rubidium 0.7.1

**Comment by haubna** [comment]
Please read through the tested setups (https://minecraftphysicsmod.com/installation). The latest version of Rubidium is not supported since it doesn't have a proper Oculus version supporting it.
