### ISSUE TITLE
Bug description [BUG] V160 collapse function failure

### ISSUE THREAD

**Issue by EZPZLMS** [haubna/PhysicsMod#751]
**Describe the bug**
Block collapse function failure！！！
However, this issue does not seem to appear on fabric

Minecraft Version: <version> forge 1.20.1
Physics Mod Version: <version>160

**Comment by haubna** [comment]
Have you tried v160b? I fixed it with v160a.

**Comment by EZPZLMS** [comment]
> 你试过 v160b 吗？我用 v160a 修复了它。

I can't find 160a for 1.20.1forge.........

**Comment by haubna** [comment]
Where are you downloading it from? It is both on my patreon and ko-fi page.
