### ISSUE TITLE
Crash with Embeddium

### ISSUE THREAD

**Issue by knoxhack** [haubna/PhysicsMod#752]
Crashlog: [https://gist.githubusercontent.com/knoxhack/652105eac09a415679375f92cd068d83/raw/8af15d53b4d2c4ff8e9aa9dca05ea869b2e2e03c/physics](https://gist.githubusercontent.com/knoxhack/652105eac09a415679375f92cd068d83/raw/8af15d53b4d2c4ff8e9aa9dca05ea869b2e2e03c/physics)

**Comment by haubna** [comment]
Please update to the latest forge version. I have uploaded a fix about 24 hours ago :)
