### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by knoxhack** [haubna/PhysicsMod#753]
[crash-2023-10-01_02.00.25-client.txt](https://github.com/haubna/PhysicsMod/files/12776506/crash-2023-10-01_02.00.25-client.txt)

Minecraft Version: 1.20.1
Physics Mod Version: physics-mod-3.0.8a-mc-1.20.1-forge

**Comment by knoxhack** [comment]
Happened when started raining

**Comment by haubna** [comment]
Update to 3.0.8b when using the latest oculus + rubidium
