### ISSUE TITLE
Water became transparent

### ISSUE THREAD

**Issue by AyakariRuka** [haubna/PhysicsMod#756]
Hello! In the process of using the Physics mod, I noticed that the ocean becomes transparent in large areas with a depth of one block. This happened while playing in a flat world. However, when I dug down to a depth of two blocks, the ocean appeared normal again. Additionally, I would appreciate it if you could optimize block collapses. Currently, when I dig a block, it causes any unsupported block within a nine-block radius below it to collapse. However, if I extend the blocks horizontally, no matter how far, they do not collapse. This makes the physics aspect seem not very “physical” at all.

Minecraft Version: <1.20.1>
Physics Mod Version: <V160b>

**Comment by haubna** [comment]
I was able to reproduce it in a flat world. The fix will be included in v161a. Thanks for the report!

**Comment by haubna** [comment]
Fixed with v162.
