### ISSUE TITLE
Compatibility with EMF

### ISSUE THREAD

**Issue by TqLxQuanZ** [haubna/PhysicsMod#757]
Currently, EMF just released a newer version for 1.18.2, I would like to request if possible, allow the ragdoll category section to be compatible with the mod itself, as right now all the enemies killed with Physics mod and EMF will just disappear entirely without any animation.

https://legacy.curseforge.com/minecraft/mc-mods/entity-model-features

**Comment by haubna** [comment]
Old mods not for Minecraft 1.20 will not receive support. Apart from that this is impossible since I have to create every ragdoll for every single feature by hand. Only vanilla mobs with no modifications have ragdoll support.

**Comment by Traben-0** [comment]
Hi I'm the dev for EMF, 

I am very interested in trying to get ragdoll support for custom models, I know a lot of pack devs wouldn't mind having to write up their own custom definitions for applying ragdoll connections and i dont mind making some way for them to do this themselves to apply via a RagdollHook on EMF's end.

However EMF does extend from ModelPart, and really needs that functionality, which i can see will break certain hooks from your message in the README. Is there something I could do on my end to fix this?

I have experimented several times with replacing the model with an identical copy made of regular vanilla model parts during mob death (this looses several model details but thats not important for this), however this also doesnt seem to be mapping/connecting joints correctly. Is this a limitation imposed by the vanilla models already having mappings perhaps?

I also am not very sure how the index numbers for the mapped parts works as it seems to be inconsistent from model to model , and between the same model when using the mapping function and when it is actually rendered as a ragdoll, I have no clues where to start to understand what is causing that on my end
