### ISSUE TITLE
Big lag spikes when using the mod with xaero world map [BUG]

### ISSUE THREAD

**Issue by Answordy** [haubna/PhysicsMod#758]
**Describe the bug**
This might be a super specific issue but it's quite annoying, as it makes the world map unusable with these settings. 

**To Reproduce**
1. Turn on Ocean Physics, specifically Adjust Hitboxes (not sure about that).
2. Open the world map.
3. There should be lag spikes every few seconds (only when the map is open), the more you have the map open and the more you explored the worse they get, world generation mods like Terralith, Tectonic etc make it worse for some reason. In my survival world where I have a couple thousand blocks explored I cant even use the world map its so laggy. 

**Screenshots**
Can make video if needed.

Minecraft Version: 1.19.2 forge 43.3.2 
Physics Mod Version: pro v153 forge 1.19.2
Xaero's World Map Version: 1.34.1 for forge 1.19.2

**Comment by haubna** [comment]
Old versions of the mod no longer get updates. This bug might already be fixed in 1.20. If you encounter the bug there please open a new issue. Thanks for the report anyways!
