### ISSUE TITLE
(1.16.5) zero fps with the dynamic trees mod

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [haubna/PhysicsMod#76]
standing in a forest drops the fps to near zero, the lag stops if block physics are disabled so i assume its just a simple fix of blacklisting block physics for dynamic trees.

**Comment by WitherSkell** [comment]
1.16.5 physics mod is old version, wait for 1.18 to when both mods will update.

**Comment by haubna** [comment]
Old versions of Minecraft are no longer supported.

**Comment by C4PTRAMPAGE** [comment]
because its that simple to update my 300+ mod modpack and every mod i use will be instantly updated when i need them to be.
thanks for nothing.

**Comment by haubna** [comment]
There is already a custom file for blocking certain blocks from triggering block physics. It can also be accessed over the physics settings menu ingame. That's all I have for you.
