### ISSUE TITLE
Issue with Physics Mod not creating ragdolls, and creating an error

### ISSUE THREAD

**Issue by 1Mercenary** [haubna/PhysicsMod#760]
Hi!

I didn't want to list this as a bug, and just wanted abit of help with trying to figure out this issue. Feel free to let me know if you're not up for this.

I have alot of mods, but this error consistently pops up. I'm very sure it;s a mod incompatibility, just unsure with what. Here's the log
[latest.log](https://github.com/haubna/PhysicsMod/files/12872557/latest.log)

You'll find several of the error at the bottom of the log. I killed 3 wolves and each gave an error.

Thank you!

**Comment by haubna** [comment]
This error can come up when the vanilla model got changed (through resource packs/mods) or it wasn't able to create the ragdoll due to other reasons. It basically is just an info for myself when somebody sends in crash logs.
