### ISSUE TITLE
Player being teleported into the void when breaking the ship helm [BUG]

### ISSUE THREAD

**Issue by respear** [haubna/PhysicsMod#761]
**Describe the bug**
Player being teleported into the void when breaking the ship helm.

**To Reproduce**

Build a ship.
Activate the ship.
Break a block on a ship.

**Screenshots**

https://github.com/haubna/PhysicsMod/assets/99116475/3ae3da4a-9a51-4612-9c34-ae53442c0af3

![image](https://github.com/haubna/PhysicsMod/assets/99116475/8788b6a5-59b7-4674-9f89-4e72cf2a2623)
![image](https://github.com/haubna/PhysicsMod/assets/99116475/37704ae9-c2d6-4007-a9fa-7de14b398cd2)

Minecraft Version: <1.20.1>
Physics Mod Version: <physics-mod-pro-v163-fabric-1.20.1_sodium_0.4.10.jar>

**Comment by haubna** [comment]
Interesting bug, can you reproduce this without the physics mod too? I am actually only changing the rendering part but it seems like it actually teleports you to the ship location (where it is located at by valkyrien skies). Until I find a fix I would suggest avoiding it, haha :D

**Comment by respear** [comment]
I reproduced it without the physics mod too, seems to be the valkyrien skies problem.
