### ISSUE TITLE
[BUG] Game crashing on Forge: 48.0.26

### ISSUE THREAD

**Issue by ArsiTheFox** [haubna/PhysicsMod#762]
**Describe the bug**
Mod Version: physics-mod-pro-v163-forge-1.20.2
Minecraft Version: 1.20.2
Forge Version: 48.0.26

Game crashes when trying to load just Physics Pro Mod
Tried on multiple other versions and still crashes.... it worked a week ago just fine......

![image](https://github.com/haubna/PhysicsMod/assets/24835664/9bf6fa11-81fc-4fd9-b14f-cb16c1863f9f)
Crash Report: [crash-2023-10-14_02.08.21-client.txt](https://github.com/haubna/PhysicsMod/files/12903279/crash-2023-10-14_02.08.21-client.txt)

Mod Version: physics-mod-pro-v163-forge-1.20.2
Minecraft Version: 1.20.2
Forge Version: 48.0.26

**Comment by haubna** [comment]
It seems like your forge install is corrupt. It says that is missing a class which Minecraft itself uses `Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.google.common.collect.ImmutableMap`

**Comment by haubna** [comment]
Switch to Forge 48.0.4 for it to work. I will upload a fix for the most recent Forge version as soon as possible. Seems like a fundamental issue on Forge's side though.

**Comment by haubna** [comment]
This was fixed on Forge's end.
