### ISSUE TITLE
Lag spike on block breaking [BUG]

### ISSUE THREAD

**Issue by Rad586** [haubna/PhysicsMod#763]
**Describe the bug**
It creates a lag spike on block breaking when first join the world

**To Reproduce**
1. join the world
2. break a block

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/99306685/88d344f6-a68f-4503-958a-eaf878bcfee5)

Minecraft Version: 1.19.2
Physics Mod Version: 2.12.5
(no other mods besides fabric api)

**Comment by haubna** [comment]
This can happen due to libraries being loaded. But in your particular case it is probably more noticable because your single core CPU performance isn't very good.
