### ISSUE TITLE
Hanging sings connected to chains

### ISSUE THREAD

**Issue by Specimen-420** [haubna/PhysicsMod#765]
Hanging signs should swing with chains when connected to them.

**Comment by Specimen-420** [comment]
Ik it's more of an enhancement and not a bug but I didn't know where else to put it

**Comment by haubna** [comment]
You can actually create something like that yourself by editing it in dynamic blocks -> customize. Simply set the block it can link to to chains.

**Comment by Specimen-420** [comment]
![image](https://github.com/haubna/PhysicsMod/assets/79764173/00d51bb4-1e19-4530-bf8c-cb7dc571647b)
how so? if i link it throught chain setting i can only select one sign

**Comment by haubna** [comment]
You will need to edit it on the chain block, it won't be fancy though.

**Comment by Specimen-420** [comment]
Can I link it to multiple blocks or just one?
