### ISSUE TITLE
Fire Block [BUG]

### ISSUE THREAD

**Issue by moritztim** [haubna/PhysicsMod#766]
**Describe the bug**
Extinguishing fire spawns a fire physics object

**To Reproduce**
light a block on fire, left click the fire

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/90388353/0353a060-92f4-40b2-ad6c-e9302ccef0ac)

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.9a

**Comment by moritz-t-w** [comment]
![image](https://github.com/haubna/PhysicsMod/assets/90388353/466da8b9-15c9-462c-a021-1c3cd039b2f8)

**Comment by haubna** [comment]
Edit the block break type to "OFF" in blocks > customize.

**Comment by moritztim** [comment]
My Point is that this doesn't make sense, so it should be disabled by default
