### ISSUE TITLE
Potential fix for block/dynamic block destruction incompatibility with CREATE

### ISSUE THREAD

**Issue by VOLKOUL** [haubna/PhysicsMod#768]
So whenever a block or a dynamic block (like a trapdoor) is part of a Create contraption that starts moving, it will register that movement as being destroyed and therefore will make a physics block break particle/entity, resulting in this mess:

![2023-10-27_10 46 38](https://github.com/haubna/PhysicsMod/assets/97387920/fc258810-c94e-4266-941e-4316e44bf570)

Making blocks linked with Create's glue blacklisted from exhibiting such behavior could fix the issue. If you want to make a moving contraption you **need** glue. So basically when Physics Mod sees a glued block it will disable it's physics.

**Comment by haubna** [comment]
Thanks for the info. I haven't tried Create myself but will definitely have a look at better mod compatibility in the future!

**Comment by haubna** [comment]
Closed due to duplicate
