### ISSUE TITLE
Can we get separate lifetime sliders for mobs versus blocks?

### ISSUE THREAD

**Issue by InfernoDigital** [haubna/PhysicsMod#77]
I like to see the mob ragdolls stick around for a while, but I want the particles for blocks to go away pretty quickly so they don't clog up my vision, is there any way we could get separate sliders in options for the lifetime of mobs and blocks? that way I can have block physics particles stay around for like 0.5 seconds and have the mob ragdolls stay for like 8 seconds? That would be sick!

Keep up the great work!

**Comment by haubna** [comment]
Sure. Will add it in a future update.

**Comment by SylisMC** [comment]
this will be a nice addition :)

**Comment by haubna** [comment]
Already implemented. Comes in the next release :)

**Comment by haubna** [comment]
Version 2.5.5 is now released and contains this feature.
