### ISSUE TITLE
The Twisting Vines that are placed when the Dynamic Block Physics is on are incorrect [BUG]

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [haubna/PhysicsMod#770]
Place a Twisting Vine and use Bone Meal to grow it when the Dynamic Block Physics is on.

Minecraft Version: 1.20.2
Physics Mod Version: v163 fabric

https://github.com/haubna/PhysicsMod/assets/102716584/7dcccb6e-07ad-4275-9d32-925bcd726b6d

**Comment by MrSteveOff** [comment]
What mods are you using? and send the log file

**Comment by haubna** [comment]
Thanks for the report, this can indeed happen when the bone meal is applied to fast. I will have a look at it!

**Comment by MrSteveOff** [comment]
bro really waited a whole year to just close a problem💀
