### ISSUE TITLE
Not loading [FATAL BUG/COMPAT ISSUE]

### ISSUE THREAD

**Issue by Feliks-WR** [haubna/PhysicsMod#771]
Game not loading

Install all my mods, I guess (check log)

N/A

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.9a

**Comment by haubna** [comment]
You didn't provide any logs

**Comment by Feliks-WR** [comment]
https://mclo.gs/Y5EkmMq

**Comment by Feliks-WR** [comment]
https://mclo.gs/AQhXLDK
