### ISSUE TITLE
Snow appears black when using SEUS PTGI [BUG]

### ISSUE THREAD

**Issue by CuzImTim** [haubna/PhysicsMod#775]
**Description**
As the title states, when I use any version of SEUS PTGI (I have tested it with E12, HRR 2.1 and HRR 3) snow appears as a solid black. It retains all of its functionality, it's just the appearance that is wrong. However, when using any other Shader, including SEUS Renewed, this issue doesn't occur and the Snow apears how it should. When destroying a Snow Block, it appears in its regular color.

**To Reproduce**
As ive said, the snow simply appears completly black when using SEUS PTGI E12 / HRR Test 2.1 / HRR 3 but not with any other Shader. However, the snow sometimes appears correctly when far away or at the edges of the screen, however I couldn't find a clear pattern here yet.

**Screenshots**

![2023-1
![2023-11-13_20 4
![2023-11-13_20 46 48](https://github.com/haubna/PhysicsMod/assets/150730027/3410e876-b70d-4992-9801-74115edd4cfb)
6 44](https://githu
![2023-11-13_20 46
![2023-11-13_20 47 13](https://github.com/haubna/PhysicsMod/assets/150730027/61741e35-2834-46a7-a515-b8e3f4d9d5a7)
55](https://github.com/haubna/PhysicsMod/assets/150730027/dd188ba2-14e2-446a-b955-fcae6
![2023-11-13_20 47 5
![Uploading 2023-1
![2023-11-13_20 48 10](https://github.com/haubna/PhysicsMod/assets/150730027/08f7186d-25b4-49d3-b1ce-c842be174ec7)
1-13_20.47.34.png
![2023-11-13_20 48 15](https://github.com/haubna/PhysicsMod/assets/150730027/e8546d91-4915-42a9-8048-707e1549039e)
…]()
6](https://github.com/haubna/PhysicsMod/assets/150730027/76bd6a64-1c89-44a8-af36-e9bf3b2eedd9)
7d48d31)
b.com/haubna/PhysicsMod/assets/150730027/3909591f-9986-4306-8fe7-74898e2227b4)
1-13_20 46 37](https://github.com/haubna/PhysicsMod/assets/150730027/1b59e2c3-bb3d-4efb-982f-fa589888844c)

Minecraft Version: 1.19.2
Physics Mod Version: physics-mod-pro-v153-fabric-1.19.2

**Comment by haubna** [comment]
Somebody in the past has made a fix for this on my discord server but I am not sure if this fix is still online. Only the shaderpack creator can fix that (or people that modify those shaderpacks).
