### ISSUE TITLE
Invisible snow block [COMPATIBILITY]

### ISSUE THREAD

**Issue by Xen0traX** [haubna/PhysicsMod#776]
**Describe the bug**
The physical blocks of the 'snow' type are invisible, allowing the user to see under the map (they can see through the block located beneath the snow block).
When I break the snow block, the 'pieces' are visible, and the block located beneath the snow block returns to normal (you can no longer see through it).

**To Reproduce**
The issue appears to be related to the 'OptiFine_1.19.2_HD_U_I2' mod, as I only use the following mods:

fabric-api-0.76.1+1.19.2
optifabric-1.13.25
OptiFine_1.19.2_HD_U_I2
physics-mod-pro-v153-fabric-1.19.2
along with the shader: 'Continuum 2.1 Beta Build 23'
and the resource pack: 'Stratum 1024x.zip'

I tried disabling shaders and the resource pack, but the issue persisted. However, when I removed Optifabric and OptiFine, the problem with the snow physics disappeared.

**Screenshots**

***With Optifine and Optifabric :***
![Bug_Physics_Mod](https://github.com/haubna/PhysicsMod/assets/150948206/de7072b0-d536-4213-b7ce-3e23f521acbb)

***Without Optifine and Optifabric :***
![Whitout_Optifine_and_Optifabric](https://github.com/haubna/PhysicsMod/assets/150948206/468002f5-88f4-4824-8b53-a029a4baabeb)

Minecraft Version: <1.19.2>
Fabric-Loader Version :  <0.14.11-1.19.2>
Physics Mod Version: <physics-mod-pro-v153-fabric-1.19.2>
[Mods_For_Reproduce_Snow_Glitch.zip](https://github.com/haubna/PhysicsMod/files/13368496/Mods_For_Reproduce_Snow_Glitch.zip)

**Comment by haubna** [comment]
Optifabric is not supported, sorry. Either use Optifine on Forge or Iris + Sodium on Fabric.
