### ISSUE TITLE
Conflicts with the Timeless and Classics Guns MOD  [BUG]

### ISSUE THREAD

**Issue by xiaohang-like-car** [haubna/PhysicsMod#778]
Timeless and Classics Guns mod's projectiles will collide with the mod's projectiles

![image](https://github.com/haubna/PhysicsMod/assets/120241952/8eb3d91a-0588-43d3-9906-51d24c237eda)
[minecraft-exported-crash-info-2023-11-18T11-30-50.zip](https://github.com/haubna/PhysicsMod/files/13398832/minecraft-exported-crash-info-2023-11-18T11-30-50.zip)

Minecraft Version: 1.16.5
Physics Mod Version: Forge 2.6.7

**Comment by xiaohang-like-car** [comment]
It was a crash as soon as it was loaded

**Comment by haubna** [comment]
I am sorry but old versions of the mod are no longer supported. Thanks for the report though!
