### ISSUE TITLE
strange lighting around water physics blocks [BUG]

### ISSUE THREAD

**Issue by ser-tonin** [haubna/PhysicsMod#779]
**Describe the bug**
whenever a block that has water physics, like a cactus, the water comes out normally, but black areas show up around the water and stay on screen. if the black areas get on to the player, they stay on screen and follow around the camera 

**To Reproduce**
physics mod  1.20.1
MakeUp - Ultra Fast shaders

1. place a block that breaks with water physics
2. break said block and stare at the water for a few seconds (1-3 seconds should be long enough)
3. the black areas should appear next to and on the water, they grow outwards when moving your character and camera, or both

**Screenshots**
a video of what i mean (i had a hard time describing it since i havent seen anything like it)
https://github.com/haubna/PhysicsMod/assets/151402947/a271b184-b1f0-4da0-bc13-ffef7b721170
another screenshot i got when i let the black spots sit for a little
![image](https://github.com/haubna/PhysicsMod/assets/151402947/2e0cab9c-9b2c-4366-94f3-7af2cc57f580)
screenshot of all the mods im using (i dont think any of them apart from starlight should be an issue since its to do with lighting)
![image](https://github.com/haubna/PhysicsMod/assets/151402947/46f1e1d2-2465-4b6b-aa63-4e9d5ff0bd24)

Minecraft Version: <Fabric 1.20.1>
Physics Mod Version: <3.0.10>

**Comment by haubna** [comment]
Some shaderpacks are not supported and cause graphical issues. Here is a list of the supported liquid physics shaderpacks: https://pastebin.com/BHJv430d
