### ISSUE TITLE
Incompatibility with "Fresh Animation" recourse pack

### ISSUE THREAD

**Issue by CormacZ** [haubna/PhysicsMod#78]
![image](https://user-images.githubusercontent.com/71203678/129835368-8c404aa8-06df-477f-b3f5-4dc8e9550193.png)
basically this happen. There's more but I can't capture them cuz they go crazy lmao

**Comment by WitherSkell** [comment]
its obviously, physics mod uses own models, fresh animations others.

**Comment by haubna** [comment]
Things like other resource packs or mods will only be supported if the creator of those will implement them with the RagdollAPI.

**Comment by CormacZ** [comment]
Oh, alright then
