### ISSUE TITLE
when I kill the mobs there is no animation, they just disappear.

### ISSUE THREAD

**Issue by sMerAS26** [haubna/PhysicsMod#780]
**Describe the bug**

I am using embeddium, because I have better results with embeddium and all that, and well to be able to use the texture pack of fresh animation I have had to put other mods among those I put the entity model features and the entity texture features, among other mods but testing I have seen that when I have the physics mod the mobs disappear when I kill them, except if I remove those two mods already said, and well I do not know what to do, someone help me or if you know of a mod that makes this compatible.

![image](https://github.com/haubna/PhysicsMod/assets/141413536/a5bfb47e-e28e-4e1e-9051-ca9cd5a746ee)
![image](https://github.com/haubna/PhysicsMod/assets/141413536/00f4f7e6-9508-4693-8fbb-8301877d3c58)

Minecraft Version: <1.19.2-forge>
Physics Mod Version: <151pro>

**Comment by Maulment** [comment]
I think its something with the ingame config

**Comment by haubna** [comment]
Everything changing entities is not supported and causes issues (i.e. fresh animations).
