### ISSUE TITLE
Whenever i install the physics mod, it says get pro dispite me having pro

### ISSUE THREAD

**Issue by Maulment** [haubna/PhysicsMod#781]
**Describe the bug**
The mod is saying i dont have the pro version.

**To Reproduce**
Install the mod and the pro version.

**Screenshots**
![Screenshot 2023-11-22 024325](https://github.com/haubna/PhysicsMod/assets/149014851/df5cf742-c5c8-40b6-b9ef-7ea1eb7fd651)
![Screenshot 2023-11-22 0244045](https://github.com/haubna/PhysicsMod/assets/149014851/2e645dc5-b89c-4c83-a365-d81690a50146)

Minecraft Version: <1.19.2>
Physics Mod Version: <2.12.5>

**Comment by haubna** [comment]
You need to remove the lite version.
