### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by ilkerpro78** [haubna/PhysicsMod#782]
**Describe the bug**
When I enter the game, it gives an error screen. The version of Forge is the latest version, but I install the mod, I open the game, but an error screen appears, please fix it.

**To Reproduce**
please solve this problem as soon as possible

Minecraft Version: 1.19.3
Physics Mod Version: 2.12.5

**Comment by haubna** [comment]
Please include a log file or screenshot and open a new issue. Thanks!

**Comment by ilkerpro78** [comment]
OK, I took a photo, but please find the solution.

![Screenshot_2023-11-25-20-07-53-641_net.kdt.pojavlaunch.jpg](https://github.com/haubna/PhysicsMod/assets/141463253/7eb3c44d-c336-4fe2-8049-44415c8577c1)
