### ISSUE TITLE
The game crashed whilst mouseclicked event handler Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3225 failed[BUG]

### ISSUE THREAD

**Issue by SteelyArc** [haubna/PhysicsMod#783]
**Describe the bug**
When Im clicking on ,,create new world'', the game is crashing and showing this error message. 

The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3225 failed

**To Reproduce**
idk everytime i open the game and create a new world
![Bild_2023-11-26_205351706](https://github.com/haubna/PhysicsMod/assets/152097433/177f7d92-83e0-4425-b8cc-fc9fbf8557c7)

**Screenshots**

Minecraft Version: <1.20.2>
Physics Mod Version: <[Fabric 1.20.2 23w44a]
![Bild_2023-11-26_205507164](https://github.com/haubna/PhysicsMod/assets/152097433/ca5c57ac-77ec-4c60-b8f7-e212e48286c8)
![Screenshot 2023-11-26 205340](https://github.com/haubna/PhysicsMod/assets/152097433/24b167e0-4947-400a-b8d0-a1f11331c2a9)
>

**Comment by haubna** [comment]
You were using incompatible versions. Please make sure your Minecraft version and mod version match.
