### ISSUE TITLE
I can’t open Minecraft using the physics mod

### ISSUE THREAD

**Issue by josephpro123** [haubna/PhysicsMod#786]
Hey I’m trying to run Minecraft with the original launcher at the version 1.19.2 with forge in my Mac M2
I don’t know what to do for trying running this mod into my game, if someone know what to do please help me!
![IMG_8568](https://github.com/haubna/PhysicsMod/assets/152226001/f07650c3-e708-4512-b9e0-836f01267355)
![IMG_8569](https://github.com/haubna/PhysicsMod/assets/152226001/994ae15f-ef68-4139-bda6-37d9f9bd146f)

**Comment by haubna** [comment]
Your hardware isn't supported, sorry.
