### ISSUE TITLE
Configs randomly reset.

### ISSUE THREAD

**Issue by Amiiban** [haubna/PhysicsMod#79]
When I change a setting such as gravity, block specific configs or max particles, upon reloading the game, random configs will be reset.

**Comment by haubna** [comment]
Include the log after you changed settings.

Amiiban ***@***.***> schrieb am Mi. 18. Aug. 2021 um 11:25:

**Comment by Amiiban** [comment]
I actually managed to work out the issue myself. You appear to have two config files with the name: physics_client_config.json.
Basically, when you change a mob setting it replaces this file with a file of the same name, containing only mob information and no information about gravity and other physics settings. Or when you change gravity or physics settings it overwrites the mob settings.

You may need to merge these configs so they don't overwrite each other, or make a new config with a different name for mob settings. This problem is in 2.5.2 of the mod.

**Comment by haubna** [comment]
Thanks for figuring it out. Helped a lot. Fixed in the newest version (2.5.3).
