### ISSUE TITLE
MODPACK TESTING || TICKING ENTITY || TNT EXPLOSIONS [BUG]

### ISSUE THREAD

**Issue by makumaku1974** [haubna/PhysicsMod#790]
**Describe the bug**
Hi Im Maku. Im testing out some mods i've chosen for a personal use of modpack. For some reason the TNT chain explosion happens to crash the game with Physics on. I tested this out in 1.20.1 it was fine but for some reason in 1.20.2 (Ticking Entity somehow appears on mclogs as I tested the 248 mods and crashed the game already 3 times. Other mods were fine and only suspected the Physics mod which somehow can this be checked out?

**To Reproduce**

(Spamming TNT's and ignite it)

**Screenshots**

Minecraft Version: <1.20.2>
Physics Mod Version: <3.0.10>

[2023-12-04-7.log.gz](https://github.com/haubna/PhysicsMod/files/13542089/2023-12-04-7.log.gz)

An accurate way to reproduce the problem:
[mod list 1.20.2 Fabric.txt](https://github.com/haubna/PhysicsMod/files/13542162/mod.list.1.20.2.Fabric.txt)

**Comment by haubna** [comment]
Doesn't seem related to the physics mod (according to the logs).

**Comment by makumaku1974** [comment]
it's the mutant monsters
