### ISSUE TITLE
Leaves in trees are despawning constantly

### ISSUE THREAD

**Issue by WerewolfBX13** [haubna/PhysicsMod#793]
I have a video for better view: https://youtu.be/grAYH2-0IdE

Minecraft Version: 1.19.2
Physics Mod Version: physics-mod-pro-v153-forge-1.19.2

**Comment by haubna** [comment]
This happens due to the leave blocks not being close enough to the logs. However this is a feature of vanilla Minecraft and still happens without the physics mod installed. If you don't like the physics of the leaves you can turn them off in physics settings > blocks > customize.
