### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by MAYOSAD** [haubna/PhysicsMod#795]
**Describe the bug**
I have several worlds and servers with mods and they have always opened well. When I put the mod, without any shader mods [Optifine, Oculus, Rubidium], everything opens great for me, however when I try to open the world with shaders, it doesn't open. I have 32GB of RAM and the shaders have always worked correctly for me between 80/100 FPS. I use Forge because I need certain mods that are not for fabric.

**Error**
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraftforge.client.gui.overlay.ForgeGui.renderSelectedItemName(net.minecraft.client.gui.GuiGraphics, int)'

**Screenshots**
![Captura de pantalla 2023-12-19 215557](https://github.com/haubna/PhysicsMod/assets/154377344/ac98320e-30d2-4a1c-8af4-903361a6dd40)

Minecraft Version: <version>
Physics Mod Version: <version>

**Comment by haubna** [comment]
This is not related to the physics mod but you can't install Optifine and Oculus + Rubidium. Either use Optifine or Oculus + Rubidium.
