### ISSUE TITLE
Dynamic tall plant glitch

### ISSUE THREAD

**Issue by cccarrrottt** [haubna/PhysicsMod#797]
**Describe the bug**
Visual glitch, but physics don't work till the whole model shows up. Happens only with player-placed blocks, world-generated (and bone meal-generated too) blocks aren't affected. Can be fixed with either right-clicking on invisible parts of plant (they appear), by flying away, or with F3+A. Doors and trapdoors work fine.

UPDATE:
1.19.2 and 1.19.4 don't have this issue.

**To Reproduce**
1. Launch game
2. Load/create world
3. Enable dynamic blocks
4. Place any tall plant block

**Screenshots**
![2023-12-28_22 03 23](https://github.com/haubna/PhysicsMod/assets/123668783/6d5fcf31-c794-4516-81b5-aa92a59016af)

Minecraft Version: 1.20.1
Physics Mod Version: v164b (Pro)

**Comment by haubna** [comment]
Are you using any other mods?

**Comment by cccarrrottt** [comment]
No, only NeoForge 47.1.88 right now, but it happens in Forge and Fabric too if i remember correctly.

**Comment by haubna** [comment]
Thanks for the report, fix will be included in next version!
