### ISSUE TITLE
Physics Mod (physicsmod) has failed to load correctly

### ISSUE THREAD

**Issue by catzdogz** [haubna/PhysicsMod#798]
java.lang.reflect.InvocationTargetException: null
i am trying to make a realistic modpack and i am getting this error when Minecraft starts. I am using 1.19.2 and forge 43.3.0.
[latest.log](https://github.com/haubna/PhysicsMod/files/13805976/latest.log)

**Comment by haubna** [comment]
There seem to be a lot of other things going wrong with your install. Make sure you have the proper versions installed https://minecraftphysicsmod.com/installation
