### ISSUE TITLE
crash with "Linked Physics: OFF" [BUG]

### ISSUE THREAD

**Issue by peow** [haubna/PhysicsMod#799]
**Describe the bug**

when using **Physics Mod Pro**, together with the **Explosive Enhancement** mod (which basically adds more visual effects to explosions), when a **TNT** explodes a **Dynamic Block** that is configured as "**Linked Physics: OFF**", the game closes and a create a file named "hs_err_pid.log"

this crash doesn't happen all the time, I would say it has a 1/3 chance of happening and it **stops** happening when changing the Dynamic Block setting to "**Linked Physics: ON**"

**To Reproduce**
1- Place some oak_trapdoors
2- Set the oak_trapdoor to "Linked Physics: OFF"
3- use TNTs to blow up the trapdoors

i recorded this problem, please watch it: https://www.youtube.com/watch?v=gYfLrSxBDLs

I tried to reproduce this bug in Fabric 1.20.1 and Fabric 1.20.4, and it happened in both

--------------

hs_err_pid.log in **Fabric 1.20.1** - 
[hs_err_pid9340.log](https://github.com/haubna/PhysicsMod/files/13888102/hs_err_pid9340.log)

hs_err_pid.log in **Fabric 1.20.4** - 
[hs_err_pid11796.log](https://github.com/haubna/PhysicsMod/files/13888107/hs_err_pid11796.log)

Minecraft Version: 1.20.1/1.20.4
Physics Mod Pro Version: v164 / v165
Explosive Enhancement Version: 1.2.2 (https://modrinth.com/mod/explosive-enhancement)

If possible, please fix this problem for Fabric 1.20.1 with support for Fabric Loader 0.14.22, and I also ask you to see my other post where I list bugs I found in your mod - #794

**Comment by haubna** [comment]
I have changed something in the dynamic block physics with V166. It wasn't meant to fix this issue but it could technically work. If this crash still occurs please let me know!

**Comment by peow** [comment]
I think it's fine now
