### ISSUE TITLE
Create Water Wheel crashes with certain particle type

### ISSUE THREAD

**Issue by StellaBiscuit** [haubna/PhysicsMod#802]
**Describe the bug**
When break a normal or large water wheel, if the particle is set to Blocky (or Voxel for the large one) it will crash the game
This is an expansion of another bug report : #736

**To Reproduce**
Place a water wheel of any type
Set the block particle to Blocky
Break it
Crash!

**Screenshots**
Video from the original report : https://clipchamp.com/watch/r9LhUIHlNQD
Crash Report : [2024-01-15-6.log](https://github.com/haubna/PhysicsMod/files/13940523/2024-01-15-6.log)

Minecraft Version: 1.20.1
Physics Mod Version: v164b (Pro)

**Comment by StellaBiscuit** [comment]
It is an Out of Memory error, so it is likely that physics mod tries to create the wheel but for some reason loops infinitely causing the game to stop working instantly

Certain create blocks like cogwheel spawn twice when broken so maybe fixing that issue would fix the water wheel crash

**Comment by haubna** [comment]
My first guess is the model is very complex so it needs quite a bit of data and the stack that I use doesn't have enough memory. Will be fixed in future versions. Thanks for the report!

**Comment by haubna** [comment]
Should be fixed with latest versions.
