### ISSUE TITLE
Ripples cause water color/transparency issue [BUG]

### ISSUE THREAD

**Issue by eilamg** [haubna/PhysicsMod#805]
**Describe the bug**
Ripples seem to cause an issue with water color and/or transparency.

**To Reproduce**
Jump in some water.

**Screenshots**
Without ripples:
![2024-01-23_16 04 57](https://github.com/haubna/PhysicsMod/assets/4570254/fd56a46f-929a-48a3-9975-640a139aabe3)
With ripples:
![2024-01-23_16 05 08](https://github.com/haubna/PhysicsMod/assets/4570254/7ee60bf6-dbfa-4856-8dbf-e752122697de)

Minecraft Version: 1.20.1
Physics Mod Version: Pro v166 on both Fabric and Forge. Happens with and without Sodium/Embeddium and Iris/Oculus.

**Comment by haubna** [comment]
Fixed with v166a.
