### ISSUE TITLE
[BUG] Breaking particles glitch

### ISSUE THREAD

**Issue by cccarrrottt** [haubna/PhysicsMod#806]
**Describe the bug**
Some blocks don't have breaking particles anymore, every other block does, but they appear with glitched textures (problem occurs only with "particles" type).

**To Reproduce**
1. Install Physics Mod Pro
2. Set "Block Physics" to "Particles"
3. Break block

Minecraft Version: 1.20.1
Physics Mod Version: Pro v166a

https://github.com/haubna/PhysicsMod/assets/123668783/10fa11f2-b826-4901-bdf6-ba9230fd96b1

**Comment by haubna** [comment]
Thanks for the quick report, fixed with v166b!
