### ISSUE TITLE
Freezes on mojang loading scren [BUG]

### ISSUE THREAD

**Issue by nethernoah** [haubna/PhysicsMod#808]
My game launches fine and doesnt crash but when I get to the mojang loading screen, it freezes right before the bar finishes loading

It happens everytime I launch the game with physics mod

![Screenshot 2024-01-27 183908](https://github.com/haubna/PhysicsMod/assets/157935235/a4783627-f8e4-4cc4-99a2-6cf35c5110b8)

Minecraft Version: 1.20.2
Physics Mod Version: 3.0.11

**Comment by haubna** [comment]
Please include the Minecraft version + mod loader version (fabric/forge)
