### ISSUE TITLE
Item break particles spawn when swapping an item from the off hand to a empty hotbar slot [BUG] (Fabric)

### ISSUE THREAD

**Issue by BigBrainRobin29** [haubna/PhysicsMod#809]
**Describe the bug**
If you swap an item that can break from the off hand into an empty hotbar slot or vice versa, the item break particles show up.

**To Reproduce**
Enter a world.
Take an item with durability (e.g. Sword).
Swap it to the off-hand.

**Screenshots**

https://github.com/haubna/PhysicsMod/assets/152532785/7e23b48e-528a-4fd7-a04e-b5af6e93d958

Minecraft Version: <1.20.1>
Physics Mod Version: <3.0.10>

**Comment by YoshiRulz** [comment]
Repro'd on version 3.0.11, with Minecraft 1.20.4 and Fabric API 0.95.1. It seems to only affect *items which can't be placed* (cake and seeds aren't affected, for example).

**Comment by haubna** [comment]
Fixed with Pro v167, thanks for the report!
