### ISSUE TITLE
Break particles appear when you destroy items in ceartive backpack or use container like craftable,chest and furnace sometime

### ISSUE THREAD

**Issue by NoNameTeam-NoNamer** [haubna/PhysicsMod#811]
Break particles appear when you destroy items in ceartive backpack or use container like craftable,chest and furnace sometime.

How it happened
1.Create a new world or get in a server
2.If you are in creative mode,open your backpack,get an item to hotbar,then destroy it.
3.If you are in survival mode,open craftable,craft something.
4.Sometime it will happend.

**Screenshots**
It's strange that when I find this BUG,it don't appear again......

Minecraft Version: 1.20.4
Physics Mod Version: 3.0.11,Pro,NO shaderpack

**Comment by YoshiRulz** [comment]
Repro'd on version 3.0.11, with Minecraft 1.20.4 and Fabric API 0.95.1. Specifically shift-clicking the "Destroy Item" slot in creative. Seems to affect the same items as #809.

**Comment by haubna** [comment]
Fixed with Pro v167, thanks for the report!
