### ISSUE TITLE
 Small block of transparent glass/snow [BUG]

### ISSUE THREAD

**Issue by Snipy44** [haubna/PhysicsMod#814]
**Describe the bug**
Hello, once the snow is no longer on the block after walking on it, I can see through the ground

**To Reproduce**
You must remove the snow by walking on a mini block of ice as indicated on the screenshoot

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/3805333/4531ee06-2fb0-4ad3-8cae-043db7d91d9e)
![image](https://github.com/haubna/PhysicsMod/assets/3805333/d45b695a-0a11-4a72-805a-0d46f1fade09)
![image](https://github.com/haubna/PhysicsMod/assets/3805333/17509058-0d43-49b2-9b49-206ed6dfac99)

Minecraft Version: <1.20.4>
Physics Mod Version: <physics-mod-pro-v166a-fabric-1.20.4>

My mod list : 
![image](https://github.com/haubna/PhysicsMod/assets/3805333/6ad7a989-09ce-4644-9872-5d8e6e436b36)

My server mod list : 
![image](https://github.com/haubna/PhysicsMod/assets/3805333/22a2c967-9e9a-4451-b2b1-1f1abd013feb)

**Comment by Snipy44** [comment]
After try to disable Snow Physics : 
![image](https://github.com/haubna/PhysicsMod/assets/3805333/06b5a507-039e-4c99-b7e2-dae28aaf704b)

**Comment by haubna** [comment]
It seems like you are using a version of Iris that hasn't officially been released. Stick to Iris 1.6.14 and Sodium 0.5.5 for now.

**Comment by Snipy44** [comment]
ok thx you i try this today !

**Comment by Snipy44** [comment]
is work thx :)

**Comment by Snipy44** [comment]
Hello after install the update 'physics-mod-pro-v167d-fabric-1.20.4' the problem is back

> It seems like you are using a version of Iris that hasn't officially been released. Stick to Iris 1.6.14 and Sodium 0.5.5 for now.
