### ISSUE TITLE
[1.20.1][FORGE/NeoForge] Crash with Oculus 1.6.15 when applying shaders.

### ISSUE THREAD

**Issue by VOLKOUL** [haubna/PhysicsMod#815]
Details, crash report and latest log: https://github.com/Asek3/Oculus/issues/545

Physics Mod Pro v166b forge 1.20.1

**Comment by haubna** [comment]
Please stick to older versions of oculus for now. Iris has no official 1.16.5 release yet and usually Oculus and Iris versioning is pretty much the same.

**Comment by VOLKOUL** [comment]
As far as I know the Oculus 1.6.15 update was more of a patch that aimed to fix compatibility with Embeddium, rather than an actual major Iris/Oculus update. (kinda off topic, but currently Iris is developing Distant Horizons compatibility)

Previous versions of Oculus won't work with the last SEVEN Embeddium releases. Having to downgrade to Embeddium 0.2.13 would require to downgrade all of it's addons (Lazurite, Extra, Dynamic Lights, TexTrue's Options, etc) and a MULTITUDE of other mods that had to update to support the fixes and performance improvements new Embeddium provides (ETF, EMF, libraries, etc). All this just makes it easier to not use Oculus or Physics Mod alongside each other at all. 

I don't want to put pressure on you nor force you to do anything, but if you have the time I would suggest looking into it, as downgrading Oculus doesn't seem very plausible. Thanks.

**Comment by haubna** [comment]
v166c for Forge 1.20.1 is now available and supports Embeddium 0.3.1 and Oculus 1.6.15.

**Comment by VOLKOUL** [comment]
Wow, thank you! That was fast
