### ISSUE TITLE
Mob physics not working on the lastest version [BUG]

### ISSUE THREAD

**Issue by elAltrex** [haubna/PhysicsMod#816]
The mob physics is not working on this version,
Steps to reproduce the behavior.
- Launch the game
- Kill a mob

Minecraft Version: 1.20.1 FORGE
Physics Mod Version: physics-mod-pro-v166b-forge-1.20.1

**Comment by haubna** [comment]
Everything works fine on my end. You might be using an incompatible mod. If you figure out which one please open a new issue. Thanks for the report though!
