### ISSUE TITLE
Camera shaking when killed with mob physics turned on [BUG]

### ISSUE THREAD

**Issue by elAltrex** [haubna/PhysicsMod#817]
When you die with mob physics turned on the camera shakes violently in the death screen

Steps to reproduce the behavior.
Launch the game
Third person camera (optional)
use /kill

Minecraft Version: 1.20.1
Physics Mod Version: physics-mod-pro-v164b-forge-1.20.1

**Comment by elAltrex** [comment]
https://github.com/haubna/PhysicsMod/assets/156161230/ea1fad4b-a10b-4f28-b635-708e5700870d

Here's a video proof

**Comment by Renowbrine** [comment]
Me too, but, my Minecraft Version is 1.19.2 Mod Version is physics-mod-2.12.3-mc-1.19.2-forge

**Comment by haubna** [comment]
Fixed with Pro v167, thanks for the report!
