### ISSUE TITLE
How do you make it so that block physics collapsing stops?

### ISSUE THREAD

**Issue by Frizzledizzley** [haubna/PhysicsMod#82]
I've been trying to figure out this for me and my server and i just cant seem to find out what works, better yet is that i go in the config and just try and try and when im on single player it works crisp and clean. I use apex hosting and this is what i've done to try and figure this out 

[Server]
	#Enable/Disable collapsing blocks.
	collapse = false
	#Maximum number of collapsing block events that get caused by one update.
	#Range: -1 ~ -1
	maxCollapseObjects = -1
	#Collapsing speed in ticks. 0 means instant collapse.
	#Range: -1 ~ -1
	collapseSpeed = 0
	
	If there is anything im doing wrong just please let me know.

**Comment by haubna** [comment]
Which version are you using? The proper config should be in config/physicsmod/physics_server_config.json and should contain this:
```
{
  "collapse": true,
  "maxCollapseObjects": 195,
  "collapseSpeed": 10,
  "dropBlocks": true
}
```
Legacy versions of Minecraft are no longer supported.

**Comment by Frizzledizzley** [comment]
i am using 1.16.5 for forge, will that help?

**Comment by Frizzledizzley** [comment]
by the way, can you please send me a copy and paste so that i can disable it entirely? i dont want to break one structure and have it all collapse please.

**Comment by haubna** [comment]
If you can't seem to disable it, you might not want to tinker with configs. Or the 1.16.5 of the physics build is broken. Either way there is nothing that I can do for you since legacy versions are not supported.
