### ISSUE TITLE
Falling off the edge of some blocks even when croughing.

### ISSUE THREAD

**Issue by bababoul** [haubna/PhysicsMod#820]
When crouching on the edge of some blocks, instead of stopping me from falling, it does the opposite and lets me fall off the block. Not all blocks do this, but I can't figure out which do and which don't...

I have some other mods installed, maybe those are the root of the problem, all for forge:
  -Borderless Window;
  -Chunk Animator;
  -Create mod;
  -Valkyrien Skies;
  -Eureka;
  -Just Enough Items (JEI);
  -Just Enough Resources (JER);
  -Kotlin for Forge.
All the mods are on the right version of the game.

I am also playing on an Aternos server without the Physics Mod installed, only client-side.

Minecraft Version: 1.20.1
Physics Mod Version: PRO v164b forge 1.20.1

**Comment by haubna** [comment]
This issue not related to the physics mod.
