### ISSUE TITLE
Create Mod contraption particle bug.

### ISSUE THREAD

**Issue by VOLKOUL** [haubna/PhysicsMod#821]
This affects every Physics Mod version.

So whenever a block or a dynamic block (like a trapdoor) is part of a Create contraption that starts moving, it will register that movement as being destroyed and therefore will make a physics block break particle/entity. Making blocks linked with Create's glue blacklisted from exhibiting such behavior could fix the issue. If you want to make a moving contraption you **need** glue. So basically when Physics Mod sees a glued block it will disable it's physics.

This is a really annoying thing that makes the game look broken. Imagine opening a giant vault door and seeing it crumble as if it was made out of dust or ice lol

Whoops, sorry I forgot I had already reported this in https://github.com/haubna/PhysicsMod/issues/768

![2024-02-12_16 33 20](https://github.com/haubna/PhysicsMod/assets/97387920/8fd7311f-c57e-4974-b7be-2b5ec55c9135)

**Comment by haubna** [comment]
I will try to implement that logic for 1.20+, will come back to you once I have results.

**Comment by haubna** [comment]
I've uploaded v167b which attempts to fix this issue. I tried the glue approach but that sadly didn't work out. It is now using a similar fix to the falling sand block problem (which captures the built contraptions and its used blocks and simply avoids creating block physics on its positions for the next 3 ticks (create uses 3 stale ticks because of some rendering issues)). Please let me know if that works!

**Comment by VOLKOUL** [comment]
Unfortunately, the issue still persists in v167b. Blocks and dynamic blocks still produce particles when moved by a create contraption (I didn't have to enable anything in the config menu, right?). I could give you the latest log, but I don't know if it would be relevant, as I have a pretty big modpack (though I don't think any of the mods conflict with this directly) Anyway, if you need me to provide anything else, please notify me and I'll try to help ya!

**Comment by haubna** [comment]
I've only tried a simple door contraption from this video: https://www.youtube.com/watch?v=YPFy-OCe020
Are you using Fabric or Forge (only tested it on Fabric so far)? Dynamic Blocks probably won't be fixable due to its complexity.

**Comment by VOLKOUL** [comment]
I am on Forge. Well, NeoForge actually, but it's basically the same for 1.20.1, the version I'm on. They are and will remain compatible for 1.20.1. Just made the same door from the video and got the same result: 

![2024-02-13_19 50 24](https://github.com/haubna/PhysicsMod/assets/97387920/2cd24af6-55c4-4cca-8a2f-0e868d597614)

**Comment by haubna** [comment]
Yup, can confirm that it doesn't work on Forge. It works on Fabric though so I should be able to pinpoint the problem.

**Comment by haubna** [comment]
Uploaded v167c, please let me know if that works for you :)

**Comment by VOLKOUL** [comment]
It works! Thank you! 
My eyes feel so much better
And yes, jlyk dynamic blocks still exhibit the bug, but as you said that's unlikely to be fixable.
I guess I can close this issue now.
