### ISSUE TITLE
Ocean/liquid physics don't affect lava [BUG]

### ISSUE THREAD

**Issue by bobthebobbert** [haubna/PhysicsMod#822]
Oceans of lava aren't affected by ocean physics. If you make a lava cauldron and destroy it, it just breaks without any liquid forming.

To reproduce, just go to a lava lake or break a lava cauldron.

Minecraft Version: 1.20.1
Physics Mod Version: physics-mod-pro-v166b-fabric-1.20.1

**Comment by haubna** [comment]
Lava liquids are not a thing in my mod
