### ISSUE TITLE
Mob death physics not working [BUG]

### ISSUE THREAD

**Issue by serioos** [haubna/PhysicsMod#823]
**Describe the bug**
The game runs, and loads, but It doesn't matter what settings I change the mob physics to, they are not working at all, and they die the default way. It used to work in the beta 166b of physics mod when I tried, but now I am in version 167 fabric physics mod and it's not working.

So I had some look in the log and found these errors. It didn't manage to inject the ragdoll animations, and then afterwards, I keep getting the index out of bounds errors every time I killed a mob:

Error logs:

https://pastebin.com/Enh1uvE4

I have these:

Minecraft 1.20.1 Fabric
physics-mod-pro-v167-fabric-1.20.1.jar
sodium-fabric-0.5.8+mc1.20.1.jar
iris-mc1.20.1-1.6.17.jar
sodium-extra-0.5.4+mc1.20.1-build.115.jar

Complete mods list:

https://pastebin.com/rJt7rcDF

**To Reproduce**
Killing mobs does nothing. They die normally and there are error being thrown in the log every time I do so.

Minecraft Version: 1.20.1 Fabric
Physics Mod Version: 167

**Comment by haubna** [comment]
Thanks for the report! Fixed with v167a.
