### ISSUE TITLE
Ragdoll Physics not working in Sodium version 0.5.8 [BUG]

### ISSUE THREAD

**Issue by anmorogz** [haubna/PhysicsMod#824]
Every other physics work in-game but the entity ones. None of them work.

Downgrading from Sodium 0.5.8 to 0.5.0 fixed the issue. 

Minecraft Version: 1.20.1 (Fabric) | Sodium 0.5.8 
Physics Mod Version: 3.0.10

**Comment by haubna** [comment]
Thanks for the report! I've uploaded 3.0.13 which fixes that issue (you will need at least Iris 1.6.17 + Sodium 0.5.8 for the new version).

**Comment by anmorogz** [comment]
Thank you so much!!
