### ISSUE TITLE
Mob Ragdolls missing [BUG]

### ISSUE THREAD

**Issue by Eridith** [haubna/PhysicsMod#826]
**Description**
Mobs will exhibit the default animation for death, rather than using the physics mod's ragdolls that are generated.

**Steps To Reproduce**
Set mob physics to any setting, kill any mob, no ragdoll is generated.

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.12
Quilt Loader Version: 0.23.1
Arch Linux: 6.7.4 (Artix)

I've conducted a test where the only mods installed are Sodium 0.5.8, PhysicsMod v166c, and qfapi 7.5.0
Below is a snippet of the logs when the mod tries to create the ragdoll.
![ErrorLogs](https://github.com/haubna/PhysicsMod/assets/128656761/96f72099-5e20-4d0a-b1fd-c31bec63126c)

**Comment by haubna** [comment]
Are you using any mods? Make sure to use Iris 1.6.17 and Sodium 0.5.8 and no prior versions of it.

**Comment by Eridith** [comment]
Apologies for the delayed response. I've used the same list of mods on Windows with no issues encountered, so the issue is isolated to the Linux operating system. All mods have been verified as up to date for the version of Minecraft being used.
Another potential note is that _Quilt 0.23.1_ is the modloader that is being used.
And if it helps, Minecraft is being run through Wayland with the package _glfw-wayland-minecraft-libdecoration_

### Full list of mods with version info
Iris 1.6.17
Sodium 0.5.8

***Additional Mods***
AmbientSounds 5.3.8
Autohud 6.3.3
BetterAnimationsCollection 8.0.0
BetterF3 7.0.2
BetterPingDisplay 1.1.1
BetterStats 3.8
BlanketClientTweaks 1.1.4
BadWitherNoCookie 3.17.0
ChatAnimation 1.0.5
ChunksFadeIn 1.0.5
Clothconfig 11.1.118
Continuity 3.0.0-beta.4
CreativeCore 2.11.16
CullLessLeaves 1.3.0
DarkLoadingScreen 1.6.14
Dashloader 5.0.0-beta.2
DripSounds 0.3.2
DynamicFPS 3.3.3
DynamicCrosshair 7.4.4
DynamicCrosshairCompat 3.7.2
EnhancedBlockEntities 0.9
EntityCulling 1.6.2
FallingLeaves 1.15.4
FastPing 1.0.1
FerriteCore 6.0.1
ForgeConfigAPIport 8.0.0
ImmediatelyFast 1.2.10
ImmersiveThunder 1.2.2
Indium 1.0.30
Krypton 0.2.3
LambdaBetterGrass 1.5.2
LambDynamicLights 2.3.2
LanguageReload 1.5.10
Lithium 0.11.2
LunadeFastAnim 1.6
Malilib 0.16.3
MemoryLeakFix 1.1.5
MidnightLib 1.4.1.1
MiniHUD 0.27.0
ModMenu 7.2.2
MoreCulling 0.22.1
MoreCullingExtra 1.1
MouseWheelie 1.13.0
NoMorePurple 1.2.1
NoTelemetry 1.8.0
NotEnoughAnimations 1.7.1
OkZoomer 5.0.1
PhysicsMod v166c
PickupNotifier 8.0.0
PresenceFootsteps 1.9.1
Puzzle 1.5.2
PuzzlesLib 8.1.16
qfapi 7.5.0 / qsl 6.1.2 / fapi 0.91.0 (The most confusing version info I have ever seen)
ReesesSodiumOptions 1.7.2
ServerPingFixer 1.0.4
SharedResources 1.7.0
SkinLayers3D 1.6.2
SmoothSwapping 0.9.3.1
SodiumExtra 0.5.4
SoundPhysicsRemastered 1.3.1
Starlight 1.1.2
StatusEffectBars 1.0.3
TinyItemAnimations 1.1
VectorOrientation 1.0.1a
WorldEdit 7.2.15
YetAnotherConfigLib 3.2.1

**Comment by Eridith** [comment]
I've updated the post to include a sample of the errors received when the mod is generating the ragdoll.
Hope it helps, and thanks for all you've done to bring such an amazing mod to this game!

**Comment by haubna** [comment]
Oh my bad, I didn't see you were using an older version. Please update to v167. This adds the compatibility for the latest Sodium and Iris versions.
