### ISSUE TITLE
The items spun around on the ground.

### ISSUE THREAD

**Issue by oprifine** [haubna/PhysicsMod#827]
So, I am using compatible shaders (Aurora's Shaders for Ocean Physics) with the Physics mod (167d on 1.20.4) and when I hit a cow and a pig, the drops were spinning, and I could not collect the items. I am not sure how this came up, but one of the mods i'm using might be an issue:
cloth-config-api
collective
comforts
continuity
cristellib
william wythers expanded ecosphere
fabric api & kotlin
iris
lambdynamiclights
lithium
physics mod (pro 167d fabric 1.20.4)
plasmovoice
realcamera
realisticbees
realistic-item-drops
realistic-rowing
realisticsleep
remove-terralith-intro-message
sodium
soundphysicsremastered
starlight
tectonic
terratonic
terralith
yet-another-config-lib
zoomify

Down there is a video example of my issue.

[2024-02-18-11-11-30.zip](https://github.com/haubna/PhysicsMod/files/14323341/2024-02-18-11-11-30.zip)

I would like to know if any mods are causing an issue.

Sincerely, oprifine

**Comment by haubna** [comment]
Physics Mod is only visual and shouldn't change any gameplay. It changes the item animations so that they spin and then lay flat on the ground.

**Comment by oprifine** [comment]
Okay, I will try to find out!
