### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by Xtrendence** [haubna/PhysicsMod#828]
**Mods**

fabric-api-0.95.4+1.20.4
sodium-fabric-0.5.8+mc1.20.4
iris-mc1.20.4-1.6.17 (crashes with or without shaders)
indium-1.0.30+mc1.20.4 (crashes with or without it)
physics-mod-pro-v167d-fabric-1.20.4

**Settings**

- Any kill effect (ragdoll, fracture etc.) other than vanilla. **Blocky is better, and only crashes at around 15+ mobs.**
- Any ragdoll limit greater than 0 (even crashes on 1).
- No shaders (I use them in the video, but it also happens with no shaders and no resource packs enabled except the one that comes with the Physics Mod).
- 8GBs of RAM allocated to Minecraft.
- RTX 4080, driver 551.52 (released 13/02/2024), also happened with previous version.

**Describe the bug**

Enemies dying due to fall damage crash the game when turning into ragdolls. Sometimes happens with only 1 mob, sometimes a few. Does not happen due to too many mobs dying at the same time. I tried placing hundreds on magma blocks and it didn't crash the game when they all died. Seems to specifically be fall-related somehow.

**To Reproduce**

Build a tower tall enough for mobs to die from fall damage, then spawn mobs (I tested humanoid mobs, but should work with any that die from fall damage, usually mine crashes at around 3-5 mobs, sometimes even 1). I tested dropping them in a spread out way, and that didn't seem to cause a crash, so might be only when mobs die from fall damage right next to or on top of an existing ragdoll?

**Video**

Crash happens at the 0:19 mark when things get laggy. Seems to spike RAM usage too.

Video: https://www.youtube.com/watch?v=UL2mVkxydu4

Minecraft Version: 1.20.4
Physics Mod Version: physics-mod-pro-v167d-fabric-1.20.4

**Crash Log**

The last few stack traces before it crashes, slightly different, the first one will probably be the most useful, specifically `java.lang.IndexOutOfBoundsException: Index (8) is greater than or equal to list size (8)`.

https://pastebin.com/gMCCeVZj

https://pastebin.com/1TFamKhb

https://pastebin.com/MSXJayam

**Comment by haubna** [comment]
Do you have an actual crash log for me? The messages in the log are simply for failed creations of a ragdoll as an info. That doesn't cause a crash. As you said there seems to be something else going on causing the RAM spike + the crash. Probably for some odd reason a lot of physics objects are getting created? Could you by any chance enable the physics debug keybind in the keybind settings and then open it and make a video of it when it happens?

**Comment by haubna** [comment]
Wait I just noticed something in your logs. Please disable GPU liquids. As stated in that description it will make everything else very unstable.
Something internally that causes it to malfunction. It might get fixed when I upgrade to the latest PhysX library.
eINTERNAL_ERROR: PhysX Internal CUDA error. Simulation can not continue!

**Comment by Xtrendence** [comment]
You absolute legend, turning off GPU liquids did in fact fix it! I didn't think it'd be related as I was dropping mobs on dry land, but if, as you say, having it on affects and makes other things unstable, then that makes sense. Thank you again! Love the mod and really didn't want to give it up, now I don't have to.
