### ISSUE TITLE
[Request] configurable blocks collapsing

### ISSUE THREAD

**Issue by SylisMC** [haubna/PhysicsMod#83]
### It would be really nice to be able to configure what blocks do and don't collapse, 

I really love the feature but it's not really playable in survival. 

- You can end up losing half your house if you try to punch a hole in the 2nd floor just to add a ladder access

- When mining, everything comes crashing down on your head if you mine skywards. regardless of if you have built some sort of logical support system.

A whitelist/blacklist/global setting for blocks would be a supreme addition, the same way you have per block settings for break physics!, _personally id probably only leave collapse physics on non-natural non-stone matirials, like leaves, dirt, sand, etc_

As always. thanks for all your hard work providing this FREE mod for the community, people like you are the reason minecraft is still going strong 10 years later

**Comment by haubna** [comment]
I will definitely rework the collapse feature once I am satisfied with the client physics. I am thinking of realistic physics where you can build support structures for caves/houses so they don't collapse!

**Comment by SylisMC** [comment]
that would be really awesome... and if it's something you are already thinking about, I'm sure you will do a really nice job of it when you get the time. I'm really looking forward to seeing what you come up with!
