### ISSUE TITLE
Physics mod pro crashing with Valkyrien Skies [BUG]

### ISSUE THREAD

**Issue by Barerock** [haubna/PhysicsMod#830]
**Describe the bug**
Loading world produces a crash

**To Reproduce**
Install both mods, crash when loading world

Minecraft Version: 1.20.1
Physics Mod Version: pro-v167d-forge-1.20.1

[crash-2024-02-23_23.49.58-client.txt](https://github.com/haubna/PhysicsMod/files/14391791/crash-2024-02-23_23.49.58-client.txt)
Not sure if relevant, I am unfamiliar with how physics mod works, but VS2 has issues with sodium and the log clearly references sodium as the culprit for the crash, though the source of said crash is noted as both VS2 and PMP.

**Comment by haubna** [comment]
Please make sure to update to the latest Oculus + Embeddium versions (Embeddium is required for it to work with Oculus).

**Comment by Barerock** [comment]
Embeddium is not compatible with Valkyrien Skies. Gargantuan L that this and that can't go together due to the length of update time.

**Comment by Barerock** [comment]
And optifine is a hot pile of garbage.

**Comment by haubna** [comment]
You could technically try an older version of Physics Mod Pro. I don't remember which version upgraded to the latest Oculus though (should be part of the patreon posts).
