### ISSUE TITLE
Invisble snow layer [BUG]

### ISSUE THREAD

**Issue by Cypherus24** [haubna/PhysicsMod#831]
Snow layer is invisble after walking thru' it.
I tried tweaking snow physics settings still the bug remains.

Screenshot:
![2024-02-24_11 31 46](https://github.com/haubna/PhysicsMod/assets/161108626/732c6452-1b9b-403c-9478-5470d53d998d)

Minecraft Version: 1.20.4
Physics Mod Version: v165-fabric-1.20.4
Other Mods in use: sodium 0.5.8 & iris 1.6.17

**Comment by haubna** [comment]
Update to v167.
