### ISSUE TITLE
Weird behavior of trapdoors with dynamic blocks physics [BUG]

### ISSUE THREAD

**Issue by elAltrex** [haubna/PhysicsMod#833]
**Describe the bug**
The trapdoors when put together like in villages/dungeons from mods act erratically.

**To Reproduce**
Go to a village with trapdoors put together, in the video example they're used as part of a street light (?

**Video**
https://github.com/haubna/PhysicsMod/assets/156161230/f07b7f0e-6406-4dd9-9a7b-dc1314c34dc2

Minecraft Version: 1.20.1
Physics Mod Version: physics-mod-pro-v167-forge-1.20.1

https://github.com/haubna/PhysicsMod/assets/156161230/f07b7f0e-6406-4dd9-9a7b-dc1314c34dc2

**Comment by haubna** [comment]
You can disable collision for trapdoors in the dynamic block settings under customize.

**Comment by Macintosh-Fan** [comment]
But, will the bug be fixed, or is it meant to do that?

**Comment by haubna** [comment]
It is fixed by disabling collision. Fences are 1.5 blocks tall, that's the collision Mojang decided to use (try standing on top of one, you will float). Nothing I can change about that.

**Comment by haubna** [comment]
Fixed in 26.1 Snapshot 1 (will most likely be ported to 1.21.11 too).
