### ISSUE TITLE
Crash on ATM Gravitas2 [BUG]

### ISSUE THREAD

**Issue by ArtkoXT** [haubna/PhysicsMod#835]
**Describe the bug**
Game crashes on startup when added to ATM Gravitas2

**To Reproduce**
Download ATM Gravitas2
Add physics mod to the mod folder
Launch the game

[crash-2024-03-01_16.05.32-client.txt](https://github.com/haubna/PhysicsMod/files/14462801/crash-2024-03-01_16.05.32-client.txt)

Minecraft Version: 1.20.1
Physics Mod Version: physics-mod-pro-v167d-forge-1.20.1

**Comment by haubna** [comment]
Please update to the latest Oculus + Embeddium versions.
