### ISSUE TITLE
collapse in server no disble [BUG]

### ISSUE THREAD

**Issue by mizancraft** [haubna/PhysicsMod#836]
**Describe the bug**
I can't disable the colapse physic in my homemade server, I put false in the file "config\physicsmod\physisics_server_config.json" I put a screenshot down there.

**To Reproduce**
I install the mod with the version "v167d" for forge 1.20.1. and put in the file "false" in the line that says "collapse:"

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/126361722/6dc95c84-c7b9-4ee1-a435-735839ec9491)
(some stuff are in spanish, becasue I'm spanish, but I know a lot of inglish)

Minecraft Version: 1.20.1
Physics Mod Version: V167d
forge version: 47.2.20

**Comment by haubna** [comment]
If you don't want the collapse feature, simply remove the mod from the server. It is the only feature it adds on the server side.

**Comment by mizancraft** [comment]
oh ok, thanks
