### ISSUE TITLE
liquid physics dont work for me

### ISSUE THREAD

**Issue by omgbruhhhhhhhhhhhhhhhhhhhhhhh** [haubna/PhysicsMod#837]
**Describe the bug**
whenever i try liquid help it says the command does not exist when i try to me water by breaking melons and enchanting tables it does not work can anybody help?

![image](https://github.com/haubna/PhysicsMod/assets/161897056/f2edefaf-e39a-4386-8321-d9af64a97d6d)
![image](https://github.com/haubna/PhysicsMod/assets/161897056/2069d674-b197-44a9-a534-61353f41a3a5)

Minecraft Version: 1.20.4
Physics Mod Version: v167

**Comment by omgbruhhhhhhhhhhhhhhhhhhhhhhh** [comment]
btw im on fabric

**Comment by haubna** [comment]
Are they enabled in the settings (can you send a screenshot of the settings)? The command is `/liquids help` not `/liquid help`

**Comment by omgbruhhhhhhhhhhhhhhhhhhhhhhh** [comment]
![image](https://github.com/haubna/PhysicsMod/assets/161897056/799120c9-89a7-4300-ab43-4e39d311a4ee)

**Comment by haubna** [comment]
Where did you download the mod? Why is there a PhysX > CPU text on the top left? You will need to type `/liquids sphere ~ ~5 ~ 3` to spawn liquids above your head.
