### ISSUE TITLE
crash when shaders and oculus [BUG]

### ISSUE THREAD

**Issue by mizancraft** [haubna/PhysicsMod#838]
**Describe the bug**
my game crashes when I put shaders with oculus, but without shaders it do well but with no. 

**To Reproduce**
1. enter minecraft 
2. enter server(or single player)
3. activate shaders
4.crash

**Screenshots**
I will put my outputs here
[latest.log](https://github.com/haubna/PhysicsMod/files/14469707/latest.log)
[crash-2024-03-02_15.18.17-client.txt](https://github.com/haubna/PhysicsMod/files/14469709/crash-2024-03-02_15.18.17-client.txt)

Minecraft Version: 1.20.1
Physics Mod Version: v167d

PD: I have more mods a part of physics mod. every mod  works with shaders without physics mod

**Comment by haubna** [comment]
Please update to the most recent Oculus and Embeddium versions. Yours are outdated.

**Comment by mizancraft** [comment]
ok thanks

**Comment by mizancraft** [comment]
now it crashes but without anything, it says that it can't loas resorucepacks and then I try enter my server and it crash, the launcher says "Error:  java.lang.nosouchfiererror:  quads"

**Comment by haubna** [comment]
Include the entire crash log

**Comment by mizancraft** [comment]
[latest.log](https://github.com/haubna/PhysicsMod/files/14469908/latest.log)

**Comment by mizancraft** [comment]
[crash-2024-03-02_15.59.56-client.txt](https://github.com/haubna/PhysicsMod/files/14470000/crash-2024-03-02_15.59.56-client.txt)

**Comment by haubna** [comment]
Seems like you need to update vivecraft as well.

**Comment by mizancraft** [comment]
I uptated vivecraft and it don't work, and I removed the entire folder and reinstall every mod. and it don't work

**Comment by haubna** [comment]
You probably have incompatible mods. I am not a modpack creator. You will need to check the mods individually.

**Comment by mizancraft** [comment]
ok thanks for all, goodbye
