### ISSUE TITLE
[Idea] Push weight for ragdolls

### ISSUE THREAD

**Issue by SylisMC** [haubna/PhysicsMod#84]
With Physics mods, you can kill a large creature. like a ghast, or the ender dragon, and then kick its ragdoll corpse across the world like a balloon, it kinda makes sense when the creature is set to fracture and you toss the tiny little chunks around, but even then, when you kill a ghast, the chunks are still 10x your size, they are absolutely massive.

_I could kinda understand this if steve was never skipped leg day, but to be fair, he spends most of his time working on his arms, (lol humor) but in all seriousness, as hilarious as it is playing soccer with the corpse of that chicken that wouldn't stop clucking next to your house while your rummaging through your 14 chests looking for those diamonds that your friends probably stole but your not sure because you have a hoarding problem and cant not pick up every single thing you come across because you have a deep-rooted fear of not having enough due to growing up poor_ Okay that happened

But yes, a weight factor for ragdolls, fractured particles, and blocks would be a really nice addition to make this mod feel a little more immersive, I love playing with this mod, but it often kinda feels like gravity only exists for living creatures, _I guess that chickens soul weighed more on its body than it did on my conscience_ haha

As always. thanks for all your hard work providing this FREE mod for the community, people like you are the reason minecraft is still going strong 10 years later

**Comment by haubna** [comment]
This won't be implemented since it is a client side mod. The player doesn't have physics (where he walks slower when there is a big body in front of him). That would mean synchronizing physics across client and server which would siginificantly slow down big servers. So sorry no.

**Comment by SylisMC** [comment]
but If its client-side, are the ragdolls not register on the client's side? when a player walks over them they yeet them across the map, thats all still only client-side, so wouldn't adding gravity to the ragdolls also only be clientside?

**Comment by haubna** [comment]
The yeeting happens due to collision solving. Has nothing to do with the weight of the object. Nothing of priority for me because it is more fun this way. If I find an easy way to make the ragdolls "heavier" (their mass already depends on their volume), I will do so.

**Comment by haubna** [comment]
The yeeting should be reduced in version 2.5.4.
