### ISSUE TITLE
Game crashes when I try to open the config menu (1.20.4) [BUG]

### ISSUE THREAD

**Issue by Datsolodude** [haubna/PhysicsMod#840]
In 1.20.4, whenever I try to, well, open the config menu for this mod in both forge and fabric, the game crashes. I have attached some screenshots of the issue below.

https://github.com/haubna/PhysicsMod/assets/162055483/d59af30a-828b-44a7-a520-79f481913e8c

![image](https://github.com/haubna/PhysicsMod/assets/162055483/72cbecfb-b939-4ed4-a065-e78fafa77354)

**Comment by haubna** [comment]
Please include the entire crash log (I am assuming you are not using the 1.20.4 version of the mod)
