### ISSUE TITLE
game crashed when i open a world [BUG]

### ISSUE THREAD

**Issue by justwannatokyo** [haubna/PhysicsMod#841]
**Describe the bug**
Minecraft crashes when I enter a world. When the mod is disabled, everything is fine

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.9
https://pastebin.com/Tgvyexmd

**Comment by haubna** [comment]
Update to the latest version of the physics mod
