### ISSUE TITLE
1.19.2 Physics Mod crash when mining Large Water Wheel in Create Mod [BUG]

### ISSUE THREAD

**Issue by mikkolukas** [haubna/PhysicsMod#842]
### Describe the bug
Minecraft 1.19.2 with Create and Physics Mod installed. 
When I mine a Large Water Wheel in Create Mod, the game crashes with a `java.lang.OutOfMemoryError: Out of stack space`, caused by the Physics Mod.

### To Reproduce
1. Make a new instance of Minecraft 1.19.2 with Forge 43.3.8
2. Add Create Mod 0.5.1.f [release] (create-1.19.2-0.5.1.f.jar)
3. Add Physics Mod 2.12.5 [release] (physics-mod-2.12.5-mc-1.19.2-forge)
4. Start the game
5. Create a new world
6. Place Large Water Wheel
7. Destroy Large Water Wheel

### Game log
[https://mclo.gs/Pr01Wpw](https://mclo.gs/Pr01Wpw)

Minecraft Version: 1.19.2
Physics Mod Version: 2.12.5

### Observations
The game does not crash when trying the same in Minecraft 1.20.1, Forge 47.2.20, Create 0.5.1.f, Physics 3.0.13

The bug is triggered regardless of the orientation of the Large Water Wheel.

The bug is not triggered by the small Water Wheel.

I don't know if other blocks triggers the bug.

### Screenshots
![2024-03-06_13 10 35](https://github.com/haubna/PhysicsMod/assets/1522239/2bd2da1a-58a7-4175-b3f8-5e46b20ab99c)
![2024-03-06_13 10 49](https://github.com/haubna/PhysicsMod/assets/1522239/69445d8e-78de-433b-bc9b-3e676592689f)
![2024-03-06_13 11 07](https://github.com/haubna/PhysicsMod/assets/1522239/073bfa60-15fa-4b4b-977f-ffd81c1cf679)
![Screenshot 2024-03-06 131124](https://github.com/haubna/PhysicsMod/assets/1522239/8c930af4-7696-4431-9f62-387da3c32d51)

**Comment by haubna** [comment]
This is already fixed with 1.20.1+, thanks for the report though!

**Comment by mikkolukas** [comment]
@haubna Yeah, I know it is fixed in 1.20.1 - but it is still broke in 1.19.2, which is still in widespread use 🙂
