### ISSUE TITLE
config file not working for block physics and ragdolls (Forge 1.20.1, newest version forge and mod) [BUG]

### ISSUE THREAD

**Issue by EfficientStinkbug** [haubna/PhysicsMod#844]
I only want to use the ocean physics.

There are many options in the configs and I turned everything to false that doesn't have anything to do with oceans.
But the block breaking physics and ragdolls are still working, even though they shouldn't. Or is there no option for them?

Minecraft Version: <1.20.1 Forge>
Physics Mod Version: <167d>
![grafik](https://github.com/haubna/PhysicsMod/assets/162632344/e8e26d0f-d59a-4aa8-806d-5e2e6ed793bd)

**Comment by EfficientStinkbug** [comment]
{
  "maxPhysicsObjects": 10000,
  "particleLifetimeVines": 4.0,
  "particleLifetimeItems": 3.0,
  "particleLifetimeParticles": 0.1,
  "particleLifetimeLiquids": 6.0,
  "particleLifetimeSmoke": 60.0,
  "particleDespawnTimeSmoke": 3.0,
  "particleLifetimeVarianceVines": 3.0,
  "particleLifetimeVarianceItems": 3.0,
  "particleLifetimeVarianceParticles": 3.0,
  "particleLifetimeVarianceLiquids": 3.0,
  "particleLifetimeVarianceSmoke": 15.0,
  "particleDespawnTimeVarianceSmoke": 12.0,
  "cpuThreads": 4,
  "itemPhysics": false,
  "minecraftBlockBreakParticles": false,
  "vinePhysics": false,
  "capePhysics": false,
  "fishingRodPhysics": false,
  "leashPhysics": false,
  "bannerPhysics": false,
  "clothSmoothShading": false,
  "showUpdateNotifications": false,
  "clothThreads": 2,
  "leashLength": 3.0,
  "fishingLineLength": 12.0,
  "pvpServerCompatibility": false,
  "snowballModel": 0,
  "snowballImpact": 1,
  "snowballShade": false,
  "enderpearlModel": 0,
  "enderpearlImpact": 1,
  "enderpearlShade": false,
  "eggModel": 0,
  "eggImpact": 1,
  "eggShade": false,
  "crackPhysicsParticles": false,
  "liquidPhysics": false,
  "liquidSourceDistance": 6.0,
  "liquidThreads": 2,
  "bannerPhysicsRange": 48.0,
  "soundVolume": 1.0,
  "blockPhysicsRange": 96.0,
  "vineRange": 32.0,
  "waterDensity": 3,
  "snowPhysics": false,
  "snowTracks": true,
  "snowTrackEntities": 6,
  "snowTrackDistance": 48.0,
  "snowThickness": 0.0,
  "grassSnowy": false,
  "snowType": 0,
  "snowSmoothShading": false,
  "snowChunkSize": 0,
  "blockSettings": {
    "Physics Type": 0,
    "Lifetime": 4.0,
    "Lifetime Variance": 3.0,
    "Scale": 1.0,
    "Animation": -1
  },
  "mobSettings": {
    "Physics Type": 0,
    "Lifetime": 4.0,
    "Lifetime Variance": 3.0,
    "Animation": -1
  },
  "sprintingPhysicsParticles": false,
  "eatingPhysicsParticles": false,
  "serverBlockPhysicsParticles": false,
  "smokePhysics": false,
  "smokeParticleLimit": 6000,
  "verificationCode": "",
  "smokeColorRed": 0.56,
  "smokeColorGreen": 0.56,
  "smokeColorBlue": 0.56,
  "smokeDenseColorRed": 0.364,
  "smokeDenseColorGreen": 0.364,
  "smokeDenseColorBlue": 0.364,
  "smokeDensity": 0.9,
  "smokePhysicsRange": 100.0,
  "smokeBlaze": 0.05,
  "smokeCampfire": 0.3,
  "smokeFire": 0.3,
  "smokeOther": 1.0,
  "smokeShadowTransformer": 0,
  "maxLoadedDynamicBlocks": 20,
  "windPhysics": true,
  "weatherParticles": true,
  "weatherClearStrength": 0.1,
  "weatherRainStrength": 1.0,
  "weatherThunderStrength": 1.4,
  "windVolume": 1.0,
  "weatherRainParticleAmount": 5,
  "weatherThunderParticleAmount": 2,
  "oceanPhysics": true,
  "oceanAdjustHitbox": false,
  "oceanDetail": 1.0,
  "oceanWaveHeightMultiplier": 1.0,
  "oceanBlockRange": 32,
  "oceanWeatherClear": 0.0,
  "oceanWeatherRain": 0.75,
  "oceanWeatherThunder": 0.25,
  "oceanBaseSpeed": 1.0,
  "oceanHorizontalWaveScale": 1.0,
  "oceanParticles": true,
  "oceanParticleAlpha": 0.5,
  "oceanStickyEntities": false,
  "oceanSplashVolumeNew": 1.0,
  "snowLOD": 1.0,
  "particleRainOpacity": 1.0,
  "particleSnowOpacity": 1.0,
  "particleDustOpacity": 1.0,
  "itemRotationSpeed": 1.0,
  "jointBreakForce": 1.0,
  "jointBlood": 1.0,
  "mobRagdollLimit": 16,
  "clothEntityRange": 48.0,
  "clothForceArmor": false,
  "oceanPuddles": false,
  "oceanFoamAmount": 0.8,
  "oceanFoamOpacity": 0.5,
  "cudaLiquids": false,
  "cudaLiquidsParticleSize": 0.1,
  "cudaLiquidsBlurPasses": 3,
  "playbackSpeed": 1.0,
  "oceanRainPuddleAmount": 0.5,
  "puddleResolutionQuality": 2048,
  "itemBreakPhysics": false,
  "customizedGravities": [
    "minecraft:the_nether",
    0.0,
    -9.81,
    0.0,
    "minecraft:overworld",
    0.0,
    -9.81,
    0.0,
    "minecraft:the_end",
    0.0,
    -9.81,
    0.0,
    "graveyard:past",
    0.0,
    -9.81,
    0.0,
    "aether:the_aether",
    0.0,
    -9.81,
    0.0,
    "twilightforest:twilight_forest",
    0.0,
    -9.81,
    0.0,
    "undergarden:undergarden",
    0.0,
    -9.81,
    0.0
  ],
  "customizedBuoyancies": [
    "minecraft:the_nether",
    0.0,
    2.0,
    0.0,
    "minecraft:overworld",
    0.0,
    2.0,
    0.0,
    "minecraft:the_end",
    0.0,
    2.0,
    0.0,
    "graveyard:past",
    0.0,
    2.0,
    0.0,
    "aether:the_aether",
    0.0,
    2.0,
    0.0,
    "twilightforest:twilight_forest",
    0.0,
    2.0,
    0.0,
    "undergarden:undergarden",
    0.0,
    2.0,
    0.0
  ]
}

**Comment by haubna** [comment]
Please only use the ingame settings (it should make it easier to disable everything else their).
