### ISSUE TITLE
The smoke is transparent [BUG]

### ISSUE THREAD

**Issue by kromos18** [haubna/PhysicsMod#845]
**Describe the bug**
 
The smoke doesn't come out as it should, it comes out transparent, another bug that I don't know if it's a bug is in the snow because when you put a block 
 or a layer of snow turns the block underneath into snow.
**To Reproduce**

https://github.com/haubna/PhysicsMod/assets/162636407/8cbbf672-77f2-4853-9f85-905506bb2299

https://github.com/haubna/PhysicsMod/assets/162636407/1a8e08cb-f70f-4bc5-8a45-d9238ae832f9

Minecraft Version: 1.19.2

Physics Mod Version:  physics-mod-pro-v153-forge-1.19.2

**Comment by haubna** [comment]
The first one can happen with some shaders that aren't supported and the second one is a feature which can be disabled in the snow settings.
