### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by irondragon12** [haubna/PhysicsMod#846]
**Describe the bug**
When having shaders enabled the water becomes weird when looking downwards. the reflections go crazy.

**Screenshots**
![2024-03-08_15 35 23](https://github.com/haubna/PhysicsMod/assets/30564310/119dfc7a-c0b9-4268-bbd6-eb6047e255c9)
![2024-03-08_15 35 25](https://github.com/haubna/PhysicsMod/assets/30564310/ddaf2172-21ea-44d4-a260-d88bde08ce9c)

Minecraft Version: forge 1.19.2
Physics Mod Version: physics-mod-pro-v153-forge-1.19.2

**Comment by devismurder** [comment]
mine looks like that when i get out the water. the only thing for me that can fix it is getting back in the water, or throwing something into the water. it's really annoying. yeah and when i look up it's okay but when i look down it's a mess.

**Comment by haubna** [comment]
Please consider using newer versions of the mod which address this issue. Older shaderpacks might fix this too.
