### ISSUE TITLE
The world refuses to boot up. Possible snow rendering error with starlight [BUG]

### ISSUE THREAD

**Issue by Kukidoo** [haubna/PhysicsMod#848]
**Describe the bug**
I was walking around the world, and as soon as snow appeared in the frame, the world crashed and no longer launched with Starlight and Physics paired. After removing one of the mods, the world starts up. Here is the crash report after the last launch
[crash-2024-03-09_21.36.41-client.txt](https://github.com/haubna/PhysicsMod/files/14547669/crash-2024-03-09_21.36.41-client.txt)

**To Reproduce**
1. install my modpack (?), or starlight and physics
2. Install my mod settings for physics (?)
[physics_cloth_config.json](https://github.com/haubna/PhysicsMod/files/14547683/physics_cloth_config.json)
[physics_mobs_client_config.json](https://github.com/haubna/PhysicsMod/files/14547684/physics_mobs_client_config.json)
[physics_server_config.json](https://github.com/haubna/PhysicsMod/files/14547685/physics_server_config.json)
[physics_vines_client_config.json](https://github.com/haubna/PhysicsMod/files/14547686/physics_vines_client_config.json)
[physics_animations_client_config.json](https://github.com/haubna/PhysicsMod/files/14547687/physics_animations_client_config.json)
[physics_blocks_client_config.json](https://github.com/haubna/PhysicsMod/files/14547688/physics_blocks_client_config.json)
[physics_client_config.json](https://github.com/haubna/PhysicsMod/files/14547689/physics_client_config.json)

3. find a location with snow in the world
4. the world collapses and you cannot re-enter, game crashes too

**Mods installed**
- additionalstructures 4.2.1
	- advanced_runtime_resource_pack 0.8.1
	- advancementinfo 1.20-fabric0.83.0-1.4
	- ambientsounds 5.3.9
	- animatica 0.6+1.20
	- antighost 1.20-fabric0.83.0-1.1.5
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- artifacts 9.3.0
	- auto_third_person 2.1
	- badpackets 0.4.3
	- beaconoverhaul 1.8.4+1.20
	- betterf3 7.0.2
	- bettermounthud 1.2.2
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.9.0
	- bookshelf 20.1.9
	- borderlessmining 1.1.8+1.20.1
	- bundle_jumble 1.0.2-mc1.20.1
	- bushierflowers 0.0.3-1.20.1
	- c2me 0.2.0+alpha.11.5
	- cameraoverhaul 1.4.0-fabric-universal
	- capes 1.5.2+1.20
	- carryon 2.1.2.7
	- cavedust 1.4.1
	- chat_heads 0.10.31
	- chatanimation 1.0.5
	- citresewn 1.1.3+1.20
	- cloth-config 11.1.118
	- clumps 12.0.0.3
	- collisionfix 1.0.1
	- companion 5.1.0
	- completeconfig 2.5.0
	- continuity 3.0.0-beta.4+1.20.1
	- controlling 12.0.2
	- create 0.5.1-f-build.1335+mc1.20.1
	- creativecore 2.11.24
	- damagevignette 2.0.2
	- debugify 1.20.1+2.0
	- ding 1.4.1
	- disable_custom_worlds_advice 4.1
	- dynamiccrosshair 7.4.4+1.20
	- dynamiclights 1.7.1+mod
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- eatinganimationid 1.20+1.9.5
	- elytra_physics 1.3-1.20
	- emojitype 2.2.3+1.20.4
	- enhancedblockentities 0.9+1.20
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	- entityculling 1.6.2-mc1.20.1
	- essential-container 1.0.0
	- expandeddelight 0.3.0.2
	- fabric-api 0.92.0+1.20.1
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	- fabricloader 0.15.7
	- fabricskyboxes 0.7.3+mc1.20.1
	- fabrishot 1.10.1
	- fallingleaves 1.15.4
	- farmersdelight 1.20.1-1.4.3
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.1
	- fluidvoidfading 1.1.3
	- forgeconfigapiport 8.0.0
	- fpsreducer 1.20-2.5
	- fsb-interop 1.3.6+mc1.20.1-build.50
	- geckolib 4.4.2
	- gravestones v1.15
	- gravestonesfix 1.0.0
	- handcrafted 3.0.6
	- harvestwithease 8.0.1.0
	- holdthatchunk 2.0.1
	- hybrid-aquatic 1.2.2
	- iceberg 1.1.18
	- immediatelyfast 1.2.10+1.20.4
	- immersive_weathering 1.20.1-2.0.1
	- indium 1.0.30+mc1.20.4
	- inventorysorter 1.9.0-1.20
	- isxander-main-menu-credits 1.1.2
	- itemphysic 1.7.0
	- java 17
	- kiwi 11.5.5
	- krypton 0.2.3
	- languagereload 1.5.10+1.20.1
	- lazydfu 0.1.3
	- leavesbegone 8.0.0
	- legendarytooltips 1.4.4
	- lilac 1.0.0-beta.3
	- lithium 0.11.2
	- make_bubbles_pop 0.2.0-fabric
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- mixin-conflict-helper 1.2.0
	- mixintrace 1.1.1+1.17
	- mobplaques 8.0.1
	- modelfix 1.14
	- modernfix 5.14.0+mc1.20.1
	- modmenu 7.2.2
	- moonlight 1.20-2.11.0
	- morechathistory 1.3.0
	- moreculling 1.20.4-0.22.1
	- moremobvariants 1.2.2
	- mousetweaks 2.25
	- naturalist 4.0.3
	- nimble 5.0.1
	- no-resource-pack-warnings 1.3.0
	- no-telemetry 1.8.0
	- nochatreports 1.20.1-v2.2.2
	- noisium 1.0.2+mc1.20.x
	- notenoughanimations 1.7.1
	- nvidium 0.2.6-beta
	- nyfsspiders 2.1.1
	- optigui 2.1.7
	- oscimate_soulflame 1.1.0
	- overflowingbars 8.0.0
	- physicsmod 3.0.13
	- pickupnotifier 8.0.0
	- presencefootsteps 1.9.0
	- prism 1.0.5
	- puzzle 1.5.2+1.20
	- puzzleslib 8.1.17
	- qdaa 1.1.2
	- realisticsleep 1.10.2+mc1.20-1.20.1
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- resourcefullib 2.1.23
	- roughlyenoughitems 12.0.684
	- rrls 3.2.0-1.20.1-fabric
	- searchables 1.0.1
	- serverpingerfixer 1.0.4
	- shouldersurfing 2.5
	- skinlayers3d 1.6.2
	- slight-gui-modifications 2.6.1
	- smoothmenu 1.1.0
	- smoothscroll 1.8.1
	- smoothswapping 0.9.3.1
	- snowrealmagic 10.3.1
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	- sound_physics_remastered 1.20.1-1.1.2
	- stack-to-nearby-chests 0.5.4
	- structory 1.3.2
	- tia 1.20-1.1
	- tramplenomore 13.0.3
	- trinkets 3.7.1
	- usefulspyglass 0.5.1
	- videotape 1.2.1
	- visuality 0.7.1+1.20
	- visualworkbench 8.0.0
	- wakes 0.2.0
	- weaponmaster 3.0.5
	- xaerominimap 23.9.7
	- xaeroworldmap 1.37.8
	- yet_another_config_lib_v3 3.2.2+1.20
	- yosbr 0.1.2
	- zoomify 2.11.2

Minecraft Version: 1.20.1, fabric loader 0.15.7
Physics Mod Version: physics-mod-pro-v167d-fabric-1.20.1

**Comment by dionisokan** [comment]
Experiencing similar crash here, the game crashes when I load into a server with Physics 3.0.13 (physics-mod-3.0.13-mc-1.20.1-fabric.jar), Create Sodium Fix v0.5.1.d, Sodium 0.5.8 and Starlight 1.1.2 on Minecraft 1.20.1 @ Oracle Java 21.0.2

- Mod list:  [modlist.txt](https://github.com/haubna/PhysicsMod/files/14551098/modlist.txt)

- Latest crash log: [crash-2024-03-11_00.51.40-client.txt](https://github.com/haubna/PhysicsMod/files/14551103/crash-2024-03-11_00.51.40-client.txt)

- Physics mod configs: 
[physics_vines_client_config.json](https://github.com/haubna/PhysicsMod/files/14551108/physics_vines_client_config.json)
[physics_server_config.json](https://github.com/haubna/PhysicsMod/files/14551109/physics_server_config.json)
[physics_mobs_client_config.json](https://github.com/haubna/PhysicsMod/files/14551110/physics_mobs_client_config.json)
[physics_cloth_config.json](https://github.com/haubna/PhysicsMod/files/14551111/physics_cloth_config.json)
[physics_client_config.json](https://github.com/haubna/PhysicsMod/files/14551112/physics_client_config.json)
[physics_blocks_client_config.json](https://github.com/haubna/PhysicsMod/files/14551113/physics_blocks_client_config.json)
[physics_animations_client_config.json](https://github.com/haubna/PhysicsMod/files/14551114/physics_animations_client_config.json)

**Comment by haubna** [comment]
Thanks for the report! This will be fixed with Minecraft 1.20.5 and onward. For now you can either remove Starlight or disable snow physics to fix the issue.

**Comment by haubna** [comment]
This is fixed with 1.20.5
