### ISSUE TITLE
color inconsistency with distant horizons

### ISSUE THREAD

**Issue by eternalbluepetya** [haubna/PhysicsMod#849]
**Describe the bug**
i doubt this is truly a bug and instead a conflict between the two mods i cant understand, my best guess being one mod thinks the water is swamp water while the other doesnt. the physics mod displays the water as green while distant horizons and regular water displays it as blue

**To Reproduce**
load a world with physics mod pro, distant horizons, and william wythers' expanded ecosphere, some biomes will have this kind of water

**Screenshots**
![here](https://github.com/haubna/PhysicsMod/assets/75097370/44d8d02a-094b-4789-8fa7-4258afc57909)

Minecraft Version: 1.18.2
Physics Mod Version: pro v167 (jar says v153?)

**Comment by haubna** [comment]
I suppose this is the color that is getting used by distant horizons for water. I am not too familiar with that mod though.
