### ISSUE TITLE
[FEATURE] Dynamic Blocks Breaking Animations

### ISSUE THREAD

**Issue by nco2k** [haubna/PhysicsMod#851]
i like the animations for dynamic blocks when interacting with them, but i hate the animations for dynamic blocks when breaking them. it would be cool if you could provide an option to disable dynamic blocks breaking animations and instead use the regular blocks breaking animations.

**Comment by haubna** [comment]
Since they use a separate system for their animations (more complex due to linkages) it is all I can provide for now. The only addition that would be possible is the block breaking particles.
