### ISSUE TITLE
Fire behaves like blocks

### ISSUE THREAD

**Issue by DeltaRazerNova** [haubna/PhysicsMod#854]
**Describe the bug**
When you extinguish fire it spawn particles like if its a block.

**To Reproduce**
Left-click on fire to recreate the bug.

**Screenshots**
![Screenshot (169)](https://github.com/haubna/PhysicsMod/assets/106472366/1729b865-2c59-448e-903d-f42720177356)

Minecraft Version: 1.20.4
Physics Mod Version: 3.0.11

**Comment by haubna** [comment]
You can customize it under physics settings > blocks > customize
