### ISSUE TITLE
[Bug] Buttons overlap with Datapack/Gamerule Menus

### ISSUE THREAD

**Issue by nco2k** [haubna/PhysicsMod#857]
**Describe the bug**
response from the [developer](https://github.com/Estecka/mc-PackRule-Menus/issues/9): "This issue comes from PhysicsMod. Unfortunately, their mod is closed-source, so no-one but them have the ability fix this. I was able to peek at their code by decompiling the mod's jar, but I wouldn't be able to easily make change to it nor submit a PR for this. This should be reported to them. In PackruleMenu, I place the buttons by using Mojang's Gridwidget.adder (Yarn mappings), which is used to place all vanilla buttons. This method automatically adapts the menu's layout to its content, so this kind of issue would never happen amongst buttons registered in this way. The issue is that physics Mod does not use the Gridwidget.adder, and instead places its button at fixed coordinates, assuming this position would always be empty."

**To Reproduce**
install the [Datapack/Gamerule Menus](https://modrinth.com/mod/packrule-menus) mod.

**Screenshots**
![316350161-cdf0347b-ee85-4202-a808-f7ad99806265](https://github.com/haubna/PhysicsMod/assets/26080123/39edc77a-4a01-43de-afe4-90947c8366de)

Minecraft Version: 1.20.4
Physics Mod Version: 3.0.13
Datapack/Gamerule Menus Version: 1.2.1+1.20.1

**EDIT:** now that i think about it, i would prefer the option to remove the "Physics Settings..." button entirely. when i want to change the settings, i can get to them through Mod Menu.

**Comment by haubna** [comment]
Thanks for the report, with Minecraft 1.20.5 and onward I will use this to add the physics button (at least I hope that is what he meant). Here is the new code snippet:

```Java
@Mixin(OptionsScreen.class)
public class MixinOptionsScreen extends Screen {

	protected MixinOptionsScreen(Component title) {
		super(title);
	}
	
	@Redirect(method = "init()V", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/gui/layouts/GridLayout;createRowHelper(I)Lnet/minecraft/client/gui/layouts/GridLayout$RowHelper;"))
	private RowHelper physicsmod$button(GridLayout instance, int columns) {
		RowHelper rowHelper = instance.createRowHelper(columns);
		Button physicsButton = Button.builder(Component.translatable("physicsmod.menu.main.title"),
				button -> this.minecraft.setScreen(new PhysicsSettingsScreen(this))).width(308).build();
		rowHelper.addChild(physicsButton, 2);
		return rowHelper;
	}

}
```

**Comment by nco2k** [comment]
can you please give us an option to remove that button entirely? even if you fix the overlapping issue, chances are high that with multiple mods installed, the options menu will be cluttered to the point of not being able to press "Done" anymore. this way we can remove the buttons we dont use very often and keep the menu nice and tidy.

**Comment by Estecka** [comment]
> (at least I hope that is what he meant).

Looks like the right thing. 👍 

My only recommendation would be to grab the RowHelper using MixinExtra's `@Local`. That would save you the need for a `@Redirect`.
This is how I did my inject, I think the same would work for you as well: [[x]](https://github.com/Estecka/mc-PackRule-Menus/blob/da2ef99c8f9e07675f15491153a7717f0a4c553c/src/main/java/tk/estecka/packrulemenus/mixin/OptionScreenMixin.java#L46C52-L46C81)
```java
@Inject( method="init", at=@At(value="INVOKE", ordinal=1, shift=Shift.AFTER, target="net/minecraft/client/gui/widget/GridWidget$Adder.add (Lnet/minecraft/client/gui/widget/Widget;)Lnet/minecraft/client/gui/widget/Widget;") )
private void gameruleMenu$Init(CallbackInfo info, @Local GridWidget.Adder adder)
{
    // ...
}
```
