### ISSUE TITLE
[Compatibility] Minecraft Ten Font

### ISSUE THREAD

**Issue by nco2k** [haubna/PhysicsMod#860]
the [Minecraft Ten Font](https://modrinth.com/resourcepack/mc10) breaks the readability of the options menu. any chance to workaround it?

![font](https://github.com/haubna/PhysicsMod/assets/26080123/5fd5f011-1941-4afc-93c3-dd97d628fe91)

**Comment by haubna** [comment]
You could try tinkering with the language files of the mod. I suppose this happens due to everything being upper case.
