### ISSUE TITLE
Compatability Issue With Iris 1.7.0

### ISSUE THREAD

**Issue by DTX3** [haubna/PhysicsMod#862]
**Describe the bug**
Incompatible mod found. 

Mod 'Iris' (iris) 1.7.0-snapshot+mc1.20.4-b3ac58d is incompatible with version 3.0.13 or earlier of mod 'Physics Mod' (physicsmod), but a matching version is present: 3.0.13!

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/59918994/a650e988-eaec-4995-a09c-135f7ccb440d)

Minecraft Version: 1.20.4
Physics Mod Version: v167d pro

It's the Iris version which comes with the Distant Horizons mod.

**Comment by omenumm** [comment]
the same problem, I'm really looking forward to help

**Comment by NightfallCT** [comment]
Same problem here

**Comment by Patrekokes** [comment]
physics mod is not compatible with snapshot version of iris (1.7.0), you would have to use a featured version, like iris 1.6.17

**Comment by damianeickhoff** [comment]
Same issue! Guess we will need to wait on a new version :)

**Comment by haubna** [comment]
I have created a build for Minecraft 1.20.4 which is compatible with Iris 1.7 + Distant Horizons. Have fun!

**Comment by Mrgaton** [comment]
@haubna  and will ne a 1.20.1? we can wait but that version is very popular too

**Comment by haubna** [comment]
No plans on 1.20.1 since over time mods will migrate to the newest versions anyways.

**Comment by Mrgaton** [comment]
😢

**Comment by YNICO1122** [comment]
Okay but how do we actually get that version? is it paid only?

**Comment by haubna** [comment]
It is now available for 1.20.1!

**Comment by Mrgaton** [comment]
Thank you very much

**Comment by DTX3** [comment]
Thanks for the update. Afraid still getting an error with 1.20.1.

![image](https://github.com/haubna/PhysicsMod/assets/59918994/be9d1870-5e8d-4c89-a356-0b5dc5f3f0e3)

**Comment by Jellevs** [comment]
Hi!
I installed these versions and the physics mod pro fabric 1.20.4 but I still get this error
"<html>Mod 'Iris' (iris) 1.7.0+mc1.20.4 is incompatible with version 3.0.13 or earlier of mod 'Physics Mod' (physicsmod), but a<br>matching version is present: 3.0.11!</html>"

How do I fix this?
Thanks!
![image](https://github.com/haubna/PhysicsMod/assets/95053189/3c5cfc48-0080-4f99-bfd6-9e32f30626a2)
