### ISSUE TITLE
TNT disappears when broken

### ISSUE THREAD

**Issue by Macintosh-Fan** [haubna/PhysicsMod#864]
No idea what I did, but only TNT seems to not want to break into fractured blocks, even though it seems to be configured to fracture like any other block.

https://github.com/haubna/PhysicsMod/assets/50642934/61479fe2-65d9-4dea-a255-abb851022edb

Using Minecraft 1.20.2 with the latest version of the physics _pro_ mod.

**Comment by haubna** [comment]
This is an exception for the blocks because it would also fracture when it gets ignited (which looks very odd).
