### ISSUE TITLE
Crashing on world load [BUG]

### ISSUE THREAD

**Issue by kerenb14** [haubna/PhysicsMod#865]
**Describe the bug**
Minecraft loads to the menu fine, but when loading a world it freezes at 100% and crashes. I skimmed the crash report and didn't see any other mods being named, but shaders being involved suggests to me that it could be Iris or Sodium like the other reports here.

Edit to add: The game loads a world fine the *first* time, but on subsequent loads with the mod enabled it crashes. I'm going to try loading with Iris & Sodium removed in the next few days, as well as with a stable release because I may have been using the snapshot release when this happened.

**To Reproduce**
Open Minecraft
Load a world
???
Crash

**Screenshots**
N/A

Minecraft Version: 1.20.4
Physics Mod Version: Pro v167d

**Most recent crash report**
[hs_err_pid11300.log](https://github.com/haubna/PhysicsMod/files/14817274/hs_err_pid11300.log)

**Comment by haubna** [comment]
It's an odd place to crash but it might've happened due to the beta iris & sodium versions. If this happens with full releases please open up a new issue. Thanks for the report!

**Comment by YNICO1122** [comment]
I am having this same issue. Just after it loads to 100 percent on joining world it crashes

**Comment by moinx** [comment]
I have the same Problem. 
When loading a world, it loading 100 % then crash.

Minecraft version: 1.20.4
mod version: physics-mod-pro-v169e-fabric
