### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by MrFantastico1** [haubna/PhysicsMod#866]
Desc:
my game crashes after forge is done loading mods

It just keeps crashing on launch 
**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**
i have minecraft crash text as proof but dont have any screenshots   
[crash-2024-03-31_23.24.28-client.txt](https://github.com/haubna/PhysicsMod/files/14817571/crash-2024-03-31_23.24.28-client.txt)

Minecraft Version: <1.16.5>
Physics Mod Version: <36b>
Forge version: 36.2.42

**Comment by haubna** [comment]
Old versions of the mod no longer get updates, please upgrade to the latest version, thanks!
