### ISSUE TITLE
Can mod be splited to be less than 100mb?

### ISSUE THREAD

**Issue by Mrgaton** [haubna/PhysicsMod#867]

**Comment by haubna** [comment]
No

**Comment by Mrgaton** [comment]
or compressed or something please

**Comment by haubna** [comment]
You can try to open the jar and remove the files "PhysXGpu_64.dll" and "PhysXGpu_64.dll.sha1" inside of "de/fabmax/physxjni/windows". After this you won't be able to use GPU liquid physics but it will reduce the size drastically. I have never tried this so it might not work.

**Comment by Mrgaton** [comment]
Thx 🙏😊 

I will try it

**Comment by Mrgaton** [comment]
You could try using upx for compressing dlls is very good at it

https://github.com/upx/upx

Make sure to set the settings at --best for better compresión.

**Comment by haubna** [comment]
The mentioned dll is already compressed (from 232 MB down to 78 MB).

**Comment by Mrgaton** [comment]
oh
