### ISSUE TITLE
Pro doesn´t work

### ISSUE THREAD

**Issue by Pollmaha** [haubna/PhysicsMod#868]
**Describe the bug**
When Iput the Pro Mod in the mods folder, start the game and go to the physics settings, it still says: Get Pro!

**To Reproduce**
Install Labymod 4.2.7, install Fabric Loader for Labymod, intall the modmenu mod and put the Pro version of the physics mod in the mods folder.

Minecraft Version: Minecraft 1.20.4, LabyMod 4.2.7
Physics Mod Version: v167d-fabric-1.20.4

**Comment by haubna** [comment]
You probably still have the lite version installed. You need to remove that.
