### ISSUE TITLE
Incompatibility with the latest DH and Iris. 

### ISSUE THREAD

**Issue by YNICO1122** [haubna/PhysicsMod#872]
**Describe the bug**
The latest update for the physics mod released 5 days ago is incompatible with the latest DH and Iris. Unfortunately, I can't download an older version of Iris and DH due to it not being available anymore. 

What happens is the game loads the world then gets to joining then crashes,

Minecraft Version: 1.20.4 and using the latest pro physics mod released 5 days ago.

**Comment by haubna** [comment]
Do you have a crash log for me? I just tried it and I didn't experience a crash.

**Comment by YNICO1122** [comment]
Slooshie and I both tried it. In your discord server, we tagged you with the logs. Here are bnoth of our logs 
[latest (1).log](https://github.com/haubna/PhysicsMod/files/15060643/latest.1.log)
[latest.log](https://github.com/haubna/PhysicsMod/files/15060645/latest.log)

**Comment by Slooshie1** [comment]
This appears to have been (probably inadvertently) fixed on either DH's or Iris' end in a beta update

**Comment by YNICO1122** [comment]
[latest.log](https://github.com/haubna/PhysicsMod/files/15064093/latest.log)

**Comment by YNICO1122** [comment]
https://mclo.gs/8Kldr6V

**Comment by haubna** [comment]
> This appears to have been (probably inadvertently) fixed on either DH's or Iris' end in a beta update

Perfect! There are a lot of changes in each update so it could break at any given point. Once it is out of beta support this will probably change :)
