### ISSUE TITLE
Incompability with iris (latest version; 1.7.0)

### ISSUE THREAD

**Issue by rakantoh** [haubna/PhysicsMod#873]
the recent update 1.7.0 of iris is incompatible with physics <= 3.0.13 mod in 1.20.4 

To Reproduce:
iris v1.7.0 and physics mod any version in 1.20.4

**Comment by haubna** [comment]
Thanks for the report. 3.0.14 is now available and supports Iris 1.7 (curseforge will take a bit to process, but on my website + modrinth it is already ready for download)!

**Comment by JENOVAAbsolute** [comment]
> Thanks for the report. 3.0.14 is now available and supports Iris 1.7 (curseforge will take a bit to process, but on my website + modrinth it is already ready for download)!

v169 for the pro version of Physics Mod is incompatible with Iris 1.7. I'm specifically using the Iris build that comes with their installer to use DH with shaders. I'm running on MC 1.20.1.

[latest.log](https://github.com/haubna/PhysicsMod/files/15144705/latest.log)
