### ISSUE TITLE
Bug destroying any kind of blocks on latest 3.0.14 version 1.20.1

### ISSUE THREAD

**Issue by Pictorrez** [haubna/PhysicsMod#874]
**Describe the bug**
When I destroy a block, it starts to "rain" around the block 
a few seconds after the action itself. The sound and particles are annoying after a while when building.

**To Reproduce**
Install latest Physics mod version alongside sodium 0.5.8, then destroy any block around, and see the bug.

**Screenshots**
![Captura de pantalla 2024-04-24 060009](https://github.com/haubna/PhysicsMod/assets/83793680/59ced309-f0ce-4071-90f5-5c2748f3929b) with latest iris 1.7, and without iris installed:
![Captura de pantalla 2024-04-24 060701](https://github.com/haubna/PhysicsMod/assets/83793680/30aeddd1-a658-407f-9cd3-767f98fbba6c)

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.14

**Comment by Pictorrez** [comment]
Just tell me if you need any logs or more info, love your mod btw, thanks for making:)

This is a bit off-topic, but, will it be a Distant Horizons + Iris 1.7 support on 1.20.1 Physics Pro version? I saw it's already out for 1.20.4 and it works nicely as I tested :D

**Comment by haubna** [comment]
I wasn't able to reproduce this issue. Which mods do you have installed? Maybe the resource pack is causing that issue. Yeah I have updated the 1.20.1 Pro version already to support Iris 1.7.0.

**Comment by Pictorrez** [comment]
After a bit of testing, it seems that Physics mod config was changed after I updated, so destroying block animation was changed to "splash" instead of "default" or whatever. So, I just solve this on settings. 

Sorry for that, the sound generated by every single splash when building was driving me crazy lol. Now everything is working fine, thank you for making such an amazing mod!

**Comment by haubna** [comment]
No problem, have fun!
