### ISSUE TITLE
Bug description [incompatability]

### ISSUE THREAD

**Issue by YNICO1122** [haubna/PhysicsMod#875]
I have a bunch of other mods installed, however, it seems to work perfectly fine with the latest physics mod from Modrinth but not the Pro version from Patreon. What happens is I get in and when it gets to the joining world screen the game just closes. I have attached my log below. 

Even if you can't fix the issue, do you know what mod might be causing it? I have attached a snapshot of all my mods installed as well

Iris 1.7.0
DH 2.0.3
Latest Bliss from discord
Latest Physics mod from Patreon (V169 Pro 1.20.4)
MC version 1.20.4

![All Mod Pic](https://github.com/haubna/PhysicsMod/assets/167622483/6fe035c9-5925-46dc-a59a-0de7d2a6094b)

[latest.log](https://github.com/haubna/PhysicsMod/files/15094641/latest.log)

**Comment by haubna** [comment]
Disabling "Use No Error Context" in the Performance menu might fix it. Could you let me know if that works for you?

**Comment by YNICO1122** [comment]
That fixed it! Thankyou so much!

**Comment by haubna** [comment]
Perfect, I will include a fix that disables this setting by default with the next version.
