### ISSUE TITLE
Instant Crash to Desktop when breaking Create large water wheel

### ISSUE THREAD

**Issue by Lyra-Vhess** [haubna/PhysicsMod#876]
**Describe the bug**
As the title says, when attempting to break the large water wheel in the Create mod, an instant CTD is experienced.
This appears to have been an issue brought up on the Create github, but I think compatibility would be much better addressed by physicsmod:
 https://github.com/Creators-of-Create/Create/issues/4800
It appears to be easily solvable by just making an exception for the part but I felt it would be best to make an issue here so it can be resolved for others. I've confirmed that making said exception solves the problem. It appears to be an out of memory error? I'm not sure why but I'll leave that to you guys.

EDIT: Same problem with the small water wheel

**To Reproduce**
1. Enable both Create and Physicsmod
2. Place a large water wheel
3. Attempt to break it

**Screenshots**
![2024-04-26_01-06](https://github.com/haubna/PhysicsMod/assets/91616359/ebcb7286-a05b-40b1-9255-f0e94974773b)

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.10

**Comment by haubna** [comment]
Yup, this got fixed with more recent versions already. Thanks for the report though!
