### ISSUE TITLE
Weird particle texture

### ISSUE THREAD

**Issue by dblt-tim** [haubna/PhysicsMod#877]
when breaking blocks, eating or anything else that makes the cubic particle the texture is not the desired one 
![2024-04-26_17 05 30](https://github.com/haubna/PhysicsMod/assets/167763787/31da1125-ce5b-4474-bf19-51615d104c0e)

**Comment by T1wim** [comment]
also don't mind the server lmao

**Comment by haubna** [comment]
Which Minecraft version + Physics Mod version are you using?

**Comment by dblt-tim** [comment]
> Which Minecraft version + Physics Mod version are you using?

minecraft 1.20.4, fabric
latest physics mod version

**Comment by haubna** [comment]
Can you send me a list of all mods used? I need the exact version numbers.

**Comment by dblt-tim** [comment]
> Can you send me a list of all mods used? I need the exact version numbers.

well um I don't know how, but I somehow solved the problem. Thanks anyway :)
