### ISSUE TITLE
Crashes on World Load after New update

### ISSUE THREAD

**Issue by ArcadianEcho** [haubna/PhysicsMod#878]
**Describe the bug**
When loading a world, the game crashes almost immediately.

**To Reproduce**
Load up the game, select and load world. World loads fine for a few seconds and then crashes

**Screenshots**

![image_2024-04-28_230218723](https://github.com/haubna/PhysicsMod/assets/168392072/e946c01f-1a20-452b-b3c4-df822eeb32a5)

[crash-2024-04-28_23.01.52-client.txt](https://github.com/haubna/PhysicsMod/files/15144814/crash-2024-04-28_23.01.52-client.txt)

Minecraft Version: 1.20.4
Physics Mod Version: 3.0.14

**Comment by haubna** [comment]
Please update to the latest Iris (1.7.0) and Sodium (0.5.8) version.
