### ISSUE TITLE
1.20.1 Forge | Crashing after world loading [BUG]

### ISSUE THREAD

**Issue by marcell123455** [haubna/PhysicsMod#880]
[crash-2024-05-01_01.23.35-client.txt](https://github.com/haubna/PhysicsMod/files/15172171/crash-2024-05-01_01.23.35-client.txt)

I installed the physics mod and now it always crashes after the world loading has finished.
Deleting old files in the config folder made no difference. It says it has no acces to some file like physicsmod.mixins.json. Check out the log.

Is there a way to fix this for 1.20.1?
Love your mod!

Minecraft Version: Forge 1.20.1-forge-47.2.0
Physics Mod Version: physics-mod-pro-v167d-forge-1.20.1

**Comment by haubna** [comment]
Oculus 1.7.0 is incompatible with Pro v167. Please download Pro v169 (I uploaded it today).
