### ISSUE TITLE
game crashes if the server disconnects the client (authentication failure (cracked servers) , network error )

### ISSUE THREAD

**Issue by OCTAMIUM** [haubna/PhysicsMod#882]
**Describe the bug**
the game crashes if the server disconnects the client (authentication failure on cracked server or a network error 

**To Reproduce**
have physics mod , connect to a server (cracked) , dont authenticate 

**Screenshots**

all the mods are client side 

https://youtu.be/QPDO9ruZkTo (all the mods enabled)

https://youtu.be/IhpFQMQAmfM (physics mod disabled , other mods enabled)

https://youtu.be/ONb88-QzRpg (only physics mod enabled , all other mods disabled )

Minecraft Version: fabric 1.20.4 / fabric loader 15.10
Physics Mod Version: <3.0.14> v169 fabric

**Comment by haubna** [comment]
Those servers are not supported.
