### ISSUE TITLE
1.20.1, Oculus of Forge 47.2.30 is not compatible with real physical MODs

### ISSUE THREAD

**Issue by LiuHao422** [haubna/PhysicsMod#888]
**Describe the bug**
Displaying light and shadow will cause physical MODs to crash

**To Reproduce**
nothing

**Screenshots**
nothing

Minecraft Version: 1.20.1,Forge 47.2.30
Physics Mod Version: physics-mod-pro-v167d-forge-1.20.1

**Comment by haubna** [comment]
Update to Pro v169.
