### ISSUE TITLE
[Feature Request] Blocky Fractured Block physics and Breaking Block particles

### ISSUE THREAD

**Issue by NaiNonTH** [haubna/PhysicsMod#89]
You may have heard about Fancy Block particle mod before. It changes Minecraft 2d block particles into 3d ones. Also, there are block particles when breaking too. It would be so cool if these are added into the mod.

![ZfiAoir](https://user-images.githubusercontent.com/61338902/130483055-cc19079d-50c7-4a8e-90f0-387a28b8b6cf.gif)

That mod also hasn't been updated since October 2018. Maybe it's pretty great to see this being added

**Comment by haubna** [comment]
Added it to my todo list :)

**Comment by NaiNonTH** [comment]
> Added it to my todo list :)

Noice :D

**Comment by haubna** [comment]
Added in 2.6.0
