### ISSUE TITLE
Particle problem need help [BUG]

### ISSUE THREAD

**Issue by Twichinator** [haubna/PhysicsMod#895]
I join my friends realm and From what i can see over some time of playing a bunch of particles (blood, plant, blocks, i mainly see grass) spawns causing a TON of lag and a confirmed crash, no way to recover. I can continue playing after i restart the game

**To Reproduce**
There's no way to efficiently reproduce. it just happens seemingly random times

**Screenshots**
I have no screenshots but i do have mods i use 
![image](https://github.com/haubna/PhysicsMod/assets/170581205/dffc9e08-e60e-44f5-8bcc-8831880ebaa0)
EDIT: i think i just got a screenshot of some particles 
![2024-05-22_18 13 51](https://github.com/haubna/PhysicsMod/assets/170581205/a0f82a3e-2410-409c-b795-5724f2e7b6f8)
![2024-05-22_18 13 54](https://github.com/haubna/PhysicsMod/assets/170581205/7c99aeca-7cc6-48df-ab93-465ed1bc92ae)
![2024-05-22_18 00 53](https://github.com/haubna/PhysicsMod/assets/170581205/e826c5c0-fcf8-4b10-ad49-816ef95f91ca)
the blood and grass dont come from skeletons

Minecraft Version: Fabric 1.20.4
Physics Mod Version:  As seen in screenshot : physics-mod-pro-v165-fabric-1.20.4

**Comment by haubna** [comment]
Please update to v169f and open up a new issue if the crash still occurs. Also make sure to update to Iris 1.7 and the latest Sodium version. Thanks!
