### ISSUE TITLE
requires fabric (or can't see fabric?) 

### ISSUE THREAD

**Issue by Stardelis** [haubna/PhysicsMod#9]
I installed it in the mods folder, i had fabric before cause i use replay mod, and it doesn't work with forge. So the game crushed saying Physics mod requires fabric. I Updated everything from 1.16.4 to 1.16.5, launcher, optifine and optifabric. My PC does not let me run fabric api to update it. I'm not sure if it requires fabric api or it doesn't see fabric launcher, and idk why .jar file does not want to turn on. Do i even have to update if i was on 1.16.4?

**Comment by haubna** [comment]
Please read general instructions on how to install mods. It seems like you mixed the mods from Fabric and Forge.

**Comment by Stardelis** [comment]
I have never had forge and i downloaded fabric version of the mod. Did you even read what i wrote?

**Comment by haubna** [comment]
Yeah but your text doesn't make any sense. You are doing something completely wrong. Read the instructions on how to install mods for either Forge or Fabric.
