### ISSUE TITLE
Ragdolls become blocky when the player model is loaded when using Figura avatars 

### ISSUE THREAD

**Issue by SkyTheNerd** [haubna/PhysicsMod#9]
Figura is a mod that makes it so you can have more capability with Minecraft skins using block bench and the Lua coding language. (basically the bedrock avatar creator in java edition but better)

The problem isn't that figura avatars aren't the ragdoll, it's just when if you do something like open your inventory or go in third person (F5) at ANY time, the ragdoll (which is the vanilla Minecraft skin/model, not the figura skin/model) becomes blocky instead of ragdoll.

This USED to not be a problem, but if you want to try and fix it, you have to join the figura discord and download the newest 1.17 pre-release. (or I can attach a download)

I hope this gets fixed soon because figura + physics mod makes a great team.

**Comment by SkyTheNerd** [comment]
I was using figura-0.0.5g-1.17.jar btw, just in case if you're wondering.

**Comment by SkyTheNerd** [comment]
it's also open source.
https://github.com/Blancworks/Figura/tree/main

**Comment by haubna** [comment]
Other mods are not supported yet.
