### ISSUE TITLE
Outer Layer Is Seperate from Inner Layer when Blocky

### ISSUE THREAD

**Issue by miclol** [haubna/PhysicsMod#90]
I believe this is not what the expected behaviour is but if it is me dum (To be fair I'm using ver. 2.5.4, but I don't think it's fixed in 2.5.5 as it's not in the changelog)
![image](https://user-images.githubusercontent.com/64191125/130710590-aae3968e-3362-4197-9a90-1f08468ae723.png)

(Also, maybe there can be a variation of the Ragdoll Option, so if I get killed by a stalagmite or similar, it calculates where on the body it killed the player and separates that part from the rest of the ragdoll?)

**Comment by QAQlinmiao** [comment]
2.5.5 It is indeed not repaired

**Comment by haubna** [comment]
Fixed
