### ISSUE TITLE
Latest version (v169g) crashes game when loading world [BUG]

### ISSUE THREAD

**Issue by Chris6ix** [haubna/PhysicsMod#903]
**Describe the bug**
I just updated all mods in my modpack and when I try to load into a world, the game just crashes. The error log says something about physicsmod, so I just reverted back to the previous version (v167d) and it no longer crashes, so it's specifically v169g that is the issue. Crash log: 
[crash-2024-05-31_15.48.11-client.txt](https://github.com/user-attachments/files/15514609/crash-2024-05-31_15.48.11-client.txt)

**To Reproduce**
Use PhysicsMod v169g and load a world?

**Screenshots**
/

Minecraft Version: 1.20.1
Physics Mod Version: v169g

**Comment by haubna** [comment]
Pro v169 requires Oculus 1.7 and the latest Embeddium version.

**Comment by Chris6ix** [comment]
Ah, thank you. I checked and realized that I had forgotten Oculus when updating my modpack. With Oculus 1.7 the crash is indeed fixed.
