### ISSUE TITLE
[BUG] Smoke Shader crash

### ISSUE THREAD

**Issue by HockeyZman2000** [haubna/PhysicsMod#905]
**Describe the bug**
At seemingly random intervals, the game crashes with the shader crash report referencing the "render thread" and interactions between Oculus (Iris) and the smoke shaders inside of the physics mod. This occurs even with everything smoke related turned off in the settings for the mod. I have attached a copy of the crash that I keep getting.

**To Reproduce**
1. Load into a world with Physics Mod Pro and shaders on (in my case Complementary Reimagined w/ Euphoria Patches).
2. After some time, game crashes

Minecraft Version: 1.20.1
Forge Version: 47.3.1
Physics Mod Version: Pro 170b

[hs_err_pid42668.log](https://github.com/user-attachments/files/15754152/hs_err_pid42668.log)

**Comment by HockeyZman2000** [comment]
I have further noticed that I can reliably reproduce it by eating a cooked cod, for some reason?

**Comment by haubna** [comment]
This happens when it tries to compile the smoke shader (probably some smoke in your area). Disable smoke for now. I wasn't able to reproduce this on my end.

**Comment by haubna** [comment]
I was able to find the issue and fixed it with Pro V170d.
