### ISSUE TITLE
Support for old versions of mac os?

### ISSUE THREAD

**Issue by GradersPro88** [haubna/PhysicsMod#91]
Will there be support for macos el Capitan as I can't get the mod to work as it crashes when trying to load in world or server

**Comment by haubna** [comment]
Crash log please :)

**Comment by GradersPro88** [comment]
Where do I find the crash lgs

**Comment by GradersPro88** [comment]
Actually pretty sure it crash because my Mac is x32

**Comment by GradersPro88** [comment]
o k found out where crash log are stored and I looked in it and there's nothing 🤨

**Comment by haubna** [comment]
Hmm probably a PhysX JNI problem. Not much I can do, sorry.
