### ISSUE TITLE
the water is clear but when i go under the water it became normal

### ISSUE THREAD

**Issue by haraldz91** [haubna/PhysicsMod#910]
**Describe the bug**
the water is clear but when I go under the water it becomes normal

![Screenshot 2024-06-16 175802](https://github.com/haubna/PhysicsMod/assets/172993205/e128e04e-abb9-40fa-8506-bcf75505541f)
![Screenshot 2024-06-16 175959](https://github.com/haubna/PhysicsMod/assets/172993205/9f50c4d1-c0f2-494f-a05f-ca8b6b87e9d2)

Minecraft Version: 1.21
Physics Mod Version: physics-mod-3.0.16-mc-1.21.0-neoforge

**Comment by haubna** [comment]
Thanks for the report, I was able to reproduce it. I will let you know once a fix is available.

**Comment by haubna** [comment]
Fix is now online. Simply redownload the NeoForge 3.0.16.

**Comment by haraldz91** [comment]
thank you for fixing it
