### ISSUE TITLE
Crash when loading end dimension with ocean physics mod (possible mod incompat?)

### ISSUE THREAD

**Issue by Syclusion** [haubna/PhysicsMod#915]
**Describe the bug**
Crashing when going to outer end islands in the end, crash stops when physics mod is removed. Seems to be related to the ocean physics.

**To Reproduce**
Go to end islands, see water. Crash

**Screenshots**

Minecraft Version: <1.20.1 Forge 47.1.3>
Physics Mod Version: <170d>

[crash-2024-06-26_01.28.57-client.txt](https://github.com/user-attachments/files/15982899/crash-2024-06-26_01.28.57-client.txt)

**Comment by haubna** [comment]
It seems like it is unable to create ocean shaders for the end dimension. This might be fixable by changing your shaderpack. Which one are you currently using?

**Comment by Syclusion** [comment]
Oh I see, I've been using bliss with distant horizons. It does give the not supported error but they render fine in the overworld. I'll try switching to see if it fixes it

**Comment by Syclusion** [comment]
Yup, its a bliss issue
