### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by Ragnilotl** [haubna/PhysicsMod#916]
[**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

Minecraft Version: <version>
Physics Mod Version: <version>
](https://mclo.gs/NkJIb0k)

**Comment by haubna** [comment]
You are mismatching versions. Please try to use Minecraft 1.20.6 with the appropriate mod versions (for 1.20.6).
