### ISSUE TITLE
Something having a conflict with Phycics mod in my modpack

### ISSUE THREAD

**Issue by Yuganson** [haubna/PhysicsMod#92]
When i join my world it just says "Saving world" and crashes the game.

My crashlog: 
[crash-2021-08-26_19.53.38-client.txt](https://github.com/haubna/PhysicsMod/files/7061473/crash-2021-08-26_19.53.38-client.txt)

**Comment by haubna** [comment]
You have a version mismatch. You are trying to run the Physics Mod version for 1.17.1 but you are using Minecraft 1.17. Please download the proper physics mod version (https://minecraftphysicsmod.com/).

**Comment by Yuganson** [comment]
> You have a version mismatch. You are trying to run the Physics Mod version for 1.17.1 but you are using Minecraft 1.17. Please download the proper physics mod version (https://minecraftphysicsmod.com/).

That didnt help. It loaded my world this time but when i tried to break a block - "Saving world" and crash.

[crash-2021-08-28_20.32.44-client.txt](https://github.com/haubna/PhysicsMod/files/7071155/crash-2021-08-28_20.32.44-client.txt)


UPD. It worked without shaders. I guess Seus Renewed conflicts with the mod.

UPD2. I checked almost every shader i have and it is always a crash.

**Comment by haubna** [comment]
Yeah there is a bug in 1.17 with shaders. It got fixed in the new versions for MC 1.17.1. Legacy versions of Minecraft are not supported.
