### ISSUE TITLE
GPU liquids on aarch64 is non-toggleable

### ISSUE THREAD

**Issue by Dabicco** [haubna/PhysicsMod#920]
No matter the version of Physics Mod Pro or Minecraft you install, for me, it is impossible to toggle the "Enable GPU Liquids" option. I have three rigs, one with an RTX 4090, one with an RTX 3090, and one old one with an RTX 3060. None of them allow me to toggle the "Enable GPU Liquids" Feature in options. I am opening it from the Main Menu. All rigs have the same operating system (arch linux 64)

**To Reproduce**
- Install Minecraft
- Install Physics Mod and Fabric
- Boot up the game, and in the Main Menu, navigate to the Physics Mod Settings category
- Open the liquids tab and attempt to toggle "Enable GPU Liquids" option.

**Screenshots**
       
![gscreenshot_2024-07-01-200303](https://github.com/haubna/PhysicsMod/assets/89596009/950e0cb5-19dc-4b55-834c-e99bc0925fb1)
   

Minecraft Version: 1.20.1-1.21
Physics Mod Version: 168-170d
*GPU(s): NVIDIA RTX 3060, NVIDIA RTX 3090, NVIDIA RTX 4090
OS: Arch Linux (KDE Plasma) (wayland)

**Comment by haubna** [comment]
My bad. I forgot to update the description. I removed the GPU liquid support for linux due to the massive mod file size. I will change the text with the next update.

**Comment by Dabicco** [comment]
Okay, that's all good! :smile:
