### ISSUE TITLE
Fresh Animations Incompatibility

### ISSUE THREAD

**Issue by Mostovm** [haubna/PhysicsMod#921]
Fabric 1.21

This mod is amazing and you did an amazing job with this. I did run into an issue with fresh animations and I can already tell its because of the uv re texturing they've done.
I'm no coder but I think a solution to this is having a config button to toggle vanilla textures or equipped textures would be an easy fix but other than that I appreciate what you've done and I would love to see this compatibility, and the extra mile to make the game more rich. 

Thank you

**Comment by mpustovoi** [comment]
See https://github.com/haubna/PhysicsMod/issues/78
I guess it's not planned at all.
