### ISSUE TITLE
[BUG] 1.20 items such as bamboo trapdoor and just bamboo door are not affected by the physics in dynamic blocks toggle

### ISSUE THREAD

**Issue by EgertSUS** [haubna/PhysicsMod#923]
1.20 items such as bamboo trapdoor and just bamboo door are not affected by the physics in dynamic blocks toggle

I think its a eazy fix but i dont know how to do it (just copy the code from other doors and trapdoors)

Minecraft Version: 1.20-1.21
Physics Mod Version: vesions 1.20 to 1.21

**Comment by mpustovoi** [comment]
You can add a block in the dynamic block customization section in-game.
Just choose the block and the type of animation (door or trapdoor's). The default settings should be fine.

**Comment by haubna** [comment]
They already got added but when you use the old config for new minecraft versions it doesn't add them. You will have to do that manually or resetting your config file by deleting it.
