### ISSUE TITLE
Mod fails to load on 1.21 with linux

### ISSUE THREAD

**Issue by redstonegenious** [haubna/PhysicsMod#924]
I was updating my mods to 1.21 versions and this one was giving me issues. For a sanity check, I made a fresh 1.21 instance that only had this mod, iris, and its dependencies installed to get the same stack trace.

Minecraft Version: 1.21
Physics Mod Version: pro-v170d-fabric

Crash report:
[crash-2024-07-06_04.16.07-client.txt](https://github.com/user-attachments/files/16115653/crash-2024-07-06_04.16.07-client.txt)

**Comment by haubna** [comment]
You should be able to fix this issue by following this: https://github.com/fabmax/physx-jni/issues/69
