### ISSUE TITLE
Pro version not recognized in LABYMOD launcher 4.2.28

### ISSUE THREAD

**Issue by Muscle87** [haubna/PhysicsMod#925]
**Describe the bug**
You can use the free version and select it in the "browse mods" under fabric mods. It seems to think that when you replace that file with the PRO version that its still the FREE version. even after removing the FREE version from the modlist, and you manually put the pro.jar file the mods folder and hit "refresh" it shows up again thinking its the FREE version.

**To Reproduce**
Manage modpack in LABYMOD , open up fabric mod folder , add PRO version , refresh modpack, it will show the FREE version.

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/174904841/091a60c7-ff48-4732-a899-cf8033fd2d49)
![image](https://github.com/haubna/PhysicsMod/assets/174904841/d8ebf46a-5f64-43b3-9aeb-2b929194171d)

Minecraft Version: <1.21>
Physics Mod Version: <v170d-fabric>

**Comment by haubna** [comment]
This is probably due to the lite version being installed as well. I am not familiar with this launcher but I can tell you 100% that there is somewhere the lite version installed in your configuration.
