### ISSUE TITLE
Crash With Snow and Third Person Camera Collision [BUG]

### ISSUE THREAD

**Issue by danieljross** [haubna/PhysicsMod#927]
**Describe the bug**
When Minecraft's third-person camera collides with Physics Mod Pro Snow, a type conversion error is thrown, and the game crashes.

**To Reproduce**
Place or locate a snow block in the world. Enter third person, and rotate the camera such that the camera collides with the snow. The default behavior of this collision is to push the camera toward the player to prevent occlusion but instead, the game crashes when the camera collides with physics mod snow.

**Screenshots**
N/A

Minecraft Version: 1.21.0
Physics Mod Version: 170d

**Comment by RodoxVR** [comment]
yup same issue, its very easy to reproduce.

**Comment by haubna** [comment]
Fixed with v171, thanks for the report!
