### ISSUE TITLE
How do I purchase the pro version?

### ISSUE THREAD

**Issue by pil0lo** [haubna/PhysicsMod#929]
How do I purchase the pro version?
Is there a video on how to purchase the pro version??
I don't know because Discord is all in English.
It seems like it's telling me to sign up for some site.
Can I get it just by signing up?

**Comment by mpustovoi** [comment]
> How do I purchase the pro version?

You can support the mod's author, but not buy the Pro version.

> Can I get it just by signing up?

You can. It's the only way. You just go to `Patreon` from mod's page on `Modrinth` or `CurseForge`, scroll down a little to the last post and find the version you need.

**Comment by pil0lo** [comment]
Is it impossible to buy the pro version?
How do you use the rest of the features???
