### ISSUE TITLE
Add a toggle button for ragdolls upon entity removal

### ISSUE THREAD

**Issue by caoqt1** [haubna/PhysicsMod#93]
switched to windows and i am using this mod again but what pees me off is that in the new update it made it so ragdolls will not be created when an entity gets removed which renders this mod useless on players on servers as almost all minecraft servers remove the players character when they die thus causing a ragdoll to not spawn, please add a togglable button in the physics options to turn this on or off (make it default to off), thanks!

**Comment by Khodyn** [comment]
@haubna Perhaps this criteria should be made configurable for each entity with players defaulting to the old behavior.

**Comment by GradersPro88** [comment]
@haubna pls read

**Comment by haubna** [comment]
Already read it. Will be done in a future version :)

GradersPro88 ***@***.***> schrieb am So. 29. Aug. 2021 um
11:39:

**Comment by GradersPro88** [comment]
Hopeful y it will be done soon so fi do manage to ply Minecraft with this mod I cloud play on servers with rageolls

**Comment by QAQlinmiao** [comment]
This item is very suitable for pvp servers, I hope to be able to add

**Comment by haubna** [comment]
Added option for PvP Server compatibilty in version 2.5.15 (Physics Settings -> General Settings).
