### ISSUE TITLE
Crash with Sodium on Neoforge 1.21

### ISSUE THREAD

**Issue by TheVirusNVGM** [haubna/PhysicsMod#930]
The official fork of Iris and Sodium has been released to neoforge and the game crashes because:
physics-mod-pro tries to call the disableWorkaround method in the Sodium class (line Sodium.java:98).
The SodiumClientMod class from the Sodium mod was not found, resulting in a NoClassDefFoundError.

Minecraft Version: 1.21 neoforge
Physics Mod Version: 170d

[crash-2024-07-09_22.55.48-client.txt](https://github.com/user-attachments/files/16149751/crash-2024-07-09_22.55.48-client.txt)

**Comment by haubna** [comment]
Embeddium will be supported once the Sodium 0.6 multiloader version officially releases. Because by then embeddium will probably be replaced by Sodium itself. I don't know why Embeddium chose to release a non finished/released version of Sodium honestly.

**Comment by haubna** [comment]
It hasn't been officially released yet but I will upload a version that works with it today!

**Comment by haubna** [comment]
V171 that adds support for Sodium 0.6 + Iris 1.8 is now online. Keep in mind it might have some bugs. If you encounter any feel free to report them in a new issue, thanks!
