### ISSUE TITLE
water particle question

### ISSUE THREAD

**Issue by pil0lo** [haubna/PhysicsMod#931]
Current Status
![1](https://github.com/haubna/PhysicsMod/assets/143984023/f4fdcfbb-c914-4c6b-a288-fc8765e42a3f)

How do I make it look like a liquid?
![2](https://github.com/haubna/PhysicsMod/assets/143984023/b6c41f9a-5da5-45ac-ad1a-417fc6faedba)

Even though I turned on the GPU liquid, it doesn't look like liquid and looks the same as usual.
![3](https://github.com/haubna/PhysicsMod/assets/143984023/8272d0d1-dd02-4141-bce5-65670cdd68ba)

Resource pack for previous version?
![1](https://github.com/haubna/PhysicsMod/assets/143984023/55a0e559-cb74-40f7-9c3f-e345b5ea177f)

**Comment by DarkFireNinja** [comment]
The mod doesn't change regular water to look like the picture you shared. It creates a new type of water that you can create by placing and then breaking an Enchantment Table.

But if you just want ocean water to look cool then turn on the Ocean Physics

**Comment by haubna** [comment]
^
