### ISSUE TITLE
how to fix this crash [Crash]

### ISSUE THREAD

**Issue by Idk1248545** [haubna/PhysicsMod#936]
**Describe the bug**
Not really sure what happens but when i load in falling blocks it crashes my minecraft. This happened at first when i placed an anvil and then it happened wehn i teleported to a different area which happened to have falling gravel so it crashed again

**To Reproduce**
Place an anvil from high up and letting it fall.

**Screenshots**
![Screenshot 2024-07-13 104050](https://github.com/user-attachments/assets/0de9ae71-bd3e-4a79-82da-1f5678a9ea97)

Minecraft Version: 1.20.4
Physics Mod Version: physics-mod-pro-v169f-fabric-1.20.4

**Comment by haubna** [comment]
I am not sure, this doesn't seem to be related to the physics mod.
