### ISSUE TITLE
Crash Report in 1.17.1

### ISSUE THREAD

**Issue by Drhodesw** [haubna/PhysicsMod#94]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "physx.geomutils.PxConvexMesh.getAddress()" because "mesh" is null
Exit Code: -1

**Comment by haubna** [comment]
Which physics mod version are you using?

**Comment by Drhodesw** [comment]
It's 2.5.5, I reloaded the game a few times and it crashed again but I ran away from the area and it seems  to be resolved for now

**Comment by haubna** [comment]
What kind of area? Any guess on which mob/block caused it?

**Comment by Drhodesw** [comment]
So I was diggin into a mountain cave, and stacking dirt into a staircase when it happened. There were zombies and spiders around. Additionally, whenever I log in, the game reads "A new version of Physics Mod is available, click here!"

**Comment by haubna** [comment]
Ok thanks! Yeah because the most recent version is 2.5.6.

**Comment by Zelrog** [comment]
2.5.6 has the same problem. Not sure what caused it, but I can't load into my world when the mod is enabled ( crashes a few seconds after the load is finished )

**Comment by Drhodesw** [comment]
> Ok thanks! Yeah because the most recent version is 2.5.6.

Oh! Where does one pick this up? I only saw 2.5.5 on Curseforge :0

**Comment by Zelrog** [comment]
> > Ok thanks! Yeah because the most recent version is 2.5.6.
> 
> Oh! Where does one pick this up? I only saw 2.5.5 on Curseforge :0

Well, as you said before -> "click here!" :)
https://linkvertise.com/349514/physicsmod256fabric?o=sharing
But 2.5.6 is bugged too :c

**Comment by haubna** [comment]
Yeah, I might have a fix for it. Will be released with version 2.6.0 (includes vine physics). But it is gonna take a couple of days.

**Comment by Zelrog** [comment]
Good to know ^^

**Comment by haubna** [comment]
Should be fixed in version 2.5.7. Let me know if it works! :)
