### ISSUE TITLE
Thunder Tanking FPS [BUG]

### ISSUE THREAD

**Issue by 07Productions** [haubna/PhysicsMod#940]
Description:
Thunder destroying my FPS from 29 to 1-2 FPS, I've tried arranging settings to lighten it but no effect.

Reproduction: /weather thunder  (rain works smoothly)

Minecraft Version: 1.20.1
Physics Mod Version: v170

![Desktop Screenshot 2024 07 20 - 20 02 25 88](https://github.com/user-attachments/assets/85df1523-4d65-479f-a477-9bf1e22a696c)

**Comment by haubna** [comment]
It seems like your PC can't handle the load of thunder. You can change the amount of particles under weather settings -> thunder weather particle amount. Simply set it to the same amount as rain to avoid this issue.

**Comment by 07Productions** [comment]
> It seems like your PC can't handle the load of thunder. You can change the amount of particles under weather settings -> thunder weather particle amount. Simply set it to the same amount as rain to avoid this issue.

I did that but it still lags, I disabled the wind thinking it might have been all the physics of the vines going off, but still the same effect.
