### ISSUE TITLE
Won't show up

### ISSUE THREAD

**Issue by Z3R0R4ND0M** [haubna/PhysicsMod#942]
So, I downloaded the mod for forge (Not fabric) and I was using Curseforge. For some reason, when I put it into the mods file, it just doesn't show up on curseforge, I genuinely don't know what to do, and I need help. (The version I was using was 1.20.1)

**Comment by haubna** [comment]
There are plenty of good tutorials on how to install minecraft mods on YouTube with specific modloaders like curseforge. I personally only use the vanilla launcher so I can't give you any information on how to do that.
