### ISSUE TITLE
Minecraft crash 5 second after launching a world

### ISSUE THREAD

**Issue by ilansupernova** [haubna/PhysicsMod#946]
Minecraft crash 5 second after launching a world with any shader and even shader disabled.
This code appear: 
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.diebuddies.mixins.iris.MixinExtendedShaderAccessor. Mixin is defined in physicsmod.mixins.json and cannot be referenced directly

something to do?

**Comment by haubna** [comment]
You are mismatching Iris + Sodium versions. Make sure you use the one that is intended for use with the current physics mod version. Usually the most up to date version of Iris + Sodium + Physics Mod will work.
