### ISSUE TITLE
Trap doors react to physics when they shoudn't

### ISSUE THREAD

**Issue by BlackCube4** [haubna/PhysicsMod#947]
In my opinion the doors and trap doors should be static when they reach their end position.

https://github.com/user-attachments/assets/fb2a7ab3-28dc-4354-872c-655004157b70

Minecraft Version: 1.20.1
Physics Mod Version:  v170

**Comment by haubna** [comment]
You can disable the interaction with dynamic entities in the settings of the dynamic blocks.
