### ISSUE TITLE
Game crashing no longer than a minute in game after load [BUG]

### ISSUE THREAD

**Issue by Zarandolph01** [haubna/PhysicsMod#949]
Once I open my save game, it doesn't matter what I do, it'll crash after a certain amount of time, not exceeding a minute. All errors point to PhysX engine. I really don't want to remove the physics mod as it adds a lot of beauty to the game, but if needed I can remove it. 

To reproduce, I'm not sure you can reproduce. 

Minecraft Version: 1.20.1 Forge Java
Physics Mod Version: v170D
Shaders used: Sildur's Vibrant Shaders v1.52 Extreme VL (Volumetric lighting) [I did notice its not a supported shader for liquid physics v2]

I've checked, and there is no duplicate mod for Physics Mod. For crash logs, I was only given the hs_err logs. Attaching the 2 most recent logs.

[hs_err_pid5464.log](https://github.com/user-attachments/files/16396486/hs_err_pid5464.log)
[hs_err_pid17832.log](https://github.com/user-attachments/files/16396535/hs_err_pid17832.log)
[latest.log](https://github.com/user-attachments/files/16396491/latest.log)
[2024-07-26-3.log](https://github.com/user-attachments/files/16396495/2024-07-26-3.log)

**Comment by Zarandolph01** [comment]
UPDATE: Removed Physics mod last night and it worked. Confirmed that this mod is the cause.

**Comment by haubna** [comment]
I've uploaded v171 which hopefully fixes the crash. In case it doesn't please reopen a new issue, thanks for the report!
