### ISSUE TITLE
static debris

### ISSUE THREAD

**Issue by JhonatanSanga** [haubna/PhysicsMod#95]
the debris from the destroyed blocks does not move when I watch the replay in ReplayMod.
They stay like this
![Captura de pantalla 2021-08-28 112528](https://user-images.githubusercontent.com/65356841/131222857-353383be-eb8d-403b-852a-5944bd4f33ea.png)

**Comment by haubna** [comment]
ReplayMod isn't supported yet. I will look at it in the future though. Great potential for cinematics! :)

**Comment by JhonatanSanga** [comment]
ok thanks, keep going, I love your mod, I hope the support will be possible in the future :D

**Comment by haubna** [comment]
ReplayMod support is now available in early access on www.minecraftphysicsmod.com
