### ISSUE TITLE
Texture related crash with shaders[BUG]

### ISSUE THREAD

**Issue by thecreeper3326** [haubna/PhysicsMod#951]
**Describe the bug**
When I load up a world or join a server, alot of block textures are not rendered and when you try to reload textures, the whole pc freezes and crashes without making a crash report, it did however output a file in the main directory uploaded below. I must mention that i was using complementary reimagined, it does not crash using the vanilla renderrer

[hs_err_pid2632.log](https://github.com/user-attachments/files/16405459/hs_err_pid2632.log)

**To Reproduce**
install physics mod
load up a world
press F3 + T

**Screenshots**
![image](https://github.com/user-attachments/assets/e539b57f-7a09-4702-9b7b-bc9a75619871)

Minecraft Version: 1.21
Physics Mod Version: Physics mod pro v170d

**Comment by haubna** [comment]
I've uploaded v171 which hopefully fixes the crash. In case it doesn't please reopen a new issue, thanks for the report!
