### ISSUE TITLE
v171 Hangs Indefinitely after breaking Dynamic Block with Vine physics type

### ISSUE THREAD

**Issue by danieljross** [haubna/PhysicsMod#954]
**Describe the bug**
The game will hang indefinitely when a dynamic block with the Vine physics type is broken, due to what seems to be a memory leak. All allocated memory will become utilized.

**To Reproduce**
Using the Prism Launcher, install Minecraft 1.21.0 with the Fabric Mod Loader, version 0.16.0. Install Physics mod Pro v171-1.21.0 alongside Fabric API version 0.102.0-1.21. Start a new world, and locate/place a block with the Vine physics type. Break the block and observe the game hang. If left to hang for enough time, Minecraft will close the world and return the user to the title screen with the "Out of Memory!" message.

**Screenshots**
N/A

Minecraft Version: 1.21.0
Physics Mod Version: physics-mod-pro-v171-fabric-1.21.0

[latest.log](https://github.com/user-attachments/files/16557049/latest.log)

**Comment by Arocles** [comment]
Confirming this bug. Occurred in my testing as well. 
Providing additional [video](https://www.dropbox.com/scl/fi/tigf38ufntfjcvf2dlj2o/RE-090824.mp4?rlkey=137b9tle4utc68cosalbmvd0m&st=ai1c33fl&dl=0) of my testing.

**Comment by haubna** [comment]
Thank you for the report, I am currently looking into this issue!

**Comment by haubna** [comment]
Fix is now online with v171a. Sorry for the inconvenience. That was a really stupid oversight!
