### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by justjosh104326** [haubna/PhysicsMod#957]
any time I try to launch the game with this mod installed, it crashes with the error code -1 

To Reproduce
install fabric loader version 0.16.0 for 1.21, then install the following mods:
![image](https://github.com/user-attachments/assets/f21f4625-1b35-4650-ad46-82fb33746e74)
![image](https://github.com/user-attachments/assets/fe5a85cd-c452-4cc0-a0a5-0b0f037d86a4)
![image](https://github.com/user-attachments/assets/131d325d-2b4c-4f81-8dea-aa9fd21353a8)

Screenshot
![image](https://github.com/user-attachments/assets/5fc54041-5109-458f-84b5-bf2dc649712c)

Minecraft Version: <1.21>
Physics Mod Version: <3.0.16>
Fabric Loader Version: <0.16.0>
Specs: 
![image](https://github.com/user-attachments/assets/75c73d5d-57d3-48dd-8998-5abb82764086)

**Comment by haubna** [comment]
This doesn't seem to be physics mod related
