### ISSUE TITLE
Bug description [BUG]

### ISSUE THREAD

**Issue by sami2468555** [haubna/PhysicsMod#959]
i tried loading the game but it just crashed me while joining a server 

[crash-2024-08-14_01.07.16-client.txt](https://github.com/user-attachments/files/16606131/crash-2024-08-14_01.07.16-client.txt)

Minecraft Version: 1.20.1
Physics Mod Version: 1.20.1 [Forge - Physics Mod 3.0.14]

**Comment by haubna** [comment]
Make sure to install the proper oculus + embeddium versions (Oculus 1.7.0 + Embeddium 0.3.14) for shaders. A list of appropriate version can be found here: https://minecraftphysicsmod.com/installation
