### ISSUE TITLE
Server or Client side install?

### ISSUE THREAD

**Issue by Zxurian** [haubna/PhysicsMod#96]
I checked CurseForge & Readme, but couldn't find a direct answer.

- Does this mod need to be installed on server AND client, or just server, or just client?
- If it does get installed on server, can you set server physics configs on server side so client side configurations are ignored?

**Comment by GradersPro88** [comment]
If you install the mod on the server you can set a config for everybody to use and if you install on the client you get all that stuff

**Comment by haubna** [comment]
You can install it either on server (enables collapsing structures) or on client (physics simulations) or on both.
