### ISSUE TITLE
Physics Mod Lite 3.0.16 Causes Intermittent Crashes on Minecraft 1.21 When Exiting Server with Custom Texture Pack

### ISSUE THREAD

**Issue by MiguVT** [haubna/PhysicsMod#961]
**Describe the bug**
When using Minecraft version 1.21 with Physics Mod Lite version 3.0.16, the game intermittently crashes upon exiting a server after loading a custom texture pack. This issue occurs more than half of the time with both the latest Fabric Loader version and version 0.15.11. The crash is observed on the server `play.miguvt.com` but does not happen on `play.mccisland.com`.

**To Reproduce**
1. Launch Minecraft 1.21 with Physics Mod Lite 3.0.16.
2. Join the server `play.miguvt.com`.
3. Allow the custom texture pack to load.
4. Exit the server.
5. Observe the intermittent crash.

**Additional Information**
Initially, it was thought that the issue was related to the version of Fabric Loader, but the crashes also occur on version 0.15.11, leaving the cause unclear. The crashes happen more often on servers where the texture pack loads after joining, like `play.miguvt.com`. However, on `play.mccisland.com`, where the texture pack loads immediately upon joining, the issue does not occur. The exact cause remains unknown.

Minecraft Version: 1.21  
Physics Mod Version: Lite 3.0.16

[**Log**](https://mclo.gs/A8XnGeR): https://mclo.gs/A8XnGeR

**Comment by MiguVT** [comment]
i think its because method_1562() is returning null, any fix?

**Comment by haubna** [comment]
I've just released version 3.0.18 that should fix this issue. In case it still happens on your end please open a new issue. Thanks for the report!
