### ISSUE TITLE
Particles don't disappear [BUG]

### ISSUE THREAD

**Issue by Lumi-Nation** [haubna/PhysicsMod#964]
**Describe the bug**
After eating food and running around, particles do not disappear - they remain in place, even when walked through and blocks underneath are broken. Particles also remain when teleporting away from the location and then back. It just randomly started happening out of nowhere. [edit: also happens when breaking blocks] This also creates some lag, but not a horrendous amount.

**To Reproduce**
Run around and eat some food. Go break some blocks too, if you feel like it.

**Screenshots**
![2024-08-19_11 49 08](https://github.com/user-attachments/assets/fd98bdf4-5de9-4901-ab1d-9f264b812b25)
![so many particles](https://github.com/user-attachments/assets/a19ea844-35e7-4cc6-b511-4b7f2a2608ec)
![gravity took a day off](https://github.com/user-attachments/assets/9b5e5740-91dd-48d1-8053-774a75e2a826)

Minecraft Version: 1.19.2
Physics Mod Version: 2.12.5

**Comment by Lumi-Nation** [comment]
Turns out ragdolls don't fall either
![I'm still standing](https://github.com/user-attachments/assets/148f5a52-065e-46ff-a143-0853c4baafe1)

**Comment by Lumi-Nation** [comment]
I restarted the game/world and it fixed it.
[edit: it's done it again]

**Comment by haubna** [comment]
You are using an old version of the mod that no longer gets updated. This issue might be fixed with never versions.
