### ISSUE TITLE
game crashes when using physics mod and iris shaders togheter

### ISSUE THREAD

**Issue by DogeTOM1143** [haubna/PhysicsMod#966]
**Describe the bug**
physics mod wont work with iris it just crashes everytime i try to play or load in the world

**To Reproduce**
basicaly i try to play the game with physics mod and shaders and everytime i try doing so it just crashes im using a modpack called fabulously optimised i tried with that it crashes then i tried with only iris/sodium/physics mod same thing it crashes

**Screenshots**
![Screenshot 2024-08-23 124313](https://github.com/user-attachments/assets/7fe91f4a-afb9-4738-994c-ece74706ff86)

Minecraft Version: <1.21.1>
Physics Mod Version: < v172 >
 
[latest.log](https://github.com/user-attachments/files/16726887/latest.log)

**Comment by haubna** [comment]
Please update to Iris 1.8 + Sodium 0.6

**Comment by DogeTOM1143** [comment]
i aleready did and its the same thing all over

**Comment by haubna** [comment]
Can you provide the crash log? Maybe there is a hs_err_pid file in your minecraft folder.

**Comment by DogeTOM1143** [comment]
uhhh let me check but i dont think i have it

**Comment by DogeTOM1143** [comment]
![image](https://github.com/user-attachments/assets/46855235-371b-401d-8b96-0b4f3ef44aa2)

it seems i do not have the required file

**Comment by DogeTOM1143** [comment]
and also im playing minecraft trough curse forge and not the original launcher..

**Comment by DogeTOM1143** [comment]
[launcher_log.txt](https://github.com/user-attachments/files/16737730/launcher_log.txt)

maybe this will help you hopefully its from curse forge launcher or sum like that

**Comment by DogeTOM1143** [comment]
also some things i have noticed if i run the game with the mod and no shader it works if i run the game with the mod and shader it crashes if i run the game with no mod and shader on it works so yea idk it could be of the mod could be from the shader i have no idea honestly

**Comment by haubna** [comment]
I've just uploaded V172a which hopefully fixes your issue. Can you let me know if that works?

**Comment by DogeTOM1143** [comment]
okay sure let me try it and i will let you know!

**Comment by DogeTOM1143** [comment]
nope it crashed
![image](https://github.com/user-attachments/assets/0c432243-2c34-49e8-947c-21e1f28e40c0)
[latest.log](https://github.com/user-attachments/files/16739832/latest.log)
here is log as well

**Comment by DogeTOM1143** [comment]
![image](https://github.com/user-attachments/assets/14b95d8b-5bf9-4698-b9ae-b0dce28496e8)
wtf i tried without shader too and it crashes without shaders too

**Comment by DogeTOM1143** [comment]
here is a better view of the log
https://mclo.gs/I7vZksY

**Comment by haubna** [comment]
You are not using Iris 1.8 + Sodium 0.6

**Comment by DogeTOM1143** [comment]
lemme use and do another test also im using the shader called rethinking voxels just letting u know

**Comment by DogeTOM1143** [comment]
[latest.log](https://github.com/user-attachments/files/16741418/latest.log)

dang it crashed right when the game loaded

**Comment by haubna** [comment]
Yeah you have some other mods that are incompatible with the new Sodium + Iris. Reeses Sodium Options is on of them. You will need to update all of them or stick to the old versions and use Physics Mod Pro v171 (which is compatible with the old Iris + Sodium version).

**Comment by DogeTOM1143** [comment]
iirc i updated the other sodium mods as well is it cuz of those not being able to work at the moment?

**Comment by DogeTOM1143** [comment]
so i have sodium reeses at version 1.8.0 beta2 and sodium extra at version 0.6.0 beta1 wich those are the newest versions possible

**Comment by DogeTOM1143** [comment]
and yes i also have sodium at 0.6.0 beta1 and iris at 1.8.0 beta3

**Comment by DogeTOM1143** [comment]
hello so game works now with mod and shader so if i use more culling and sodium reeses options gotta not use those for now and yea it works now no crashes although if i end up with more problems ima let you know right here in this thread and i wanna thank you verry much since u took ur own time to respond here i appreciate it man and sorry if u had to respond this much haha also cannot wait to see what will be added into this mod it sure is an awesome mod and prolly my fav one by far anyways have a good one man :)

**Comment by haubna** [comment]
Perfect, thank you!
