### ISSUE TITLE
Cannot enable GPU liquids [BUG]

### ISSUE THREAD

**Issue by spenkluker645** [haubna/PhysicsMod#968]
**Describe the bug**
I can't enable the GPU liquids. I have an Nvidia gpu on Linux, and i am on the main menu.

**To Reproduce**
Try to enable GPU liquids on linux

**Screenshots**
![image](https://github.com/user-attachments/assets/8e80c20f-3922-48d2-8c83-aeda73c3c3e1)

Minecraft Version: 1.20.1
Physics Mod Version: v171b

**Comment by haubna** [comment]
Sorry, I forgot to remove that Linux is no longer supported by default for GPU liquids (since the mod file size exploded). I don't know if this works but you could try downloading [physx-jni-natives-linux-cuda-2.3.2.jar](https://github.com/fabmax/physx-jni/releases/download/v2.3.2/physx-jni-natives-linux-cuda-2.3.2.jar) and merge the "de" folder from this jar into the "de" folder from the physics mod jar.

**Comment by Czechia777** [comment]
i have the same issue but im on windows

**Comment by tamescrawl2** [comment]
i am on mac and i really want gpu liquids. Do you have any idea if i can enable it?

**Comment by redstonegenious** [comment]
> Sorry, I forgot to remove that Linux is no longer supported by default for GPU liquids (since the mod file size exploded). I don't know if this works but you could try downloading [physx-jni-natives-linux-cuda-2.3.2.jar](https://github.com/fabmax/physx-jni/releases/download/v2.3.2/physx-jni-natives-linux-cuda-2.3.2.jar) and merge the "de" folder from this jar into the "de" folder from the physics mod jar.

I just tried, I don't know if I did it wrong, but either way, didn't work. Linux Mint on a 4080 btw

**Comment by cowwannabe** [comment]
I also have this issue. I'm using windows 10 and a GTX 2070 super. I hope that this issue can be fixed soon because I desperately want to be able to use GPU liquids.

*edit: I am so desperate to use GPU liquids, that I created this account specifically to ask for help.

**Comment by hackthedev** [comment]
I have the same issue on windows 11 with a 3080. its not showing me the option at all

**Comment by TilaSofa** [comment]
Is there a solution to the problem yet?

Linux EndeavourOS and NVIDIA GeForce RTX 4060 here

**Comment by Mr1millionZM** [comment]
I also cannot enable GPU liquids, and I have windows 11 laptop with RTX 3050 ):
