### ISSUE TITLE
A Reply for Reprint

### ISSUE THREAD

**Issue by HeatenIsHere** [haubna/PhysicsMod#97]
致组件:Physics Mod的开发者,haubna：
您好，我们是我的世界中国版的一位开发者。我们觉得您的组件: Physics Mod很新颖，我们希望转载它。请问您是否能将本组件授权给我们，我们会将其作为收费5CNY（约0.714USD）的价格售卖，由于我的世界中国版运营公司：上海网之易璀璨网络科技有限公司会收取30%平台费。由此，您最高收取的价格为70%（3.5CNY/0.5USD）。如果您要联系我们或者同意授权，请邮件联系：wangyifan090224@outlook.com。谢谢！
如果您要收取任何费用，我们支持微信支付或银行转账。如有平台费，请您自行承担！
期待您的回复！
                                我的世界中国版暖气工作室室长
                                          2021年8月

To the developer of the mod: Physics Mod，haubna: 
Hello, we are a developer of Minecraft China Edition. We think your mod: Physics Mod is very novel, and we hope to reprint it. May I ask if you can authorize this component to us, we will sell it as a charge of 5CNY (about 0.714USD), because the operating company of Minecraft China: Shanghai NetEase Bright Network Technology Co., Ltd. will charge 30% of the platform Fee. Therefore, the highest price you charge is 70% (3.5CNY/0.5USD). If you want to contact us or confirm authorization. Please email: wangyifan090224@outlook.com. Thank you! 
If you want to charge any fees, we support WeChat and bank card payment. If there is a platform fee, please bear it yourself! 
Looking forward to your reply! 
Director of Minecraft China Heaten Workroom 
August 2021

**Comment by GradersPro88** [comment]
Ooh @haubna
