### ISSUE TITLE
crash on startup of world 1.20.1 [BUG]

### ISSUE THREAD

**Issue by Kuro-Itami** [haubna/PhysicsMod#971]
**Crash on startup of world**
Error: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.diebuddies.mixins.iris.MixinExtendedShaderAccessor. Mixin is defined in physicsmod.mixins.json and cannot be referenced directly
is the error i get whenever i start up or load a world, clears initial startup

i have no other mods besides embeddium 3.31 + oculus 1.70
i tried earlier versions that had the same issue
my forge versions i used are 47.3.3 and 47.3.7

Minecraft Version: <1.20.1>
Physics Mod Version: <v-164 forge>
EDIT: removing embeddium + oculus fixed this issue

**Comment by haubna** [comment]
It seems like you are using the wrong versions for Embeddium + Oculus. The right versions can be found here: https://minecraftphysicsmod.com/installation
