### ISSUE TITLE
crashes when i join any world

### ISSUE THREAD

**Issue by superpelmenipoedatel** [haubna/PhysicsMod#976]
here's logs:
Time: 2024-09-16 15:51:05
Description: Unexpected error

java.lang.AbstractMethodError: Receiver class net.diebuddies.compat.DummyVertexConsumerSodium does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.caffeinemc.mods.sodium.api.vertex.format.VertexFormatDescription)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at net.caffeinemc.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboid(EntityRenderer.java:90)
	at net.minecraft.class_630$class_628.handler$dmi000$sodium$onCompile(class_630.java:2049)
	at net.minecraft.class_630$class_628.method_32089(class_630.java:288)
	at net.minecraft.class_630.method_22702(class_630.java:175)
	at net.minecraft.class_630.method_22699(class_630.java:123)
	at net.minecraft.class_4592.method_22949(class_4592.java:62)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_4592.method_2828(class_4592.java:62)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:30)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at net.minecraft.class_1309.handler$coo000$physicsmod$onDeath(class_1309.java:10311)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at net.minecraft.class_1308.method_5711(class_1308.java:366)
	at net.minecraft.class_634.method_11148(class_634.java:1082)
	at net.minecraft.class_2663.method_11471(class_2663.java:41)
	at net.minecraft.class_2663.method_11054(class_2663.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-- Head --
Thread: Render thread
Stacktrace:
	at net.caffeinemc.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboid(EntityRenderer.java:90)
	at net.minecraft.class_630$class_628.handler$dmi000$sodium$onCompile(class_630.java:2049)
	at net.minecraft.class_630$class_628.method_32089(class_630.java:288)
	at net.minecraft.class_630.method_22702(class_630.java:175)
	at net.minecraft.class_630.method_22699(class_630.java:123)
	at net.minecraft.class_4592.method_22949(class_4592.java:62)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_4592.method_2828(class_4592.java:62)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:30)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at net.minecraft.class_1309.handler$coo000$physicsmod$onDeath(class_1309.java:10311)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at net.minecraft.class_1308.method_5711(class_1308.java:366)
	at net.minecraft.class_634.method_11148(class_634.java:1082)
	at net.minecraft.class_2663.method_11471(class_2663.java:41)
	at net.minecraft.class_2663.method_11054(class_2663.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)

-- Uptime --
Details:
	JVM uptime: 167.667s
	Wall uptime: 142.556s
	High-res time: 128.024s
	Client ticks: 1352 ticks / 67.600s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['justfishbutacid'/19, l='ClientLevel', x=-977.32, y=68.54, z=544.14]]
	Chunk stats: 5041, 538
	Level dimension: minecraft:overworld
	Level spawn location: World: (-960,73,544), Section: (at 0,9,0 in -60,4,34; chunk contains blocks -960,-64,544 to -945,319,559), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
	Level time: 559 game time, 559 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 216

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, ambientsounds, appleskin, bettercommandblockui, betterf3, betterpingdisplay, betterstats, calcmod, chatshot, cherishedworlds, chunksfadein, chunky, cicada, cloth-config, creativecore, custom-crosshair-mod, debugify, do_a_barrel_roll, dynamic_fps, emi, entity_model_features, entity_texture_features, entityculling, euphoria_patcher, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fallingtrees, flow, forgeconfigapiport, inventoryprofilesnext, iris, jade, justzoom, konkrete, languagereload, libipn, lootbeams, modernfix, modmenu, mru, notebook, notenoughanimations, pandalib, peek, physicsmod, placeholder-api, presencefootsteps, resourcify, rolling_down_in_the_deep, rrls, shared-resources, shared-resources-api, smoothscroll, sodium, sodium-extra, sound_physics_remastered, sounds, tcdcommons, ukulib, visuality, xaeroworldmap, yet_another_config_lib_v3, file/Rainbow_Outlines.zip, file/§3§lC418 Songs Only [All Versions].zip, file/Shiny Trims v5 (Vanilla Animated).zip, file/Color Enchantment.zip, file/Round-Trees-7.1-1.19+.zip, presencefootsteps:default_sound_pack, file/cubic-sun-moon-v1-8a.zip

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.2, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 604497256 bytes (576 MiB) / 2550136832 bytes (2432 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Phenom(tm) II X6 1090T Processor
	Identifier: AuthenticAMD Family 16 Model 10 Stepping 0
	Microarchitecture: K10
	Frequency (GHz): 3.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Radeon RX 560 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: Other
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: Other
	Memory slot #2 capacity (MiB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: Other
	Memory slot #3 capacity (MiB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: Other
	Virtual memory max (MiB): 19325.18
	Virtual memory used (MiB): 10815.73
	Swap memory total (MiB): 2943.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 3311.80, total: 114371.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 3311.80, total: 114371.00
	Space in storage for io.netty.native.workdir (MiB): available: 3311.80, total: 114371.00
	Space in storage for java.io.tmpdir (MiB): available: 3311.80, total: 114371.00
	Space in storage for workdir (MiB): available: 3311.80, total: 114371.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.1.0
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		bettercommandblockui: BetterCommandBlockUI 0.5.2a
		betterf3: BetterF3 11.0.2
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21
		calcmod: CalcMod 1.3.2+fabric.1.21
			clientarguments: clientarguments 1.9
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		chatshot: ChatShot 1.0.3
		cherishedworlds: Cherished Worlds 10.0.2+1.21.1
		chunksfadein: Chunks Fade In 1.0.2-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		chunky: Chunky 1.4.16
		cicada: CICADA 0.8.3+1.21-and-above
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		creativecore: CreativeCore 2.12.11
			net_neoforged_bus: bus 7.2.0
		custom-crosshair-mod: Custom Crosshair Mod 1.6.0-fabric
		debugify: Debugify 1.21.1+1.0
		do_a_barrel_roll: Do a Barrel Roll 3.6.2+1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.1
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		emi: EMI 1.1.13+1.21.1+fabric
		entity_model_features: Entity Model Features 2.2.5
		entity_texture_features: Entity Texture Features 6.2.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		euphoria_patcher: Euphoria Patcher 0.3.4-fabric
			io_sigpipe_jbsdiff: jbsdiff 1.0
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.104.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.22+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.7.0+4053855719
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.19+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.2.0+d38f898f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.2
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fallingtrees: Panda's Falling Tree's 0.12.7
		ferritecore: FerriteCore 7.0.0
		flow: Flow 2.1.2+1.21
			yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		forgeconfigapiport: Forge Config API Port 21.1.0
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fusion: Fusion 1.1.1
		helditemtooltips: Held Item Tooltips 21.1.0
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		iris: Iris 1.8.0-beta.3+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 15.3.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		justzoom: Just Zoom 2.0.0
		konkrete: Konkrete 1.9.9
		languagereload: Language Reload 1.6.1+1.21
		libipn: libIPN 6.0.2
		lootbeams: Lootbeams 2.1.2+1.21.1
			microconfig: Microconfig 3.0.0
		melody: Melody 1.0.10
		minecraft: Minecraft 1.21.1
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
		mru: Mineblock's Repeated Utilities 1.0.2+1.21+fabric
		notebook: Notebook 4.0.5
		notenoughanimations: NotEnoughAnimations 1.7.6
		pandalib: PandaLib 0.4.2
		peek: Peek 1.21.1-1.3.5
		physicsmod: Physics Mod 3.0.20
		placeholder-api: Placeholder API 2.4.1+1.21
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		puzzleslib: Puzzles Lib 21.1.3
		resourcify: Resourcify 1.4.1
			universalcraft: UniversalCraft 342
		rolling_down_in_the_deep: Rolling Down in the Deep 0.2.0+1.21
		rrls: Remove Reloading Screen 5.0.7+mc1.21-fabric
		shared-resources: Shared Resources 1.9.1+1.21
			shared-resources-api: Shared Resources API 1.9.1
		smoothscroll: Smooth Scroll 2.1.3
		sodium: Sodium 0.6.0-beta.1+mc1.21
		sodium-extra: Sodium Extra 0.6.0-beta.1+mc1.21.1
			com_lodborg_interval-tree: interval-tree 1.0.0
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sounds: Sounds 2.0.4+1.21+fabric
			mixinextras: MixinExtras 0.5.0-beta.2
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		tectonic: Tectonic 2.4.1a
		tia: Tiny Item Animations 1.2.1
		ukulib: ukulib 1.3.0+1.21
		visuality: Visuality 0.7.7+1.21
		xaeroworldmap: Xaero's World Map 1.39.0
	Loaded Shaderpack: BSLClassic_v8.3.zip
		Profile: MINIMUM (+1 option changed by user)
	Launched Version: Fabric 1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Radeon RX 560 Series GL version 3.2.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 2560x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1000, source=API, type=ERROR, severity=HIGH, message='glBindTextureUnit has generated an error (GL_INVALID_OPERATION)' x 25
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 32/32 chunks
	Resource Packs: vanilla, fabric, ambientsounds, appleskin (incompatible), bettercommandblockui, betterf3, betterpingdisplay, betterstats, calcmod, chatshot, cherishedworlds (incompatible), chunksfadein, chunky, cicada, cloth-config, creativecore, custom-crosshair-mod, debugify, do_a_barrel_roll (incompatible), dynamic_fps, emi, entity_model_features, entity_texture_features, entityculling, euphoria_patcher, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fallingtrees, flow, forgeconfigapiport, inventoryprofilesnext, iris, jade (incompatible), justzoom (incompatible), konkrete (incompatible), languagereload, libipn, lootbeams, modernfix (incompatible), modmenu, mru (incompatible), notebook, notenoughanimations, pandalib, peek, physicsmod, placeholder-api, presencefootsteps, resourcify (incompatible), rolling_down_in_the_deep, rrls, shared-resources, shared-resources-api, smoothscroll, sodium, sodium-extra, sound_physics_remastered, sounds, tcdcommons, ukulib, visuality, xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), file/Rainbow_Outlines.zip (incompatible), file/§3§lC418 Songs Only [All Versions].zip, file/Shiny Trims v5 (Vanilla Animated).zip (incompatible), file/Color Enchantment.zip, file/Round-Trees-7.1-1.19+.zip (incompatible), presencefootsteps:default_sound_pack, file/cubic-sun-moon-v1-8a.zip
	Current Language: ru_ru
	Locale: ru_RU
	System encoding: Cp1251
	File encoding: UTF-8
	CPU: 6x AMD Phenom(tm) II X6 1090T Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['justfishbutacid'/19, l='ServerLevel[Новый мир]', x=-977.32, y=68.54, z=544.14]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, sounds (incompatible), tectonic:tectonic
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, sounds (incompatible), tectonic:tectonic, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -1077033335159232807

**Comment by haubna** [comment]
Physics Mod 3.0.20 requires Sodium 0.6.0-beta2 and Iris 1.8.0-beta4
