### ISSUE TITLE
game crashes after killing mobs(tried possible solutions) [BUG]

### ISSUE THREAD

**Issue by crystalist-hub** [haubna/PhysicsMod#982]
**Describe the bug**
The mod is fine on doing everything else(should be, cant try out everything yet cuz i just crash after like a minute into game)
Update: tried to kill a mob as quick as I can, tested multiple times too, after killing one mob it just crash me. I have seen a post about killing mob crash your game, but i did what the comment stated, (install lastest sodium and iris) and unsurprisingly didnt work.

Here is the error code if need.
The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Receiver class net.diebuddies.compat.DummyVertexConsumerSodium does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.minecraft.class_293)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.

**To Reproduce**
killing mobs, thats all i found for now

Minecraft Version: <1.21.1>
Physics Mod Version: <V172 - Sodium 0.6 + Iris 1.8 Beta> (correct me if im wrong here idk where to find lol)

**Comment by crystalist-hub** [comment]
Heres the whole crash report, if needed.

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-09-19 16:03:29
Description: Unexpected error

java.lang.AbstractMethodError: Receiver class net.diebuddies.compat.DummyVertexConsumerSodium does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.minecraft.class_293)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at net.caffeinemc.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboid(EntityRenderer.java:90)
	at net.minecraft.class_630$class_628.handler$cbp000$sodium$onCompile(class_630.java:2049)
	at net.minecraft.class_630$class_628.method_32089(class_630.java:288)
	at net.minecraft.class_630.method_22702(class_630.java:175)
	at net.minecraft.class_630.method_22699(class_630.java:123)
	at net.minecraft.class_630.method_22699(class_630.java:127)
	at net.minecraft.class_5597.method_2828(class_5597.java:32)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:30)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at net.minecraft.class_1309.handler$bkf000$physicsmod$onDeath(class_1309.java:7311)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at net.minecraft.class_1308.method_5711(class_1308.java:366)
	at net.minecraft.class_634.method_11148(class_634.java:1082)
	at net.minecraft.class_2663.method_11471(class_2663.java:41)
	at net.minecraft.class_2663.method_11054(class_2663.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.caffeinemc.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboid(EntityRenderer.java:90)
	at net.minecraft.class_630$class_628.handler$cbp000$sodium$onCompile(class_630.java:2049)
	at net.minecraft.class_630$class_628.method_32089(class_630.java:288)
	at net.minecraft.class_630.method_22702(class_630.java:175)
	at net.minecraft.class_630.method_22699(class_630.java:123)
	at net.minecraft.class_630.method_22699(class_630.java:127)
	at net.minecraft.class_5597.method_2828(class_5597.java:32)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:30)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at net.minecraft.class_1309.handler$bkf000$physicsmod$onDeath(class_1309.java:7311)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at net.minecraft.class_1308.method_5711(class_1308.java:366)
	at net.minecraft.class_634.method_11148(class_634.java:1082)
	at net.minecraft.class_2663.method_11471(class_2663.java:41)
	at net.minecraft.class_2663.method_11054(class_2663.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)

-- Uptime --
Details:
	JVM uptime: 98.012s
	Wall uptime: 86.901s
	High-res time: 83.588s
	Client ticks: 1305 ticks / 65.250s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['MKiMine'/38, l='ClientLevel', x=-8.75, y=73.00, z=38.15]]
	Chunk stats: 1369, 913
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,77,0), Section: (at 0,13,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1058 game time, 1058 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 183

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, cicada, cloth-config, do_a_barrel_roll, entity_model_features, entity_texture_features, essential, essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, invmove, iris, jankson, libgui, midnightlib, packedup, physicsmod, repurposed_structures, sodium, supermartijn642corelib, voxelmap, wurst, yigd, minecraft:physicsmod, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1278214144 bytes (1219 MiB) / 2558525440 bytes (2440 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6081
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 42935.89
	Virtual memory used (MiB): 32692.54
	Swap memory total (MiB): 26624.00
	Swap memory used (MiB): 1571.55
	Space in storage for jna.tmpdir (MiB): available: 294736.03, total: 975635.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 294736.03, total: 975635.00
	Space in storage for io.netty.native.workdir (MiB): available: 294736.03, total: 975635.00
	Space in storage for java.io.tmpdir (MiB): available: 294736.03, total: 975635.00
	Space in storage for workdir (MiB): available: 294736.03, total: 975635.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		cicada: CICADA 0.8.3+1.21-and-above
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		do_a_barrel_roll: Do a Barrel Roll 3.6.2+1.21
			mixinsquared: MixinSquared 0.1.1
		elementa: Elementa 665
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 1.3.4.1
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.104.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.22+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.7.0+4053855719
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.19+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.2.0+d38f898f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		invmove: InvMove 0.8.8
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		midnightlib: MidnightLib 1.6.3
		minecraft: Minecraft 1.21.1
		org_jetbrains_annotations: annotations 23.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		packedup: Packed Up 1.0.30+c
		physicsmod: Physics Mod 3.0.19
		repurposed_structures: Repurposed Structures 7.5.10+1.21.1-fabric
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+c
		universalcraft: UniversalCraft 362
		vigilance: Vigilance 306
		voxelmap: Voxelmap 1.21-1.13.1
		wurst: Wurst Client v7.45.1-MC1.21.1
		yigd: You're in Grave Danger 2.4.7
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
	Loaded Shaderpack: §r§lAstra§4§lLex§r§l_By_LexBoosT_§4§lV93.0§r§l.zip
		Profile: Custom (+1 option changed by user)
	Launched Version: fabric-loader-0.16.5-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.81, NVIDIA Corporation
	Window size: 3440x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 15/15 chunks
	Resource Packs: vanilla, fabric, cicada, cloth-config, do_a_barrel_roll (incompatible), entity_model_features, entity_texture_features, essential (incompatible), essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, invmove, iris, jankson, libgui, midnightlib, packedup, physicsmod, repurposed_structures, sodium, supermartijn642corelib, voxelmap (incompatible), wurst, yigd, minecraft:physicsmod (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: GBK
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['MKiMine'/38, l='ServerLevel[New World]', x=-8.75, y=73.00, z=38.15]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, packedup (incompatible), repurposed_structures, supermartijn642corelib (incompatible), yigd
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, packedup (incompatible), repurposed_structures, supermartijn642corelib (incompatible), trade_rebalance, vanilla, yigd
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -4224839447828036804

**Comment by haubna** [comment]
Please update to Physics Mod 3.0.20, previous versions are not compatible with your current Iris + Sodium versions.

**Comment by Sadpow** [comment]
So which is the 'Pro' version equivalent to the mod you just described
