### ISSUE TITLE
why aint u porting the new updates to older versions like 1.16.5 atleast

### ISSUE THREAD

**Issue by trollxslaya** [haubna/PhysicsMod#99]
not everybody wanna play on 1.17

**Comment by haubna** [comment]
Read www.minecraftphysicsmod.com/faq

**Comment by haubna** [comment]
Read www.minecraftphysicsmod.com/faq

**Comment by trollxslaya** [comment]
thats not a good reason u seem to b updating it like evry day it wouldnt hurt to do 1.16.5 atleast

**Comment by haubna** [comment]
Do you want to get banned from here? Respect my decision, I am not your slave.

**Comment by trollxslaya** [comment]
y u goin all aggresive on me mane im just suggesting something and hoping u reconsider

**Comment by haubna** [comment]
You aren't suggesting. I said no and you still insisting.

trollxslaya ***@***.***> schrieb am Mo. 30. Aug. 2021 um
09:22:

**Comment by trollxslaya** [comment]
ight ill leave u alone but im just sayin u should be a lil more open to change. good work tho

**Comment by haubna** [comment]
What change?! You don't even know how much work this is. I ain't getting
paid.

trollxslaya ***@***.***> schrieb am Mo. 30. Aug. 2021 um
09:29:

**Comment by trollxslaya** [comment]
well me askin is still the same as a suggestion but i understand its hard work bru and i respect ur grind
