### ISSUE TITLE
Non-Full Block Fracture Bug [BUG]

### ISSUE THREAD

**Issue by User122312** [haubna/PhysicsMod#993]
**Description:**
Non-full blocks (eg. torches, fire) glitch out and break weirdly  when using voxel fracture (normal fracture not tested)

**Reproduction:**
Use fracture or voxel fracture mode and break a torch

**Screenshots:**
![image](https://github.com/user-attachments/assets/6e4d8f7a-a923-4c44-9136-a1d99e94dcdb)
![image](https://github.com/user-attachments/assets/d6b91621-cd33-47ea-b663-bbbe166d9332)

Minecraft Version: 1.21.1
Physics Mod Version: PRO - V172

**Comment by haubna** [comment]
Yup that's the nature of those specific blocks since the internal structure of a torch is very different from what you see. The best way is to set this specific block to the type "particles".

**Comment by User122312** [comment]
thanks for responding, i didn't know that you could change the way one specific block breaks so thanks for that too.
