### ISSUE TITLE
Please help me, Game crashes when ragdoll is activated

### ISSUE THREAD

**Issue by Sadpow** [haubna/PhysicsMod#995]
**Describe the bug**
Whenever I kill a mob and activate the ragdoll, my game crashes.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-10-24 02:47:02
Description: Unexpected error

java.lang.AbstractMethodError: Method net/diebuddies/compat/DummyVertexConsumerSodium.push(Lorg/lwjgl/system/MemoryStack;JILnet/caffeinemc/mods/sodium/api/vertex/format/VertexFormatDescription;)V is abstract
	at knot//net.diebuddies.compat.DummyVertexConsumerSodium.push(DummyVertexConsumerSodium.java)
	at knot//net.caffeinemc.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboid(EntityRenderer.java:90)
	at knot//net.minecraft.class_630$class_628.handler$dab000$sodium$onCompile(class_630.java:1049)
	at knot//net.minecraft.class_630$class_628.method_32089(class_630.java:288)
	at knot//net.minecraft.class_630.method_22702(class_630.java:175)
	at knot//net.minecraft.class_630.method_22699(class_630.java:123)
	at knot//net.minecraft.class_4592.method_22949(class_4592.java:62)
	at knot//com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at knot//net.minecraft.class_4592.method_2828(class_4592.java:62)
	at knot//net.minecraft.class_922.method_4054(class_922.java:145)
	at knot//net.minecraft.class_922.method_3936(class_922.java:30)
	at knot//net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at knot//net.minecraft.class_1309.handler$cje000$physicsmod$onDeath(class_1309.java:9811)
	at knot//net.minecraft.class_1309.method_6078(class_1309.java)
	at knot//net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at knot//net.minecraft.class_1308.method_5711(class_1308.java:366)
	at knot//net.minecraft.class_634.method_11148(class_634.java:1082)
	at knot//net.minecraft.class_2663.method_11471(class_2663.java:41)
	at knot//net.minecraft.class_2663.method_11054(class_2663.java:13)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.diebuddies.compat.DummyVertexConsumerSodium.push(DummyVertexConsumerSodium.java)
	at knot//net.caffeinemc.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboid(EntityRenderer.java:90)
	at knot//net.minecraft.class_630$class_628.handler$dab000$sodium$onCompile(class_630.java:1049)
	at knot//net.minecraft.class_630$class_628.method_32089(class_630.java:288)
	at knot//net.minecraft.class_630.method_22702(class_630.java:175)
	at knot//net.minecraft.class_630.method_22699(class_630.java:123)
	at knot//net.minecraft.class_4592.method_22949(class_4592.java:62)
	at knot//com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at knot//net.minecraft.class_4592.method_2828(class_4592.java:62)
	at knot//net.minecraft.class_922.method_4054(class_922.java:145)
	at knot//net.minecraft.class_922.method_3936(class_922.java:30)
	at knot//net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at knot//net.minecraft.class_1309.handler$cje000$physicsmod$onDeath(class_1309.java:9811)
	at knot//net.minecraft.class_1309.method_6078(class_1309.java)
	at knot//net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at knot//net.minecraft.class_1308.method_5711(class_1308.java:366)
	at knot//net.minecraft.class_634.method_11148(class_634.java:1082)
	at knot//net.minecraft.class_2663.method_11471(class_2663.java:41)
	at knot//net.minecraft.class_2663.method_11054(class_2663.java:13)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)

-- Uptime --
Details:
	JVM uptime: 26.166s
	Wall uptime: 21.305s
	High-res time: 20.161s
	Client ticks: 259 ticks / 12.950s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['fancyslug'/17, l='ClientLevel', x=-146.15, y=96.00, z=-20.05]]
	Chunk stats: 529, 284
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,64,-16), Section: (at 0,0,0 in -1,4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 2274 game time, 2274 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 82

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/gen_assets.zip, file/Eyeless Fresh Moves v3.0.1.zip, file/freshly-modded-1-5-7.zip, file/Recolourful Containers 1.1.1 (1.19.4-1.21.x).zip, file/Dot Crosshair.zip, file/Simple Grass Flowers v1.8.1.zip, file/VanillaTweaks_r209614_MC1.21.x.zip, file/VanillaTweaks_r569364_MC1.21.x.zip, file/xali's enchanted books v0.13.0.zip, file/AL's Boss Rush 1.1.zip, file/AL's Boss Rush+FA 1.1.zip, file/pleasework.zip, file/FreshAnimations_v1.9.2.zip, file/astraliyte-s-animated-textures-v1-4.zip, file/Better Chainmail.zip, fabric, c2me, cloth-config, distanthorizons, enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, krypton, lithium, modernfix, modmenu, noisium, physicsmod, reeses-sodium-options, sodium, sodium-extra, stutterfix, minecraft:physicsmod

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1958359928 bytes (1867 MiB) / 3321888768 bytes (3168 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 28
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-14700KF
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 3.42
	Number of physical packages: 1
	Number of physical CPUs: 20
	Number of logical CPUs: 28
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8188.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6603
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.20
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.20
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 37974.44
	Virtual memory used (MiB): 17856.50
	Swap memory total (MiB): 5376.00
	Swap memory used (MiB): 90.48
	Space in storage for jna.tmpdir (MiB): available: 641525.69, total: 952913.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 641525.69, total: 952913.00
	Space in storage for io.netty.native.workdir (MiB): available: 641525.69, total: 952913.00
	Space in storage for java.io.tmpdir (MiB): available: 641525.69, total: 952913.00
	Space in storage for workdir (MiB): available: 641525.69, total: 952913.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		badoptimizations: BadOptimizations 2.1.4
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.204+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.204+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.204+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.204+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.204+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.204+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.204+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.204+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.204+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.204+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.204+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.204+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.204+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.204+1.21.1
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		distanthorizons: Distant Horizons 2.2.1-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.103.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.21+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.1+9b16164119
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.18+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.0.0
		iris: Iris 1.8.0-beta.3+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lithium: Lithium 0.13.0
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		physicsmod: Physics Mod 3.0.20
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.2+mc1.21.1
		sodium: Sodium 0.6.0-beta.1+mc1.21
		sodium-extra: Sodium Extra 0.6.0-beta.1+mc1.21.1
			com_lodborg_interval-tree: interval-tree 1.0.0
		stutterfix: StutterFix mc1.21-0.2.3
	Loaded Shaderpack: ComplementaryReimagined_r5.2.2.zip
		Profile: Custom (+72 options changed by user)
	Launched Version: fabric-loader-0.16.7-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 4060/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.03, NVIDIA Corporation
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 8/8 chunks
	Resource Packs: vanilla, file/gen_assets.zip, file/Eyeless Fresh Moves v3.0.1.zip, file/freshly-modded-1-5-7.zip, file/Recolourful Containers 1.1.1 (1.19.4-1.21.x).zip, file/Dot Crosshair.zip, file/Simple Grass Flowers v1.8.1.zip, file/VanillaTweaks_r209614_MC1.21.x.zip, file/VanillaTweaks_r569364_MC1.21.x.zip, file/xali's enchanted books v0.13.0.zip, file/AL's Boss Rush 1.1.zip, file/AL's Boss Rush+FA 1.1.zip, file/pleasework.zip, file/FreshAnimations_v1.9.2.zip, file/astraliyte-s-animated-textures-v1-4.zip (incompatible), file/Better Chainmail.zip (incompatible), fabric, c2me, cloth-config, distanthorizons (incompatible), enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, krypton, lithium, modernfix (incompatible), modmenu, noisium, physicsmod, reeses-sodium-options, sodium, sodium-extra, stutterfix, minecraft:physicsmod (incompatible)
	Current Language: en_us
	Locale: en_GB
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 28x Intel(R) Core(TM) i7-14700KF
	Server Running: true
	Player Count: 1 / 8; [class_3222['fancyslug'/17, l='ServerLevel[New World]', x=-146.15, y=96.00, z=-20.05]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 7882880080869226613

**Comment by haubna** [comment]
Update to the Sodium 0.6.0-beta.2 and Iris 1.8.0-beta.4

**Comment by Sadpow** [comment]
thank you so much !!!!
