### ISSUE TITLE
Distant Horizons Mod and water physics issue [BUG]

### ISSUE THREAD

**Issue by Knightfire66** [haubna/PhysicsMod#997]
**Describe the bug**
While using distant horizons mod I think the physics mod renders the WHOLE water in the render distance of the distant horizons mod with water physics. thats in my case 16 (MC-render) + 256 DH-render distance. so thats a lot of water to render. I get 20-30% less fps. although the shaderpack is also active so far away, it is usefull. But I think I dont need water physics 500+ blocks away. Maybe I am wrong and the water only rendered outside of the "normal" render distance with physics mod because I was using the free cam mod to look.

In the settings could you add a render distance for the physics mod? a default option for MC render distance. and a slider for custom render distance. if we use speical mods like the distant horizon mod then this could be helpful

**To Reproduce**
fabric+physics mod +freecam mod +distant horizons (+complementary shader and support mods for all those)

**Screenshots**
![Screenshot 2024-10-29 235905](https://github.com/user-attachments/assets/a99e407b-0c28-438a-8490-90532dfa5ca5)

Minecraft Version: 1.20.1
Physics Mod Version: v171b

**Comment by haubna** [comment]
It is only because of the free cam mod. Physics Mod ocean physics doesn't apply to DH water.
